### ISSUE TITLE
Please provide a React example

### ISSUE THREAD

**Issue by mkondel** [paypal/paypal-checkout-components#1002]
### Description

I would like to add a paypal button to a page. Everyone writing React code uses webpack, not `<script>` tags in some plain HTML file. The examples given in this repo all use some kind of ancient syntax with `window.React.createClass`. Searching the past issues for a fix yields hax and workarounds from as far back as 2016. Here is what I have tried with various degrees of failure:

* adding via `<script>` to `<head>` of my root html document, then using `paypal.Button.driver` in my render method gets me `paypal is not defined`
* installing `paypal-checkout` the NPM module, then using `import paypal from 'paypal-checkout'` in my React component gets me `window is not defined`

## For the script method:

- Add `<script src="https://www.paypalobjects.com/api/checkout.js"></script>` to `<head>` of my app's root layout.
- I can see the script in the HTML using browser development tools.
- In the component where I want a button, add this in the `render()` method:
```javascript
const PayPalButton = paypal.Button.driver('react', { React, ReactDOM });
```

## For the module method:

- `yarn add paypal-checkout`
- In the React component try to import it, and get an error:
```javascript
import paypal from 'paypal-checkout';
```

**Comment by mkondel** [comment]
I was trying to render on both server and client. The error about 'no window' was coming from the server side. That example is using a plain HTML file and adds react through `<script>` tags. I cant use it because I am using webpack. Is there a more modern example somewhere else?

Here is a working example that imports `paypal-checkout` the NPM module inside the `componentDidMount()`, then saves it to state. Please give me any comments, this seems like an anti-pattern...

```javascript

class Cart extends React.Component {

  state = {
    PayPalButton: ()=><div>PAYPAL BUTTON PLACEHOLDER</div>,
    env: 'sandbox',
    commit: true,
    client: {
      sandbox:    'AWi18rxt26-hrueMoPZ0tpGEOJnNT4QkiMQst9pYgaQNAfS1FLFxkxQuiaqRBj1vV5PmgHX_jA_c1ncL',
      production: '<insert production client id>',
    },
  }
 
  payment = (data, actions) => {/**/}
 
  onAuthorize = (data, actions) => {/**/}

  componentDidMount(){
    const paypal = require('paypal-checkout')
    const PayPalButton = paypal.Button.driver('react', { React, ReactDOM })
    this.setState({ PayPalButton })
  }

  render(){
    const { PayPalButton, commit, env, client } = this.state

    return (
      <PayPalButton
        commit={ commit }
        env={ env }
        client={ client }
        payment={ (data, actions) => this.payment(data, actions) }
        onAuthorize={ (data, actions) => this.onAuthorize(data, actions) }
      />
    )
  }
}
```

**Comment by bluepnume** [comment]
The code is not set up to work on the server. So you'd have to do something like:

```
let paypal = (typeof window !== 'undefined') ? require('paypal-checkout') : null;

return (
    paypal && <PayPalButton ... />
);
```

**Comment by mkondel** [comment]
I did not have to check for 'window' in the code I already posted above. It will help countless people trying to get Paypal to work in their React project. Please add it as an example to the docs.

**Comment by AAverin** [comment]
Is React example still relevant with new https://developer.paypal.com/docs/checkout ?

**Comment by bluepnume** [comment]
React demos have now been updated. Please run `npm run demo`
