### ISSUE TITLE
Make timeouts configurable in sandbox mode

### ISSUE THREAD

**Issue by adelphes** [paypal/paypal-checkout-components#1003]
This is related to #477 

During development, debugging any server-side API calls relating to PayPal becomes tedious when the client library keeps timing out after 10 seconds. In https://github.com/paypal/paypal-checkout/commit/3d7652e the timeout for `payment` calls was removed in non-production environments.

Could you update the rest of the API calls to also remove the timeout requirement in non-prod environments - or, ideally, make it configurable in some way?

Like in https://github.com/paypal/paypal-checkout/issues/477#issuecomment-336932358 the only way around this seems to be replacing all of the hardcoded timeouts with longer values.

**Comment by bluepnume** [comment]
Timeout has been removed in the latest integration. Please see https://developer.paypal.com/docs/checkout/reference/upgrade-integration/ for the upgrade path
