### ISSUE TITLE
Inconsistent Redirect and Cancel behavior in Microsoft Edge

### ISSUE THREAD

**Issue by nodonoghue-SLP** [paypal/paypal-checkout-components#1009]
### Description

In only Microsoft Edge when completing or canceling a PayPal transaction from within the popup  results in the popup not closing and showing an error saying that the specified URL cannot be found.  We don't have a specific URL to pass in as the calling application is a single page web app with error and success functions handled through javascript.  This works in Chrome, Opera, and Firefox as expected.  In all browsers except for Edge the popup closes as expected and the Jacascript fires off as desired.

Also of note, we are using a server side implementation for calling the create and execute payment methods.

Below is a screenshot of the resulting error in Edge:
![paypal-edge-redirect-error](https://user-images.githubusercontent.com/47334507/52232621-db77fc80-2871-11e9-910b-17ac69b75867.png)

Front end code calling the button:
```
//PayPal Button render code
    paypal.Button.render({
        env: 'sandbox', // Or 'production'
 
        style: {
            label: 'checkout',
            size: 'responsive',
            shape: 'pill',
            color: 'white'
        },
 
        payment: function(data, actions) {
            return actions.request.post('@Model.ApplicationWebAddress' + '/api/CreatePayPalPayment', {
                IdentityToken: jQuery("#tid").val(),
                PaymentMethod: "Create",
                Amount: jQuery("#hdnAmount").val(),
                AccountIdentifier: "@Model.AccountIdentifier",
                MerchantTransactionId: "@Model.MerchantTransactionID",
                ProgramCode: '@Model.MerchantApplication',
                Fee: CalculateCLFee(Request.Amount),
                FirstName: jQuery('#hdnFirstName').val(),
                LastName: jQuery('#hdnLastName').val()
            })
                .then(function(response) {
                    if (response.Status == "Approved") {
 
                        jQuery("#tid").val(response.IdentityToken);
                        return response.PayPalPaymentId;
                    } else {
                        throw new Error("Create failed, no Payment Id");
                    }
                }).catch(function(error) {
                    PayPalCreateError(error);
                });
        },
        // Execute the payment:
        // 1. Add an onAuthorize callback
        onAuthorize: function(data, actions) {
            // 2. Make a request to your server
            return actions.request.post('@Model.ApplicationWebAddress' + '/api/ExecutePayPalPayment', {
                IdentityToken: jQuery("#tid").val(),
                PaymentMethod: "Execute",
                Amount: jQuery("#hdnAmount").val(),
                PayerId: data.payerID,
                PaymentId: data.paymentID,
                AccountIdentifier: "@Model.AccountIdentifier",
                ProgramCode: '@Model.MerchantApplication',
                Fee: CalculateCLFee(Request.Amount),
                MerchantTransactionId: "@Model.MerchantTransactionID",
                FirstName: jQuery('#hdnFirstName').val(),
                LastName: jQuery('#hdnLastName').val()
            })
                .then(function(response) {
                    if (response != null) {
                        if (response.Status == "Approved") {
                            // 3. Return response.id from the response
                            PayPalExecuteSuccess(response);
 
                            return response.PayPalPaymentId;
                        } else {
                            throw new Error("Create failed, no Payment Id");
                        }
                    } else {
                        throw new Error("Unable to communicate with PayPal.");
                    }
 
                }).catch(function(error) {
                    //Gain control of the page back from the paypal popup and display an error
                    PayPalCreateError(error);
                });
        },
        onCancel: function(data, actions) {
            //Show a cancel page or take them back to the funding source selection?
            ReturnToSourceSelector();
        }
    }, '#paypal-button');
```

Please provide a short description of the issue here, along with:

- Screenshots or videos that show the issue
- Your code
- The `paypal.version` from your browser console
- The exact browser version
- A link to your page with the issue, if possible
- All console logs during the time of the issue, especially error messages
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
- Does the issue occur consistently, or intermittently?

### Steps to reproduce

Load SPAN Express through the test app at: [https://ceapspanex.slpuat.com/SpanExpressTest/Main/Placeholder
](url)

This will need to be refreshed for each new test, if the values of the "MerchantID" isn't "Sightline", change it to Sightline after refreshing, also make sure that the MerchantApplication has a value of "LCP01".

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by nodonoghue-SLP** [comment]
After adding the sites to the security zones neither loaded.

Though looking at the article, this would be if a redirect had failed, which isn’t the problem we have.  We need the popup to simply close without any redirects.  This is the behavior we get on all other browsers.  Only edge is being problematic.

**Comment by bluepnume** [comment]
Can you confirm if this is happening on an intranet or corporate site at least? And if you see the same issue at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?

If so, there's not much we can recommend other than following the guide at https://developer.paypal.com/docs/checkout/troubleshoot/internet-explorer/ -- the script will not work in trusted or intranet mode.

**Comment by nodonoghue-SLP** [comment]
The issue does not seem to be present in the demo.   Could very likely be the page being on an intranet causing the problem.

We are setting up a test scenario which places the calling machine outside of our network to test if the problem is present when not on the same network as the web server.  I will followup again after this external test has been conducted.

I did follow the steps in the trouble shooting IE document and continue to have the issue, along with now seeing an error from PayPal implying that PayPal is down, screenshot attached below:

![image](https://user-images.githubusercontent.com/47334507/52501662-b519d000-2b95-11e9-8bd4-418d80456489.png)

**Comment by nodonoghue-SLP** [comment]
After performing tests external to the office network, both of the above issues do not appear to be happening.  Thanks for the help, looks like it's caused by the network infrastructure and is not a general issue with Microsoft browsers.

**Comment by bluepnume** [comment]
Sounds good! That's exactly our understanding too. This is one of those issues we here about a lot from corporate networks, but not from external customers. Annoyingly it's not an issue we have any good solve for.
