### ISSUE TITLE
PayPal integration w/ React.JS | Serveless | Lambda

### ISSUE THREAD

**Issue by rfdc** [paypal/paypal-checkout-components#1013]
### Description
I'm trying to implement paypal to a serveless react app that uses AWS Lambda as REST API. I have found this great video explaining implementation of PayPal REST SDK:
https://youtu.be/7k03jobKGXM

## Problem
But the REST API is suppose to redirect using:
```
"redirect_urls": {
    "return_url": "http://example.com/your_redirect_url.html",
    "cancel_url": "http://example.com/your_cancel_url.html"
  }, 
```
That is an issue for a serveless approach w/ lambda because REST API are called in this manner:
```
const onToken = (amount, description) => async (token) => {
    try {
      const result = await API.post('stripeapi', '/stripe', {
        body: {
          token,
          charge: {
            currency: stripeConfig.currency,
            amount,
            description
          }
        }
      });
      console.log('StripeCheckout result:', result);
      //   history.push('/app/campaigns/PaymentReceived');
      history.push({
        pathname: '/app/campaigns/PaymentReceived',
        state: { data: result }
      });
    } catch (err) {
      console.log('StripeCheckout ERROR:', err);
    }
  };
```
This makes hard to use that redirection approach. 

**Is there a way to overcome this issue?** 

Thanks

**Comment by mcntsh** [comment]
Hey @rfdc, I'm still not clear what the issue is. Are you saying that the return/cancel URL's aren't going to be known at the time you create the payment? In that case you can use the `onCancel` and `onAuthorize` callbacks.

**Comment by rfdc** [comment]
hi @mcntsh, That is right, URL cannot be returned to the app. Does `onAuthorize` returns the the token? Where is it at the docs pls? 

So far I successfully integrate w/ `express-checkout` using `braintree-sdk` because it returns the token via:
```
app.get("/client_token", function (req, res) {
  gateway.clientToken.generate({}, function (err, response) {
    res.send(response.clientToken);
  });
});
```
Can I do something like that w/ the API?
Thanks

**Comment by bluepnume** [comment]
Please see https://developer.paypal.com/docs/checkout/ for full docs on how to integrate without a return url.

**Comment by rfdc** [comment]
Just saw this on the doc:
> Important: The PayPal REST API no longer supports new direct credit card integrations. Please instead consider Braintree Direct; which is, PayPal's preferred integration solution for accepting direct credit card payments in your mobile app or website. Braintree, a PayPal service, is the easiest way to accept credit cards, PayPal, and many other payment methods.

Gonna try something else - thanks

**Comment by bluepnume** [comment]
I'm confused -- are you trying to accept credit cards directly (as in, on a form on your site), or via paypal (after a user logs in our checks out as a guest)? The latter is certainly still possible with this integration.

**Comment by rfdc** [comment]
Hi @bluepnume, I'm trying to accept CC directly. Thought Paypal had checkout feature like Stripe:
https://stripe.com/payments/checkout
It was so easy to implement.
