### ISSUE TITLE
New Facebook messenger webview is not detected as webview

### ISSUE THREAD

**Issue by osus** [paypal/paypal-checkout-components#1019]
Hi guys,

I've been working on an integration into Facebook Messenger webview and found that this old issue:

https://github.com/paypal/paypal-checkout-components/issues/217

Is happening again, probably with the new Messenger release. The popup can't be loaded so the screen stays in the spinner infinitely. It works fine on browsers, desktop or mobile.

My webview user agent is now: 

Mozilla/5.0 (Linux; Android 9; ONEPLUS A5000 Build/PKQ1.180716.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/72.0.3626.96 Mobile Safari/537.36 [FB_IAB/Orca-Android;FBAV/201.0.0.12.99;]

Could you please take a look into this?

Thank you very much.

**Comment by bluepnume** [comment]
We check for `FBAV` so I suspect our detection is working fine. Can you share a video of what you see?

**Comment by osus** [comment]
Hi!

Here you have a video
https://www.dropbox.com/s/u8fxvkviabe67cb/2019_02_13_12_06_48.mp4?dl=0

I've tested in another device and the problem persists. Perhaps it is related to last Messenger version.

In desktop works fine.

**Comment by cesarvarela** [comment]
Any news about this? I'm having the same issue on both iOS and Android

**Comment by bluepnume** [comment]
Tracking here: https://github.com/paypal/paypal-checkout-components/issues/1061
