### ISSUE TITLE
Is now https required for localhost?

### ISSUE THREAD

**Issue by gety9** [paypal/paypal-checkout-components#1025]
When implementing paypal checkout in August we did all the testing on localhost over http and it worked fine.

Now however it works only over https (otherwise nothing happens after button is clicked)

Also there is an error:

```
Content Security Policy: The page’s settings blocked the loading of a resource at http://www.paypalobjects.com/api/checkout.js (“script-src”).
TypeError: window.paypal is undefined
```

FireFox 65, Windows 10

**Comment by bluepnume** [comment]
Sounds like your page is setting a `content-security-policy` header, to block http. 

Also -- `http://www.paypalobjects.com/api/checkout.js` will auto-redirect to `https://www.paypalobjects.com/api/checkout.js` anyway. So you may as well use `https`
