### ISSUE TITLE
Re-load SDK with different parameters

### ISSUE THREAD

**Issue by raRaRa** [paypal/paypal-checkout-components#1028]
Hi.

How do I load the SDK with different parameters after it has been loaded? E.g. on the payment page I pass the `currency`, `commit`, `vault=false`, etc. But then I visit the subscription page and I need to pass `vault=true`

For a client-side application this is an issue. I'd need to manually unload the SDK and somehow load it again.

Any help would be much appreciated.

**Comment by bluepnume** [comment]
Fix is ready for the next release 👍reloading the script will cause the old script and any associated components to be auto-destroyed and `window.paypal` to be repopulated.

**Comment by bluepnume** [comment]
OK this is pushed! Reloading the script will now work without any errors -- it will auto-unmount the previous version when you reload.
