### ISSUE TITLE
[Upgrading Integration] createOrder callback

### ISSUE THREAD

**Issue by martinmckenna** [paypal/paypal-checkout-components#1030]
### Description

I'm having issues upgrading my existing checkout code with the latest version of the JavaScript SDK. Specifically, I'm having issues with the `createOrder` callback which replaced the `payment` callback, as it was deprecated.

The `payment` callback seemed to expect a promise that returned a `payment_id` returned, but `createOrder` expects a promise that returns an `order_id`. Here are my console errors:

```
Uncaught Error: PAYID-1234 does not match pattern for order-id, ec-token or cart-id

Uncaught Error: PAYID-1234 does not match pattern for order-id, ec-token or cart-id
```

And in my code

```js
  /**
   * Callback function which serves the purpose of providing Paypal with
   * the payment_id that we get from APIv4. It is imperative that this step happens before
   * we make the call to our internal API
   */
  createOrder = () => {
    return stagePaymentInMyAPI({
      cancel_url: 'https://hello.com/billing',
      redirect_url: 'https://hello.com/billing',
      usd: (+usd).toFixed(2)
    })
      .then(response => {
        return response.payment_id;
      })
      .catch(errorResponse => {
        return;
      });
  }
```

The issue here is that my server code does not return an `order_id`. Is there any way to create an order without having access to the `order_id`?

**Comment by bluepnume** [comment]
Hi Martin,

There is still a token you can use from /v1/payments api with the new sdk. Please see https://developer.paypal.com/docs/checkout/reference/upgrade-integration/#server-side-rest-integrations-with-v1payments

**Comment by martinmckenna** [comment]
Ok. In that case, I'll open a ticket internally to get our API to return the express checkout code. Just to be clear, will I still need to supply the `payment_id` and `payer_id` to finalize the transaction?

**Comment by bluepnume** [comment]
Yep, that's correct. The SDK will still return `data.paymentID` in `onApprove` to help facilitate that.

**Comment by erin-doyle** [comment]
Using v5 it doesn't look like `paymentID` is being returned by `onApprove` anymore if it was at one time.  I only see `orderID` and `payerID` in `data`.
