### ISSUE TITLE
302 Response from https://www.paypal.com/webapps/hermes/button

### ISSUE THREAD

**Issue by martinmckenna** [paypal/paypal-checkout-components#1031]
### Description

Getting a 302 error when using v4 checkout scripts. Once the button renders this URL is requested

```
https://www.paypal.com/webapps/hermes/button?env=production&style.color=blue&style.shape=rect&domain=mysite.com&sessionID=3a70365e0a_ge3tumjshizde&buttonSessionID=8e50401939_ge3tumjuhi2ta&funding.disallowed=venmo&locale.x=en_US&logLevel=warn&sdkMeta=eyJ1cmwiOnt9fQ%3D%3D&uid=43ab006813&version=4&xcomponent=1
```

which results in a redirect to 

```
https://www.paypal.com/webapps/hermes/error?token=undefined
```

However this 302 error is not consistent among our users. I cannot reproduce consistently myself. For example, this URL gives back a 200 response and I'm not really sure what the delta is between this one and the previous URL:

```
https://www.paypal.com/webapps/hermes/button?env=production&style.color=blue&style.shape=rect&domain=mysite.com&sessionID=0e3034f46b_ge3tunbwhi2ta&buttonSessionID=83a14ab561_ge3tunbwhi2te&funding.disallowed=venmo&funding.remembered=paypal&locale.x=en_US&logLevel=warn&uid=4d1f7f1701&version=4&xcomponent=1
```

### Steps to reproduce

Cannot provide consistent instructions. Only affecting some users. Clearing the cache seems to work but we can't inform every user to do that.

### Other Notes

Upgrading to the new JavaScript SDK for us at this point is not an option - since we have other front-end projects that are relying on the same internal API endpoint. Upgrading the project that is having this issue would mean we need to upgrade our API integration and all other projects that rely on our internal API

### Affected browsers

- [ x] Chrome
- [ ?] Safari
- [x ] Firefox
- [ ?] Edge
- [ ?] IE
- [ ?] Chrome Mobile/Tablet
- [ ?] Safari Mobile/Tablet
- [ ?] Web View / Safari ViewController
- [ ?] Other

**Comment by bluepnume** [comment]
Hi Martin,

This definitely looks like an issue we already uncovered and fixed. But that was at least a month ago. Can you confirm:

1. What's the version you're loading on your site (is it just the standard paypalobjects/checkout.js url?)
2. What version your users see when experiencing the issue? (By typing `paypal.version` in the console)

**Comment by martinmckenna** [comment]
Hey @bluepnume 

I was using this script URL:

`https://www.paypalobjects.com/api/checkout.v4.js`

which was giving me this version number:

`4.0.240`

but after using:

`https://www.paypalobjects.com/api/checkout.js` I get version: `4.0.257`

That seems to work

**Comment by bluepnume** [comment]
Got it. Yeah please do not use checkout.v4.js -- this isn't intended for public consumption and will not always be up to date with the latest fixes.
