### ISSUE TITLE
`validate` prop disappeared on react driver

### ISSUE THREAD

**Issue by IcanDivideBy0** [paypal/paypal-checkout-components#1032]
### Description

Using the react driver, we used to have a `validate` prop which allow to disable the paypal button. This feature seems to have disappeared with latest release.
This was really useful for disabling button if shipping information are not valid for example.

At least, a `disabled` prop would be nice, it's a very basic property to have for a "button" and I think most developers would assume to have it on any kind of button in any language.

`https://www.paypal.com/sdk/js?client-id=xxxx`
> paypal.version
"1.0.114"

**Comment by bluepnume** [comment]
Agreed on this. We're working on getting a better version of validate() in which works for async validation too.

**Comment by bluepnume** [comment]
Please see https://developer.paypal.com/docs/checkout/integration-features/validation/
