### ISSUE TITLE
'Click to Continue' Doesn't re-focus the incontext window in Chrome, Firefox or Safari

### ISSUE THREAD

**Issue by dasx199** [paypal/paypal-checkout-components#1036]
### Description

'Click to Continue' Doesn't re-focus the incontext window in Chrome, Firefox or Safari.
(I know this has been reported for Firefox before, but it seems to affect other browsers as well now!)

Please provide a short description of the issue here, along with:

- Screenshots or videos that show the issue: 
https://drive.google.com/file/d/1sRRUk9FVnrdPsuYfjE19APu1FJ5rtic-/view?usp=sharing 

- Your code: NA - reproduced on the demo site.
- The `paypal.version` from your browser console: 5.0.1
- The exact browser version: 
-- Chrome: Version 72.0.3626.109 (Official Build) (64-bit)
-- Firefox: 65.0.1 (64-bit)
--Safari: Version 12.0.3 (14606.4.5)
- A link to your page with the issue, if possible: https://developer.paypal.com/demo/checkout
- All console logs during the time of the issue, especially error messages
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)? Yes
- Does the issue occur consistently, or intermittently? Consistently

### Steps to reproduce

Steps:
1. Go to: https://developer.paypal.com/demo/checkout/#/pattern/client
2. Click the PayPal button.
3. Once the incontext window loads, click away from it to the merchants site.
4. Click ‘Click to Continue’
5. Observe that the focus isn’t returned to the incontext window.

### Affected browsers

- [X] Chrome
- [X] Safari
- [X] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Thanks for the report! Looks like a browser change finally killed this when the window is focused from a different frame than where it was created.

I have a potential fix that I'll try out soon.

**Comment by bluepnume** [comment]
Fix is in for wednesday checkout.js release.

**Comment by bluepnume** [comment]
This is now resolved for checkout.js in all browsers except firefox.
