### ISSUE TITLE
Handling funding failures (INSTRUMENT_DECLINED error)

### ISSUE THREAD

**Issue by gpozos-pp** [paypal/paypal-checkout-components#1040]
### Description

Documentation (here: https://developer.paypal.com/docs/checkout/integration-features/funding-failure/) specifies that actions.restart() should recover an INSTRUMENT_DECLINED error, nevertheless it is not working neither for client-side (which should have the handler without having to add any code), nor for server-side.  

I used a sandbox account that worked well for checkout.js. This account forces the INSTRUMENT_DECLINED. I performed several tests which you can see here: https://screencast-o-matic.com/watch/cqnO3q0lLi

**Comment by underthecocotree** [comment]
@gpozos-pp I have been looking into performing negative testing as well.

I read that docs page you are linking to a few times as well but I kept missing it.  The code works for server instances.
> Note: This step is necessary if you are directly calling the Orders API from your server. If you are using actions.order.capture(), the PayPal script automatically restarts the Checkout flow and prompts the buyer to select a different funding source.

My guess is that on the server side there needs to be a successful response that has `details.error`.  It would be great if the docs had clearer examples.

How did you set up your sandbox account to get the error.  I see that you are using your preferred payment method which creates the decline.  (I never got to that step)  I only read somewhere that you can tell your sandbox profile to add negative testing.

**Comment by gpozos-pp** [comment]
Basically in order for it to work it must be like this:
` onApprove: function(data, actions) {

          console.log('**data:' + JSON.stringify(data));
          
          return  fetch(CAPTURE_ORDER_URL, {
                    method: "POST",
                    mode: "same-origin",
                    credentials: "same-origin",
                    body: JSON.stringify({
                      "orderID": data.orderID
                    }),
                    headers:{
                      "Content-Type": "application/json"
                    }
                  }).then(function(res) {
                    return res.json();
                  }).then(function(details) {

                    if (details.details[0].issue === 'INSTRUMENT_DECLINED') {
                      return actions.restart();
                    }
                      // Show a success message to the buyer
                      console.log('***Transaction ' + JSON.stringify(details));
                  	  //localStorage.removeItem("cartArray");
                      //window.location = "index.php";
                  });
        },`

Regarding the question you made, you can just turn it on/off in developer.paypal.com . The account I'm using is too old. Before, we needed to set up the account in order for it to decline the transaction.

**Comment by bluepnume** [comment]
Are you still seeing an issue here?

**Comment by gpozos-pp** [comment]
> Are you still seeing an issue here?

Yes.[ Documentation](https://developer.paypal.com/docs/checkout/integration-features/funding-failure/) is wrong regarding the handle of server-side funding failures.  It should be something like this: 
` if (details.details[0].issue === 'INSTRUMENT_DECLINED') {
return actions.restart();
}`
Instead of this:
`if (details.error === 'INSTRUMENT_DECLINED') {
return actions.restart();
}`

**Comment by richardscarrott** [comment]
I've implemented this https://developer.paypal.com/docs/checkout/integration-features/funding-failure/ however I can't see any difference with `actions.restart` and without?...it works fine in both cases -- why do we need to call `actions.restart` if capturing on the server?

**Comment by bluepnume** [comment]
@gpozos-pp I would recommend against returning the entire `details` object from your server. It would be better to pass a flag from your server to indicate that `restart()` needs to be called.

@richardscarrott are you hitting an `INSTRUMENT_DECLINED` error on your server when you test? `actions.restart()` is only necessary when you hit that error. The error indicates that a buyer's card could not be used, and they need to go through the paypal flow again to pick a different card. `actions.restart()` will open up the checkout window again and ask them to pick a different card.
