### ISSUE TITLE
example on paypal connect

### ISSUE THREAD

**Issue by leogoesger** [paypal/paypal-checkout-components#1042]
### Description

Please provide a short description of the issue here, along with:
Is there an example on paypal connect. I have implemented paypal checkout button, but not sure what is the right approach for getting paypal connect for authentication paypal user wokring?

For paypal checkout I am using something similiar to this:
```
const Button = paypal.Button.driver('react', { React, ReactDOM });
```

```
<Button
      env={PAYPAL_ENV}
      client={client}
      payment={(data, actions) => payment(data, actions)}
      onAuthorize={data => execute(data.payerID, data.paymentID)}
      style={{
        size: 'medium', // tiny, small, medium
        color: 'blue', // orange, blue, silver
        shape: 'rect', // pill, rect
      }}
    />
```

**Comment by bluepnume** [comment]
This SDK does not manage paypal connect. Please follow the docs at https://developer.paypal.com/docs/integration/direct/identity/connect-with-paypal/
