### ISSUE TITLE
Call payment() function onEnter

### ISSUE THREAD

**Issue by cipriano200** [paypal/paypal-checkout-components#1045]
Is it possible to call payment function() when the button is initiated, without users to click on the actual button?

I tried doing this:
```
onEnter: function() {
       this.payment();
},
```

Here is my full code:
<div id="paypal-button-container"></div>

    <script>
        paypal.Button.render({

            env: 'sandbox', // sandbox | production

            // PayPal Client IDs - replace with your own
            // Create a PayPal app: https://developer.paypal.com/developer/applications/create
            client: {
                sandbox:    '<insert sandbox client id>',
                production: '<insert production client id>'
            },

			onEnter: function() {
				this.payment();
			},

            // Show the buyer a 'Pay Now' button in the checkout flow
            commit: true,

            // payment() is called when the button is clicked
            payment: function(data, actions) {
                // Make a call to the REST api to create the payment
                return actions.payment.create({
                    payment: {
                        transactions: [
                            {
                                amount: { total: '10.00', currency: 'USD' }
                            }
                        ]
                    }
                });
            },

            // onAuthorize() is called when the buyer approves the payment
            onAuthorize: function(data, actions) {

                // Make a call to the REST api to execute the payment
                return actions.payment.execute().then(function() {
                    window.alert('Payment Complete!');
                });
            },
			
        }, '#paypal-button-container');

    </script>

**Comment by bluepnume** [comment]
No, the user must actually click on the button to proceed.
