### ISSUE TITLE
Determine PaymentMethod (Debit or Credit)

### ISSUE THREAD

**Issue by kkagill** [paypal/paypal-checkout-components#1052]
### Description

Please provide a short description of the issue here, along with:

I'd like to find out whether customer used debit or credit, more specifically which credit card is used (visa, master, etc). 

What should I pass or where can I retrieve that value?

### Steps to reproduce

checkout.js:

     paypal.Button.render({
        env: 'sandbox', // Or 'production',
        style: {
            size: 'medium',
            height: 48,
            color: 'silver',
            shape: 'rect',
            label: 'checkout',
            tagline: 'true',
            fundingicons: 'true',
            layout: 'horizontal'
        },      
        // Set up the payment:
        // 1. Add a payment callback
        payment: function (data, actions) {
            // 2. Make a request to server
            return actions.request.post('/api/RewardsManagerAPI/create-payment/')
                .then(function (res) {
                    ....
                }
              }

backend using PayPal SDK 2.0.0-beta:

    var payment = new Payment()
                {
                    ExperienceProfileId = experienceProfileId,
                    Intent = "sale",
                    Payer = new Payer()
                    {
                        PaymentMethod = ?,
                    },

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Sorry, we do not have plans to support this from the sdk.
