### ISSUE TITLE
Express checkout broken in edge browser

### ISSUE THREAD

**Issue by VivekVikranth** [paypal/paypal-checkout-components#1053]
### Description
In Microsoft Edge as soon as user clicks any smart button paypal sandbox window is opening and automatically the overlay behind the window is closed, While debugging we found that it is automatically calling `onCancel` method. 

[Edge Error.zip](https://github.com/paypal/paypal-checkout-components/files/2962184/Edge.Error.zip)

![triggers_oncancel_automatically](https://user-images.githubusercontent.com/3896638/54291482-e75f8880-45ac-11e9-926c-4a71e373fffa.PNG)

![apaypal_without_overlay](https://user-images.githubusercontent.com/3896638/54291622-1f66cb80-45ad-11e9-801c-8c72fa628916.PNG)

**paypal version** : "4.0.262"

**Affected browsers**
Edge

**Comment by lianee** [comment]
same thing with Chrome, only FireFox seems to work here, tested on [this page](https://developer.paypal.com/demo/checkout/#/pattern/checkout)

**Comment by lianee** [comment]
works again with Chrome

**Comment by bluepnume** [comment]
Can you please share all of the console logs from the point where the page loads and the button is rendered, up to the point where the error happens, from IE11.

**Comment by VivekVikranth** [comment]
Initially I missed to add the meta tag `<meta http-equiv="X-UA-Compatible" content="IE=edge" />`  so the edge browser console I have seen a warning stating missing meta I thought that is causing the issue. But it is not. Even though I added the meta it is not working.

Below are the console logs screenshot of both my page that contains smart buttons and paypal checkout now window after broken.

![Console for page that contains smart buttons](https://user-images.githubusercontent.com/3896638/54607900-cb962f80-4a4f-11e9-8940-9e888264ce69.png)

![Console for paypal checkout now page](https://user-images.githubusercontent.com/3896638/54607949-eb2d5800-4a4f-11e9-97f9-389ce3c8edc4.png)

As I mentioned before, we are facing this issue only on `Microsoft edge (Edge/16.16299)`

**Comment by bluepnume** [comment]
- I've set up a quick demo page -- can you try here: http://bluesuncorp.co.uk/icv4/button.htm
- Does anything in this doc help? We've seen intranet mode can affect edge users too: https://developer.paypal.com/docs/checkout/troubleshoot/internet-explorer/
- Do you see the issue only when browsing on a corporate device? or are you able to reproduce on a personal device off your corporate network?

**Comment by tfulton** [comment]
confirmed, Edge is somehow invoking the onCancel() as the issue suggests.  here is a quick gist that might be easier to diagnose: https://gist.github.com/tfulton/45617db33d90d005975b547623969b5f

**Comment by VivekVikranth** [comment]
@bluepnume To answer your questions -

The quick demo page that you provided me is working fine on my Edge browser.

I haven't got any such error related to intranet.

We don't have access to our DEV environment outside of our corporate network.

**Comment by VivekVikranth** [comment]
Sorry, I closed this ticket by mistake. Re-opened it now,

**Comment by bluepnume** [comment]
Looks like this is almost certainly an intranet issue. There will not be any errors as this is virtually impossible for us to detect in Edge.

I suggest following these guides; unfortunately this is the best we can offer: 

https://developer.paypal.com/docs/checkout/troubleshoot/internet-explorer/
https://medium.com/@bluepnume/ie-intranet-and-trusted-modes-a852d3a0bd47
