### ISSUE TITLE
Unable to display login window on Android mobile phone

### ISSUE THREAD

**Issue by jiangfu204** [paypal/paypal-checkout-components#1054]
### Description

I use the Quick Payment button, the Android mobile browser can not display the login window, in IOS and PC can be used normally, why?
I try to use millet, Huawei mobile browser is not good

`<!DOCTYPE html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <script src="https://www.paypal.com/sdk/js?client-id=AZbcyH7xML8U9pCrZjnlniOMk3xPstN7KOAFJG7s7R9QxSWQq5lGRkqNDBDNyW1SQXJynnKW5uAOgg-a"></script> 
  
</head>

<body>
  <div id="paypal-button-container"></div>

  <script>
  paypal.Buttons({
    createOrder: function(data, actions) {
      return actions.order.create({
        purchase_units: [{
          amount: {
            value: '1.00'
          }
        }]
      });
    },
    onApprove: function(data, actions) {
      // Capture the funds from the transaction
      return actions.order.capture().then(function(details) {
        // Show a success message to your buyer
        alert('Transaction completed by ' + details.payer.name.given_name);
      });
    }
  }).render('#paypal-button-container');
</script>
</body>`

### Steps to reproduce

1. Open this page

2. Click the PayPal button

3. Waiting for a pop-up login window

### Affected browsers

- [ ] Other
Android Mobile Browser

**Comment by isuex** [comment]
Has the problem been solved? What is a good solution?

**Comment by bluepnume** [comment]
Hi all. If you're still seeing this issue, can you please open a new ticket and answer all of the questions (including error logs, screenshots, and exact browser versions)? We really need that information to help triage.

Thanks!
