### ISSUE TITLE
Multiple Paypal buttons throws error

### ISSUE THREAD

**Issue by prindacerk** [paypal/paypal-checkout-components#1066]
I have tried integrating the new Paypal Checkout script into my angular project. The previous script worked fine but as that has been archived and a new version has been promoted, I was trying to change my application to work with the new version.

One problem I have is when I have multiple (3 to be exact) Paypal buttons in the same page. Each button has it's own unique Id and has it's own render call.

I get the following exception.

"Error: zoid desroyed all at no (https://www.paypal.com/sdk/js?client-id=xxxxx&currency=AUD&commit=true:1:100969) at Ra (https://www.paypal.com/sdk/js?client-id=xxxxx&currency=AUD&commit=true:1:186269) at https://www.paypal.com/sdk/js?client-id=xxxxx&currency=AUD&commit=true:1:189023 at Array.forEach (<anonymous>) at Object.value (https://www.paypal.com/sdk/js?client-id=xxxxx&currency=AUD&commit=true:1:188996) at https://www.paypal.com/sdk/js?client-id=xxxxx&currency=AUD&commit=true:1:188375 at Module.<anonymous> (https://www.paypal.com/sdk/js?client-id=xxxxx&currency=AUD&commit=true:1:189062) at t (https://www.paypal.com/sdk/js?client-id=xxxxx&currency=AUD&commit=true:1:157) at https://www.paypal.com/sdk/js?client-id=xxxxx&currency=AUD&commit=true:1:941 at https://www.paypal.com/sdk/js?client-id=xxxxx&currency=AUD&commit=true:1:950"

Please advice on what could be causing this and how to resolve it. I noticed that in the Interactive Window, this happens as well if I were to switch to different links quickly. Don't know if it's the same cause but the error message seems similar.

![image](https://user-images.githubusercontent.com/4536573/54722375-82adba80-4bb8-11e9-92a4-7239ff8d6552.png)

**Comment by bluepnume** [comment]
Are you loading the script multiple times? Can you avoid that? You should be able to render the button without loading the script several times.

**Comment by prindacerk** [comment]
It could be possible. Not sure. I am using a porting package https://github.com/Enngage/ngx-paypal to implement it so maybe that module is loading it multiple times.

One related question though. Why are we passing the Client Id now in the script url? It used to be configurable in the paypalConfig before and that got passed into the render as a parameter. I would prefer that as I change the clientId based on environment and other reasons. Setting it in the script url makes this switching difficult. That's why I had to resort to the component which allowed me to set the PaypalConfig from the javascript and not in the url.

**Comment by bluepnume** [comment]
> Why are we passing the Client Id now in the script url? It used to be configurable in the paypalConfig before and that got passed into the render as a parameter

This means we can decide which buttons you're eligible for when building the script. It means we can deliver a much more streamlined, optimized script that's specific to your site and your buyers.

**Comment by prindacerk** [comment]
Thanks for the explanation. Appreciate it. However, doesn't this create a
risk of exposing the client id to anyone who can just view the page source?
Also, won't I have to configure different urls based on environment
(sandbox or prod) instead of passing a client Id in code in runtime?

This may be a bit messy approach on a SPA architecture I think. Please feel
free to let me know otherwise.

**Comment by prindacerk** [comment]
Rendering this without the package directly is creating the problem mentioned in #1063

**Comment by Enngage** [comment]
@bluepnume Hey, I'm the author of the mentioned `ngx-paypal` lib for Angular. From what I understand, it is not possible to have multiple script on a single page which essentially means you could not have 2 PayPal buttons whose URL parameters differ - e.g. different currency, is that correct? 

Additionally, is there any way of destroying PayPal script? When remove paypal from window object and remove script tag from DOM, it is still not enough because as soon as I try to include new script, it fails with following error: 

```
Bootstrap Error for buttons:

Can not register multiple components with the same tag: paypal-buttons

Error: Can not register multiple components with the same tag: paypal-buttons
```

Can you possibly let me know how can I restore page to its original state as PayPal script was never called? This is especially important for SPA applications where you might go back and forth without hard refresh and you may change parameters of the script.
