### ISSUE TITLE
Checkout.js - return_url issue

### ISSUE THREAD

**Issue by abby999** [paypal/paypal-checkout-components#1068]
PayPal Redirect Issue. 

 - JS CODE : 

	
<div id="paypal-button-container"></div>

<script src="https://www.paypalobjects.com/api/checkout.js"></script>
 <script>
// env: 'sandbox', // sandbox | production
paypal.Button.render({
env: '<%=((String) session.getAttribute("MODE")).equals("LIVE") ? "production" : "sandbox"%>',
locale: 'en_CA',
style: {
label: 'pay',
 fundingicons: true, // optional
branding: true, // optional
  size:  'large', // small | medium | large | responsive
shape: 'rect',   // pill | rect
color: 'blue'   // gold | blue | silver | black
 },
// Show the buyer a 'Pay Now' button in the checkout flow
commit: true,
// payment() is called when the button is clicked
payment: function() {
// Set up a url on your server to create the payment
 var CREATE_URL = '<%=request.getContextPath()%>/createAgreementToken.action';
// Make a call to your server to set up the payment
return paypal.request.post(CREATE_URL).then(function(response1) {
 //alert("My TokenId: " + response1.token_id);
return response1.token_id;
 });
},
onCancel: function(data, actions) {
return actions.redirect();
 },
onError: function(err) {
return actions.redirect();
 },
// onAuthorize() is called when the buyer approves the payment
 onAuthorize: function(data, actions) {
// Set up a url on your server to execute the payment
var EXECUTE_URL = '<%=request.getContextPath()%>/createAgreement.action';
// Set up the data you need to pass to your server
var data = {
 paymentID: data.paymentID,
 billingToken: data.billingToken
};
 // Make a call to your server to execute the payment
return paypal.request.post(EXECUTE_URL, data)
	 .then(function (res) {
console.log(res);
	});
}
						
}, '#paypal-button-container');
 </script>								
		

- paypal.version  

"4.0.263"

 - The exact browser version - 

Firefox Quantum 66.0.1

- All console logs during the time of the issue, especially error messages

Use of Mutation Events is deprecated. Use MutationObserver instead.
script.js:60:8
paypal.version
"4.0.263"
Blocked loading mixed active content “http://pp.netparcel.com/myaccountinfo.action”[Learn More] viewpaymentinfo.action
ppxo_xc_ppbutton_error 
Object { error: "./node_modules/post-robot/src/index.js/_RECEIVE_MESSAGE_TYPE[conf.b.POST_MESSAGE_TYPE.RESPONSE]@https://www.paypalobjects.com/api/checkout.js:4570:31\nreceiveMessage@https://www.paypalobjects.com/api/checkout.js:4612:60\nmessageListener@https://www.paypalobjects.com/api/checkout.js:4633:13\n", timestamp: 1553559019532, windowID: "aa0963c2d9", pageID: "062333790b", prev_corr_ids: "", referer: "https://pp.netparcel.com", host: "www.paypal.com", path: "/webapps/hermes/button", env: "production", country: "CA", … }
 

 ./node_modules/post-robot/src/index.js/_RECEIVE_MESSAGE_TYPE[conf.b.POST_MESSAGE_TYPE.RESPONSE]@https://www.paypalobjects.com/api/checkout.js:4570:31
receiveMessage@https://www.paypalobjects.com/api/checkout.js:4612:60
messageListener@https://www.paypalobjects.com/api/checkout.js:4633:13
logger.js:63:12
ppxo_unhandled_error 
{…}
​
country: "US"
​
env: "production"
​
errtype: "[object Error]"
​
host: "pp.netparcel.com"
​
lang: "en"
​
pageID: "dcc05c43d2"
​
path: "/admin/viewpaymentinfo.action"
​
prev_corr_ids: ""
​
referer: "pp.netparcel.com"
​
stack: "An error was encountered while handling error:\n\n ./node_modules/zoid/src/component/parent/index.js/_class</ParentComponent.prototype.listeners/_ref9[constants.POST_MESSAGE.ERROR]@https://www.paypalobjects.com/api/checkout.js:7529:32\n_loop/listener<@https://www.paypalobjects.com/api/checkout.js:5775:32\n./node_modules/post-robot/src/index.js/_RECEIVE_MESSAGE_TYPE[conf.b.POST_MESSAGE_TYPE.REQUEST]/<@https://www.paypalobjects.com/api/checkout.js:4540:24\n./node_modules/zalgo-promise/src/index.js/promise_ZalgoPromise</ZalgoPromise.try@https://www.paypalobjects.com/api/checkout.js:5660:30\n./node_modules/post-robot/src/index.js/_RECEIVE_MESSAGE_TYPE[conf.b.POST_MESSAGE_TYPE.REQUEST]@https://www.paypalobjects.com/api/checkout.js:4536:17\nreceiveMessage@https://www.paypalobjects.com/api/checkout.js:4612:60\nmessageListener@https://www.paypalobjects.com/api/checkout.js:4633:13\n\n\nonError@https://pp.netparcel.com/admin/viewpaymentinfo.action:473:23\npromisify/</<@https://www.paypalobjects.com/api/checkout.js:9305:28\n./node_modules/zalgo-promise/src/index.js/promise_ZalgoPromise</ZalgoPromise.try@https://www.paypalobjects.com/api/checkout.js:5660:30\npromisify/<@https://www.paypalobjects.com/api/checkout.js:9304:24\nresultValue@https://www.paypalobjects.com/api/checkout.js:6916:32\nonce/<@https://www.paypalobjects.com/api/checkout.js:8717:33\ndecorate/</<@https://www.paypalobjects.com/api/checkout.js:14026:66\n_loop@https://www.paypalobjects.com/api/checkout.js:5529:42\n./node_modules/zalgo-promise/src/index.js/promise_ZalgoPromise</ZalgoPromise.prototype.dispatch@https://www.paypalobjects.com/api/checkout.js:5543:57\n./node_modules/zalgo-promise/src/index.js/promise_ZalgoPromise</ZalgoPromise.prototype.reject@https://www.paypalobjects.com/api/checkout.js:5503:17\n_loop/<@https://www.paypalobjects.com/api/checkout.js:5541:29\n_loop@https://www.paypalobjects.com/api/checkout.js:5529:42\n./node_modules/zalgo-promise/src/index.js/promise_ZalgoPromise</ZalgoPromise.prototype.dispatch@https://www.paypalobjects.com/api/checkout.js:5543:57\n./node_modules/zalgo-promise/src/index.js/promise_ZalgoPromise</ZalgoPromise.prototype.reject@https://www.paypalobjects.com/api/checkout.js:5503:17\n_loop@https://www.paypalobjects.com/api/checkout.js:5525:33\n./node_modules/zalgo-promise/src/index.js/promise_ZalgoPromise</ZalgoPromise.prototype.dispatch@https://www.paypalobjects.com/api/checkout.js:5543:57\n./node_modules/zalgo-promise/src/index.js/promise_ZalgoPromise</ZalgoPromise.prototype.reject@https://www.paypalobjects.com/api/checkout.js:5503:17\nZalgoPromise/<@https://www.paypalobjects.com/api/checkout.js:5458:42\nrequest/</<@https://www.paypalobjects.com/api/checkout.js:16160:21\n\n./node_modules/zoid/src/component/parent/index.js/_class</ParentComponent.prototype.error/<@https://www.paypalobjects.com/api/checkout.js:7781:27\n_loop@https://www.paypalobjects.com/api/checkout.js:5529:42\n./node_modules/zalgo-promise/src/index.js/promise_ZalgoPromise</ZalgoPromise.prototype.dispatch@https://www.paypalobjects.com/api/checkout.js:5543:57\n./node_modules/zalgo-promise/src/index.js/promise_ZalgoPromise</ZalgoPromise.prototype.then@https://www.paypalobjects.com/api/checkout.js:5559:17\n./node_modules/zalgo-promise/src/index.js/promise_ZalgoPromise</ZalgoPromise.prototype.catch@https://www.paypalobjects.com/api/checkout.js:5563:24\n./node_modules/zoid/src/component/parent/index.js/_class</ParentComponent.prototype.error@https://www.paypalobjects.com/api/checkout.js:7780:20\n./node_modules/zoid/src/component/parent/index.js/_class</ParentComponent.prototype.listeners/_ref9[constants.POST_MESSAGE.ERROR]@https://www.paypalobjects.com/api/checkout.js:7529:21\n_loop/listener<@https://www.paypalobjects.com/api/checkout.js:5775:32\n./node_modules/post-robot/src/index.js/_RECEIVE_MESSAGE_TYPE[conf.b.POST_MESSAGE_TYPE.REQUEST]/<@https://www.paypalobjects.com/api/checkout.js:4540:24\n./node_modules/zalgo-promise/src/index.js/promise_ZalgoPromise</ZalgoPromise.try@https://www.paypalobjects.com/api/checkout.js:5660:30\n./node_modules/post-robot/src/index.js/_RECEIVE_MESSAGE_TYPE[conf.b.POST_MESSAGE_TYPE.REQUEST]@https://www.paypalobjects.com/api/checkout.js:4536:17\nreceiveMessage@https://www.paypalobjects.com/api/checkout.js:4612:60\nmessageListener@https://www.paypalobjects.com/api/checkout.js:4633:13\n"
​
timestamp: 1553559019715
​
uid: "655c8a97a4_gaydumbyhiyte"
​
ver: "4.0.263"
​
windowID: "abb9f4fef8"
​
<prototype>: Object { … }
logger.js:63:12

- Does the issue also occur at [developer.paypal.com/demo/checkout]

(https://developer.paypal.com/demo/checkout)? No. I am PayPal REST Billing Agreement Flow

- Does the issue occur consistently, or intermittently?

Consistently 

### Steps to reproduce

Please provide each individual step required to reproduce the issue

URL: https://pp.netparcel.com/home.action, 
1. you need to sign in with PayPal account
2. Click on My Account
3. Click on My Payment Info - Edit button
4. Click on "Pay with PayPal" button
5. After successful, it should go back to the previous page, but it doesn't
[web_browser_console_190325.log](https://github.com/paypal/paypal-checkout-components/files/3005986/web_browser_console_190325.log)

**Comment by bluepnume** [comment]
Looks like the call to the server is failing (a url which is not in our control):

<img width="1389" alt="Screen Shot 2019-03-26 at 3 30 56 PM" src="https://user-images.githubusercontent.com/1219075/55037816-34475400-4fdc-11e9-97e0-fe73f568cff8.png">

Then the code is trying to do `actions.redirect()` in `onError`. That's not supported. Should just do a regular `window.location = '...'` here.

I think all of these failures are specific to the integration.
