### ISSUE TITLE
CORB error from Chrome

### ISSUE THREAD

**Issue by prindacerk** [paypal/paypal-checkout-components#1069]
In Chrome v73, I am getting 
`Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.sandbox.paypal.com/xoplatform/logger/api/logger with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`
in the console. It is creating a lot of noise in the console.

Is there anything I can do to prevent this from happening? Would this happen in Production client id or is it only for the Sandbox client id?

**Comment by bluepnume** [comment]
This is a fire-and-forget call -- but I'll try changing the content-type to application/json and see if that helps. It definitely should not be html.

**Comment by teambuktu** [comment]
Happens in production as well. However, everything is still working. 

Hopefully changing the content-type fixes the issue...whenever it comes to payments, console warnings just look bad ;)

**Comment by bluepnume** [comment]
Thanks for the clarification. I think a recent chrome update might have triggered this. But we have a fix in for the next release.

**Comment by smakosh** [comment]
Seeing the same warning on the console

**Comment by ashishsaxena84** [comment]
> This is a fire-and-forget call -- but I'll try changing the content-type to application/json and see if that helps. It definitely should not be html.

Please suggest how to do it

**Comment by Chris-KCIT** [comment]
Hi, any update on this?

**Comment by rosa2** [comment]
Any update? Thanks

**Comment by gijsmater** [comment]
Hi, is there any update on this issue?

**Comment by glauber-sampaio** [comment]
Hello there! I'm having the same issue and I think it's the cause of error message like "you can't purchase right now. try again later".

**Comment by lcampanis** [comment]
Any update on the issue? Thanks!

**Comment by bluepnume** [comment]
Can anyone confirm if this error is still showing up? Will re-open if so. Thanks!

**Comment by prindacerk** [comment]
It seems to be resolved now. Haven't seen it recently and just tested and couldn't see it.
