### ISSUE TITLE
Amount from session on createOrder

### ISSUE THREAD

**Issue by nestonian** [paypal/paypal-checkout-components#1071]
Is this possible to "enforce" somehow the retrieval of a session variable for the amount.
The exame tries to use the variable cost, but the var is retrieved only once on site opening...

`
    

     paypal.Buttons({
      
      createOrder: function(data, actions) {
      var cost = "<?php echo $this->session->userdata('finalCost')?>";

      // Set up the transaction
      return actions.order.create({
        purchase_units: [{
          amount: {
            value: cost
          }
        }]
      });
    }}).render('#paypal-button-container');

`

**Comment by bluepnume** [comment]
Can you please clarify the question? If you want to retrieve a new `amount` from your server, you can make an ajax call to your server, and return a promise to the `createOrder` function, then call `actions.order.create()` once that ajax call completes.
