### ISSUE TITLE
XMLHttpReq from CORS error and afterwards the pay now button does nothing

### ISSUE THREAD

**Issue by b101** [paypal/paypal-checkout-components#1074]
I'm having the same problem as it was mentioned in [ISSUE 1070](https://github.com/paypal/paypal-checkout-components/issues/1070) 
but when I just continue with the checkout and try to complete the purchase nothing is happening when hitting the pay now button. In my browser dev tools I see this: 

`Failed to load resource: the server responded with a status of 400 () https://www.paypal.com/webapps/hermes/api/checkout/91L22265FX768934B/session/createPayment`

also I can see that something with an object that is being passed around is not right, Im not sure what is tho:

```
windowload_timeout_setting
Object

client_elapsed: 15

event: "windowload_timeout_setting"

level: "info"

pageID: "132fefba"

req_elapsed: 4595

state: "pre_bootstrap"

throttle: 0

timeout: 20000

timestamp: "Sat Apr 06 2019 15:06:22 GMT+0200 (CEST)"

token: "91L22265FX768934B"

Object Prototyp

__defineGetter__(propertyName, getterFunction)

__defineSetter__(propertyName, setterFunction)

__lookupGetter__(propertyName)

__lookupSetter__(propertyName)

constructor: function()

arguments: TypeError: 'arguments', 'callee', and 'caller' cannot be accessed in this context.

assign(target, ...sources)

caller: TypeError: 'arguments', 'callee', and 'caller' cannot be accessed in this context.

create(prototype, [propertiesObject])

defineProperties(object, properties)

defineProperty(object, propertyName, descriptor)

entries()

freeze(object)

fromEntries()

getOwnPropertyDescriptor(object, propertyName)

getOwnPropertyDescriptors()

getOwnPropertyNames(object)

getOwnPropertySymbols(object)

getPrototypeOf(object)

is(value1, value2)

isExtensible(object)

isFrozen(object)

isSealed(object)

keys(object)

length: 1

name: "Object"

preventExtensions(object)

prototype: {}

seal(object)

setPrototypeOf(object, prototype)

values()

Function Prototyp

hasOwnProperty(propertyName)

isPrototypeOf(property)

propertyIsEnumerable(propertyName)

toLocaleString()

toString()

valueOf()
```

I dont know what this is supposed to be `TypeError: 'arguments', 'callee', and 'caller' cannot be accessed in this context.` but it doesnt seem right.
maybe its all related to the CORS problem? 

_Originally posted by @b101 in https://github.com/paypal/paypal-checkout-components/issues/1070#issuecomment-480502239_

**Comment by bluepnume** [comment]
Please open a new issue and answer all of the asked questions, including a link to a page where we can reproduce the issue, and instructions to reproduce. Thanks!

**Comment by b101** [comment]
@bluepnume another new issue? I thought this one would do 😅because it is a new one..
