### ISSUE TITLE
Payment REST API return 403 "PERMISSION_DENIED"

### ISSUE THREAD

**Issue by libaoqian** [paypal/paypal-checkout-components#1076]
### Description
 I created a new application and it does not work, with the client_id of an old application works well, it seems that happen with the new apps.

`curl --verbose --request POST 'https://api.sandbox.paypal.com/v1/payments/payment/PAYID-LSWYSTY5GC60571HK0201839/execute' \
  --header "Authorization:BearerA21AAEC82KJpvWx_UCOMoJpdCDbFNcePiBP7hzqMrwa5jRd1Bj5KWBjY0PKzfRyqQHCsE9RBkkovxEG_D3QdQLw21a0L3RZFQ" \
  --header "User-Agent:PayPalSDK/  (v=1.8.0_40; vendor=Oracle Corporation; bit=64; 
       os=Windows_8.1 6.3)" \
  --header "PayPal-Request-Id:16c8341b-fbe4-4cb7-b8de-3a75e9c6d261" \
  --header "Accept:application/json" \
  --header "Content-Type:application/json" \
  --data '{
  "payer_id": "4UDMF95SXWHPA"
}'
Error response:
 {"name":"PERMISSION_DENIED","message":"No permission for the requested operation"
 ,"information_link":"https://developer.paypal.com/docs/api/payments/#errors",
 "debug_id":"fafc3222f2d8a"}`

**Comment by bluepnume** [comment]
Please make sure the client id you're using to set up the payment is the same client id you're using to call /execute.
