### ISSUE TITLE
Page close and page unload trigger onError function of Smart Payment Button

### ISSUE THREAD

**Issue by kerko** [paypal/paypal-checkout-components#1077]
### Description
When you define an onError function like in the following code example, every time you navigate away from a page with a Smart Payment Button the following happens : 
* Browser opens new url
* Browser get immediately redirected to url defined in on error

Is this expected behavior of the onError function ? It doesn't feel right to check the message of the error to not show the errorpage on errors with message "Window navigated away"

-  `paypal.version`  "5.0.23"
- The exact browser version  -> Firefox 66.0.2
- All console logs during the time of the issue, especially error messages -> "Errormessage is: Window navigated away"

### Steps to reproduce
* Add Smart Payment Button mit the following on ErrorFunction:
`onError: function(error) {
    window.location.href = "https://mydomain.com/errorPage";
 }`
* Naviagte away from page 
Please provide each individual step required to reproduce the issue

### Affected browsers
Only tested this with Chrome and Firefox. Chrome seems to ignore the location change.
- [ ] Chrome
- [x] Firefox

**Comment by bluepnume** [comment]
Can you let me know the specific error you see being passed to `onError`? And do you have a page where we can reproduce the problem?

**Comment by kerko** [comment]
Hi the Error passed is "Window navigated away"
I was able to trace it back to this function in the sdk : 
```
 _proto.watchForUnload = function watchForUnload() {
                var _this16 = this;

                var unloadWindowListener = addEventListener(window, 'unload', once(function() {
                    _this16.component.log("navigate_away");

                    _this16.destroy(new Error("Window navigated away"));
                }));
                this.clean.register(unloadWindowListener.cancel);
            }
            ;
```
I was no able to create a simple reproducer and we already have a workaround in place on our page :/. Maybe this is a race condition that the unload eventListener is not canceled fast enough somehow on our page ?

**Comment by springknees** [comment]
I have the same/similar issue - here are the specific details.

It can reproduced by adding the documented onError function to the demo page at (https://developer.paypal.com/demo/checkout), like this:-

`onError: function (err) {	 console.log("Error here");  console.log(err);   }`

A page load/refresh triggers the "Window navigated away" error at each page load time. The console displays:-

> Error: Window navigated away
 at VM31 js:1
 at VM31 js:1

Tested with Chrome Version 75.0.3770.100 (Official Build) (64-bit) desktop in both Sandbox and Production SDK

**Comment by shrayasr** [comment]
@bluepnume et. al. 

This is an issue that I'm facing as well. And as @springknees pointed out, it still happens on the demo page. Are there any plans to add this issue to your roadmap soon? It would be really helpful make this already great SDK even better.

**Comment by bluepnume** [comment]
Hi all,

Taking another look into trying to reproduce the issue. Can you confirm if you're still seeing it? Thank you

**Comment by shrayasr** [comment]
Hi @bluepnume. 

We are still seeing it, yes.

**Comment by noctivityinc** [comment]
We have this error as well.  Is there any resolution
