### ISSUE TITLE
Clicking the button on the mobile page is invalid.

### ISSUE THREAD

**Issue by i7eo** [paypal/paypal-checkout-components#1080]
### Description

The buttons worked in the desktop browser, but when I used chrome mobile debugging, it didn't work. Safari mobile debugging worked. This confused me. At first I suspected it was a style problem, but in safari it worked.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by i7eo** [comment]
Chrome Mobile/Tablet is invalid, Safari Mobile/Tablet is effective.

**Comment by bluepnume** [comment]
Please fill out the entire issue template when submitting issues. We ask specific questions to help us triage.
