### ISSUE TITLE
checkout.js button not clickable at some portion

### ISSUE THREAD

**Issue by kitrak17** [paypal/paypal-checkout-components#1086]
### Description
SPB is not clickable only at the some portion(especially at the top section) in few mobile devices when we test it in the Chrome browser. Also this happens only when we use Bootstrap classes along with the button render code.

Please provide a short description of the issue here, along with:

- Screenshots or videos that show the issue
![image](https://user-images.githubusercontent.com/20160950/56646841-fc483500-669d-11e9-8103-ce74e86c970b.png)

- Your code
<script>  
                paypal.Button.render({
                    env: 'sandbox',
                    style:{
                        layout: 'vertical', 
                        size:  'medium',   
                        shape: 'rect',   
                        color: 'gold'   
                    }, 
                    client: {  
                        sandbox: 'xxxxxx' 
                    },  
                    commit: true, 
                    payment: function(data, actions) { 
                        return actions.payment.create({  
                            payment: {  
                                transactions: [{  amount: { total: '1.00', currency: 'AUD' }, item_list: { items: [  { name: 'Test product', quantity: '1', price: '1.00', currency: 'AUD' } ] } }] 
              
                            } 
                        })
                    },  
                    onAuthorize: function(data, actions) { 
                            return actions.payment.execute().then(function(payment) { alert('Payment completed');  });  
                    } 
                }, "#paypal-button");
    </script>

- The `paypal.version` from your browser console
4.0.267

- The exact browser version
Version 73.0.3683.103 (Official Build) (32-bit)

- A link to your page with the issue, if possible
https://spb-onclick-issue.herokuapp.com/

- All console logs during the time of the issue, especially error messages
No error messages.

- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
No. This issue occurs only when we use it along with bootstrap package and with the nav classes.
- Does the issue occur consistently, or intermittently?
Consistently

### Steps to reproduce
1. Include the bootstrap js and css in the html file.
2. Place the PayPal button inside the bootstrap classes.
3. Run the page in the Chrome browser.
4. Click F12 and Toggle the device toolbar
5. Choose the device Pixel 2, Pixel 2 XL, iPhone 6,7,8 plus

### Affected browsers
- [x] Chrome

**Comment by bluepnume** [comment]
Are you still able to repro? I can't get the issue to occur in chrome.

Does this happen in real mobile device browsers, or only in chrome in mobile testing mode?
