### ISSUE TITLE
Sandbox returns oncancel on all transactions since 4/29/19

### ISSUE THREAD

**Issue by Ed-SA** [paypal/paypal-checkout-components#1088]
### Description

Code working 2 days ago now fires onCancel event always, regardless of payment method chosen (tried sandbox paypal account, test visa, test mastercard, etc).

### Steps to reproduce

Any sandbox transaction using the javascript buttons API now fails.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [x ] Firefox
- [ ] Edge
- [ x] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Thanks for the heads-up. This should now be fixed -- can you please check and see if you're still seeing the issue?

**Comment by Ed-SA** [comment]
That was fast!  Works fine again now, thanks!!
