### ISSUE TITLE
Can't scroll down on messenger Webviews

### ISSUE THREAD

**Issue by gbaudry303** [paypal/paypal-checkout-components#1089]
### Description

On the facebook messenger WebViews, when the paypal button modal is opened, it is not possible to scroll down the modal. 

- The `paypal.version` from your browser console
latest from the sdk
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
yes
- Does the issue occur consistently, or intermittently?
consistently

### Steps to reproduce

Just open up the demo button on a fb webview (opening the link on the facebook, messenger or instagram mobile app) [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)
Make sure more content than the height of the modal is loaded. The credit card buttons works well for that. 

### Affected browsers

- [x] Web View / Safari ViewController

**Comment by gbaudry303** [comment]
kinda related to issue #1061

**Comment by bluepnume** [comment]
Thanks for the report. I believe I've discovered the problem; pushing a potential fix tomorrow.

**Comment by gbaudry303** [comment]
fantastic, if possible let me know when the potential fix has been deployed, so I can test it.

**Comment by bluepnume** [comment]
Feel free to give it a try. Hopefully you get the latest script; if it's still broken please wait a few hours then try once more.

Thanks again!

**Comment by gbaudry303** [comment]
it did fix the issue, thanks a lot!

**Comment by sheravanan** [comment]
Hi Guys, I am also facing this issue. I am using a web-view angular component inside my mobile app. when the PayPal sandbox opens it's not able to scroll. I am using Braintree services. Please help me, anybody. it would be very helpful. I appreciated your reply. Thanks

**Comment by bluepnume** [comment]
@sheravanan can you please raise a new issue and answer all of the questions? Thanks,
