### ISSUE TITLE
MicroSoft Edge - Closing of pop up window throwing errors on page

### ISSUE THREAD

**Issue by alisonp** [paypal/paypal-checkout-components#1091]
Hi there, 
Error occurring with orders V2 Payments sdk in production. This browser has been used to test the website while in sandbox mode and this error was not present.

When closing the PayPal pop-up, the following errors are thrown. The JavaScript seems to stop processing further, which we believe causes users to not be able to click on anything within the webpage. At this point the website page becomes frozen and no actions can be taken by the user.
When the JS stops working this results in the full scale viewport overlay (s) <DIV> elements not being destroyed, as a result, no page elements can be focused. 

Error message 
SCRIPT5007: Unable to set property 'knownWindows' of undefined or null reference
js (1,49881)

SCRIPT462: The remote server machine does not exist or is unavailable
js (1,5011)
{
   [functions]: ,
   __proto__: { },
   env: "production",
   err: "Error: The remote server machine does not exist or is unavailable

Steps to reproduce

Merchant using Edge v42.17134.1.0 ,Click on PayPal button then close the window. Or input incorrect login details.

Affected browsers

- [x] Edge

The issue look similar to that of issue 1087 but the conditions for triggering are a little different. 

Thanks

**Comment by bluepnume** [comment]
Hi @alisonp -- could you please answer the questions from the original issue template? We at least need a url where we can test this out :)

**Comment by alisonp** [comment]
Yes here is the URL
https://staging.rnib.panlogic.co.uk/donations-and-fundraising/donate-now 

Thanks

**Comment by jpbarber1** [comment]
You can see the problem on our dev site at https://www.uktights.info 
PayPal credit and Guest checkouts (cards) cause the overlay to remain in Edge when the Popup is closed.
If you pick PayPal Express all ok if you pick PayPal Express then change to guest and close overlay remains.

**Comment by bluepnume** [comment]
Can you check this issue again? We've rolled out some potential fixes.

(If you still see issues, please also let me know what you see when entering `paypal.version` in your javascript console. Thanks!)

**Comment by jpbarber1** [comment]
Hi Daniel

 

No change, it still has the overlay on Edge when the popup is closed

 

Cheers

Jonathan

**Comment by alisonp** [comment]
Hi Daniel,

Thanks for the update.
The issue still remains. 
The PayPal version returned: 5.0.29

**Comment by bluepnume** [comment]
Quick update: I managed to reproduce this issue in my testing environment. I've pushed out another fix which resolved the issue for me.

Can you please test again, and make sure console.log(paypal.version) in your browser console shows at least '5.0.32'.

Thanks,
Daniel

**Comment by jpbarber1** [comment]
Looks like you've fixed it.

Many thanks
Jonathan

**Comment by alisonp** [comment]
Hi Daniel, I can confirm also that the issues has been resolved.
Many thanks

**Comment by irbrownie** [comment]
Please explain what his fix was as I'm facing this in my own application.
