### ISSUE TITLE
Enforce shipping address

### ISSUE THREAD

**Issue by peppeocchi** [paypal/paypal-checkout-components#1093]
### Description

I was using the previous version of the checkout and it allowed me to pass a shipping address and to enforce that address to the users, preventing them to change it. A nice message was showing up when they tried to change it

<img width="449" alt="Screenshot 2019-05-06 at 18 35 12" src="https://user-images.githubusercontent.com/4161743/57240228-3ca89b00-702e-11e9-8d30-c20aa24544f3.png">

Even when choosing "Pay with a Debit or Credit Card" the shipping address wasn't being shown

<img width="441" alt="Screenshot 2019-05-06 at 18 50 32" src="https://user-images.githubusercontent.com/4161743/57240926-1a178180-7030-11e9-855a-b987364320f2.png">

### New version of the checkout

Now with the new version of the checkout there is no way to enforce a shipping address and the users are allowed to change it to any of their saved addresses. No differences when I set the parameter
```javascript
application_context: {
     shipping_preferences: 'SET_PROVIDED_ADDRESS',
},
```
<img width="433" alt="Screenshot 2019-05-06 at 18 56 51" src="https://user-images.githubusercontent.com/4161743/57241212-c9ecef00-7030-11e9-9a81-88b5455801a7.png">
<img width="435" alt="Screenshot 2019-05-06 at 18 57 06" src="https://user-images.githubusercontent.com/4161743/57241214-ca858580-7030-11e9-8733-79955579cfad.png">

And when paying with a debit/credit card there is also the option to "Ship to my billing address"

<img width="443" alt="Screenshot 2019-05-06 at 18 51 26" src="https://user-images.githubusercontent.com/4161743/57240957-31566f00-7030-11e9-8466-4999a078dcdc.png">

### This is the problem

The option to change shipping address caused a lot of headaches with our customers because of frauds they couldn't get the money back for, because the shipping address of the order on our system was different than the shipping address saved against the PayPal payment.
It seems the only option could be to listen for address changes and reject the order if that changes?

This is my code

```javascript
paypal.Buttons({
    style: {
        layout:  'vertical',
        color:   'blue',
        shape:   'rect',
        label:   'pay'
    },
    createOrder: (data, actions) => {
        return actions.order.create({
            intent: 'CAPTURE', // DEV ONLY
            application_context: {
                 shipping_preferences: 'SET_PROVIDED_ADDRESS',
            },
            purchase_units: [{
                 reference_id: this.orderId,
                 description: 'Attempt n.' + this.attempt + ' for Quote ID ' + this.orderId,
                 amount: {
                     currency_code: this.currency,
                     value: this.total
                 },
                 shipping: {
                      address: {
                          address_line_1: this.deliveryAddress.line1,
                          address_line_2: this.deliveryAddress.line2,
                          admin_area_2: this.deliveryAddress.city,
                          admin_area_1: this.deliveryAddress.state,
                          postal_code: this.deliveryAddress.zip,
                          country_code: this.deliveryAddress.country,
                      }
                  }
              }]
          })
      },
      onApprove: (data, actions) => {
          return actions.order.capture().then(this.charge)
      }
}).render('#pb-container');
```

**Comment by peppeocchi** [comment]
Just to add some more info about the problem with different shipping address, by default a transaction that has a shipping address (in PayPal) and is delivered to a different address does not qualify for the "Seller Protection Programme" as described in [section 11.6](https://www.paypal.com/uk/webapps/mpp/ua/useragreement-full?locale.x=en_GB#r011)
> For tangible items, post the item to the shipping address on the “Transaction Details” page. If the item is delivered in person or if the Payment Recipient posts the item to a different address (for example, if the buyer asks that you send to another address on the basis that it is a “work address” or a “gift” address) then you will not be eligible for re-imbursement under the terms of the programme

The use case is that a user goes through our checkout flow, selects billing/shipping address, then at the last step he's presented with the "Pay with PayPal" button that loads the PayPal UI. At that point the order is saved on our records with a shipping address (it might be a fraudulent address), but then if he's able to change the shipping address when making the payment, the transaction in PayPal will have a different address than where we're actually delivering the items. To avoid this issue with the previous version of the checkout we were able to enforce (and not let the user change) the shipping address and that decreased a lot the attempts of frauds, and also increased the number of transactions that were eligible for the "Seller Protection Programme".

**Comment by bluepnume** [comment]
@rajarampadmanathan can you please help with this one.

**Comment by rsdighe76** [comment]
it should be                  

```shipping_preference: 'SET_PROVIDED_ADDRESS',```

there is no "s" at the end of preference it's "preference" not "preferences"

can you please let me know where did you read it as shipping_preferences - looks like a documentation issue to me that we can help fix. 

Thanks

**Comment by peppeocchi** [comment]
Hi @rsdighe76 thanks for your reply, I thought I did a copy&paste but I probably added a "s" by mistake, sorry that was my bad. This issue can be closed thanks!

Something I noticed is that if I have both the braintree drop in and the paypal sdk, most of the requests via the paypal sdk are failing with 
```
{
    "name": "AUTHENTICATION_FAILURE",
    "message": "Authentication failed due to invalid authentication credentials or a missing Authorization header.",
```

But I can see the authorization header in the **orders** request

![Screenshot 2019-05-14 at 11 18 59](https://user-images.githubusercontent.com/4161743/57686592-25733a00-763a-11e9-9b3e-c6789b1f1274.png)


This to me feels very random, if I keep clicking on the "PayPal" button sometime it works and sometime it doesn't, see screenshot below that over 3 requests, the first one was a success (201), the second one failed (401) and the third click was a success again (201).
![Screenshot 2019-05-14 at 11 20 35](https://user-images.githubusercontent.com/4161743/57686976-e0033c80-763a-11e9-855d-11add9ba811b.png)

Or in the example below where a bunch of 201 and 401 are being returned.
![Screenshot 2019-05-14 at 11 28 44](https://user-images.githubusercontent.com/4161743/57687300-79325300-763b-11e9-9353-609be8df7c32.png)


If I remove the Braintree dropin script I constantly get a success (201).

So just to be clear, if I have both these scripts in the html page
```
<script src="https://js.braintreegateway.com/web/dropin/1.18.0/js/dropin.min.js"></script>
<script src="https://www.paypal.com/sdk/js?client-id=my_client_id&currency=gbp"></script>
```
I get random failures
But if I have only the paypal sdk
```
<script src="https://www.paypal.com/sdk/js?client-id=my_client_id&currency=gbp"></script>
```
no failure

I didn't notice any failure from the Braintree dropin when both scripts are loaded

Does that ring any bell?

Thanks!

**Comment by peppeocchi** [comment]
Maybe the 401 error is unrelated to what I mentioned, for some reason it doesn't happen when the braintree dropin script is there on my dev env.
It seems there is some issue with the Paypal Sandbox Environment, even the demo page (https://developer.paypal.com/demo/checkout/#/pattern/client) doesn't work giving back the same authorization error, and I've tested other sites where I've implemented paypal checkout and most of them with the sandbox client id give back an intermittent 401 error.

**Comment by rajarampadmanathan** [comment]
@bluepnume - This looks like the same SBX authentication issue which your'e working on. Can you please provide the reference ticket number here?

**Comment by bluepnume** [comment]
Are you still seeing this issue?

**Comment by peppeocchi** [comment]
@bluepnume I haven't seen this happening in the last month of testing, I think this can be closed thanks for the help!
