### ISSUE TITLE
Error with 'tracking' (STC) for client side integration. 

### ISSUE THREAD

**Issue by zanneee** [paypal/paypal-checkout-components#1094]
### Description

The error has been occurred since STC API migration in end of April, therefore the merchant cannot complete the checkout with 'tracking' fields.

Please provide a short description of the issue here, along with:

Here's a feedback from the team - https://engineering.paypalcorp.com/jira/browse/PPPLMER-70210

> This was an intentional change that we did and returned a response with no entity instead of an empty object with null values in all the fields
> 
> We migrated recently from riskassessmentserv(helix) to riskpartnerinfoserv(raptor) which was a platform change and we always returned the below response which was an empty object
> {"tracking_id":null,"sender_account":null,"receiver_account":null,"sub_orders":[],"device":null,"ip_address_info":null,"additional_data":[],"create_time":null,"update_time":null}
> 
> 
> If the clients want to validate the POST/PUT call they can use the GET api using the tracking id that can fetch the data that was posted/saved in STC call.
> 

### Steps to reproduce
`
    <script>
        paypal.Button.render({

            env: 'production', // sandbox | production

            // PayPal Client IDs - replace with your own
            // Create a PayPal app: https://developer.paypal.com/developer/applications/create
            client: {
                sandbox:    '',
                production: 'AbgkAf2i8o0OyoU4dwp5bbbdHjeTO7CgrJofTg9sxXSzXnZLtziOlzTR5EE2AV6pwcoP4GDmmsMriBYd'
            },

            // Show the buyer a 'Pay Now' button in the checkout flow
            commit: true,

            // payment() is called when the button is clicked
            payment: function(data, actions) {

                // Make a call to the REST api to create the payment
                return actions.payment.create({
                    tracking: {
                        "id": "ZGVDJYCLAQ3DL",
                        "data": [
                            {
                                "key": "sender_account_id", "value": "12345"
                            },
                            {
                                "key": "sender_first_name", "value": "Peter"
                            }
                        ]
                        },
                    payment: {
                        transactions: [
                            {
                                amount: { total: '0.01', currency: 'USD' }
                            }
                        ]
                    }
                });
            },

            // onAuthorize() is called when the buyer approves the payment
            onAuthorize: function(data, actions) {

                // Make a call to the REST api to execute the payment
                return actions.payment.execute().then(function() {
                    window.alert('Payment Complete!');
                });
            }

        }, '#paypal-button-container');

    </script>
</body>
`

Error in console

> strategies.js:55 Uncaught Error: Error: Invalid json: . Correlation id: 8c9cde16c58e3, 8c9cde16c58e3
    at XMLHttpRequest.<anonymous> (VM112 checkout.js:16298)
    at Object._RECEIVE_MESSAGE_TYPE.<computed> [as postrobot_message_response] (VM112 checkout.js:4570)
    at receiveMessage (VM112 checkout.js:4612)
    at messageListener (VM112 checkout.js:4633)
    at Object._RECEIVE_MESSAGE_TYPE.<computed> [as postrobot_message_response] (VM112 checkout.js:4570)
    at receiveMessage (VM112 checkout.js:4612)
    at messageListener (VM112 checkout.js:4633)
    at deserializeError (VM112 checkout.js:5215)
    at VM112 checkout.js:5236
    at VM112 checkout.js:5050
    at eachArray (VM112 checkout.js:5033)
    at each (VM112 checkout.js:5039)
    at replaceObject (VM112 checkout.js:5049)
    at VM112 checkout.js:5051
    at eachObject (VM112 checkout.js:5036)
    at each (VM112 checkout.js:5039)
    at replaceObject (VM112 checkout.js:5049)

**Comment by bluepnume** [comment]
I've reported this to the owner of this api. They're planning to make a fix.

**Comment by bluepnume** [comment]
Are you still seeing this issue?
