### ISSUE TITLE
PayPal button not working on Chrome Canary (76.0.3787.0)

### ISSUE THREAD

**Issue by longbridge-pm** [paypal/paypal-checkout-components#1096]
### Description

Please provide a short description of the issue here, along with:

- Screenshots or videos that show the issue
- Your code
Create a html (e.g. paypal.html) using source from (https://developer.paypal.com/demo/checkout/#/pattern/client)
- The `paypal.version` from your browser console
"5.0.29"
- The exact browser version
Chrome Canary (76.0.3787.0)
- All console logs during the time of the issue, especially error messages
Uncaught TypeError: Cannot read property 'sessionID' of undefined

- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
No
- Does the issue occur consistently, or intermittently?
Consistently

### Steps to reproduce

1. Create a html (e.g. paypal.html) using source from (https://developer.paypal.com/demo/checkout/#/pattern/client)
2. start a static http server (e.g. npx server -l 8081)
3. browse to the html (e.g. http://localhost:8080/paypal.html)

At Step 3
Expected: PayPal button works (Note; This is working with Chrome (74.0.3729.131))
Actual: PayPal button does not work when clicking on it
Note: observe the following error in console
```
Uncaught TypeError: Cannot read property 'sessionID' of undefined
```

Note: It seems that the window.xprops was undefined.

### Affected browsers

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Does the issue occur when you run the sdk on an https server, rather than http?

**Comment by longbridge-pm** [comment]
![Paypal_SessionID_error](https://user-images.githubusercontent.com/49376558/57736238-8ce8c280-76ea-11e9-9cf0-0236013db31f.png)

I started a local static http server by running
```
npx serve -l 8081
```

**Comment by AbuHani** [comment]
I have same issue on google chrome canary (76.0.3805.0)
<img width="1440" alt="Screen Shot 2019-05-25 at 3 40 58 PM" src="https://user-images.githubusercontent.com/17643875/58369486-c64bda00-7f03-11e9-8375-95396f4cb3ed.png">

**Comment by sheepsteak** [comment]
I've also been getting this with Google Chrome Dev (76.0.3807.0). I just tried Google Chrome Beta (75.0.3770.66) and it works.

I've made a CodePen that uses the [React demo in this repo](https://github.com/paypal/paypal-checkout-components/blob/master/demo/react.htm). If you try on Google Chrome Dev you'll get the `sessionID` error. On Google Chrome Beta everything will work fine:

https://codepen.io/anon/pen/KLJerM

**Comment by sheepsteak** [comment]
I think this issue has now progressed to Chrome Beta as 76 has now moved on to there:
![image](https://user-images.githubusercontent.com/1379888/60103285-3ba30880-9757-11e9-95f9-3677b63ad099.png)

Here is a CodePen you can try which contains what is in https://github.com/paypal/paypal-checkout-components/blob/master/demo/button.htm

https://codepen.io/anon/pen/KLJerM

Works in every browser except Chrome Beta (76) for me.

**Comment by sheepsteak** [comment]
I've just tried this on Chrome 77 and the latest Chrome Dev (78.0.3876.0) and the problem seems to be resolved.

**Comment by bluepnume** [comment]
Thanks for confirming!
