### ISSUE TITLE
Merchant receiving errors in console.

### ISSUE THREAD

**Issue by Phyrekracker** [paypal/paypal-checkout-components#1097]
We are seeing some errors in the console, and while everything seems to work fine, we are wondering whether we could/should eliminate any of them.
 
1.	 On the shopping cart page, when a returning Paypal user clicks Paypal button, we do not want to proceed to Paypal, but redirect to our Summary page.  To test whether the user is returning we are hooking in into the Buttons.createOrder callback.  The following error appears on Paypal button click. 
 
 
 
js?client-id=sb&commit=false&currency=USD&disable-funding=card%2Ccredit&intent=authorize&locale=en_US:1 Uncaught Error: Expected a promise for a string order id to be passed to createOrder
    at https://www.paypal.com/sdk/js?client-id=sb&commit=false¤cy=USD&disable-funding=card%2Ccredit&intent=authorize&locale=en_US:1:183397
    at i (https://www.paypal.com/sdk/js?client-id=sb&commit=false¤cy=USD&disable-funding=card%2Ccredit&intent=authorize&locale=en_US:1:5396)
    at n.e.dispatch (https://www.paypal.com/sdk/js?client-id=sb&commit=false¤cy=USD&disable-funding=card%2Ccredit&intent=authorize&locale=en_US:1:5859)
    at n.e.resolve (https://www.paypal.com/sdk/js?client-id=sb&commit=false¤cy=USD&disable-funding=card%2Ccredit&intent=authorize&locale=en_US:1:4543)
    at https://www.paypal.com/sdk/js?client-id=sb&commit=false&currency=USD&disable-funding=card%2Ccredit&intent=authorize&locale=en_US:1:4190
 
 
Our implementation of the buttons on the Cart page is as follows.  We use server side setup of the order contents and authorization.  
 
         onLoadedPaypalScript = () => {
                 const paypalButtonsRef = paypal.Buttons({
                          style: {
                                   height: 25,
                                   label: 'checkout',
                                   layout: 'horizontal',
                                   tagline: false
                          },
                          createOrder: (e: any) => { 
                     return zfetchPost('/co/expressCheckout', { returnToken: true }, { postAsFormUrlEncoded: true }).then((data: any) => {
                                           // reference transaction dictates we skip to Summary page
                                            if (data.redirectUrl) {
                                                    window.location.href = data.redirectUrl; // ! this is when the error occurs
                                            }
                                            else {
                                                    return data.token;
                                            }
                                   })
                          },
                          onApprove: (data: any) => {
                                   const url = addReplaceQSParams(this.props.zUrl('WwwPag', 'co/summary'), {
                                            // checkout keep cache
                                            ckc: true,
                                            // express checkout shortcut
                                            ecs: true,
                                            PayerId: data.payerID,
                                            token: data.orderID
                                   });
                                   window.location.href = url;
                          },
                          onCancel: (e: any) => {
 
Other errors seem to be coming from your scripts:

2. CORP error:
js?client-id=sb&commit=false&currency=USD&disable-funding=card%2Ccredit&intent=authorize&locale=en_US:1 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.sandbox.paypal.com/xoplatform/logger/api/logger with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
 
3. Non-passive event listener:
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
Recommendation from Lighthouse: https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners

**Comment by bluepnume** [comment]
> On the shopping cart page, when a returning Paypal user clicks Paypal button, we do not want to proceed to Paypal, but redirect to our Summary page

This is not a supported pattern right now. The SPB only supports first-time users. We will be introducing support for returning users in the next few months.
