### ISSUE TITLE
Responsive width issue

### ISSUE THREAD

**Issue by asecaida** [paypal/paypal-checkout-components#1099]
This is my current configuration,
`{
    locale: 'en_US',
    style: {
        size: 'responsive',
        shape: 'rect',
        color: 'white',
        tagline: 'false'
    },
	funding: {
		disallowed: [ paypal.FUNDING.CARD ]
	}
}`

From the docs, https://developer.paypal.com/docs/archive/checkout/how-to/customize-button/#size, if I set size to responsive my minimum width should be 100px but it's actually 150px.  Am I doing something wrong.

![image](https://user-images.githubusercontent.com/3698208/57490532-6c45e600-726e-11e9-98f4-8c507ad5ac34.png)

**Comment by bluepnume** [comment]
The minimum width of the paypal button is 150px.

**Comment by asecaida** [comment]
![image](https://user-images.githubusercontent.com/3698208/57672147-b52dcf80-75cb-11e9-9bbe-2d225572db60.png)
