### ISSUE TITLE
Question: How to disable the card icons in ReactJS

### ISSUE THREAD

**Issue by radi-cho** [paypal/paypal-checkout-components#1102]
### Question
How to disable the card icons in ReactJS?
I tried passing fundingIcons prop or fundingIcons parameter in the style object, but without effect.
Also tried to add funding prop with disallowed `paypal.CARD`, but it throws undefined.

**Comment by bluepnume** [comment]
Please see https://developer.paypal.com/docs/checkout/reference/customize-sdk/#disable-funding
