### ISSUE TITLE
set funding.allowed paypal.FUNDING.CARD has some errors

### ISSUE THREAD

**Issue by i7eo** [paypal/paypal-checkout-components#1106]
### Description

In this page [https://developer.paypal.com/demo/checkout/#/pattern/client](https://developer.paypal.com/demo/checkout/#/pattern/client),
i want to set funding.allowed paypal.FUNDING.CARD , but console report Cannot read property 'CARD' of undefined.

paypal.version : "5.0.29"

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

![image](https://user-images.githubusercontent.com/18899748/57691223-32158380-7676-11e9-9ba0-b1bf96a459cd.png)

**Comment by bluepnume** [comment]
You don't need to manually enable cards in this sdk. It's enabled by default for the vertical buttons.
