### ISSUE TITLE
production site appears broken since 5/14 

### ISSUE THREAD

**Issue by Ed-SA** [paypal/paypal-checkout-components#1108]
PayPal button code that worked yesterday no longer works today.  The PayPal status page shows all green.  Any assistance will be greatly appreciated.  I'm getting back the following stack traces and have been unable to process payments since 10:42am EST this morning (sometimes one message, sometimes the other message):

{"description":"The remote server machine does not exist or is unavailable","stack":"Error: The remote server machine does not exist or is unavailable\n   at n.isProxyWindow (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:55804)\n   at n.toProxyWindow (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:55890)\n   at r (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:58710)\n   at Anonymous function (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:87587)\n   at i (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:5392)\n   at e.dispatch (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:5859)\n   at e.resolve (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:4501)\n   at i (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:5826)\n   at e.dispatch (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:5859)\n   at e.resolve (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:4501)\n\nundefined"}

{"description":"","stack":"Error\n   at n.isProxyWindow (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:55804)\n   at n.toProxyWindow (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:55890)\n   at r (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:58710)\n   at Anonymous function (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:87587)\n   at i (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:5392)\n   at e.dispatch (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:5859)\n   at e.resolve (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:4501)\n   at i (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:5826)\n   at e.dispatch (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:5859)\n   at e.resolve (https://www.paypal.com/sdk/js?client-id=REDACTED&disable-funding=credit:1:4501)\n\nundefined"}

**Comment by Ed-SA** [comment]
The user receives a paypal popup with "things don't appear to be working at the moment" when I get the above errors in the log.  Some payments are getting through occasionally, so I suspect a browser-specific issue.

**Comment by bluepnume** [comment]
Can you please let me know the browser(s) you're seeing this on, and share a url where I can repro?

**Comment by Ed-SA** [comment]
I can no longer repro in my dev environment, possibly there are/were 2 separate issues going on, one related to a specific credit card.  The group of users still unable to process payments are all using IE11 (I had one of them try Firefox, but with the credit card that I now believe causes a separate error).  Additionally, all of these IE11 users that are still experiencing issues are within the same environment (on the same network).  They were all able to run transactions yesterday with no issues, but in the Sandbox (they ran no production transactions yesterday).  It's possible that something in their environment has changed that I'm unaware of.  Unless the above stack traces point you to some suspicion that you can convey to me, I'm going to close this issue until I can narrow down the problem further from within their environment tomorrow.

**Comment by Ed-SA** [comment]
This issue was unrelated directly to the javascript codebase.  Affected users had the site in their "trustedsites" list which is documented in paypal as disallowed when using IE.

**Comment by bluepnume** [comment]
Aha. Yep, that's definitely an issue we can't fix. Thanks for letting me know!
