### ISSUE TITLE
paypal script errors in IE

### ISSUE THREAD

**Issue by Ed-SA** [paypal/paypal-checkout-components#1110]
### Description

in IE11, errors are thrown in the base paypal js file seemingly related to when it is attempting to determine the locale 

![Capture](https://user-images.githubusercontent.com/50150171/57784548-135acf80-76fe-11e9-920e-5dd6dba1a1f2.PNG)

setting the "&locale=en_US" in the script load line made no difference

### Steps to reproduce

in both sandbox and production now, button code is unusable in IE

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [X] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Thanks for the report. We've rolled out a fix, the cache should be cleared soon with the new version.

**Comment by Ed-SA** [comment]
Works again now in IE in both production and sandbox, thanks.  Had to clear browser cache first.
