### ISSUE TITLE
CSP has some errors

### ISSUE THREAD

**Issue by i7eo** [paypal/paypal-checkout-components#1112]
### Description

paypal.version: "5.0.35"

Refused to display 'https://www.paypal.com/us/home' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https://*.paypal.com"

### Steps to reproduce

Please provide each individual step required to reproduce the issue

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by i7eo** [comment]
![image](https://user-images.githubusercontent.com/18899748/58070572-296c0280-7bcc-11e9-9808-7bb72f4d73f0.png)

**Comment by bluepnume** [comment]
Thanks for the report. There's an ongoing live routing issue on paypal.com. I'm on call to resolve this.

**Comment by i7eo** [comment]
> Thanks for the report. There's an ongoing live routing issue on paypal.com. I'm on call to resolve this.

all right...
Please let me know when you have solved the problem

**Comment by bluepnume** [comment]
This was resolved as of 1am PST.
