### ISSUE TITLE
actions.payment.patch() in onShippingChange() doesn't work with checkout.js - clientside

### ISSUE THREAD

**Issue by zanneee** [paypal/paypal-checkout-components#1113]
### Description

Please provide a short description of the issue here, along with:

When using **actions.payment.patch()** inside of **onShippingChange()** to update shipping cost it gets an error below.

- Screenshots or videos that show the issue

- Your code
`<!DOCTYPE html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://www.paypalobjects.com/api/checkout.js"></script>
</head>

<body>
    <div id="paypal-button-container"></div>

    <script>
        paypal.Button.render({

            env: 'sandbox', // sandbox | production

            // PayPal Client IDs - replace with your own
            // Create a PayPal app: https://developer.paypal.com/developer/applications/create
            client: {
                sandbox:    'AZDxjDScFpQtjWTOUtWKbyN_bDt4OgqaF4eYXlewfBP4-8aqX3PiV8e1GWU6liB2CUXlkA59kJXE7M6R',
                production: '<insert production client id>'
            },

            // Show the buyer a 'Pay Now' button in the checkout flow
            commit: true,

            // payment() is called when the button is clicked
            payment: function(data, actions) {

                // Make a call to the REST api to create the payment
                return actions.payment.create({
                    payment: {
                        transactions: [
                            {
                                amount: { total: '0.01', currency: 'USD' }
                            }
                        ]
                    }
                });
            },
            
            "onShippingChange": function (data, actions) {
            console.log("inside onShippingChange");
            // Patch cart shipping cost with amount
            function patchShippingCost(amount) {
                return actions.payment.patch([
                    {
                        op: 'replace',
                        path: '/transactions/0/amount',
                        value: {
                            total: '10.00',
                            currency: 'USD',
                            details: {
                                subtotal: '0.01',
                                shipping: amount
                            }
                        }
                    }
                ]);
            };            
            
            // Otherwise we have a flat shipping cost.
            return patchShippingCost('10.00');
        },        

            // onAuthorize() is called when the buyer approves the payment
            onAuthorize: function(data, actions) {

                // Make a call to the REST api to execute the payment
                return actions.payment.execute().then(function() {
                    window.alert('Payment Complete!');
                });
            }

        }, '#paypal-button-container');

    </script>
</body>
    
`
- The `paypal.version` from your browser console
"4.0.270"

- The exact browser version
Chrome Version 74.0.3729.131 (Official Build) (32-bit)

- All console logs during the time of the issue, especially error messages
> callback_jsv4:458 Error occurred Error: Client side patch is only available for REST based transactions
>     at Object.paymentPatch (button.js:3806)
>     at serialize.js:34
>     at Function.ZalgoPromise.try (promise.js:400)
>     at Object.handler (serialize.js:33)
>     at types.js:68
>     at Function.ZalgoPromise.try (promise.js:400)
>     at Object._RECEIVE_MESSAGE_TYPE.<computed> [as postrobot_message_request] (types.js:56)
>     at receiveMessage (index.js:114)
>     at messageListener (index.js:140)

- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
Yes

- Does the issue occur consistently, or intermittently?
Consistently

### Affected browsers
- [x] All

**Comment by bluepnume** [comment]
This is not a documented or a supported pattern. Please use `onShippingChange` in the latest sdk, documented at https://developer.paypal.com/docs/checkout/integration-features/shipping-callback/
