### ISSUE TITLE
tagline fade-out with tagline: false

### ISSUE THREAD

**Issue by zanneee** [paypal/paypal-checkout-components#1115]
### Description
When set tagline: 'false', layout: 'horizontal' then
 tag was shown and faded out 1 second later.

Please provide a short description of the issue here, along with:

- Screenshots or videos that show the issue
![tagline_gone](https://user-images.githubusercontent.com/17840593/58163674-f81c3100-7cb6-11e9-8eeb-56fa3c1da547.png)
![tagline_gone_2](https://user-images.githubusercontent.com/17840593/58163856-49c4bb80-7cb7-11e9-9cf5-39d0c5e58a8c.png)

- Your code
`
<!DOCTYPE html>

<head>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>

<body>
    
    <div id="paypal-button-container"></div>

    
    <script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD"></script>

    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({
            style: {
                tagline: 'false',
                layout: 'horizontal'
            },
            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '0.01'
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                });
            }

        }).render('#paypal-button-container');
    </script>
</body>
    `
- The `paypal.version` from your browser console
"5.0.39"

- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
Yes

- Does the issue occur consistently, or intermittently?
Consitentely

- [x] Chrome

**Comment by bluepnume** [comment]
`tagline: false` not `tagline: 'false'`.
