### ISSUE TITLE
Is v5 compatible with the v1 REST API?

### ISSUE THREAD

**Issue by erin-doyle** [paypal/paypal-checkout-components#1122]
We have upgraded our React SPA to use the v5 React integration but our backend services are still using the v1 REST API.  We are calling `actions.order.authorize` during `onApprove` and are passing the `orderID` to our backend service which uses `/v1/payments/payment/{orderID}` to try to get the payment/order and is failing to find it with an INVALID_RESOURCE_ID error.  I'm guessing because the `orderID` is not the same as the `paymentID`.  Is it still possible to get the `paymentID` from any of the v5 SDK functions?  Or do we have to update our backend to use v2 and call either `/v2/payments/authorizations/{authorization_id}` or `/v2/checkout/orders/{order_id}`?

**Comment by bluepnume** [comment]
Yes, if you're using v1/payments, you should be able to access `data.paymentID` in the `onApprove` callback. Please see https://developer.paypal.com/docs/checkout/reference/upgrade-integration/#server-side-rest-integrations-with-v1payments-1

**Comment by erin-doyle** [comment]
Is there a specific intent needed to get this data?  We're using 'authorize' and we're only getting the `orderID` and `payerID` in the data argument to the `onApprove` callback.

**Comment by bluepnume** [comment]
Oh wait a sec -- sorry, yeah, if you're using orders api / `orderID` for the rest of the integration, you will need to do a GET on `/v2/checkout/orders/{order_id}`.

**Comment by erin-doyle** [comment]
Got it, thank you!
