### ISSUE TITLE
INTERNAL_SERVICE_ERROR for /v2/checkout/orders/{order_id}/authorize  

### ISSUE THREAD

**Issue by rpundlik** [paypal/paypal-checkout-components#1123]
Hi All,

When I am trying to authorize the created order using the below api

https://api.sandbox.paypal.com/v2/checkout/orders/{order_id}/authorize, I am getting the following error

> {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","debug_id":"d21e9d6cdb272","details":[],"links":[]}

I have checked the access token and request also which seems to be valid.

Any help on this appreciated. Please provide the solution on this asap as we are looking it on urgent basis.

**Comment by bluepnume** [comment]
@rajarampadmanathan can you please check this one?

**Comment by rajarampadmanathan** [comment]
@rpundlik - Can you please provide recent samples?

**Comment by rajarampadmanathan** [comment]
@rpundlik - Any update on this?
