### ISSUE TITLE
No [payer] [email_address] when using Credit Card

### ISSUE THREAD

**Issue by springknees** [paypal/paypal-checkout-components#1127]
I'm upgrading to Smart Button SDK and having difficulty sending a confirmation email to Credit Card customers, because I'm unable to get the customer's email address from the PayPal response.

As an example - if I use this demo for a **PayPal transaction** (https://developer.paypal.com/demo/checkout) and edit the finalize code to read:-

`alert('Transaction completed by ' + details.payer.email_address + '!');`

The alert shows 'Transaction completed by somebody@example.com' - if I use the same code for a **Credit Card transaction**, the alert shows 'Transaction completed by undefined'.

The underlying issue seems to be that there is no [payer] [email_address] data in the response when using a Credit Card - am I doing something wrong?

**Comment by davidpierson** [comment]
I am having the same issue. Using www.paypalobjects.com/api/checkout.js
When paying by credit card, the email address is not supplied in the response.

It is missing from the actions.payment.get and the action.payment.execute
In the "return actions.payment.get().then(function (paymentDetails) " the
paymentDetails.payer.payer_info.email field is missing. 

We do not require customers to login to our site, instead relying on Paypal to provide the details. 

We have no way to contact our customers due to this bug. Please fix asap.

**Comment by hxddev** [comment]
I also encountered this problem.

I found this problem only in the sandbox environment, i can get the email_address in the live environment.

This should be a back-end issue, You can use the live environment to develop and test credit card payments before the official fix.

@springknees @davidpierson

**Comment by davidpierson** [comment]
I've only seen this in sandbox, because we are just about to go live, and this has thrown a spanner in the works.
 Is there a way to test credit card payments in the live environment, without making actual payments from a real credit card?

**Comment by springknees** [comment]
@davidpierson - AFAIK the only way to test CC payments in the live environment is to execute a live payment, cancel it, then issue a refund. Not very satisfactory!

In my case, I have a working implementation of Checkout that uses the archived checkout.js - I thought I'd move with the times and upgrade to use Paypal Javascript SDK. I ran into this sandbox "email_address" problem and also Issue #1077, so for the time being I'll stick with the working implementation.

**Comment by bluepnume** [comment]
@rajarampadmanathan can you please check on this? Guest/card transactions should still come with a buyer email address, right?

**Comment by springknees** [comment]
@rajarampadmanathan I have just re-tested this and found that I now receive the payer's `email_address`  in the response - so I think this issue might have been fixed - thanks.
