### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by elrumordelaluz** [paypal/paypal-checkout-components#1130]
### Description

Upgrading the `patch` version of `paypal-.checkout` the _Button_ stop working.

### Steps to reproduce

Upgrade form `paypal-checkout@4.0.274` into `paypal-checkout@4.0.275` getting this error:
<img width="1085" alt="Screenshot 2019-06-20 at 18 16 27" src="https://user-images.githubusercontent.com/784056/59864645-96b7b280-9387-11e9-8e7c-97c99cb31342.png">

Also seems the [file](https://www.paypalobjects.com/api/checkout.4.0.275.js) soesn't found.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [x] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by mcntsh** [comment]
Hey @elrumordelaluz, thanks for catching that! This should be fixed now. 

https://www.paypalobjects.com/api/checkout.4.0.275.js
