### ISSUE TITLE
SEPA Checkout optional Account

### ISSUE THREAD

**Issue by Erlix322** [paypal/paypal-checkout-components#1132]
### Description

I have the problem that sepa is not possible without paypal account on mobile. (see picture) 

### Steps to reproduce

this is the code straight from the tutorials
```
<script src="https://www.paypal.com/sdk/js?client-id=my-client-id"></script>
<script>paypal.Buttons().render('body');</script>
```

The picture below shows what I am expecting on mobile but it only works on desktop browsers. For mobile I have to open up a paypal account.
More specific this happens with mobile WebView. (e.g React Native)

![image](https://user-images.githubusercontent.com/16254580/59966911-07470680-9523-11e9-8288-8a79fb86cfb9.png)

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ x ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Can you please provide a few tokens to help us debug and check our logs?

@bluelnkd is this expected?

**Comment by 6h4k5h498h9485gh39458h9o12um3412j34lj** [comment]
@Erlix322 have you solved the issue?
