### ISSUE TITLE
Is there a complete reference of button events?

### ISSUE THREAD

**Issue by cabintech** [paypal/paypal-checkout-components#1138]
Is there a complete reference to the button APIs? I keep stumbling on new things as I wander around the PayPal documentation (e.g. https://developer.paypal.com/docs/checkout/integration-features). Is there a list of all the onXXXX functions, their arguments and methods that can be called on the 'actions'?

The 'REFERENCE' link on that page does not have it...

**Comment by bluepnume** [comment]
We have plans to add full api docs.

**Comment by beamwerks** [comment]
6 months later, any update?  subscriptions are a pita with smart buttons so far

**Comment by bluepnume** [comment]
Can track this here. https://github.com/paypal/paypal-checkout-components/issues/1222
