### ISSUE TITLE
Uncaught errors in the console

### ISSUE THREAD

**Issue by cabintech** [paypal/paypal-checkout-components#1139]
There are many reasons we might reject() a promise in onClick or other events. These always result in uncaught error messages and stack traces in the browser console. It is a goal for our web apps to produce no console output unless there is a real failure. 

Issue #600 was closed with "Rejecting in payment() is an error case and throwing to the console helps when we need to debug." OK, but make a debug configuration option instead of always producing error messages even in normal operation conditions. It is sloppy to produce console output for debugging purposes in production applications. Can you make this a configurable option instead?

**Comment by bluepnume** [comment]
Can you provide an example of a use case where you need to reject a promise in `onClick`? And in that case is it not possible to catch the promise yourself to avoid console noise?

**Comment by cabintech** [comment]
We do a lot of validation during onClick(), including calling our server and validating all the cart prices and quantities. This is because the user can put things in their cart and then not checkout for days or even weeks. Customers have used this as a means to 'freeze' pricing of items - just leave the cart page in a browser tab, and then click the PayPal button sometime (very much) later. We end up with an order that paid old prices, or orders for items no longer in stock. Makes for a bad customer experience when we cannot ship their order as submitted.

So in onClick() we do lots of validation and may make extensive changes to the cart content including removing items, reducing quantities, and changing prices. There is no hope of communicating all that through the PayPal dialog - we need them to return to our cart page where we can properly inform them of the changes and let them change quantities, look at the new prices, and re-submit if they choose to do so.

There are other validations that cannot be done until onClick() time as they are not simple UI state controls. These also have to be rejected and the user returned to our cart page to handle them in our UI.

So in general it is best if the API does not console.log() anything unless there is a debug configuration enabled.

(Side note on error handling... .I have noticed that the API does not handle any errors thrown in the event methods - e.g. if my createOrder() code throws a Javascript error the user experience is the worst - a silent failure - the PayPal dialog goes away and there is nothing that tells the user what happened. Every call to my code should be inside a try/catch of the API code, and the catch should show some kind of error message to the user. In this case the onError() event is called, but we have to assume that PayPal owns the UI at this point so we cannot display anything to the user ourselves in such failure cases.)

**Comment by bluepnume** [comment]
Hi, sounds like this should be handled using async validation. Please let me know if you see any specific errors when trying that. https://developer.paypal.com/docs/checkout/integration-features/validation/
