### ISSUE TITLE
Is there a way to resize paypal button height for mobile?

### ISSUE THREAD

**Issue by tryb-kimwan** [paypal/paypal-checkout-components#1141]
### Description

We currently have a requirement that shows different button sizes when moving from a large screen to medium/small screen. This is not a problem when reloading the page since PayPal button supports an onload styling and I can set the button height of PayPal up to 55px. But when using a high res tablet like an iPad (768 x 1024) and switching between portrait and landscape mode since I have different button height for tablet (768px portrait) and laptop (1024px) screen.

I tried looking for a solution where I can listen to window resize and reapply paypal button style but unfortunately, I don't see any documentation that supports this requirement.

![paypal-button-size](https://user-images.githubusercontent.com/47131445/60406983-388e9900-9beb-11e9-92bc-b5acf6e27765.gif)

### Steps to reproduce

1. go to: https://stackblitz.com/edit/js-eurvya
2. resize view from large screen to medium/small screen

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [x] Chrome Mobile/Tablet
- [x] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Can you render two different buttons, and then use media queries to show/hide them based on the current screen dimensions?

**Comment by tryb-kimwan** [comment]
I can try. I'll let you know.

**Comment by tryb-kimwan** [comment]
So that one works. I guess we can close this issue now. It would be nice to just have 1 paypal button though
