### ISSUE TITLE
Bug when changing order (purchase_unit) description

### ISSUE THREAD

**Issue by cabintech** [paypal/paypal-checkout-components#1147]
In our onShippingChange handler we replace (patch) the entire purchase_unit like:

        return actions.order.patch([
            {
                op: 'replace',
                path: "/purchase_units/@reference_id=='default'",
                value: updatedPurchaseUnit
            }
        ]);	

The updatedPurchaseUnit includes a new "description" field which contains important information for our customer. The PayPal UI updates the order amounts, but does not update the description that is displayed in the order-details dropdown - it still shows the old description value that existed before this event.

![image](https://user-images.githubusercontent.com/31935300/60542955-2b54d580-9ce3-11e9-8f38-53694b998430.png)

**Comment by cabintech** [comment]
From other issues it seems that nobody from PayPal monitors these issues, so I opened a technical support case with PayPal

Case Number: 06184995

**Comment by bluepnume** [comment]
@mcntsh can you take a look?
