### ISSUE TITLE
IE 11 failing with syntax error

### ISSUE THREAD

**Issue by cabintech** [paypal/paypal-checkout-components#1150]
Trying to support older browsers... we are using fetch and promise pollyfills:

[https://github.com/github/fetch]
[https://github.com/stefanpenner/es6-promise]

Using IE 11:

If my sandbox account is not logged on, clicking the PP button brings up the PayPal dialog and logon prompt as usual. After logging on, it spins for a few seconds and shows:

"Things don’t appear to be working at the moment." 

and a "Try Again" button. Clicking Try Again displays the usual payment options screen as expected, although there is a syntax error noted in the console:

SCRIPT1002: Syntax error
c63dbdb0325435e8eecf269f118979a1.js (51,17)

This references a line in the JS file https://www.paypalobjects.com/tagmgmt/codefiles/c63dbdb0325435e8eecf269f118979a1.js?conditionId0=422975

     .map(p => p.split('='))

After that, we get stuck in a showing a "Continue" button that when clicked shows a spinner and "we are returning you to the merchant" (which is incorrect) then returns to the same screen with the same "Continue" button. There are no console messages (but to be fair, the IE debugger/console is awful).

No version of IE supports the arrow function. The docs indicate that IE 11 is a supported browser.

Near as I can tell (using the crummy IE debugger) the button code is making the usual callbacks to our code (createOrder(), onClick(), etc) and we return the expected responses.

Has IE been tested and can we expect it to work?

**Comment by bluepnume** [comment]
I'm struggling to repro. Can you please share:

1. The page you're testing on
2. The sandbox user credentials you're using.
3. Do you see the same issue at https://developer.paypal.com/demo/checkout/#/pattern/client

(for future, please do not delete the issue template, these are all questions we need to triage issues. thanks!)
