### ISSUE TITLE
onInit() is not being called

### ISSUE THREAD

**Issue by cabintech** [paypal/paypal-checkout-components#1151]
All our event handlers are called as expected, except for onInit() which is never called. Verified this with consol.log() calls and setting debugger breakpoints...

	{
		// Called during JS init of the buttons at page load time
		onInit: function(data, actions) {
			console.log("Here I am");
			actions.disable(); 
		},
		
		// Called when the user first clicks on the PayPal button. 
		onClick: function(data, actions) {
			//... our onClick processing...
		}

		//... our other event methods...
	}

Has this been renamed or removed? This documentation shows it: https://developer.paypal.com/docs/checkout/integration-features/validation/#synchronous-validation

I double checked everything, it is just not getting called...

**Comment by cabintech** [comment]
OK, I just knew this had to be our own problem, and it was - we were not initing the buttons correctly... never mind.

**Comment by plamenlazarov** [comment]
> OK, I just knew this had to be our own problem, and it was - we were not initing the buttons correctly... never mind.

@cabintech, can you share more details on how you fixed the issue? What you mean by "not initing buttons correctly"?

Thanks
