### ISSUE TITLE
Disable does not change the UI appearance? And disable/enable oddness.

### ISSUE THREAD

**Issue by cabintech** [paypal/paypal-checkout-components#1153]
If we call actions.disable() in the onInit() method we would expect the PP button(s) to render as grayed out, hashed, or otherwise to appear disabled, and the pointer should not change when passing over it. This is how a disabled UI element should behave.

But the button remains clickable, and our onClick() method gets called - which seems wrong if the button is supposed to be 'disabled'. The PayPal UI just never appears. That is not a good UI design!

The example in the docs https://developer.paypal.com/docs/checkout/integration-features/validation/#synchronous-validation does not make sense. The UI event handler setup in onInit() calls action.enable() or action.disable() as needed... that should be sufficient. There should be no need to check the UI state again in the onClick() method - onClick() should not be called if the button is disabled, by definition!

This is what I would expect that sample in the docs should look like (using JQuery to keep UI access methods simple). In this example there is a checkbox which must be ticked in order to enable the PP button. There is both synchronous and async validation in the onClick() method.

		onInit: function(data, actions) {
			
			actions.disable(); // Assume disabled at start
			$("#my-required-checkbox").change(function() {
				if ($("#my-required-checkbox").is(":checked")) {
					// Enable PP payment and clear any old message
					actions.enable();
					$("#my-message").text("");
				}
				else {
					// Prevent PP payment and tell the user why
					actions.disable();
					$("my-#message").text("Hey, you need to check the box before making payment.");
				}
			});
		},
		
		onClick: function(data, actions) {
			// More complex synchronous validation
			if (!mySyncValidationOK()) {
				$("#my-message").text("Sorry, validation failed, you cannot make payment at this time.");
				return actions.reject(Error("Validation failed"));
			}
			
			// Maybe we also need some async validation from our server...
			return new Promise(function(resolve, reject) {
				//... fetch() server response
				if (ok) {
					resolve();
				}
				else {
					$("#my-message").text("Sorry, our server said no.");
					reject(Error("Server validation failed"));
				}
			});
		},

Request: Visually 'disable' the PP button(s) when in the disabled state and do nothing if the user clicks on a disabled PP button.

Workaround: Hide/show the button element instead of enable/disable (makes a clunky cart UI that keeps resizing), or overlay the iframe of the button element with a semi-transparent DIV to gray it out and reject mouse clicks (lots of work and not foolproof).

**Comment by bluepnume** [comment]
Hi, closing this one for now as it's not a commonly requested feature.
