### ISSUE TITLE
Relaunching the window in IE/Edge closes the window

### ISSUE THREAD

**Issue by Millais** [paypal/paypal-checkout-components#1155]
### Description

If a user loses focus of the PayPal Checkout window, we currently provide an option in the parent window backdrop to regain focus of the checkout window: _"Don't see the secure PayPal browser? We'll help you re-launch the window to complete your purchase."_

**Expected Behaviour** is that clicking 'Continue' brings the PayPal Checkout window back into focus, above the parent window.

**Actual Behaviour** is that clicking 'Continue' closes the PayPal Checkout window and returns the user back to the parent window. (It appears that the _onCancel_ function is triggered).

This issue is present on the _checkout.js_ demo site: https://developer.paypal.com/demo/checkout-v4/#/pattern/client

The version being used is 4.0.279. I've been able to reproduce this consistently in Edge (42.17134.1.0) on the demo site, and it's also been reported in IE. There are no console logs when this is triggered.

### Steps to reproduce

• Go to https://developer.paypal.com/demo/checkout-v4/#/pattern/client in Edge/IE
• Click the PayPal Wallet button
• Drag the PayPal Checkout window out of the centre, and click 'Continue' in the parent window
• Observe that the PayPal Checkout window is closed rather than refocused

### Affected browsers
Edge & IE

**Comment by bluepnume** [comment]
Thanks for the report. @mcntsh can you take a look at this one?

**Comment by bluepnume** [comment]
Please let us know if you're still seeing this issue. Recommend trying with the latest version of the sdk. Thanks.
