### ISSUE TITLE
Neither onError nor onCancel called when onClick returns actions.reject()

### ISSUE THREAD

**Issue by cabintech** [paypal/paypal-checkout-components#1158]
### Description
By handling `onError `and `onCancel` events we can always know when the PayPal frame has been closed and update our UI accordingly. However there is one case (we found) where neither of these events are fired, and that is if we return `actions.reject()` from the `onClick `handler. In that case the PayPal UI is closed, an unhandled error is show in the console log, and no call to `onError` or `onCancel `is made.

This can be demonstrated in the demo checkout tool at https://developer.paypal.com/demo/checkout/#/pattern/client. Paste the following code which logs every event to the console. By un-commenting `return actions.reject()` statements it is easy to test the behavior in each of the event handlers. With the `onClick` event's return uncommented the browser console will show that no event is fired, an error is logged, and the PayPal window disappears.

```
<!DOCTYPE html>

<head>
    <!-- Add meta tags for mobile and IE -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>

<body>
    <!-- Set up a container element for the button -->
    <div id="paypal-button-container"></div>

    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD"></script>

    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                console.log("createOrder");
                //return actions.reject(Error("error: createOrder"));
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '0.01'
                        }
                    }]
                });
            },
            
            onClick: function(data,actions) {
                console.log("onClick");
                return actions.reject(Error("error: onClick"));
            },
            
            onShippingChange: function(data,actions) {
                console.log("onShippingChange");
                //return actions.reject(Error("error: onShippingChange"));
            },
            
            onCancel: function(data,actions) {
              console.log("onCancel");
            },
            
            onError: function(data,actions) {
                console.log("onError");
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                console.log("onApprove");
                //return actions.reject(Error("error: onApprove"));
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                });
            }


        }).render('#paypal-button-container');
    </script>
</body>
```
With this code, clicking the PayPal button briefly shows/removes the PayPal window with the following console output:

```
onClick
js?client-id=sb&currency=USD&disable-funding=credit:1 unhandled_error {err: "Error: Window closed↵    at https://www.paypal.com…id=sb&currency=USD&disable-funding=credit:1:5751)", timestamp: "1562772186639", referer: "www.sandbox.paypal.com", uid: "4ef860e449_mtu6mjm6mdi", env: "sandbox"}
E @ js?client-id=sb&currency=USD&disable-funding=credit:1
L @ js?client-id=sb&currency=USD&disable-funding=credit:1
error @ js?client-id=sb&currency=USD&disable-funding=credit:1
(anonymous) @ js?client-id=sb&currency=USD&disable-funding=credit:1
(anonymous) @ js?client-id=sb&currency=USD&disable-funding=credit:1
(anonymous) @ js?client-id=sb&currency=USD&disable-funding=credit:1
setTimeout (async)
e.reject @ js?client-id=sb&currency=USD&disable-funding=credit:1
i @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.dispatch @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.reject @ js?client-id=sb&currency=USD&disable-funding=credit:1
(anonymous) @ js?client-id=sb&currency=USD&disable-funding=credit:1
i @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.dispatch @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.reject @ js?client-id=sb&currency=USD&disable-funding=credit:1
i @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.dispatch @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.resolve @ js?client-id=sb&currency=USD&disable-funding=credit:1
(anonymous) @ js?client-id=sb&currency=USD&disable-funding=credit:1
i @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.dispatch @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.resolve @ js?client-id=sb&currency=USD&disable-funding=credit:1
(anonymous) @ js?client-id=sb&currency=USD&disable-funding=credit:1
i @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.dispatch @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.resolve @ js?client-id=sb&currency=USD&disable-funding=credit:1
i @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.dispatch @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.resolve @ js?client-id=sb&currency=USD&disable-funding=credit:1
(anonymous) @ js?client-id=sb&currency=USD&disable-funding=credit:1
i @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.dispatch @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.resolve @ js?client-id=sb&currency=USD&disable-funding=credit:1
i @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.dispatch @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.resolve @ js?client-id=sb&currency=USD&disable-funding=credit:1
(anonymous) @ js?client-id=sb&currency=USD&disable-funding=credit:1
i @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.dispatch @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.resolve @ js?client-id=sb&currency=USD&disable-funding=credit:1
i @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.dispatch @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.resolve @ js?client-id=sb&currency=USD&disable-funding=credit:1
(anonymous) @ js?client-id=sb&currency=USD&disable-funding=credit:1
i @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.dispatch @ js?client-id=sb&currency=USD&disable-funding=credit:1
e.resolve @ js?client-id=sb&currency=USD&disable-funding=credit:1
mr.postrobot_message_response @ js?client-id=sb&currency=USD&disable-funding=credit:1
Lr @ js?client-id=sb&currency=USD&disable-funding=credit:1
(anonymous) @ js?client-id=sb&currency=USD&disable-funding=credit:1
(anonymous) @ js?client-id=sb&currency=USD&disable-funding=credit:1
Show 20 more frames
js?client-id=sb&currency=USD&disable-funding=credit:1 Uncaught Error: Window closed
    at js?client-id=sb&currency=USD&disable-funding=credit:1
    at i (js?client-id=sb&currency=USD&disable-funding=credit:1)
    at n.e.dispatch (js?client-id=sb&currency=USD&disable-funding=credit:1)
    at n.e.resolve (js?client-id=sb&currency=USD&disable-funding=credit:1)
    at i (js?client-id=sb&currency=USD&disable-funding=credit:1)
    at n.e.dispatch (js?client-id=sb&currency=USD&disable-funding=credit:1)
    at n.e.resolve (js?client-id=sb&currency=USD&disable-funding=credit:1)
    at js?client-id=sb&currency=USD&disable-funding=credit:1
    at i (js?client-id=sb&currency=USD&disable-funding=credit:1)
```

### Steps to reproduce

Paste the above code into the test tool and click on the PayPal button.

### Affected browsers
Verified in
- [X ] Chrome
- [ ] Safari
- [ ] Firefox
- [X ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by cabintech** [comment]
Oddly (or maybe not), if the return from `onClick `is a `Promise `that subsequently does a` reject() `then the `onError `event is fired as it should be (with still unhandled error messages in the console). E.g. this `onClick `handler will cause the `onError `event to be fired:

            onClick: function(data,actions) {
                console.log("onClick");
                //return actions.reject(Error("error: onClick"));
                return new Promise(function(resolve, reject) {
                    reject(Error("error: async onClick"));
                });
            },

**Comment by iamthefreeman** [comment]
I'm getting the same issue here, looking to validate form information before PayPal window. @cabintech I've tried your working around and it doesn't seem to work anymore?

@bluepnume Are there any planned fixes in the works for this?

**Comment by cabintech** [comment]
This still works for us (e.g. instead of returning `actions.reject()`, we return a Promise on which we call `reject()`). Here is our `onClick `handler (I removed the rather involved async validation, the synchronous case shows how we do it). 

You can try this yourself on our web site (cabintechglobal.com) - add something to the cart, go to checkout, be sure the "I agree..." checkbox is unchecked, and click the PayPal button. The `onClick()` handler will see the unchecked box, return a Promise with a call to `reject()`, and display our own message dialog.

Notice the try/catch here also... we found that the PayPal button code is not robust with respect to any JS errors thrown in the handler.

		onClick: function(data, actions) {
			console.log("onClick");

			try { // PayPal silently fails if this callback has any JS error, so we must catch and handle them.
				
				
				// Replace cart content with 'processing' message in our cart dialog (now behind the PayPal window).
				cartDialogOpen("processing");

				// ---- Synchronous validations. 
				
				// In general the PAY button is disabled when the cart is empty, but check just in case.
				if (simpleCart.quantity() == 0) {
					util.alertBox("Empty Cart","The cart is empty, you must have at least one item to check out.");
					// Should be able to "actions.reject()" but it does not fire correct events (https://github.com/paypal/paypal-checkout-components/issues/1158)
					return new Promise(function(resolve,reject){reject(Error("Cart is empty."));});
				}

				// v3.33 Require they agree to our policies (GDPR requirement for EU customers)
				if (!$("#agree-chk").is(':checked')) {
					util.alertBox("Policy Agreement Required","You must accept our Terms of Service and Privacy policy by checking the box just above the 'Pay' button on the shopping cart dialog.");
					// Should be able to "actions.reject()" but it does not fire correct events (https://github.com/paypal/paypal-checkout-components/issues/1158)
					return new Promise(function(resolve,reject){reject(Error("Policy agreement required."));});
				}

				// ---- Async valication
				// To stop the payment flow and dismiss the PayPal frame we must return a Promise object
				// and subsequently call reject() on it - or call resolve() to proceed.
				//
				//... async validation code...

			} catch(err) {
				// PayPal does not handle script errors, it just silently fails.
				util.reportJSError("Failed in PayPal onClick() event processing, order submit was aborted. "+err);
				util.alertBox("Software Failure","Sorry, we had a software failure interacting with PayPal and we cannot process your order right now. Our site admin has been notified and will fix this as soon as possible.<br><br>You can send us your order information by email and we will process it manually.<br><br>We apologize for this error and will get it fixed as soon as possible.");
				// Should be able to "actions.reject()" but it does not fire correct events (https://github.com/paypal/paypal-checkout-components/issues/1158)
				return new Promise(function(resolve,reject){reject(Error("Software error in onClick event."));});
			}


		},

**Comment by iamthefreeman** [comment]
Ah right, I can see now. Thanks for the quick response.

I did try out your website, and when trying this out I was still getting the uncaught error exceptions, 
![Screenshot 2019-08-20 at 16 18 44](https://user-images.githubusercontent.com/916500/63360610-96776b80-c366-11e9-823d-f436a183c3bd.png)

Is there any way to catch/suppress these errors?

**Comment by cabintech** [comment]
I saw those errors get reported by our web server, not sure what is going on there... I cannot reproduce it. I do see in our async validation code that we don't handle non-200 HTTP codes correctly, but unsure why the server would be returning non-200 status codes... need to look into that...

**Comment by cabintech** [comment]
OK, so this has become worse in some recent update. Our work around of returning a Promise() from onClick() no longer works... no matter what we return from onClick() neither the onError() or onCancel() handlers get called. In fact, returning a Promise that does a subsequent reject() no longer works at all - the PayPal window is not dismissed, it just sits there with an infinite spinning icon.

So we have returned to this code in our onClick() handler:

    if (someErrorCondidion) {
        //... cancel logic goes here ...
        return actions.reject(Error("Nobody ever sees this message."));
    }

But since this does not call onCancel() or onError() we have to duplicate our onCancel() logic. The API should be calling our onCancel() handler in this case.

**Comment by bluepnume** [comment]
Hi @cabintech 

> In fact, returning a Promise that does a subsequent reject() no longer works at all - the PayPal window is not dismissed, it just sits there with an infinite spinning icon.

Can you share an example of the code you're using here? If the window isn't dismissed that's problematic. We'll look into this right away.

> The API should be calling our onCancel() handler in this case.

`onCancel()` is designed only for user-initiated cancels, not onClick rejections. It's unlikely we'll change that unless there's something that it's not possible to handle directly in onClick.

**Comment by bluepnume** [comment]
I'm trying this and it still appears to work for me...

```javascript
            onClick: function(data, actions) {
                return new Promise(resolve => setTimeout(resolve, 500)).then(() => {
                    return actions.reject();
                })
            },
```
