### ISSUE TITLE
'Pay Now' button does not render and work in many browsers

### ISSUE THREAD

**Issue by YanzheL** [paypal/paypal-checkout-components#1161]
### Description

After I entered my credit card information, I clicked the blue button, but nothing happened.
Before I click the button, I saw bunch of errors in console.
While I'm clicking the blue button, no any new error shows in console.

Is there should be some text on the blue button? It seems that it does not be correctly rendered.

Desktop Browsers
- Screenshots or videos that show the issue
<img width="787" alt="Screen Shot 2019-07-12 at 16 21 19" src="https://user-images.githubusercontent.com/25402886/61113863-ba22d880-a4c1-11e9-9229-4ec56cd204db.png">

Console Log:
<img width="1680" alt="Screen Shot 2019-07-12 at 16 21 38" src="https://user-images.githubusercontent.com/25402886/61113891-cd35a880-a4c1-11e9-9742-085b1f9d0bef.png">

Chrome and Safari on IOS:
![IMG_1935](https://user-images.githubusercontent.com/25402886/61116751-a7ab9d80-a4c7-11e9-9f2c-4592b97681e8.PNG)

- Your code
- The `paypal.version` from your browser console
How do I get it ???
- The exact browser version
See the **Affected browsers** section.
- A link to your page with the issue, if possible
- All console logs during the time of the issue, especially error messages
```
jquery.min.js:2 Refused to load the font 'data:application/font-woff2;base64,d09GMgABAAAAAQ5sABIAAAADuOQAAQ4EAAEAgwAAAAAAAAAAAAAAAAAAAAAAAAAAG4SpIhy4XhSHMgZgAJJmCF4JgnMREAqGskiFyggSgrVoATYCJAOdOAuOXgAEIAWPGAfGYAyDGFsKfLME/nOMvX+HnQoMqyRqK6tt2TW8K2BDX9Umu4PZkCXwtMjpcHYNTx6UUmu30UdwcxxnVMvcNgAim7rdXiPZ////////////C5dF2ObuXM7ZvQeSECARwueHlaLVtkJEIaLRAI3ulswSE13cSPdM15RCyYQuuS7A0mBqpQO9pYZWQQMqa9lQb0dpJzHxHpLyCHIi8uBdwF58nNH+YOA40OpJvEjJtaokKaUkx/N5UeSinp5TWoW1vSpFjimBgeFGeCF66U0n6ZUN/qSqC4XC11GKUNmzSy2d5Jxyqw5JzGUlJUnyi0lKkE8BlxadTZsyRm8c1/Cti2hEjzIH...FVw9csGnQ1BnbMbfzgRj3WjPytwZYWpPh3OtmsLZaNcxxqaGVqMVqFffFpU8bbs/0N1vG3POWfS7LUeB81TfHn+VbD7x/UnT3lXyFltHfdX6+X6Rzmg9d4dAISK7GlTj2zgME/JUwAETAECwABAUgUmAysrKI5shRwAchnFSMheQ8UoKlvnVbkW9mMeq2+bbO9EQ2q09Z9wzsADarYt4ftoamBDi8gmfbZKnl+lkZWyRx1VYVSIpVFXs9VXy9ytCyTNYt09YIAGKjqpDT22SgOdP5OsdAK/vOCXFnrpEwA/PPTJiopB7HxZV+MlaGCT/04K/LY3kjPYV/YR146Ggg+9sX6na/c2So+Epz3PXve3PKRylPIhNZASBUYVDIGhikiWc1jj/claeVCJvljX7JfvO+xhfTDIjSXBs4HV16Ol/BMfcuFQ4NRmDOWEh6diOI6NZmGl87N9J+r2JfpW2+5NhV/fGHLO57Yavbq7zaCewa/RDxp/aSH+luOPwAA' because it violates the following Content Security Policy directive: "default-src 'self' https://*.paypal.com https://*.paypalobjects.com 'unsafe-inline'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

(anonymous) @ jquery.min.js:2
/webapps/hermes/api/batch/setbuyer:1 Failed to load resource: the server responded with a status of 400 ()
/webapps/hermes/api/checkout/EC-2W6590177G8950350/session?meta=%7B%22token%22%3A%22EC-2W6590177G8950350%22%2C%22calc%22%3A%22c4d683c0ff3b4%22%2C%22csci%22%3A%22431f1c6b24ca42bcabfb6272e07c65cd%22%2C%22locale%22%3A%7B%22country%22%3A%22C2%22%2C%22language%22%3A%22en%22%7D%2C%22state%22%3A%22ui_checkout_review%22%2C%22app_name%22%3A%22hermesnodeweb%22%7D:1 Failed to load resource: the server responded with a status of 400 ()
/webapps/hermes/api/checkout/EC-2W6590177G8950350/session?meta=%7B%22token%22%3A%22EC-2W6590177G8950350%22%2C%22calc%22%3A%22c5fe13d0bb72f%22%2C%22csci%22%3A%2284012c9f34de4d7d90068905602a21eb%22%2C%22locale%22%3A%7B%22country%22%3A%22C2%22%2C%22language%22%3A%22en%22%7D%2C%22state%22%3A%22ui_checkout_updateCard_addCardFlow_addCard%22%2C%22app_name%22%3A%22hermesnodeweb%22%7D:1 Failed to load resource: the server responded with a status of 400 ()
/webapps/hermes?flow=1-P&flow=1-P&ulReturn=true&country.x=C2&locale.x=en_US&token=EC-2W6590177G8950350#/checkout/updateCard/addCardFlow/addCard?message=NEED_AUTHENTICATED_CARD:1 Refused to load the font 'data:application/font-woff2;base64,d09GMgABAAAAAQ5sABIAAAADuOQAAQ4EAAEAgwAAAAAAAAAAAAAAAAAAAAAAAAAAG4SpIhy4XhSHMgZgAJJmCF4JgnMREAqGskiFyggSgrVoATYCJAOdOAuOXgAEIAWPGAfGYAyDGFsKfLME/nOMvX+HnQoMqyRqK6tt2TW8K2BDX9Umu4PZkCXwtMjpcHYNTx6UUmu30UdwcxxnVMvcNgAim7rdXiPZ////////////C5dF2ObuXM7ZvQeSECARwueHlaLVtkJEIaLRAI3ulswSE13cSPdM15RCyYQuuS7A0mBqpQO9pYZWQQMqa9lQb0dpJzHxHpLyCHIi8uBdwF58nNH+YOA40OpJvEjJtaokKaUkx/N5UeSinp5TWoW1vSpFjimBgeFGeCF66U0n6ZUN/qSqC4XC11GKUNmzSy2d5Jxyqw5JzGUlJUnyi0lKkE8BlxadTZsyRm8c1/Cti2hEjzIH...FVw9csGnQ1BnbMbfzgRj3WjPytwZYWpPh3OtmsLZaNcxxqaGVqMVqFffFpU8bbs/0N1vG3POWfS7LUeB81TfHn+VbD7x/UnT3lXyFltHfdX6+X6Rzmg9d4dAISK7GlTj2zgME/JUwAETAECwABAUgUmAysrKI5shRwAchnFSMheQ8UoKlvnVbkW9mMeq2+bbO9EQ2q09Z9wzsADarYt4ftoamBDi8gmfbZKnl+lkZWyRx1VYVSIpVFXs9VXy9ytCyTNYt09YIAGKjqpDT22SgOdP5OsdAK/vOCXFnrpEwA/PPTJiopB7HxZV+MlaGCT/04K/LY3kjPYV/YR146Ggg+9sX6na/c2So+Epz3PXve3PKRylPIhNZASBUYVDIGhikiWc1jj/claeVCJvljX7JfvO+xhfTDIjSXBs4HV16Ol/BMfcuFQ4NRmDOWEh6diOI6NZmGl87N9J+r2JfpW2+5NhV/fGHLO57Yavbq7zaCewa/RDxp/aSH+luOPwAA' because it violates the following Content Security Policy directive: "default-src 'self' https://*.paypal.com https://*.paypalobjects.com 'unsafe-inline'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.
```
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
No. On demo site, If I choose to pay with credit/debt card without login, I can see 'Pay Now' on the blue button. So the demo seems work well.
- Does the issue occur consistently, or intermittently?
Consistently. I cannot make payments due to this issue.

### Steps to reproduce

I tried to buy Origin Premier Access from [Origin](https://www.origin.com). I followed the steps on their site and finally be redirected to PayPal.
So I logged into my paypal account, and reached the checkout page.
Then I saw the 'Pay Now' blue button does not render.

### Affected browsers

- [x] Chrome 75.0.3770.100 (On Win10 1903 and macOS 10.14.5)
- [x] Safari 12.1.1 (macOS 10.14.5)
- [ ] Firefox
- [x] Edge
- [ ] IE
- [x] Chrome IOS Mobile/Tablet 75.0.3770.103
- [x] Safari IOS Mobile/Tablet 
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
@bluelnkd can you triage this one?

**Comment by lxj616** [comment]
@bluepnume encountered this same issue widely in mainland china, unable to make payments
