### ISSUE TITLE
Change Smart Button z-index

### ISSUE THREAD

**Issue by guidolodetti** [paypal/paypal-checkout-components#1162]
Hello,

I'm implementing a _PayPal Smart Button_, and it sets its `z-index` to `100`, which breaks all my modals in the webpage. Is there a way to prevent it from setting its `z-index`?

Thanks!

**Comment by TheDutchCoder** [comment]
You can wrap it in something with a relative position and z-index 1 to prevent the item from interfering.

Something like:
```
<div style="position: relative; z-index: 1;">
  <paypal-button-here />
</div>
```

**Comment by pmourer** [comment]
The fix above works, but why is the z-index on these buttons 100 in the first place... ?
