### ISSUE TITLE
Display issue of newly added `powered by Paypal` tagline

### ISSUE THREAD

**Issue by ensete** [paypal/paypal-checkout-components#1163]
### Description

How can I disable the newly added tagline of `powered by Paypal` or at least change the color of how it looks because sometimes it renders badly on user website without white background. Setting the customized option `style.tagline` to `false` seems not to work with `vertical` `style.layout`.

![tagline-issue](https://user-images.githubusercontent.com/39819339/61386927-55131c80-a8df-11e9-9479-88f121a3a2f3.png)

**Comment by bluepnume** [comment]
Hi, this tagline is required for legal and compliance reasons. If possible please render the buttons on a light background. Thanks.
