### ISSUE TITLE
Integrate paypal without iframe

### ISSUE THREAD

**Issue by LeiSe7en** [paypal/paypal-checkout-components#1166]
### Description

Please provide a short description of the issue here, along with:

Hi guys:
  I am doing the integration of the paypal payment on wechat browser right now. But i cannot use iframe on wechat browser. So i just curious about is there any way to do the integration without iframe? (eg: call the api manually and render the button manually)

Thanks!

**Comment by amaclean2** [comment]
@LeiSe7en, The PayPal button needs to be rendered in an iFrame because it has JavaScript that cannot be exposed to the end client, it's inherent to how the button is implemented. Many applications redirect to a webpage that has the checkout flow where the PayPal link can sit.
