### ISSUE TITLE
Funding Icons missing in IE11

### ISSUE THREAD

**Issue by Millais** [paypal/paypal-checkout-components#1167]
### Description

Funding Icons currently disappear with checkout.js in Internet Explorer when the button style is greater than 'small'. The PayPal Wallet button is retained, but changing the size upwards appears to drop the funding icons from being displayed to customers.

This is consistently reproducible on the test site in IE11 with PayPal Version 4.0.282. There are no console logs: https://developer.paypal.com/demo/checkout-v4/

Funding Icons correctly displayed with the `Small` size.
![IE11Small](https://user-images.githubusercontent.com/7149113/61789906-c4bc6680-ae0d-11e9-88e8-bebdbaedb985.png)

Funding Icons dropped with the `Medium` (or larger) size.
![IE11Medium](https://user-images.githubusercontent.com/7149113/61789947-e1589e80-ae0d-11e9-92dd-40d17576069b.png)

### Steps to reproduce

Use 
```
style: {
   label: 'pay',
   size: 'medium',
   fundingicons: true
}
```
on https://developer.paypal.com/demo/checkout-v4/ in Internet Explorer 11.

### Affected browsers

- [x] IE

**Comment by bluepnume** [comment]
@amaclean2 can you take a look? Thanks!

**Comment by amaclean2** [comment]
@Millais, I think if you aren't using checkout-v4, you should be fine. Try using https://developer.paypal.com/demo/checkout
and if at all possible, you should use Chrome, Firefox, Edge, or a more modern browser.
V4 is an old integration of checkout and IE being an old browser, it really isn't worth it to support this issue.
