### ISSUE TITLE
Cancelling payment returns user to parent window in webview modal

### ISSUE THREAD

**Issue by Millais** [paypal/paypal-checkout-components#1168]
### Description

Clicking 'Cancel & Return' on PayPal Checkout loaded in an iOS webview currently triggers unexpected behaviour. I've been able to reproduce this consistently in production with the merchant, who is using version 4.0.282 of checkout.js.

This is occurring on their iOS app only – where their checkout is loaded in a webview. Clicking 'Cancel & Return' on PayPal Checkout loads the parent page into the PayPal modal where the PayPal Checkout previously was. The page is then scrollable within this modal. A video of the experience is here: https://youtu.be/rJrEQ80Pmg4

I'm unable to reproduce the exact same behaviour on the Checkout Demo. However, there is an issue when 'Cancel & Return' is clicked in an iOS webview. A generic error page on checkout is displayed and the modal is not closed either. This could potentially be related to the merchant issue: https://youtu.be/78sKlIltHro

### Steps to reproduce
For the merchant experience:
* Download the B&Q iOS app: https://apps.apple.com/gb/app/b-q/id589374238
* Add an item to your basket and progress through checkout, selecting PayPal as your payment method.
* Click the PayPal button and then click 'Cancel & Return' once checkout is loaded. You will see that the parent page is loaded into the webview modal.

### Affected browsers
- [x] WebView (iOS only)

**Comment by abarco** [comment]
@Millais I'm unable to repro this issue on regular webviews. I'm also unable to access the app given country restrictions on the app store. Can you confirm this is still an issue on `v4.0.284`?

**Comment by Millais** [comment]
Hey @abarco – confirming that this is still an issue on `v4.0.284`. Let me connect with you internally and see if there's a way which we can get you access to the app.

Thanks,
Patrick

**Comment by farah** [comment]
Can confirm this is an issue for iPhone 7. Tested on iOS versions 10.3.4 and 13.3.1. 

I've had a chat @Millais who forwarded me to a PayPal rep,  they said they do not have an ETA on when they can get a fix.

**Comment by bluepnume** [comment]
Please confirm if you're still seeing this issue, and we'll reopen. Thanks.
