### ISSUE TITLE
Why PayPal Express checkout.min.js loading twice ?

### ISSUE THREAD

**Issue by VivekVikranth** [paypal/paypal-checkout-components#1172]
## Description

Every time when our page loads with PayPal express checkout smart buttons, the required checkout.js minified is downloaded twice: once on page load and once more when the button render function gets triggered. Is that expected behavior ?

- Screenshots or videos that show the issue
![image](https://user-images.githubusercontent.com/3896638/62201494-d8c11480-b387-11e9-9860-ac50745d9174.png)

- The `paypal.version` from your browser console - "4.0.282"
- The exact browser version - All the browser versions
- A link to your page with the issue, if possible - https://www.bose.com/
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout) ? - Yes
- Does the issue occur consistently, or intermittently? - Consistently

### Steps to reproduce

Go to the given page, add some product to the cart. It will direct you to cart page where you can find the issue.

### Affected browsers

- [ +] Chrome
- [ +] Safari
- [ +] Firefox
- [ +] Edge
- [ +] IE
- [ +] Chrome Mobile/Tablet
- [x] Safari Mobile/Tablet
- [x] Web View / Safari ViewController
- [ ] Other

**Comment by VivekVikranth** [comment]
@bluepnume  Could you please clarify regarding the posted question. Our production team is concerned about this issue as a performance degradation in the live site.

**Comment by ashishsantikari** [comment]
Okay, I am also facing a similar issue, not sure if it has the same root cause.
Using this component causes bundle size to increase(1.4 MB+), also IDK why it downloads the file from CDN too(2 times for the same job?). This seems very strange.

**Comment by jamesg1** [comment]
I also experience this with setting up paypal/braintree. I'm following the standard client setup guide - https://developers.braintreepayments.com/guides/paypal/client-side/javascript/v3#basic-configuration.

When calling `await paypal.Button.render(..)` (`https://www.sandbox.paypal.com/smart/button?env=sandbox&`) it seems to download the whole `checkout.min.js` even though it has already been loaded first on my page and `paypal` is available in `window`.

Causes an additional 192kb script load.

See this screenshot:
![Screen Shot 2019-11-14 at 12 50 15 PM](https://user-images.githubusercontent.com/3621147/68822711-61688400-06dd-11ea-960c-f533e162e7fd.png)

**Comment by bluepnume** [comment]
This is expected. The script is loading from cache inside the button iframe. It should only be downloaded a single time, and cached.

**Comment by jamesg1** [comment]
Yeah I realised i was importing the script via require js from src hence both of them getting called.
