### ISSUE TITLE
Unable to click 'Cancel and Return'/ PayPal Terms/Policies when guest checkout is displayed in an iOS webview

### ISSUE THREAD

**Issue by Millais** [paypal/paypal-checkout-components#1173]
### Description

When guest checkout is initiated in an iOS webview, it appears that the CSS/links become misaligned. This means that when the customer scrolls down to click on the PayPal Terms or PayPal Policies in the checkout footer, or tries to click 'Cancel and Return', the click is actually placed elsewhere on guest checkout and the page jumps back upwards as a result.

This was reported in a merchant app and I've been able to reproduce this by displaying the checkout demo (https://developer.paypal.com/demo/checkout-v4/#/pattern/vertical) in a webview using a webview tester app:  https://apps.apple.com/us/app/viewte-the-webview-tester/id1237657148

Please see the attached video of this experience here: https://youtu.be/FLqrudWejzk
This occurs consistently when attempting to click 'Cancel and Return' or the links in the footer.

### Steps to reproduce

Display https://developer.paypal.com/demo/checkout-v4/#/pattern/vertical in an iOS webview (potentially using the webview tester app above).

### Affected browsers
- [x] iOS webview

**Comment by bluepnume** [comment]
Can you raise this one as an internal issue. The guest team doesn't currently track issues on this github page.
