### ISSUE TITLE
CSP Problem in paypal

### ISSUE THREAD

**Issue by playma** [paypal/paypal-checkout-components#1175]
What happened?
It always be failed when I pay by visa or master
But pay by paypal is successed

<img width="1440" alt="螢幕快照 2019-08-02 下午9 15 11" src="https://user-images.githubusercontent.com/7677470/62372678-a9b6c880-b56a-11e9-8650-9a945aadfffc.png">

**Comment by bluepnume** [comment]
This repo is for issues with the sdk and smart buttons only. Please raise a ticket over at https://www.paypal-support.com/s/?language=en_US
