### ISSUE TITLE
Destroy method

### ISSUE THREAD

**Issue by MrMooky** [paypal/paypal-checkout-components#1176]
This is not really a bug report, but I am not able to find any reference on how to destroy the Smart Payment Button. Basically the opposite of `.render('#paypal-button-container')`.

I would need this when I close my modal box.

**Comment by bluepnume** [comment]
You can just destroy the modal box or remove it from the DOM, and the button will automatically be destroyed.

**Comment by simeyla** [comment]
There can be cases where the error messages still get written to the console. 
A 'dispose' would be welcome, if it doesn't exist yet.
