### ISSUE TITLE
Uncaught Error: Payee xxx does not match expected merchant id: yyy

### ISSUE THREAD

**Issue by drey101** [paypal/paypal-checkout-components#1178]
### Description

Paypal Smart Buttons suddenly encounter error regarding payee not matching merchant id. It was working yesterday, but not today, so the new release may have done something.

![Screen Shot 2019-08-08 at 4 00 41 PM](https://user-images.githubusercontent.com/2406579/62685690-bbc6ba00-b9f5-11e9-99f5-94a0e039abad.png)
![Screen Shot 2019-08-08 at 3 58 29 PM](https://user-images.githubusercontent.com/2406579/62685692-bbc6ba00-b9f5-11e9-8c28-438ed9da5168.png)

### Steps to reproduce

Follow steps to setup a smart payment button defined at: https://developer.paypal.com/docs/checkout/

### Affected browsers

- [ x ] Chrome
- [ x ] Safari

**Comment by bluepnume** [comment]
Are you passing a cusom payee when you set up the transaction?

And if so, are you passing merchant-id to the sdk? https://developer.paypal.com/docs/checkout/reference/customize-sdk/#merchant-id -- you would need to do this

**Comment by drey101** [comment]
I'm using the following to set up the transaction, but I'm still getting the error:
```
    const request = new PAYPAL_SDK.orders.OrdersCreateRequest();
    request.prefer('return=representation');
    request.requestBody({
      intent: 'CAPTURE',
      purchase_units: [
        {
          amount: {
            currency_code: 'USD',
            value: amount,
          },
        },
      ],
      application_context: {
        shipping_preference: 'NO_SHIPPING',
        user_action: 'PAY_NOW',
        payee_preferred: 'IMMEDIATE_PAYMENT_REQUIRED',
      },
    });
```

**Comment by drey101** [comment]
I've figured out why it doesn't work even if I don't add a payee, apparently using `sb` as the parameter for the `client-id` doesn't work. I need to pass my own `client-id` so that it would properly resolve the `merchant-id` and `client-id`, even though I don't define the payee anymore.

Doesn't work:
```
    <script src="https://www.paypal.com/sdk/js?client-id=sb"></script>
```
Works:
```
    <script src="https://www.paypal.com/sdk/js?client-id=<XXXXXXXXXXX>"></script>
```

Hmmn, so how does one go about defining a custom payee using an email address now? If we're required to pass the merchant id to the button, that seems to be quite restrictive, as I don't think I've spotted anything in the rest api/sdk that allows me to retrieve the `merchant-id`  from an email address.

**Comment by jwoodmansey** [comment]
Also having this exact issue.

This has broken our production checkout implementation. 

How are we now meant to facilitate a custom payee using an email address, and if a merchant-id is needed how can this be obtained? Really struggling to find clear documentation on this.

**Comment by lfarks** [comment]
Same problem here. I am reaching paypal support for help. Until yesterday it worked just fine like you all say.

**Comment by knupska** [comment]
We're suffering this same issue.

It broke our PayPal integration for our ecommerce system on all live client sites, and in every other occurrences we had, test environments, local development etc.

The dead giveaway that something had changed on PayPal's side was that we hadn't deployed any changes to production in a month, and everything was working fine up until two days ago, when our error monitoring first started picking up the issue.

We've confirmed that toggling to checkout.js works in the meantime.

It appears to be related to the changes made here:
https://github.com/paypal/paypal-smart-payment-buttons/commit/bac426f46a584dcef0c626fb7f5b1ddcf3e892e9

With our ecommerce system we transact on the behalf of clients, via the API, who currently provide us with only their PayPal account email address.

If we're expected to make an adjustment on our end to fit with the seemingly changed merchant restriction, please advise what we will need to do.

**Comment by bluepnume** [comment]
Hi all,

Given the number of instances of problems here, I've disabled this check for now. I apologize for the inconvenience. Can you please let me know the client-ids for your integration, and urls where I can test your integrations, so we can make sure you're not affected again.

**Comment by jwoodmansey** [comment]
Hi @bluepnume 

Thanks for your response. 

Our client id is `AX17VO9s87hiFXpHLCahoO7sSvP2JHRkjQO6LJE7uza0dE7swJV3PoBiupOz7eExWeU5HGBH_9LWCcdl`

And you can test the integration [here by clicking 'Buy tickets'](https://www.vibetickets.co.uk/event/22af4f71-9407-4f60-90e8-a55b43de6885/creamfields---thursday-friday,-saturday-&-sunday-creamfields-festival-warrington).

Or if you'd rather I can send details of our sandbox environment privately.

**Comment by knupska** [comment]
@bluepnume Thanks.

Our production client id is:
`AY8IEoPa2cTTVpYgjfKAYby35wyUgTE4liI1SEEXCYLGa4F2kdwSoOMSKE82jXXUL1NuXOQ1ARslBF65`

However as mentioned we're now running on the legacy `checkout.js` (which isn't experiencing the problem), until it gets fully resolved just to avoid any downtime for our clients.

I appreciate the removal of the check, but longer term we would prefer to properly comply with whatever restriction should be in effect, simply so that we don't run into it again if/when it is enabled.

Is there a method that you can point us to where we can retrieve the appropriate `merchantId` from the sellers PayPal account email address? If we can do that, then we can easily provide it to our frontend to have available at the point the sdk is retrieved.

I can provide sandbox testing environment details privately if needed.

**Comment by halomademeapc** [comment]
We're experiencing the same issue too - this broke payments in our event registration app in production.

Our Client ID is ```ATZCrZ6_m5JW1cI7AZl29lrYk3DIijxXabVcwiyQVM658ixdm05nGrsYEz-GZgiUD0nE0IJCe1-9DMkk```
You can test it [here](https://app.infarmbureau.org/eventregistration/Start?event=22)

Thanks

**Comment by bluepnume** [comment]
Thanks all,

To everyone asking about how to provide the merchant id across when you only have the seller's email address: we'll be providing detailed instructions for how to do this.

Appreciate your reports and patience on this one

**Comment by drey101** [comment]
> n

Thanks! I've verified it works on our end as well. We're still just applying Paypal integration so I'm just using sandbox accounts.

Closing this for now as it seems to be currently resolved. Will wait for detailed instructions on how to retrieve the merchant id using the seller's email address.

**Comment by knupska** [comment]
I noticed that the check was re-enabled, (albeit in a different way) shortly after it was disabled, https://github.com/paypal/paypal-smart-payment-buttons/commit/fdbce9da9302e43603737b3a9d9cf40f62ce4170

I'm curious as to what the implementation difference is there?

Does it no longer enforce that the merchanId be passed to the `sdk` include?
Is it possible to advise if that will be re-added in future?

Just looking to roll from our backup `checkout.js` back onto the `sdk` so we're more "future proof", but would prefer to know we're doing "everything right" so we don't experience it again.

**Comment by bluepnume** [comment]
Hi @knupska -- the check that's in place now will only validate if you explicitly pass the `merchant-id` parameter to the sdk.

We're working on adding a way for you to securely pass a payee email address when initializing the sdk. I'll update this thread when that's ready.

In the mean time, please feel free to upgrade again to the sdk when you're ready. We have your client id, and if we roll forwards with this validation again, we'll make sure your app is on the whitelist so your integration doesn't break while you make any changes needed to pass the payee email.

Thanks!

**Comment by knupska** [comment]
That all sounds great to me, thanks @bluepnume.

**Comment by lfarks** [comment]
Hi @bluepnume , can you also add my client id to the whitelist, so won't break in future updates:
client id: ASeuLJMrrdglkgGVsGYgW4LmhfH4s1YMWZTtTN2X94AQXxqcsKPBOZTRgslVixqmO7N7twu7T1A6adUo

**Comment by josephajose** [comment]
> Thanks all,
> 
> To everyone asking about how to provide the merchant id across when you only have the seller's email address: we'll be providing detailed instructions for how to do this.
> 
> Appreciate your reports and patience on this one

Hi @bluepnume,

Wondering if there were instructions released for this yet?  

Our Paypal Smart button integration is breaking again and now returning the following error message:
**Pass merchant-id=XYZ in the paypal script tag.**

It appears to have been introduced in the following commit and deployed on Monday, Sep  16, 2019:
https://github.com/paypal/paypal-smart-payment-buttons/commit/3bb3e5c23bdd4af59947cc4b561d0e5044a9e827

We currently were in the process of trying to backfill the merchant ID in our database based on successful Paypal Orders.  But for cases where we still don't have merchant ID and aren't including it the Script URL, we are getting this error.

Wondering if this new validation check was published anywhere.  I don't see it in any of the release notes.

Please advise as this is affecting many of our customers!  Thank @bluepnume!

**Comment by bluepnume** [comment]
Hi,

Can you confirm if this is still happening for you? There was a regression here that we pushed a fix out for yesterday.

Thanks,
Daniel

**Comment by josephajose** [comment]
@bluepnume I have confirmed this is still happening.  We have a logged failure just 3 hours ago.

<img width="953" alt="Screen Shot 2019-09-18 at 12 19 49 PM" src="https://user-images.githubusercontent.com/3230959/65178935-adb18380-da0e-11e9-859d-9d8c2f63f6d9.png">

**Comment by bluepnume** [comment]
Are you personally able to repro? I'm wondering if there's a cached script somewhere. I'll dig into it.

**Comment by josephajose** [comment]
Yes, I attempted to purchase on the same website we logged this error from and was able to reproduce it just now.  We are using the following script tag url:

```
<script src="https://www.paypal.com/sdk/js?client-id=<our_client_id>&currency=USD&disable-funding=card,credit"></script>
```

We are creating the order on the client side in the createOrder callback.

**Comment by bluepnume** [comment]
OK I think I've reproduced what you're seeing. Fix in progress.

**Comment by josephajose** [comment]
Thanks for jumping on this one @bluepnume!  Confirmed the fix you just applied is working! 🎉

**Comment by bluepnume** [comment]
Awesome, really glad to hear! Thanks for verifying

**Comment by TrevorHinesley** [comment]
@bluepnume just to clarify here: is the recommended way to specify an alternate payee via the `merchant-id` SDK param, by passing `payee[merchant_id]` to the order options, or a combo both?

I see that the referenced commit ensures that `payee[merchant_id]` is set on the order (and that it matches the SDK’s `merchant-id` param if set), but are these just failsafes? What’s the “right” way?

**Comment by bluepnume** [comment]
Hi @TrevorHinesley -- yes, ideally please pass both. They're required for different purposes, but yeah annoyingly there's some redundancy here.

**Comment by MomenB** [comment]
Hi @bluepnume - I think I have the same problem, I got this error when I execute it in localhost
![Capture](https://user-images.githubusercontent.com/48056467/83336360-7a243a00-a2bb-11ea-8306-b8cd8e5c98e8.PNG)

I hope you help me, my client-Id **"AWD-xA5A1DU202JcShB-b8mZi1LeUzjEyq2gdjLBLpaw1wsPggOvMappz5OtJR5KjIOGjFvwaPGMfwBZ"**

**Comment by Arunaliyanaarachchi** [comment]
@MomenB  I also getting this error from last week when i capture multiple orders. Did you find any solution for that ..? it used to work fine few weeks back

**Comment by bluepnume** [comment]
@MomenB @Arunaliyanaarachchi -- can you please try:

- Pass `&merchant-id=*` to the sdk url
- Pass `data-merchant-id="abc,xyz"` as a parameter to the script tag (these can be alphanumeric merchant ids or email addresses)

@weihou -- can you please share any developer docs for passing across multiple merchant ids/emails?

**Comment by MomenB** [comment]
@bluepnume it's worked Thanks a lot !

**Comment by MomenB** [comment]
@bluepnume - I tried and it's worked thanks a lot !

**Comment by MomenB** [comment]
@Arunaliyanaarachchi Yes this issue appears to me after I add multiple orders with multiple purchase units, but it's worked with bluepnume solution.

**Comment by clst** [comment]
I seem to have the same issue beginning this week on the sandbox environment. I have one order with multiple purchaseunits because of different shipping methods. That worked last week but now I get the same error. One single purchaseunit works fine. Checkout via `https://www.sandbox.paypal.com/checkoutnow?token=MYORDERID` also works with multiple purchaseunits.

I cannot pass `merchant-id=*` because the payee is the same.
Error: `Duplicates data-merchant-id. Must pass unique merchant ids to data-merchant-id.`

passing a single merchant-id seems to have no effect as it is the same `P5C2PD9ADY3TA` matching my client id:  `AU4X6Xr3hPRp8tFYvuETEt9v3wXBv7HKWfE08LTRF_lih83ijuoI3uLFTkswK2hNyCYfOMsftaeTvRcv`

**Comment by clst** [comment]
I just tried again with this tag like the console error message suggested: 
```
<script data-merchant-id='P5C2PD9ADY3TA,P5C2PD9ADY3TA' src='https://www.paypal.com/sdk/js?client-id=AU4X6Xr3hPRp8tFYvuETEt9v3wXBv7HKWfE08LTRF_lih83ijuoI3uLFTkswK2hNyCYfOMsftaeTvRcv&merchant-id=P5C2PD9ADY3TA&currency=EUR&debug=true'></script>
```
now I get a different error:
```
explicit_payee_transaction_mismatch 
{…}
​buttonSessionID: "d66831d600_mtc6mjq6mzm"
​env: "sandbox"
​merchantID: "[\"P5C2PD9ADY3TA\"]"
​payees: "[{\"merchantId\":\"P5C2PD9ADY3TA\",\"email\":{\"stringValue\":\"merchant_test@email\"}},{\"merchantId\":\"P5C2PD9ADY3TA\",\"email\":{\"stringValue\":\"merchant_test@email\"}}]"
​referer: "www.sandbox.paypal.com"
​sessionID: "a87de498e9_mtc6mjq6mzm"
​timestamp: "1591205127649"
```

Something seems to be broken.

**Comment by jaynetics** [comment]
we also now need to pass these values to be able to use the sandbox for pp4mp.

@bluepnume is this a bug? or will passing the IDs become a requirement in production, too? so far it just produces a warning in production.

**Comment by bluepnume** [comment]
Hi,

@clst -- can you let me know if you still see this error? This should have been resolved.

@jaynetics -- can you open a new ticket with specifics of the errors/warnings you're seeing? Thanks!

**Comment by clst** [comment]
@bluepnume Yes, it works fine now. Thanks a lot.

**Comment by RobertoGemo** [comment]
hi,
i am still getting this error.
i am trying to send payments from an angular pwa to paypals accounts (both personal and business) but whatever payee mail i use i get a "smart_button_validation_error_derived_payee_transaction_mismatch" error

**Comment by alabiboo** [comment]
Me too I have the same problem. If the number of merchant exceeds 1, the payment does not pass. Has anyone ever found a solution to this. please i need help

**Comment by jaynetics** [comment]
@alabiboo did you try it in production / live mode? It's still buggy for us on staging after all this time, but it has kept working in production fortunately. Apart of that, your best bet might be to open a ticket with PayPal MTS (Merchant Technical Support) and trying not to give up despite all their stalling tactics.
