### ISSUE TITLE
Different set of Smart Payment Buttons on the same page

### ISSUE THREAD

**Issue by kristina1lyba** [paypal/paypal-checkout-components#1179]
Hey guys!

We have a requirement to show different sets of Smart Payment Buttons on the same page, i.e. only yellow PayPal button on the top and all available buttons on the bottom of the checkout page. The only way to disable funding I found is to customize SDK script (https://developer.paypal.com/docs/checkout/reference/customize-sdk/#query-parameters) which sets global `paypal` object and doesn't allow to render different sets of buttons.

Is there any other way to disable fundings?
Thanks!

**Comment by bluepnume** [comment]
Hi! This isn't currently supported through this integration. The recommendation is to use a single set of buttons.
