### ISSUE TITLE
Small UI issue: Extra margin when cards disabled

### ISSUE THREAD

**Issue by kristina1lyba** [paypal/paypal-checkout-components#1183]
Extra `margin-top: 10px` appears when cards are disabled.
Really small issue but it breaks our layout cause we render not only PayPal buttons.
Please help 🙏 

<img width="1303" alt="Screen Shot 2019-08-16 at 12 53 45 PM" src="https://user-images.githubusercontent.com/47673738/63162835-3f9f2880-c02c-11e9-9438-df63c68eab26.png">

Thanks!

**Comment by jaynetics** [comment]
what worked for us was putting the button in a `div` with an appropriate `max-height` style and `overflow: hidden`.

the correct value for the style depends on the button setup - probably 50px in the case above. of course this will break things when the button layout changes.

**Comment by kristina1lyba** [comment]
@jaynetics We've disabled `cards` but not PayPal `credit` so the number of rendered buttons can be different inside an iframe, your fix wouldn't work for us :(

**Comment by bluepnume** [comment]
This should now be fixed. Thanks!

**Comment by kristina1lyba** [comment]
Seems to be fixed, thank you!
