### ISSUE TITLE
Usage with React Native

### ISSUE THREAD

**Issue by JamieCorkhill** [paypal/paypal-checkout-components#1185]
### Description
Hello. I'm just wondering what SDK I'm supposed to use to get the functionality provided by this repo in my React Native application. If necessary, I can use the native Swift and Java/Kotlin SDKs and build a wrapper around them for use with React Native.

Thank you,
Jamie

**Comment by deviousknight** [comment]
In our react native project we are using Braintree + paypal smart button in WebView and everything seems working. But you must use real page as source for webview not just html page from the app

**Comment by JamieCorkhill** [comment]
@deviousknight Thanks. I'm migrating to Stripe now. Perhaps I'll return to PayPal at a later point in time.
