### ISSUE TITLE
Inline guest checkout not working with US credit card

### ISSUE THREAD

**Issue by ChesterEcwid** [paypal/paypal-checkout-components#1188]
### Description

Hello! I'm Yuri from Ecwid.
We have js integration with PayPal (PayPal smart buttons). For three days inline guest checkout doesn't work when US credit card provided.

Client paypal.version is 4.0.284.

To avoid this issue we temporarily deactivate inline checkout but we wait for resolving.

### Steps to reproduce

Steps:
1) customer clicks PayPal inline checkout icon at payment page in online store. PayPal popup opens;
2) customer provides US credit card data;
3) customer clicks "Pay Now" button. PayPal loading icon appears;
4) after some seconds popup just becomes closed.

**Comment by bluepnume** [comment]
@khanghoang is this now resolved?

**Comment by khanghoang** [comment]
@ChesterEcwid sorry for the late reply. Is it still happening on sandbox?
