### ISSUE TITLE
A11Y: Frame title may not be clear

### ISSUE THREAD

**Issue by PhilibertDugas** [paypal/paypal-checkout-components#1189]
## Issue summary
The current value of the PayPal `iframe` `title` attribute may not clear in its meaning for people with cognitive disabilities. This could lead to a confusing user experience.

![Screen Shot 2019-06-26 at 10 21 05 AM](https://user-images.githubusercontent.com/1392632/60187786-2e8c2500-97fc-11e9-9d31-7afb30595bc6.png)

#### HTML
```html
<iframe
  …
  title="ppbutton"
  …
></iframe>
```

## Steps to reproduce

1. Navigate to https://gone-devn.myshopify.com/ with any supported browser
2. Add an item(s) to the Cart
3. Proceed to the Cart page
4. With an active screen reader, navigate to the PayPal control

### Expected

- Frame `title` text content to be clear.

### Actual

- Frame `title` text content may not be clear.

## Recommendation

Set an appropriate `title` attribute value to help describe the `iframe` purpose.

#### CSS
```html
<iframe
  …
  title="PayPal Checkout"
  …
></iframe>
```

## Specifications

- **WCAG Principle:** Perceivable
- **WCAG SC:** 1.3.1 Info and Relationships
- **Severity:** Medium
- **Effort:** Low

### Affected browsers

All

**Comment by gwardwell** [comment]
This really does need to be fixed for those of us that care about ADA compliance.

I can't seem to find a reference to `ppbutton` as the iframe title in this repo. If you can point me to the right place, I'd be happy to make a pull request.

**Comment by bradbyu** [comment]
Looks like the title for this iframe was initially added in this issue. https://github.com/paypal/paypal-checkout-components/issues/614

**Comment by bradbyu** [comment]
This issue still exists. Please address it soon!

**Comment by bluepnume** [comment]
Hi, please use the latest integration at https://developer.paypal.com/docs/checkout/ -- the iframe title is now `paypal_buttons`. Thanks.
