### ISSUE TITLE
in-line card issues on payment dialog - 17hats

### ISSUE THREAD

**Issue by travisfortney** [paypal/paypal-checkout-components#1190]
### Description

We were seeing some improvements over the last week but have a report now from multiple users that clients are unable to process payments on mobile devices (iOS so far only have been reported)

 When pressing one of the CC options (instead of 'pay with paypal' on the payment dialog), clients are now required to enter their shipping address; which isn't ideal for us but not the problem...  After doing so, clients get stuck in a loop where the payment doesn't process and they are required to enter their payment information again.  I'm including a video of the process I just personally recorded (attached or [here](http://cloud.travisfortney.com/306c0a0adda7/RPReplay_Final1566876441%252520(1).mp4)) while trying to pay one of our user's active invoices using safari on an iPhone XR (12.4).  Would you please  forward this to the appropriate team or let me know who to contact for an immediate resolution on this matter?  Payment works fine on desktop or when pressing 'pay with paypal' however if an individual credit card is selected/entered, we are not able to process payments and will be unfortunately forced to suggest to our users that they switch merchant accounts.  In my video, I used a test card which gives me 'there was an error' messaging but when using a live card, no indication is made of any payment attempt and clients are taken to the same dialog to start the process over again.  Thank you in advance for your prompt assistance in this matter! 

Travis@17hats.com

## repro steps

1) open safari on iPhone
2) navigate to live invoice (test) for our user [here](https://78640.17hats.com/p#/i/ntwwnbxpztnnbsfdxbdgdrffrcwwrkbz)
3) press 'pay invoice'
4) click on credit card button (*not* 'pay with paypal'); *example: VISA*
5) enter credit card details
6) submit payment

## expected

Payment is processed

## actual

client is brought back to original payment dialog (see video above or [here](http://cloud.travisfortney.com/306c0a0adda7/RPReplay_Final1566876441%252520(1).mp4)) and no payment is processed

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [X] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by travisfortney** [comment]
we noticed in the URL from your screenshot, token=undefined. This is a bit odd but while we haven't changed anything here since this ticket was submitted @khanghoang , we just tried again making a few payments on mobile and it seems to be working! I think we are good to close this for now and I appreciate the work done (it's been close to a month with over 100 reports so we are glad our users are able to process via PayPal again; thank you!)

**Comment by khanghoang** [comment]
@travisfortney Of course. I'm glad to hear that the issue was gone. Lemme close this.
