### ISSUE TITLE
Overlay does not stay when returning a promise

### ISSUE THREAD

**Issue by trainerbill** [paypal/paypal-checkout-components#1191]
In checkout.js, returning a non-resolving promise would keep the overlay around.  This was useful for merchants that do a redirect so that the background was not functional while the browser was performing the redirect.  I cannot get this to work in the new payments SDK.

```
onApprove: function(data, actions) {
                    actions.redirect('http://www.google.com');
                    
                    return new Promise(function (resolve, reject) {} );
                },
```

```
onApprove: function(data, actions) {
                    return actions.redirect('http://www.google.com');
                },
```

https://youtu.be/-ovTDmvu_D4

**Comment by trainerbill** [comment]
@bluepnume any idea here?  still occurring.

**Comment by vvakame** [comment]
agreed. so, old PayPal JS SDK is wait for promise resolved. I wanna move into current version, but this issue is little bit blocker for our app.

**Comment by bluepnume** [comment]
Will look into this one. Thanks.

**Comment by trainerbill** [comment]
@bluepnume anyway we can get this feature?

**Comment by gregjopa** [comment]
Bump

**Comment by mylesmacrae** [comment]
Bump.  This bug is preventing me from adopting the sdk.

**Comment by gregjopa** [comment]
Let's use #1486 to track this issue. Closing this as a duplicate.
