### ISSUE TITLE
Q: Is it possible to use overlay on window.parent if SPBs are rendered in iframe ?

### ISSUE THREAD

**Issue by vsashyn** [paypal/paypal-checkout-components#1192]
Hello guys!
Is it possible to render overlay somehow on a parent window if smart payment buttons are rendeder inside iframe? 
We have specific case and thinking how can we manage it.

![img_iframe_spb](https://user-images.githubusercontent.com/4557935/63865411-3615a900-c9ba-11e9-9f9b-f87f09d05ef1.png)

Thanks a lot!

**Comment by bluepnume** [comment]
Yes -- please load the paypal script in the parent window too. Then the overlay will appear on that page.
