### ISSUE TITLE
createSubscription flow is throwing an error 

### ISSUE THREAD

**Issue by ekhaidarov** [paypal/paypal-checkout-components#1196]
### Description
Using the latest paypal-JS-SDK:latest(https://www.paypal.com/sdk/js?client-id=sb&currency=CAD&commit=false&vault=true) unable to proceed with subscription checkout. Server is responding with the valid payload, but button is expecting a subscription Id. Payload looks correct. 

Button throws an exception 
`Erroneous payment OR failed to load script! Error: Expected an subscription id to be passed to createSubscription
   `

### Steps to reproduce

Step 1) Create subscription 
`onCreateSubscription = (data: any, actions: any, plan:PricingPlan) => {
    return new Promise((resolve, reject) => {
       resolve(actions.subscription.create({
        'plan_id': "P-YYYYYYYYYYYY"
      }));
    });
  }`

Step 2) Server responds with a valid payload and subscription id 
`{
    "status": "APPROVAL_PENDING",
    "id": "I-XXXXX",
    "create_time": "2019-09-08T02:06:40Z",
    "links": [
        {
            "href": "https://www.sandbox.paypal.com/webapps/billing/subscriptions?ba_token=BA-XXXXX",
            "rel": "approve",
            "method": "GET"
        },
        {
            "href": "https://www.sandbox.paypal.com/v1/billing/subscriptions/I-XXXXX",
            "rel": "edit",
            "method": "PATCH"
        },
        {
            "href": "https://www.sandbox.paypal.com/v1/billing/subscriptions/I-XXXXX",
            "rel": "self",
            "method": "GET"
        }
    ]
}`

### Affected browsers
- [x] All

**Comment by ravishekhar** [comment]
@ekhaidarov Can you please share the webpage where this code is hosted?

**Comment by ekhaidarov** [comment]
Hi @ravishekhar , 

This is still in development, hosted privately, but I can share bits and pieces and provide a network capture, and the console logs as needed. We are using this out of the react.js. We are using https://www.npmjs.com/package/react-paypal-button-v2 with an additions that we wrote to be able to create a subscription, which is basically the function that I shared in the bug. We created a product via REST API, assigned billable plans, and now going thought the JS checkout flow trying to get the client to purchase and activate it. I am following the guide to the letter: https://developer.paypal.com/docs/subscriptions/integrate/#4-create-a-subscription. 
I am also including a link to the recording : https://youtu.be/_uzfDOfHrZA 

Logs and the HAR are included here: 
[checkout-flow.log](https://github.com/paypal/paypal-checkout-components/files/3587661/checkout-flow.log)

**Comment by ravishekhar** [comment]
@ekhaidarov Can you pls host relevant codes in github or some place and share so that I can verify. Looking at the video it appears network calls are successful but Subscription Id (I-XXXXX) was not returned from `createSubscription` hook.

**Comment by ekhaidarov** [comment]
Hi @ravishekhar,

I ripped out all of proprietary code, and created a simple app showcasing the problem. Please review file:SectionPricing.tsx for details. It is plain vanilla button on the page with our SB key, and simple create subscription fllow. 
[paypal-subscription-createsubscription-problem.zip](https://github.com/paypal/paypal-checkout-components/files/3591106/paypal-subscription-createsubscription-problem.zip)

**Comment by ravishekhar** [comment]
Here is the issue, in this file
paypal-subscription/src/views/PricingPage/Sections/SectionPricing.tsx:L104
Change
      `createSubscription: (data: any, actions: any) => {this.onCreateSubscription(data, actions, standard)},`

to 
`createSubscription: (data: any, actions: any) => {return this.onCreateSubscription(data, actions, standard)},`
It Works!
Created a subscription as well :) 

Also You do not need commit as true for subscription.

**Comment by ekhaidarov** [comment]
@ ravishekhar thanks so much for taking the time to look at this. I have been battling this for couple of days, and without having another pair of eyes on it. Again, thank you.

**Comment by ekhaidarov** [comment]
@ravishekhar hopefull last question, I have made the changes, and indeed the diaglog is showing up now, but attempting, but upon finalizing the payment. SDK doesn't call onApprove function, but rather thrown an unhandled exception. It seems one of the server APis is responding with 500 Internall Error, seems like backend app related. 

[checkout.log](https://github.com/paypal/paypal-checkout-components/files/3591847/checkout.log)

**Comment by ravishekhar** [comment]
As I was mentioning earlier
> Also You do not need commit as true for subscription. 

We will get our docs updated.
