### ISSUE TITLE
PayPal checkout process dies at the end when creating a subscription

### ISSUE THREAD

**Issue by ekhaidarov** [paypal/paypal-checkout-components#1198]
### Description
PayPal button loads for a split second and disappears. Everything worked with this code as of September 9, 2019. Using the latest SDK : 5.0.67 . I am also attaching our sample application that reproduces the problem. Secondary problem when using createSubscription flow, user is able to login and gets a screen to perform checkout, but SDK never calls onApprove, and fails with an Error unable to capture order details. I am attaching the log. Also, as a side note, documentation around subscription flow is virtually non-existent, and the short documentation(https://developer.paypal.com/docs/subscriptions/integrate/#) is not sufficiently covering JS portion of the integration. Through experimentation, and errors in the SDK, I had to deduce that createOrder function can't be specified with createSubscription is defined. Any help better highlighting the expected flow would be very appreciated, I would be happy to provide any assistance in testing.

[paypal-button-fails.log](https://github.com/paypal/paypal-checkout-components/files/3596642/paypal-button-fails.log)

- The `paypal.version` "5.0.67"
![Screen Shot 2019-09-10 at 12 10 15](https://user-images.githubusercontent.com/5084656/64631233-ac57d980-d3c4-11e9-8333-030fc9f2e103.png)
[paypal-button-fails.log](https://github.com/paypal/paypal-checkout-components/files/3596648/paypal-button-fails.log)

### Steps to reproduce
Attaching our sample application
[paypal-subscription.zip](https://github.com/paypal/paypal-checkout-components/files/3596666/paypal-subscription.zip)

### Affected browsers

- [x] Chrome - 
Google Chrome | 76.0.3809.132 (Official Build) (64-bit)
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}

- [x] Safari - Version 12.1.1 (14607.2.6.1.1)

**Comment by ekhaidarov** [comment]
Also attaching a zip file containing har shows 500 Internal Error in the sanbox environment when try to capture the order after subscription is created. 

[checkout.har 2.zip](https://github.com/paypal/paypal-checkout-components/files/3598360/checkout.har.2.zip)

**Comment by ravishekhar** [comment]
Can you please remove commit=true from your config and try again. For Subscription you cannot capture the transaction. Capture is one time payment construct.

The similar construct for subscription is activate.
https://developer.paypal.com/docs/api/subscriptions/v1/#definition-application_context 
Pls see section `user_action`

**Comment by ekhaidarov** [comment]
Hi @ravishekhar, 

I did remove the commit, and I retried various configurations. I apologize, I must have included the original zip file before the recommended change. However, I have made the change and attaching the latest sample code that has commit set to **false** and vault set **true**. It is exactly the same problem.

[console.log](https://github.com/paypal/paypal-checkout-components/files/3600372/console.log)

[paypal-subscription.zip](https://github.com/paypal/paypal-checkout-components/files/3600365/paypal-subscription.zip)

[checkout.har.zip](https://github.com/paypal/paypal-checkout-components/files/3600368/checkout.har.zip)




> receive::err postrobot_method https://www.sandbox.paypal.com 
 Error: Order could not be captured

**Comment by ekhaidarov** [comment]
Hi @ravishekhar ,

Can you please share any code that you may have the shows complete end to end example on what should be done to integrate subscription fully?

**Comment by ekhaidarov** [comment]
@ravishekhar  Is it possible to get an update on this? We are completely blocked by this issue to be able to proceed into Production. Can you please advise how to work around it? System is clearly acknowledging the fact that the transaction succeeded, but JS code due this failure doesn't fire any other events to be able to finalize and complete user flow. Any help would be greatly appreciated

`curl 'https://www.sandbox.paypal.com/smart/api/order/2NB20988D6934524E/capture' -X POST -H 'x-paypal-internal-euat: S23AAGUJwDmpgFMz_gvovXpc3yfQLidR1IcJOAb-HK1uH7Ruri5pcdLt581QRNC0EhIRD8FDVa_1DvrOFBrv3Kftkoi4mYMmg' -H 'Origin: https://www.sandbox.paypal.com' -H 'x-requested-by: smart-payment-buttons' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36' -H 'Sec-Fetch-Mode: cors' -H 'accept: application/json' -H 'Referer: https://www.sandbox.paypal.com/smart/buttons?currency=CAD&style.layout=vertical&style.color=gold&style.shape=rect&style.tagline=false&components.0=buttons&locale.country=US&locale.lang=en&sdkMeta=eyJ1cmwiOiJodHRwczovL3d3dy5wYXlwYWwuY29tL3Nkay9qcz9jbGllbnQtaWQ9QVdIaEQ3OXc2aXBZV0UtRGpQeVRCVGFLUGFmSU1OSUhDaWIyVS1wRE5JQlhFcDNBLVloRUxiVkRIR3JTYzRvMFlSbUVYV19RTFlQYzNpRGwmY3VycmVuY3k9Q0FEJmNvbW1pdD1mYWxzZSZ2YXVsdD10cnVlJmRlYnVnPXRydWUiLCJzdGFnZUhvc3QiOm51bGwsImFwaVN0YWdlSG9zdCI6bnVsbH0&clientID=AWHhD79w6ipYWE-DjPyTBTaKPafIMNIHCib2U-pDNIBXEp3A-YhELbVDHGrSc4o0YRmEXW_QLYPc3iDl&sessionID=699ba10acc_mtq6mza6mzc&buttonSessionID=285ff60088_mtq6mza6nda&env=sandbox&fundingEligibility=eyJwYXlwYWwiOnsiZWxpZ2libGUiOnRydWV9LCJjYXJkIjp7ImVsaWdpYmxlIjp0cnVlLCJicmFuZGVkIjp0cnVlLCJ2ZW5kb3JzIjp7InZpc2EiOnsiZWxpZ2libGUiOnRydWV9LCJtYXN0ZXJjYXJkIjp7ImVsaWdpYmxlIjp0cnVlfSwiYW1leCI6eyJlbGlnaWJsZSI6dHJ1ZX19fX0=&platform=desktop&intent=capture&vault=true&debug=true' -H 'x-source: smart_buttons' --compressed`

`{"ack":"error","message":"Unhandled api error","meta":{"calc":"bd2fe3cdbcc9a","rlog":"rZJvnqaaQhLn%2FnmWT8cSUueWscmrtUHe5Y1Bd%2FeqyvyOTq66rSXAcoHt23K4aX7r7RV0T%2BAtZVLHG%2FvY24WQLjT1E6LUGubF3ndPH1fWHzY_16d302f5526"},"server":"JK_TYMXJgWgJSdz-0SCOuDK-x1bDWd73DE5pcUJYk6XFsK-rrJr8WIGrulXyMEe9Ji9rouaKL0-qkTJV3jfnudACjZLEJCuo-sPY1NzCWdPX-9cYMdNPDvi827rqoKowOy7ci7wWPMGL2Sxx1pAUUwIrHP6T_-utnB0lca8AxvS2L-1sN6-5OuUwxgVY46oCSLpcJ0iIK43f7EFrd5SPxOHkABG57OJBqbU1KLv1BRgYqdmdBIUnKCW7gW_Dmf4zxz4Jl7DucTTcAOkos7rSSW"}`

**Comment by monir12342** [comment]
Dear sir
I will glad that if you transfer money my bank account. . Bangladesh MUTUAL
TRUST BANK LTD. SHAH MAKHDUM AVENUE 12. A/C NO - 0620300014032 MY SAVINGS
ACCOUNT.
REGARDS
MONIRU ISLAM
R 18 H38 SECTOR  11 WEST UTTARA DHAKA 1230

**Comment by monir12342** [comment]
Dear sir
My bank account details
Name- MUTUAL TRUST BANK LTD
WEST UTTARA, SHAH MAKHDUM AVENUE, SECTOR-12
DHAKA 1230 BANGLADESH
A/C NO - 0620300014032 SAVINGS ACCOUNT.
MOBILE NO +8801765523107
REGARDS
MONIRUL ISLAM

**Comment by monir12342** [comment]
Dear sir,
Please sorry for account no
Below wright one
A/C NO - 0620310004032 MY SAVINGS ACCOUNT
REGARDS
MONIRUL ISLAM

**Comment by ravishekhar** [comment]
Hi @ekhaidarov,
Sorry I was out sick, could not reply earlier. 
As I was mentioning you cannot capture a subscription transaction. capture is a one time payment construct. 

In your code `src/components/Payment/PaypalButtonV2.tsx:139` change 
```
onApprove(data: any, actions: any) {
        return actions.order
            .capture()
            // @ts-ignore
            .then((details) => {
                if (this.props.onSuccess) {
                    return this.props.onSuccess(details, data);
                }
            })
            // @ts-ignore
            .catch((err) => {
                if (this.props.catchError) {
                    return this.props.catchError(err);
                }
            });
    }
``` 
to 
```
onApprove(data: any, actions: any) {
        alert('Subscription is created');
    }
```

And you should be good to go. Please read my earlier comments for documentation around it.

**Comment by monir12342** [comment]
Bank account details MUTUAL TRUST BANK LTD. SHAH MAKHDUM AVENUE SECTOR-12 WEST UTTARA DHAKA-1230
A/C No - 0620310004032  MONIRUL ISLAM

**Comment by ekhaidarov** [comment]
@ravishekhar Thanks for your help!

**Comment by synthet** [comment]
I have solved similar issue by removing all redundant fields from Smart Buttons config object copied from "Order" integration.
I left only those that are present in documentation for "Subscription".
Looks like some of them are related only to "Order" workflow causing useless "capture" request.
