### ISSUE TITLE
Buttons payment form no longer modal

### ISSUE THREAD

**Issue by Ed-SA** [paypal/paypal-checkout-components#1200]
### Description

Starting today, users have reported that almost always, the payment form is displaying inline in the page instead of modally.  It does it for me as well.  Instead of the centered modal popup with overlay, it displays a squished-looking set of the data fields within the page; and will not process the transaction when data is entered (my log shows "navigated away" as the message).

### Steps to reproduce

All users are reporting this during the checkout process when they click the "Visa" button.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [X] Firefox
- [ ] Edge
- [X] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by Ed-SA** [comment]
For anyone else experiencing this issue, the resolution was: Josh@paypal made a change to "blacklist the merchant" (his terminology) which seems to have reverted the API to the previous version for them (transactions now process and the UI is back to the modal experience).

**Comment by timlet** [comment]
Are there going to be any further announcements about changes to the behaviour of the integration or documentation around when a user might expect to see this inline vs. in the current modal popup?

It appears to be inconsistent across browsers currently (for example inline on Chrome, but not on Edge) 

Additionally should passing the integration-date parameter prevent the new inline form from triggering?

**Comment by seekingtheoptimal** [comment]
For me when hooking anything on the onShippingChange handler in the JS SDK, it opens the modal, if no event handler hooked, then I get the inline guest checkout. Problem is, the inline checkout does not succeed (fails with Internal Error 500 on PayPal side!), plus there is no price overview like in the modal (literally the price is not displayed at all in the inline guest flow, wtf :D). 
![image](https://user-images.githubusercontent.com/17144089/100292470-dde4a280-2f80-11eb-8120-f5085540e143.png)
@joshapplebaum maybe you can have a look? I would really appreciate your time!
The thing is, there is zero info on what decides which flow, modal or inline is triggered. It feels like A/B testing or lottery a bit : ( I went through all the paypal community questions, a lot of people having similar symptoms, but nobody could exactly pinpoint so far what is the real trigger logic for each.
(I am testing atm from localhost and 127.0.0.1, not sure if this has to do anything with the above)
