### ISSUE TITLE
Missing documentaion for `x-app-name` header

### ISSUE THREAD

**Issue by annshress** [paypal/paypal-checkout-components#1202]
On mutation (like `payWithCard`), we receive following as extension response,

```
"extensions": {
    "developerNotes": [
      "Please include an 'x-app-name' header with your request that identifies your client.  (Ex: 'x-app-name': 'hermione')"
    ],
    "correlationId": "9670fb273238d"
  }
```

There is no reference for such header in the documentation

**Comment by inquisitive-stha** [comment]
@annshress did u find any solution?

**Comment by annshress** [comment]
@inquisitive-stha Nope. I could not find anything on that.

**Comment by bluepnume** [comment]
This is an internal issue. We have a fix going out for the next release. Thanks!

**Comment by khanghoang** [comment]
@inquisitive-stha @annshress @bluepnume Thanks for reporting it. It will be fixed in the next release.

**Comment by SuperUserNameMan** [comment]
I'm having the same issue currently in sandbox mode.

It worked once the 28 oct 2019 at 15:08:48 CET, then all subsequent tests failed.

**Comment by djmaze** [comment]
Same problem still in the Sandbox for me.

**Comment by cjsimmons89** [comment]
Still having the same problem in Sandbox, same as @djmaze only 2 months later. Any releases coming to fix this in sandbox?
