### ISSUE TITLE
Smart Buttons works BUT no transactions are recorded

### ISSUE THREAD

**Issue by ManlyBoy** [paypal/paypal-checkout-components#1203]
I have followed the Smart Buttons Integration guide plus installed the SDK and have everything working fine including the return call from PayPal recording the approval to the capture, entering into my database etc. Only problem is that the credit/debit are not recorded in the relative sandbox accounts nor when going live in the real accounts.

Here's my script:

Created Script = "<script language="javascript" type="text/javascript">
 function populatePayPalButtons() {
   paypal.Buttons({
   // --------- createOrder ---  
    createOrder: function(data, actions) {
     return actions.order.create({
    purchase_units: [{
     description: 'Court 2 Hire', 
     amount: { value:'20.00' },
     invoice_id:'4892.01'
    }] 
  });
 },
   // --------- onApprove --- 
   onApprove: function(data, actions) { 
    // Call your server to process the transaction 
    var url = 'http://localhost/api/PayPal/VerifyAndRecordOrder';
      return fetch(url, { 
       method: 'post',  
       headers:	{ 
         'content-type': 'application/json' 
       }, 
      body: JSON.stringify({ 
       OrderID: data.orderID, 
       AmountPaid: '20',   
       BookingNumber: '4892.01',   
       Description: 'Court 2 Hire',   
       MembNumber: '4563',   
       MemberID: '20005'   
      }) 
    }).then(CloseAndReturnToParentPage('Success')); 
   }, 
   // --------- onCancel --- 
   onCancel: function(data, actions) { 
    // Show a cancel page, or return to cart 
    }, 
   // --------- onError --- 
   onError: function(err) { 
    // Show an error page 
    alert('PayPal: An error has occurred! '); 
    alert(err); 
   } 
  }).render('#paypal-button-container'); 
 } 
</script>

Here's the log file of the return from PayPal:

API.Controllers.PayPalController.VerifyAndRecordOrder Returned: [System.Threading.Tasks.Task`1[BraintreeHttp.HttpResponse]]
InvoiceID/BookingNumber: = "4891.01"
Description: = "Center Court Hire"
CustomID/MemberID: = ""
Status: = "APPROVED"
Order Id: = "2J2231"
Created: = "2019-09-13T22:43:26Z"
Intent: = "CAPTURE"
Payer.FullName: = ""
Payer.GivenName: = "Glen"
Payer.Surname: = "Buyer"
Links:
self: https://api.sandbox.paypal.com/v2/checkout/orders/2J231 Call Type: GET
capture: https://api.sandbox.paypal.com/v2/checkout/orders/2J031/capture Call Type: POST
Total Amount: AUD 30.00
Response JSON: {0} = "{
  "create_time": "2019-09-13T22:43:26Z",
  "id": "2J231",
  "intent": "CAPTURE",
  "links": [
    {
      "href": "https:\/\/api.sandbox.paypal.com\/v2\/checkout\/orders\/2J031",
      "method": "GET",
      "rel": "self"
    },
    {
      "href": "https:\/\/api.sandbox.paypal.com\/v2\/checkout\/orders\/2J0531\/capture",
      "method": "POST",
      "rel": "capture"
    }
  ],
  "payer": {
    "address": {
      "country_code": "AU"
    },
    "email_address": "buyer@aq",
    "name": {
      "given_name": "Glen",
      "surname": "Buyer"
    },
    "payer_id": "H8"
  },
  "purchase_units": [
    {
      "amount": {
        "currency_code": "AUD",
        "value": "30.00"
      },
      "description": "Center Court Hire",
      "invoice_id": "4891.01",
      "payee": {
        "email_address": "gl.au",
        "merchant_id": "W5BC"
      },
      ""
API.Controllers.PayPalController.recordOrder  [payPalDTC] = [API.PayPal.PayPalDTC] [order] = [API.PayPal.Orders.Order]
OrderID = "2J31"
API.Controllers.PayPalController.recordOrder Returned: [True]

What else do I need do to actually process the order. It's been CAPTURED and APPROVED already. Is there a "PROCESS" request!!!

**Comment by KPowroznik** [comment]
How looks your CloseAndReturnToParentPage function? I see that You didn't return action.orders.capture() function in your onApproveMethod.

**Comment by bluepnume** [comment]
Please let me know if you're still seeing this issue. Thanks.
