### ISSUE TITLE
CSP nonce does not work for styles

### ISSUE THREAD

**Issue by TheTrueRandom** [paypal/paypal-checkout-components#1218]
### Description
https://developer.paypal.com/docs/checkout/troubleshoot/support/#content-security-policy-rules states that providing a `data-csp-nonce` will propagate the nonce accordingly. This does not work for style. The attached screenshot shows the inserted style tag which misses the nonce even though data-csp-nonce is provided for the client. 

![DeepinScreenshot_select-area_20190828224103](https://user-images.githubusercontent.com/43322965/65895919-75198e80-e3ac-11e9-82a7-9e537bdecf2e.png)

paypal.version
`5.0.74`

### Steps to reproduce
include `<script src="https://www.paypal.com/sdk/js?client-id=sb&amp;currency=EUR" data-csp-nonce="random-nonce"></script>` to your html page and also make sure the csp header contains the nonce (`random-nonce`) for styleSrc. The buttons will not render correctly and the console will show many CSP style errors. 

### Affected browsers
Every modern browser with CSP support (Chrome, Firefox, Safari, ...)

**Comment by bluepnume** [comment]
@amaclean2 can you take a look? Thanks!

**Comment by WangWinson** [comment]
Hi guys, please do help to look into this.
I can create very simple script to reproduce it. and see also the error from console.

![](https://files.slack.com/files-pri/T3T9KQULR-FPNUH2ECC/image.png)

**Comment by bluepnume** [comment]
Can track this one here: https://github.com/paypal/paypal-checkout-components/issues/1248
