### ISSUE TITLE
Uncaught Error: PayPal Payments SDK script not present on page!

### ISSUE THREAD

**Issue by ThisUsedToBeAnEmail** [paypal/paypal-checkout-components#1219]
### Description

I was getting the "Uncaught Error: PayPal Payments SDK script not present on page!" error while trying to load the SDK via the following url:

https://paypal.com/sdk/js?debug=true&client-id=sb

This is demonstrated as being valid in your documentation: https://developer.paypal.com/docs/checkout/reference/customize-sdk/

This is failing if you're working in a 'sandbox environment' because the code is searching for a script tag with 'www.paypal.com' which would not exists.

L5344 `var host = getEnv() === ENV.SANDBOX ? 'www.paypal.com' : getHost();`

To fix you could possible change this line to url.indexOf(src) instead of an exact match.

L3390 `if (src === url) {`

### Steps to reproduce

<body>
        <script src="https://paypal.com/sdk/js?debug=true&client-id=sb"></script>
</body>

### Affected browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge
- [x] IE
- [x] Chrome Mobile/Tablet
- [x] Safari Mobile/Tablet
- [x] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
You need to include the www. Thanks for pointing out that doc, we'll get it fixed!

**Comment by bluepnume** [comment]
@amaclean2 can you take a look at fixing that doc? Thanks!

**Comment by nousacademy** [comment]
+ 1
