### ISSUE TITLE
ios webview login popup is flickering 

### ISSUE THREAD

**Issue by deviousknight** [paypal/paypal-checkout-components#1221]
### Description

Hello, in our React Native project we are using WebView component with braintree paypal library inside. In login paypal popup window we are having "flickering" footer which leads after password to be flickered Paypal preloader too. 

While digging through paypal iframe It looks like popup layout code is adding and then removing "footerStayPut" css class on footer tag. 

![issue-2](https://user-images.githubusercontent.com/19371283/66126638-9966ac80-e5f2-11e9-9015-d79f153820c9.gif)

### Steps to reproduce

Can be reproduced on any ios webview on input password step. Just open https://developer.paypal.com/demo/checkout/#/pattern/checkout  and click Paypal button from Skype or Telegram built-in browser

### Affected browsers
-  IOS Web View

**Comment by bluepnume** [comment]
@amaclean2 can you take a look? Thanks!

**Comment by amaclean2** [comment]
@deviousknight This doesn't appear to be a problem anymore. Can you try to retest and get back?

**Comment by deviousknight** [comment]
@amaclean2 thanks! On our iphoneX and 8 everything seems is working perfectly

**Comment by amaclean2** [comment]
@deviousknight Awesome, thanks. I'll close it then
