### ISSUE TITLE
Disable button reveal animation / transition

### ISSUE THREAD

**Issue by richardscarrott** [paypal/paypal-checkout-components#1223]
### Description

Upon revealing the PayPal button (display none -> block), it transitions in with a "reveal" animation which [looks like a bug](https://youtu.be/OvChkOHgDIo?t=31). It would be great if we could disable it?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/539309/66226044-cfc72900-e6d1-11e9-8071-c930b45a64da.gif)

### Steps to reproduce

1) Visit https://developer.paypal.com/demo/checkout/#/pattern/radio
2) Toggle between PayPal -> Card and back again.

### Affected browsers

- [x] Chrome

**Comment by bluepnume** [comment]
Thanks for the report. Checking into it.

**Comment by pabloai** [comment]
Hi @bluepnume!

Any updates on this?
It could potentially fix an issue we're having when showing and hiding the PayPal buttons several times.
It randomly fails to set the full height, which remains on 0, so it only shows the min-height of 25px.

Adyen/adyen-web#34
![paypal-issue](https://user-images.githubusercontent.com/7926613/87026180-aba5f480-c1db-11ea-9ac5-3c08c85cb4c9.gif)

**Comment by pabloai** [comment]
Hi @bluepnume and @mstuart,
Is there any update on this? Cheers!

**Comment by svitch** [comment]
any update on this?
