### ISSUE TITLE
"Click to continue" not working

### ISSUE THREAD

**Issue by gautia** [paypal/paypal-checkout-components#1225]
### Description

[](**URL: https://developer.paypal.com/demo/checkout/#/pattern/client**)
'click to continue' button in the shadow doesn't work as expected.

- Your code [Same code as in the demo link]
- The exact browser version [All the browser and MacOS,]
- Does the issue also occur at [developer.paypal.com/demo/checkout]-(https://developer.paypal.com/demo/checkout)- YES
- Does the issue occur consistently, or intermittently- Consistently

### Steps to reproduce

__To reproduce the issue,
1. Open the In-context.
2. Click the 'PayPal' button BEFORE 'Powered by PayPal' word gets initialized.
if you missed then try to reload the page again.
3. 'click to continue' button in the shadow works as expected
4. if 'Powered by PayPal' gets loaded before you click the 'PayPal' button. then 'click to continue' button in the shadow doesn't work as expected.__

### Affected browsers

All the browsers.

**Comment by bluepnume** [comment]
This should be resolved. Please let me know if you're still seeing the issue. Thanks.
