### ISSUE TITLE
you just broke the internet with 4.0.294

### ISSUE THREAD

**Issue by tobsn** [paypal/paypal-checkout-components#1226]
https://www.paypalobjects.com/api/checkout.js

there's a diff inside the published dist js in aboves url:

```<<<<<<< HEAD
      ver: "4.0.293"
=======
      ver: "4.0.294"
>>>>>>> 435ad39f6c4ddf82e58010244c18fadd55b7ab6e
    };
```

line 1448... code is broken. leads to everything else also not executing.

**Comment by tobsn** [comment]
@bluepnume ^

**Comment by bluepnume** [comment]
We're on it. Thanks for the heads up.

**Comment by bluepnume** [comment]
Fix has been rolled out and cache cleared. Looks like an issue in the deployment pipeline for the CDN. We're investigating that right now. Sincere apologies for the inconvenience here.

**Comment by Jofiman** [comment]
Please solve this :).

Thank you.

**Comment by bluepnume** [comment]
@Jofiman -- are you still experiencing the issue? Does clearing browser cache resolve it?

**Comment by kjvarga** [comment]
Working for me now after clearing my cache.

**Comment by tobsn** [comment]
new version is coming through without CDN cache - looks all fixed now.


@bluepnume can you link the post mortem on this one, I need to explain what happened because ads were blasting to our checkouts and for over an hour it was broken...

**Comment by Jofiman** [comment]
Yes, working for me too. 

Thx

**Comment by fabiosussetto** [comment]
I'm baffled that's not possible to fix the sdk version used, like any other sane SDK. The Checkout buttons SDK seems rather unstable, with things breaking quite often. That's understandable, but please release using a tag and make that available so we can pin-point the working version we integrated. People can't afford to wake up in the morning with customers screaming cause you released a new version without notice.
