### ISSUE TITLE
Locale and country code are not working all the time

### ISSUE THREAD

**Issue by samighawi** [paypal/paypal-checkout-components#1231]
### Description
I am using Paypal smart buttons and want to enforce the language to always become English and the country to always be Israel. However, both are not working most of the time. I am testing the credit card case.

In terms of country, I keep getting arbitrary countries without knowing the reason. While I got Israel at couple of tests, I also got USA, Solomon Islands, UK and Bosnia. I understand that USA is the default but not sure how Paypal decided to select the other ones.

In the case of language, most of the times it switches back to Hebrew whenever I select Israel but I have the locale set as English as per code provided. Now it worked couple of times but stops after a while even though the code was not adjusted.

### Steps to reproduce
I extracted my code and provided it below.
Steps:
1. Click on Visa => Observe the Country
2. Select Israel => Observe the language

https://jsfiddle.net/vhfbwk3u/1/

**Comment by bluepnume** [comment]
Please let me know if you're still seeing this issue. Thanks.
