### ISSUE TITLE
Logger error when using sandbox

### ISSUE THREAD

**Issue by andyli** [paypal/paypal-checkout-components#1232]
When I load the JS file with a sandbox client-id,
```
<script src='https://www.paypal.com/sdk/js?client-id=${sandbox_client}&currency=${currency}'></script>
```

In the browser console, there is a network error
```
SEVERE network https://www.sandbox.paypal.com/xoplatform/logger/api/logger - Failed to load resource: net::ERR_CONNECTION_RESET
SEVERE console-api https://www.paypal.com/sdk/js?client-id=[MASKED]¤cy=USD 0:45292 "unhandled_error" Object
SEVERE javascript https://www.paypal.com/sdk/js?client-id=[MASKED]¤cy=USD 0:44094 Uncaught Error: Request to post https://www.sandbox.paypal.com/xop…logger/api/logger failed: [object ProgressEvent].
```

`paypal.version`: "5.0.76"

- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)? Yes
- Does the issue occur consistently, or intermittently? Consistently, started from today.

**Comment by ekiametis** [comment]
I have the same error.

**Comment by bluepnume** [comment]
Hi, please let me know if you're still seeing this issue. Thanks.

**Comment by GfxKai** [comment]
I'm also getting this issue!

**Comment by dmalis** [comment]
+1

**Comment by fhferreira** [comment]
+1

**Comment by MaxithSs** [comment]
+1

**Comment by DerekRTP** [comment]
@bluepnume still seeing this issue. Thanks.

**Comment by inthisar-hamza** [comment]
Sometime AdBlock extension will block the some requests. so, check it and disable the AdBlock

**Comment by dellow** [comment]
The Brave browser throws these errors constantly possibly due to the inbuilt Adblocker. This is problematic because error logging services such as Sentry go wild every-time a Brave user loads a page with PayPal on it.

**Comment by dmalis** [comment]
Indeed, Sentry goes wild, along with its cost.

I've posted this issue a while ago: https://github.com/paypal/paypal-checkout-components/issues/1464

**Comment by samluisito** [comment]
si tienes un bloqueador de anuncios deshabilítalo o agrega las url de paypal a la lista blanca
