### ISSUE TITLE
`onShippingChange` doesn't receive the full shipping address

### ISSUE THREAD

**Issue by richardscarrott** [paypal/paypal-checkout-components#1236]
### Description

I'm unable to verify the shipping address via our shipping provider as `address_line_1` isn't surfaced in `onShippingChange`.

This means I can't let the customer know within the PayPal UI that it's an unsupported shipping method and instead have to verify it in `onApprove` and show them an error in our UI, asking them to go back through the PayPal flow.

I wondered whether this was by design, i.e. you don't provide the full address until the customer has explicitly clicked approve?

```js
const Component = window.paypal.Buttons.driver('react', {
  React,
  ReactDOM
});
<Component
     onShippingChange={async (data, actions) => {
          console.log(data.shipping_address.address_line_1); // undefined
    }}
    onApprove={async ({ orderID }, actions) => {
       const order = await actions.order.get(data.orderID);
       console.log(order.purchase_units[0].shipping.address_line_1); // "Spitalfields Arts Market"
    }}
/>
```

**Comment by bluepnume** [comment]
This is by design. For compliance reasons, we are unable to share the full address until the buyer has approved the payment. Thanks.
