### ISSUE TITLE
reviseSubscription

### ISSUE THREAD

**Issue by iam-ben** [paypal/paypal-checkout-components#1239]
Hi there,

I have been digging around all paypal docs and can't find any documentation for the reviseSubscription for the smart button. 
Thanks.

**Comment by allenchua** [comment]
Guys please do help. I too tried finding docs to revise a subscription. did not get any.

**Comment by allenchua** [comment]
this finally worked for me
paypal.Buttons({

  createSubscription: function(data, actions) {
    return actions.subscription.revise('I-qqqqqqqqqqq',{
      plan_id: 'P-qqqqqqqqqqqqqqqqqq',
      start_time: 'qqqqqqqqqqqqqq'
    });
  },

  onApprove: function(data, actions) {
    console.log(data.subscriptionID)
  }

}).render('#paypal-buttons');

ref https://github.com/paypal/paypal-smart-payment-buttons/blob/d8aff69fb2dec0595da13149a12e74c658eb0f91/src/button/props/createSubscription.js#L30

**Comment by ravishekhar** [comment]
A subscription can be revised using following code. 
For details on Subscription Revise capability and payload supported in second argument of `actions.subscription.revise` please refer https://developer.paypal.com/docs/api/subscriptions/v1/#subscriptions_revise 
```javascript
paypal.Buttons({

  createSubscription: function(data, actions) {
    // SubscriptionId - The current subscription Id of the buyer. I-XXXXXXXXX
    // plan_id : The new Plan id which the buyer wish to opt in. 
    // Buyer must login and approve the revision.
    return actions.subscription.revise(SubscriptionId, {
      plan_id: 'P-XXXXXXXXXXXX'
    });
  },

  onApprove: function(data, actions) {
    console.log(data.subscriptionID)
  }

}).render('#paypal-buttons');
```
