### ISSUE TITLE
Error: Client side payment execute is only available for REST based transactions at Object.

### ISSUE THREAD

**Issue by kgrimes** [paypal/paypal-checkout-components#1244]
### Description

When a customer tries to checkout using a credit card, as a guest (with no paypal account), where on the dev (sandbox) site works fine. But on Production site throws an "Error: Client side payment execute is only available for REST based transactions". Code:
`<script  src="https://www.paypal.com/sdk/js?client-id=<%= PaypalAPIkey %>&commit=true&locale=<%= BZiShows.com.helper.getLanguage() %>_CA&currency=CAD&disable-card=visa,mastercard,amex,jcb,elo,hiper"></script>

                        <div id="paypal-button-container"></div>

                        <script>
                            paypal.Buttons({
                                createOrder: function (data, actions) {
                                    // Set up the transaction
                                    return actions.order.create({
                                        purchase_units: [{
                                            amount: {
                                                value: '<%= total.ToString("###0.##").Replace(",",".") %>',
                                            },
                                            invoice_id: "<%= invoice %>",
                                            description: "BziShows.com"
                                        }]
                                    });
                                },
                                onApprove: function (data, actions) {
                                    openOverlay(); //opens an overlay with "please wait processing"
                                    return actions.order.capture().then(function () {
                                        //process order
                                        CreateOrder();
                                    });
                                },
                                onRendered : function () {
                                    ShowHideButtons();
                                },
                                onError: function (err) {
                                    SendError(err);
                                }
                            }).render('#paypal-button-container');

                    </script>`

- The `paypal.version` from your browser console - Paypal.version "5.0.82
- The exact browser version - Google Chrome Version 78.0.3904.70 (Official Build) (64-bit)
- A link to your page with the issue, if possible - Link to page is not possible, an account and authentication is required.
- All console logs during the time of the issue, especially error messages - Attached
-The issue does not occur on http://developer.paypal.com/demo/checkout
- Also does not occur on sandbox environment

### Steps to reproduce

1. Click the yellow Paypal button
2. Click "Pay with a credit or Visa Debit card" button
3. Fill in the credit card information (Canada), address, phone and email fields
4. Answer "No, thanks" for "Create a PayPal Account?"
5. Check the box to confirm agreement
6. Click the blue "Continue" button

### Affected browsers

- [X] Chrome
- [ ] Safari
- [X] Firefox
- [X] Edge
- [ ] IE
- [X] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

![06435089_1](https://user-images.githubusercontent.com/3534401/67810516-bdd66d00-fa68-11e9-9c18-5ab1bf67a758.jpg)
![06435089_2](https://user-images.githubusercontent.com/3534401/67810519-bfa03080-fa68-11e9-8c1a-584cb9db36af.jpg)
![06435089_3](https://user-images.githubusercontent.com/3534401/67810595-e1011c80-fa68-11e9-8dfb-1d0364057eee.jpg)
![06435089_4](https://user-images.githubusercontent.com/3534401/67810605-e494a380-fa68-11e9-9ebd-da49b90b1505.png)
![06435089_5](https://user-images.githubusercontent.com/3534401/67810617-e78f9400-fa68-11e9-8c5f-9903b95d0db8.jpg)
![06435089_6](https://user-images.githubusercontent.com/3534401/67811248-591c1200-fa6a-11e9-83e2-431ef4180c0e.png)
![06435089_7](https://user-images.githubusercontent.com/3534401/67811253-5c170280-fa6a-11e9-8552-6aed6278aaad.png)
[consol log.txt](https://github.com/paypal/paypal-checkout-components/files/3785928/consol.log.txt)
[Err object.txt](https://github.com/paypal/paypal-checkout-components/files/3785929/Err.object.txt)

**Comment by Dhimanswadia** [comment]
Hey @kgrimes Thanks for reporting this issue and for using PayPal 😄 . I work on the checkout team at PayPal and we were able to reproduce the bug and we pushed a fix for it yesterday. Could you verify on your end if you are still facing the issue?. This bug was on the new experience that you posted screenshots of(url: `checkoutweb/signup`) so you might not get the flow each time based on the A/B test. Do let me know if you are still facing the issue or have any questions. 

Thanks 
Dhiman

**Comment by kgrimes** [comment]
Hello Dhiman, thank you for the response! After I submitted the issue the developer sent me a message stating that the title and description of the issue was incorrect, so I will be editing it as soon as I get the description from them.

My apologies for the confusion.

Best Regards,

Kevin Grimes |  Engineer, Merchant Technical Support (MTS),  Global Professional Services – NA

**Comment by Dhimanswadia** [comment]
@kgrimes Sure, Do let me know but we did push couple bug fixes for the flow in the screenshots so hopefully its taken care off.
