### ISSUE TITLE
Standard Card Fields - List of country availability 

### ISSUE THREAD

**Issue by eqcb** [paypal/paypal-checkout-components#1245]
I tried to find this but wasn't able. I'm in Brazil and I'm using the sandbox environment. The new standard card fields are not showing to me.
Is is a country restriction or sandbox restriction?

**Comment by leomp12** [comment]
@eqcb doesn't work for Brazil, it's a country restriction.
I also tried, it didn't work at all, I talked to the people of PayPal Brazil and they confirmed me...
