### ISSUE TITLE
ERR_NAME_NOT_RESOLVED in sandbox

### ISSUE THREAD

**Issue by penguinstampede** [paypal/paypal-checkout-components#1246]
I don't know if this is related to #1232 but it's a similar error.  When trying to load buttons on my checkout page in sandbox mode, Chrome's console keeps showing an ERR_NAME_NOT_RESOLVED.  Switching to a production client ID fixes this.  It looks like `tracking.qa.paypal.com` is not resolving?  I'm also not sure why this tracking is running as it looks like it's for muse... but I could be misreading things.

Loading `<script src="https://www.paypal.com/sdk/js?client-id={{ paypal_client_id }}&intent=authorize&disable-funding=credit,card">` works fine, but eventually tries to load

`https://tracking.qa.paypal.com/webapps/tracking/ts?pgrp=muse%3Ageneric%3Aanalytics%3A%3Amerchant&page=muse%3Ageneric%3Aanalytics%3A%3Amerchant%3A%3A%3A&tsrce=tagmanagernodeweb&comp=tagmanagernodeweb&sub_component=analytics&s=ci&fltp=analytics-generic&pt=Checkout&dh=2560&dw=1440&bh=570&bw=1440&cd=24&sh=2560&sw=1440&v=NA&pl=pdf&rosetta_language=en-US%2Cen%2Cen-GB&e=im&t=1572990936618&g=480&completeurl=http%3A%2F%2Flocalhost%3A8000%2Fcheckout%2Fplaceorder%2F&sinfo=%7B%22partners%22%3A%7B%22ecwid%22%3A%7B%7D%2C%22bigCommerce%22%3A%7B%7D%2C%22shopify%22%3A%7B%7D%2C%22wix%22%3A%7B%7D%2C%22bigCartel%22%3A%7B%7D%7D%7D`

And Chrome complains loudly.

Production uses `https://t.paypal.com/` instead and that loads fine.  This was also working about a month ago, I think.  This fails in Firefox too, but does not throw a console error.  I noticed this because I have a check in my Selenium tests to alert me about severe console errors (to catch something I did).  I can still click the checkout button and I think things work as expected, it's just a frustrating error to see every time.

**Comment by davidecampello** [comment]
I have the same error...

**Comment by ekiametis** [comment]
I have the same error

**Comment by omkar184** [comment]
I'm getting the same error

**Comment by dmalis** [comment]
here too

**Comment by tsikah** [comment]
Same here :(

**Comment by JapinderSandhu** [comment]
same :(

**Comment by treyhunner** [comment]
I am experiencing the same error. Waiting for the eventual timeout slows my QA page load times drastically.

**Comment by castan1c** [comment]
same...

**Comment by envatic** [comment]
Same here, customer thinks its an issue with code and now we going in circles, any fix anyone?
![Screen Shot 2019-12-01 at 17 38 47](https://user-images.githubusercontent.com/48434697/69915558-7b39f300-1461-11ea-903b-933b1a2e3709.png)

**Comment by theoinglis** [comment]
It would be good to get an update on this as it seems to have been a problem for a while now. 

It was working fine for me yesterday and now it seems to always fail in all browsers with the sandbox account with the other error referenced: https://github.com/paypal/paypal-checkout-components/issues/1232

**Comment by macgrafic** [comment]
I have the same error

**Comment by ElesGergo** [comment]
Same here, any updates?

**Comment by AlessandroGambaro** [comment]
If you are using euro, you need to:
1. https://www.paypal.com/sdk/js?currency=EUR&client-id=
2. purchase_units: [{
                                    'intent': 'CAPTURE',
                                    amount: {
                                        currency_code: 'EUR',
                                        value: in string value with two decimal
                                    }
                                }]

**Comment by JapinderSandhu** [comment]
> If you are using euro, you need to:
> 
> 1. https://www.paypal.com/sdk/js?currency=EUR&client-id=
> 2. purchase_units: [{
>    'intent': 'CAPTURE',
>    amount: {
>    currency_code: 'EUR',
>    value: in string value with two decimal
>    }
>    }]

This worked for me, in my case I did CAD for canadian currency

**Comment by penguinstampede** [comment]
Adding currency=USD to the script tag does clear the error for me.  Closing.

**Comment by Khailand69** [comment]
H


Gooh

**Comment by pokono** [comment]
Not sure why I would need the currency when I load the script. As I bill in multiple currencies how do I set it dynamically if I don't know it when I load the script?

**Comment by JapinderSandhu** [comment]
> Not sure why I would need the currency when I load the script. As I bill in multiple currencies how do I set it dynamically if I don't know it when I load the script?

this is a great question that I was also wondering the answer too. How to dynamically set currencies?

**Comment by emmanueldietrich** [comment]
Hi,
I had the same error because I missed a coma in js. Chrome console didn't warn me. Firefox did ;-)
Fixed the coma and things went back ok.
