### ISSUE TITLE
can not specify subscriber when creating subscription

### ISSUE THREAD

**Issue by buggoing** [paypal/paypal-checkout-components#1247]
### Description

I specified subscriber in the code, but the subscriber in the webhook is the buyer's paypal account information, not the one I specified in the code
- My code
```
        paypal.Buttons({
            createSubscription: function (data, actions) {
                return actions.subscription.create(
                    'plan_id': 'P-xxxx',
                    'subscriber': {
                        'name': {
                            'given_name': 'customer',
                            'surname': 'customer'
                        },
                        'email_address': 'customer@example.com'
                    }
                });
            },
            onApprove: function (data, actions) {
                console.log('subscription id: ', data.subscriptionID)
            }
        }).render('#paypal-button-container');
```
- The `paypal.version` from your browser console
"5.0.85"

this is the result of webhook, the subscriber is not the one i specified in the code
![511573097062_ pic](https://user-images.githubusercontent.com/16204738/68357754-4b911700-0151-11ea-8ec3-44e6e41a26cc.jpg)

**Comment by ravishekhar** [comment]
@buggoing Can you please provide the Subscription ID.

**Comment by buggoing** [comment]
> @buggoing Can you please provide the Subscription ID.

I am testing in sandbox environment, this is a newly created Subscription ID: `I-36KMKUR1SMLJ`
Thanks!

**Comment by ravishekhar** [comment]
With the provided Wehbook Id we see following subscription `I-K2L2MMSCH21K`. 
The buyer who approved the subscription is the same as subscriber id mentioned on webhook. This is expected behaviour.

**Comment by buggoing** [comment]
As you can saw, in the code, the subscriber's email is `customer@example.com `, but in the webhook the subscriber's email is `sb-zswls522827@personal.example.com`, they do not match
this is the request data from browser's console
![551573131111_ pic](https://user-images.githubusercontent.com/16204738/68390549-7ce50380-01a0-11ea-8e65-4d73bc71a764.jpg)

this is the response from browser's console
![531573130787_ pic](https://user-images.githubusercontent.com/16204738/68390367-1a8c0300-01a0-11ea-80f4-5443bdfd599f.jpg)
this is the result from webhook
![541573131036_ pic_hd](https://user-images.githubusercontent.com/16204738/68390447-460eed80-01a0-11ea-937d-2581097c7312.jpg)

**Comment by buggoing** [comment]
After many tests, i found an phenomenon, if i logged in paypal, then do the subscription, the subscriber's info in the webhook is the paypal account's email, not the the one i specified in the code. But, if i open an incognito window, which means no cookies about paypal accunt's info,  the subscriber's info in the webhook is the one i specified in the code. So, it seems like the subscriber i specified in the code only works when i did not logged in.

**Comment by ravishekhar** [comment]
We are looking into this. We will get back to you.

**Comment by nick-inter** [comment]
Any updates on this? Have exactly the same issue. I tried to create the subscription both with Subscription API and the Smart Buttons method ('createSubscription' function). None of them sends customer details -- even in production environment.

**Comment by bluepnume** [comment]
Hi @ravishekhar -- has this one been resolved, and can it be closed out? Thanks.

**Comment by mstuart** [comment]
Hi @buggoing, the fix was released last week. Will close this issue for now. Feel free to re-open it if it's still occurring. Thank  you!
