### ISSUE TITLE
Sandbox Subscription Order Status

### ISSUE THREAD

**Issue by eqcb** [paypal/paypal-checkout-components#1251]
I'm posting here as I cant find the answers for my issues anywhere in the docs, the references, dev support community or the internet.
 
I'm using the Paypal Buttons to set up a Subscription on the sandbox environment. The Plan is all previously set up and I go through the client flow of loging in and approving the subscription. Upon finishing, the buttons code calls the **onApprove** function that comes with two parameters, **data** and **actions**. 

Data brings the **Order ID** and **Subscription ID** while actions have methods for eg., capturing the order.

By debugging and getting those ID's I'm able to, on Postman, get the subscription, that comes with status **ACTIVE**. That I believe everything must have worked just right, hence the ACTIVE status.

But, if I use postman to get the ORDER, it comes back with status APPROVED and not COMPLETED. If I try to post to the order capture end-point, using the link that comes from getting the subscription (https://api.sandbox.paypal.com/v2/checkout/orders/{ ORDER ID } /capture) it responds with a code 500(internal server error), even if Im following the correct REST setup for this endpois as in here(https://developer.paypal.com/docs/api/orders/v2/#orders_capture)

 
_I've noticed that on the developer docs, the subscription code example just don't use the **actions.order.capture()** method in opposite as it's used on the checkout examples._

1 - When subscribing, there is no need to capture the order?

2 - Why the subscription's order come with status APPROVED and not COMPLETED as the subscription is already with status ACTIVE?

3 - Why trying to capture the subscription`s order results in a server error?

_I also tried to list all subscription's transactions, and it comes empty_. (Only one random subscription(I-BRSS1CNJR324) I created during my tests has a transaction! The others don't. And even so, this sole transaction has status pending, but the subscription is active. What is happening?)

4 - _Why the transactions are blank for the subscriptions if they have ACTIVE status?_

The orders ID`s that come when I subscribe for my plan don't seem to stay alive for long. I get "INVALID_RESOURCE_ID" when using the get order end-point the next day.

5 - Why I cant I see the order for subscriptions after some time?
 

I **REALLY** need a workflow/lifecycle chart of subscriptions/orders status and events to better understand whats going on, but I cant seem to find it anywhere.

Anyone has this?

Thanks

**Comment by ravishekhar** [comment]
Hey, Was on holiday so could not follow up. 

> 1 - When subscribing, there is no need to capture the order?

You do not need to capture the order.

> 2 - Why the subscription's order come with status APPROVED and not COMPLETED as the subscription is already with status ACTIVE?

Order Status is irrelevant for subscription. 

> 3 - Why trying to capture the subscription`s order results in a server error?

It should be a 4xx from our end, will get it fixed.

> 4 - Why the transactions are blank for the subscriptions if they have ACTIVE status?

You should see all transactions within the subscription using subscriptions api https://developer.paypal.com/docs/subscriptions/full-integration/subscription-management/#list-transactions-for-a-subscription

> 5 - Why I cant I see the order for subscriptions after some time?

Order Id is irrelevant for subscriptions. 
Will get dev docs updated.

More details on subscription management is here https://developer.paypal.com/docs/subscriptions/full-integration/subscription-management/
Let me know if any further info is needed or you encounter any issues.

**Comment by eqcb** [comment]
Hi thank you for the reply.
One thing still not OK, that is the transactions response. As I said, so far from all subscriptions I created on the sandbox during tests, only one has transactions present when hitting the subscription transactions endpoint. All others come with an empty JSON object "{ }"

**Comment by ravishekhar** [comment]
Please provide the `Paypal-Debug-Id` returned in API response headers. Will check the issue.

**Comment by eqcb** [comment]
This one for example:
Subs. ID: I-GPG8BBG1EVVN
Debug ID: bf14c07784180

**Comment by ravishekhar** [comment]
I have been trying to reproduce the issue which you faced with no luck. 
API Reference: 
https://developer.paypal.com/docs/api/subscriptions/v1/#subscriptions_transactions

Please log an issue if you are still facing missing transactions when using above API.

**Comment by synthet** [comment]
I have solved similar issue by removing all redundant fields from Smart Buttons config object copied from "Order" integration.
I left only those that are present in documentation for "Subscription".
Looks like some of them are related only to "Order" workflow causing useless "capture" request.
