### ISSUE TITLE
PayPal buttons border disappearing for different screen scaling levels

### ISSUE THREAD

**Issue by VivekVikranth** [paypal/paypal-checkout-components#1254]
### Description

Paypal smart button's border styles are disappearing when the user screen layout scale is not in 100% (Please see the attached screen shot for behavior and scaling size). also the recommended screen scaling size (example: 100%, 150%..,) varies with monitor screen sizes (example: 1280 x 800. 1366 x 768..,) 

- Screenshots or videos that show the issue
   
![smart-buttons](https://user-images.githubusercontent.com/3896638/68932021-0e9cd400-0792-11ea-9274-939016a4d5ab.PNG)

- Your code
```
 env: environment,
            commit: false,
            style: {
                color  : 'white',
                shape  : 'pill',
                size   : 'responsive',
                tagline: 'false',
                height : 38
            },
```

- The `paypal.version` from your browser console 
    **"4.0.300"**
- The exact browser version - **Chrome - 78.0.3904.97**

- A link to your page with the issue, if possible
    https://www.bose.com/en_us/index.html
(add some product to the cart and navigate to cart page)

- All console logs during the time of the issue, especially error messages
  - No error
- Does the issue also occur at [developer.paypal.com/demo/checkout]
(https://developer.paypal.com/demo/checkout)? - **yes**
    
- Does the issue occur consistently, or intermittently? - Consistently on different screen scale level except 100%.

### Steps to reproduce

- Go to your display setting and change scale and layout size to anything other than 100% (like 125%, or 150%) because for my screen it is 125%, some other screen 150%..,

Please provide each individual step required to reproduce the issue

### Affected browsers

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Can you confirm if you're still seeing the issue, and can you please try with the latest version of the sdk? Thanks
