### ISSUE TITLE
Android - PayPal module is quite small by height after authorization 

### ISSUE THREAD

**Issue by VovaTer** [paypal/paypal-checkout-components#1255]
![f5d98272-b8cd-47d9-b94f-edc3243eda2d](https://user-images.githubusercontent.com/53568482/69062910-a1f13600-0a2c-11ea-94b4-487b4384b2ec.jpeg)

Steps:
1. Click PayPa Express Checkout butto
2. Fill PayPal authorization form by correct info and proceed to a list of linked cards.
3. Observe PayPal module.

Actual: PayPal module is quite small by height. It became smaller because of keyboard and didn't come back after filling information.
Expected: PayPal module occupies the most part of the screen.

Environment: Android: 1.0.6 / Sandbox

**Comment by bluepnume** [comment]
Hi -- trying to narrow down the right person to look into this. Can you confirm if you're still seeing the issue? Thanks!
