### ISSUE TITLE
iOS/Android - PayPal Express Checkout requests authorization twice

### ISSUE THREAD

**Issue by VovaTer** [paypal/paypal-checkout-components#1256]
![the_second_authorization_request](https://user-images.githubusercontent.com/53568482/69063391-79b60700-0a2d-11ea-89c6-303b5d0d450f.png)

Steps:
1) Click PayPal Express Checkout button.
2) Fill PayPal authorization form by correct info and confirm it.

Actual: One more empty PayPal authorization form appears and required to be filled once again before go forward through the process.Expected: A list of linked cards is displayed. 

Expected: A list of linked cards is displayed. 

Environment: 
iOS: 1.8.1 (314 build - RC), 1.8.2 (317)
Android: 1.0.6 (17)
Sandbox

**Comment by bluepnume** [comment]
Hi -- trying to narrow down the right person to look into this. Can you confirm if you're still seeing the issue? Thanks!
