### ISSUE TITLE
Can't login in paypal modal on IOS/Android webview (seems like missing cookies and CSRF issue)

### ISSUE THREAD

**Issue by deviousknight** [paypal/paypal-checkout-components#1258]
### Environment
braintree web sdk + paypal checkout js + react native + webview (the same for 5 and 7 versions)

### Description
Hello guys, we are having troubles with PayPal in webview
Currently almost no-one from our customers could login into account, paypal instead just keeps refreshing.
This is video from our app:

![iphone](https://user-images.githubusercontent.com/19371283/69161905-e815ca80-0afc-11ea-9ac9-f0ed7d3ac505.gif)
android meanwhile keeps login for somehow

Digging through requests I noticed that problem is in the cookies has not been set that causing in auth_csrftoken_error under the hood. 
This is request and response logged from ios. Seems like secure cookies has not been set

```
POST /signin/client-log HTTP/1.1
Host: www.sandbox.paypal.com
Content-Type: application/x-www-form-urlencoded
Origin: https://www.sandbox.paypal.com
Accept-Language: en-us
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Accept: application/json
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
Referer: https://www.sandbox.paypal.com/checkoutnow?locale.x=en_US&fundingSource=paypal&sessionID=8f13d1e7db_mtm6mzy6mjq&buttonSessionID=876f044fad_mtm6mzc6mtc&env=sandbox&fundingOffered=paypal&logLevel=warn&sdkMeta=eyJ1cmwiOiJodHRwczovL3d3dy5wYXlwYWxvYmplY3RzLmNvbS9hcGkvY2hlY2tvdXQuanMifQ%3D%3D&uid=e559d316ba&version=4&token=EC-8V092848NA4790200&xcomponent=1
Content-Length: 1229
X-Requested-With: XMLHttpRequest

_csrf=aE0yQi9e7assJo25QhUWW0ru%2F8KWD4Nip4TFA%3D&currentUrl=https%3A%2F%2Fwww.sandbox.paypal.com%2Fcheckoutnow%3Flocale.x%3Den_US%26fundingSource%3Dpaypal%26sessionID%3D8f13d1e7db_mtm6mzy6mjq%26buttonSessionID%3D876f044fad_mtm6mzc6mtc%26env%3Dsandbox%26fundingOffered%3Dpaypal%26logLevel%3Dwarn%26sdkMeta%3DeyJ1cmwiOiJodHRwczovL3d3dy5wYXlwYWxvYmplY3RzLmNvbS9hcGkvY2hlY2tvdXQuanMifQ%253D%253D%26uid%3De559d316ba%26version%3D4%26token%3DEC-8V092848NA4790200%26xcomponent%3D1&logRecords=%5B%7B%22evt%22%3A%22state_name%22%2C%22data%22%3A%22begin_hybrid_login%22%2C%22instrument%22%3Atrue%2C%22timestamp%22%3A1574084454845%7D%2C%7B%22evt%22%3A%22transition_name%22%2C%22data%22%3A%22process_next%22%2C%22instrument%22%3Atrue%2C%22timestamp%22%3A1574084454845%7D%2C%7B%22evt%22%3A%22context_correlation_id%22%2C%22data%22%3A%22717132d603ad2%22%2C%22instrument%22%3Atrue%7D%2C%7B%22evt%22%3A%22serverside_data_source%22%2C%22data%22%3A%22checkout%22%2C%22instrument%22%3Atrue%7D%2C%7B%22evt%22%3A%22intent%22%2C%22data%22%3A%22checkout%22%2C%22instrument%22%3Atrue%7D%2C%7B%22evt%22%3A%22context_id%22%2C%22data%22%3A%22EC-8V092848NA4790200%22%2C%22instrument%22%3Atrue%7D%5D&intent=checkout&_sessionID=Qwhng5P59so3lzj43U2bVsaY4SXn_Qx4

HTTP/1.1 403 Forbidden
Cache-Control: max-age=0, no-cache, no-store, must-revalidate
Content-Length: 223
Content-Security-Policy: default-src 'self' https://*.paypal.com https://*.paypalobjects.com 'unsafe-inline'; script-src 'nonce-p5YstEmMCLBgxD+Yvg3tGKn6r3gVvGKKv47IB4HZTLV/ykCI' 'self' https://*.paypal.com https://*.paypalobjects.com 'unsafe-inline' 'unsafe-eval'; img-src 'self' https://*.googleusercontent.com/ https://*.paypalobjects.com https://ak1s.abmr.net https://ak1s.mathtag.com https://akamai.mathtag.com https://ak1.abmr.net https://*.paypal.com; object-src 'none'; media-src 'self' https://*.paypal.com https://*.paypalobjects.com; font-src 'self' https://*.paypal.com https://*.paypalobjects.com; connect-src 'self' https://*.paypal.com https://*.paypalobjects.com https://192.55.233.1 'unsafe-inline'; frame-src 'self' https://*.paypal.com https://smartlock.google.com https://*.paypalobjects.com; base-uri 'self' https://*.paypal.com; block-all-mixed-content
Content-Type: application/json; charset=utf-8
Date: Mon, 18 Nov 2019 13:40:55 GMT
Etag: W/"df-bFa0YrXtm3gZUYN+jAN+1MIcuZw"
Paypal-Debug-Id: 9c70ae9619eda
Set-Cookie: LANG=en_US%3BUS; Path=/; Domain=paypal.com; Expires=Mon, 18 Nov 2019 22:26:51 GMT; Max-Age=31556; HttpOnly; Secure
Set-Cookie: enforce_policy=; Path=/; Domain=paypal.com; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Secure
Set-Cookie: x-pp-s=eyJ0IjoiMTU3NDA4NDQ1NTQ4MCIsImwiOiIwIiwibSI6IjAifQ; Path=/; Domain=paypal.com; HttpOnly; Secure
Set-Cookie: nsid=s%3AL9WTHS_Kb69EegsB4UC3-4dgdZVC9UxY.XiEkmorW8YQaH6VEPxsREWxP6JgbFSq%2FrmziML2UWI8; Path=/; HttpOnly; Secure
Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.WEB.1%26silo_version%3D880%26app%3Dunifiedloginnodeweb%26TIME%3D1574084455%26HTTP_X_PP_AZ_LOCATOR%3Dsandbox.slc; Path=/; Domain=paypal.com; Expires=Mon, 18 Nov 2019 14:10:55 GMT; HttpOnly; Secure
Set-Cookie: ts=vreXpYrS%3D1668778855%26vteXpYrS%3D1574086255%26vr%3D7ebeac1b16e0a488f31274a7ffd4c40b%26vt%3D7ebeac1b16e0a488f31274a7ffd4c40a; Path=/; Domain=paypal.com; Expires=Thu, 17 Nov 2022 13:40:55 GMT; HttpOnly; Secure
Set-Cookie: ts_c=vr%3D7ebeac1b16e0a488f31274a7ffd4c40b%26vt%3D7ebeac1b16e0a488f31274a7ffd4c40a; Path=/; Domain=paypal.com; Expires=Thu, 17 Nov 2022 13:40:55 GMT; Secure
Set-Cookie: X-PP-L7=1; Path=/; Domain=paypal.com; Secure
Vary: Accept
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Recruiting: If you are reading this, maybe you should be working at PayPal instead! Check out https://www.paypal.com/us/webapps/mpp/paypal-jobs
X-Xss-Protection: 1; mode=block
Strict-Transport-Security: max-age=63072000
Connection: Keep-alive

{"coBrand":"us","currentYear":2019,"viewName":"response500","showFooter":{"type":"imageAndContent"},"rootTxn":{"name":"signin_csrftoken_error","data":{"msg":"CSRF error: CSRF token mismatch"},"status":"0"},"csrfError":true}
```
Android has cookies in request and success in response as result

### Steps to reproduce

You could see the same behavior [https://developer.paypal.com/demo/checkout/#/pattern/checkout](https://developer.paypal.com/demo/checkout/#/pattern/checkout) but with android webview from skype like on this video:
![android](https://user-images.githubusercontent.com/19371283/69162990-89e9e700-0afe-11ea-80f9-c8887d448aef.gif)
On this page is paypal sdk version and not checkout js as we have but login behavior looks the same but for android now vice versa. 

Strange things, maybe something was changed in relation to how cookies is being set for webview?

### Affected browsers
- [x] Web View / Safari ViewController

**Comment by aharding378** [comment]
@deviousknight were you able to resolve this? I am getting the same issue and I have not been able to solve the problem.

**Comment by deviousknight** [comment]
> @deviousknight were you able to resolve this? I am getting the same issue and I have not been able to solve the problem.

unfortunately no, we switched to mobile browser implementation

**Comment by aharding378** [comment]
Do you have a link to how that is implemented? 
I am in a really bad situation becase people are unable to finish their checkout and I a getting a lot of inquiries. Thanks.

**Comment by deviousknight** [comment]
> Do you have a link to how that is implemented?
> I am in a really bad situation becase people are unable to finish their checkout and I a getting a lot of inquiries. Thanks.

its just regular web paypal but inited in browser that was launched via app. After payment completion you could return user to app via deeplink

**Comment by deviousknight** [comment]
for browser management we are using InAppBrowser

**Comment by aharding378** [comment]
Ahh got it, thanks

**Comment by gnorbsl** [comment]
Same issue here...

**Comment by riv333** [comment]
We have the same issue in Android. I think the problem is that CORS is not working because in the Webview in the InAppBrowser the login opens in the same window so that the allowed origin of the requested ressource not fits. I could solve the problem by adding the URL in the Header for `"Access-Control-Allow-Origin"` of the root website in the Response from PayPal by overriding the `shouldInterceptRequest` Method. I had to allow also third-party cookies with: `CookieManager.getInstance().setAcceptThirdPartyCookies(webview, true);`. But I am not happy with this solution

**Comment by jeisele2** [comment]
Having the same issue in ios -- this is the response from the client-log request to paypal:

```
{
    "coBrand": "us",
    "currentYear": 2020,
    "viewName": "response500",
    "showFooter": {
        "type": "imageAndContent"
    },
    "rootTxn": {
        "name": "signin_csrftoken_error",
        "data": {
            "msg": "CSRF error: CSRF token mismatch"
        },
        "status": "0"
    },
    "csrfError": true,
    "genericErrorCode": "cookieDisabled"
}
```
cookies are definitely enabled (enabled by default in webview, but I made sure with sharedCookiesEnabled={true} thirdPartyCookiesEnabled={true} in my React-Native WebView props

**Comment by bluepnume** [comment]
Hi -- trying to narrow down the right person to look into this. Can you confirm if you're still seeing the issue? Thanks!

**Comment by bluepnume** [comment]
Closing this, please re-open a new issue if you're still seeing this. Thanks.

**Comment by hicreate** [comment]
I too am seeing this issue. Can it be reopened?

**Comment by gautamkumar1008** [comment]
We are getting the same issue in the MS Edge browser.  The Edge version we are using currently is "92.0.902.55".
The response from the client-log request to Paypal:

```
{coBrand: "au", currentYear: 2021, viewName: "response500", showFooter: {type: "imageAndContent"},…}
coBrand: "au"
csrfError: true
currentYear: 2021
rootTxn: {name: "signin_csrftoken_error", data: {msg: "CSRF error: CSRF token mismatch"}, status: "0"}
data: {msg: "CSRF error: CSRF token mismatch"}
name: "signin_csrftoken_error"
status: "0"
showFooter: {type: "imageAndContent"}
type: "imageAndContent"
viewName: "response500"
```
Please let me know if needs more information.
Looking for your reply.
