### ISSUE TITLE
(feature request) - Allow multiple window.paypal objects.

### ISSUE THREAD

**Issue by trainerbill** [paypal/paypal-checkout-components#1260]
Since we are building the sdk based on query parameters it will be important that a person can load multiple scripts.  So if I want to disable cards on one set of buttons but not the other.  I tried saving window.paypal to a map with the params as the key and use each one when i need it.  the result is that when you call render on the second one the first one is destroyed.  I think this will be important if we add more and more querystring variables.

![image](https://user-images.githubusercontent.com/3578259/69363435-21158280-0c56-11ea-92b7-4ec3925e48f7.png)

here is what i am tryiing to accomplish: 

```
import * as loader from 'load-js';

export const scripts = new Map();

export function loadPayPalScript(params: string) {
    return loader(`https://www.paypal.com/sdk/js?${params}`)
        .then(() => {
            scripts.set(params, { ...(window as any).paypal });
        });
}
```

**Comment by bluepnume** [comment]
Hi -- this introduces a lot of potential failure points and isn't something we're likely to support, unless there's a really good use case.

If you need to disable cards in one case, I recommend using standalone buttons: https://developer.paypal.com/docs/checkout/integration-features/standalone-buttons/

That will give you a lot more control over what (and how) buttons are rendered on the page.
