### ISSUE TITLE
Use PayPal Checkout with Full-Page Redirect and without Smart Buttons

### ISSUE THREAD

**Issue by KenLange314** [paypal/paypal-checkout-components#1262]
I'm migrating an existing server and mobile app that currently uses Mobile Express Checkout to use PayPal Checkout.  (Because MEC is now deprecated)..

I want to integrate PayPal Checkout on the server side without modifying the Mobile App.

Can I get PayPal Checkout to work with a Full-Page redirect without using the Smart Buttons and Javascript SDK?

On the existing system, the flow is as follows:
1. Server calls SetExpressCheckout and gets Token
2. Server passes PayPal URL with Token to Mobile App
3. Mobile App opens PayPal URL in WebView
4. User does payment on PayPal hosted page
5. PayPal redirects WebView to Server. 
6. Server redirects WebView to special URL.
7. Mobile App intercepts special URL and resumes control.

That system was designed so the Mobile App is Payment Provider agnostic.  It just displays the URL provided by the server in a Web View and resumes control when the WebView is redirected to the special URL.  It currently works with PayPal MEC and a couple of other providers.

Looking at the documentation for PayPal checkout, I can't figure out how to create a payment and redirect the Web View to a PayPal URL for that Payment without using the Smart Buttons.

I realize that I could provide my own intermediate landing page that would host the Smart Buttons but that would add an awkward extra step for the user.

There's documentation for "Full-Page" redirect here:
https://developer.paypal.com/docs/archive/checkout/how-to/customize-flow/#do-a-full-page-redirect

However that seems to be referring to the return redirect after payment.   I want to do a full page redirect to PayPal before the payment and skip the Smart Buttons.

Is that possible?  Thanks.

**Comment by bluepnume** [comment]
Hi, yes, you can redirect to `https://www.paypal.com/checkoutnow?token=XYZ` in this case.

We'll soon have a native sdk for your mobile app that will handle this for you. But in the mean time that should work.
