### ISSUE TITLE
Translation errors and duplicate field names in Standard Card Fields

### ISSUE THREAD

**Issue by fstilman** [paypal/paypal-checkout-components#1263]
When selecting Argentina as Country in Standard Card Fields, some errors occur (screenshot attached)

![Screenshot from 2019-11-22 19-47-19](https://user-images.githubusercontent.com/32549461/69466000-991c9f00-0d61-11ea-8fe1-0349b4ee188d.png)
:

a) the field "Expires" is incorrectly translated to "Fecha de fecha de vencimiento". This should be "Fecha de vencimiento" or, better "Expiración"

b) the field "First name" is incorrectly translated to "Apellido:" when it should read "Nombre".

c) Lastly, the font size for the fields in spanish are too small, reducing conversion rate.

Thanks in advance for correcting this.

**Comment by bluepnume** [comment]
@khanghoang is this a known issue? Thanks

**Comment by fstilman** [comment]
Yes, it is, and was the reason for us moving to Stripe.

You can see this bug in action even on PayPal's Smart Payment Buttons demo
page on https://developer.paypal.com/docs/checkout/#

The error seems to happen in the following situation:

- Spanish UI (I think this depends on browser locale)
- Choosing a spanish-speaking country like Argentina or Uruguay. For Spain
this is not happening. Argentina/Uruguay and other latin-american countries
should look the same as Spain in terms of translation.

At least 2 errors are shown:

1) "Fecha de fecha de vencimiento" should just read "Vencimiento" as for
Spain (currently duplicates "fecha de fecha").

2) Instead of "Name" and "Last name" it says "Apellido" two times (Apellido
= Last Name in spanish). This fields should read "Nombre:" and "Apellidos:"
as for Spain.

Best regards,

Federico


Screenshot attached.

**Comment by fstilman** [comment]
Yes, it is, and was the reason for us moving to Stripe.

You can see this bug in action even on PayPal's Smart Payment Buttons demo
page on https://developer.paypal.com/docs/checkout/#

The error seems to happen in the following situation:

- Spanish UI (I think this depends on browser locale)
- Choosing a spanish-speaking country like Argentina or Uruguay. For Spain
this is not happening. Argentina/Uruguay and other latin-american countries
should look the same as Spain in terms of translation.

At least 2 errors are shown:

1) "Fecha de fecha de vencimiento" should just read "Vencimiento" as for
Spain (currently duplicates "fecha de fecha").

2) Instead of "Name" and "Last name" it says "Apellido" two times (Apellido
= Last Name in spanish). This fields should read "Nombre:" and "Apellidos:"
as for Spain.

Screenshot attached.

Best regards,

Federico

**Comment by khanghoang** [comment]
closing this issue since we just got the fix.
cc @fstilman
