### ISSUE TITLE
feature request. Add the ability to trigger(click) the PayPal button using JS.

### ISSUE THREAD

**Issue by apapazisis** [paypal/paypal-checkout-components#1264]
Would be usability improvement to add the ability to trigger(click) the paypal button through Javascript and please remove iframe because it has disadvantages.

**Comment by xtrasimplicity** [comment]
This has been requested before and has been rejected due to a policy at PayPal. :/
https://github.com/paypal/paypal-checkout-components/issues/522

Note: I'm _not_ affiliated with PayPal in any way.

**Comment by bluepnume** [comment]
Hi, sorry this is not supported, or planned.
