### ISSUE TITLE
Hi thank you for the reply.

### ISSUE THREAD

**Issue by Dianne1404** [paypal/paypal-checkout-components#1271]
Hi thank you for the reply.
One thing still not OK, that is the transactions response. As I said, so far from all subscriptions I created on the sandbox during tests, only one has transactions present when hitting the subscription transactions endpoint. All others come with an empty JSON object "{ }"

_Originally posted by @eqcb in https://github.com/paypal/paypal-checkout-components/issues/1251#issuecomment-558161923_

**Comment by ravishekhar** [comment]
I have been trying to reproduce the issue which you faced with no luck.
API Reference:
https://developer.paypal.com/docs/api/subscriptions/v1/#subscriptions_transactions

Please log an issue if you are still facing missing transactions when using above API.
