### ISSUE TITLE
404 on https://www.paypalobjects.com/api/checkout.4.0.308.js

### ISSUE THREAD

**Issue by poops** [paypal/paypal-checkout-components#1273]
### Description

Requesting https://www.paypalobjects.com/api/checkout.4.0.308.js throws a 404, which results in the Paypal checkout button not working

**Comment by kevinantonacci** [comment]
Also experiencing the issue here.

**Comment by Zirconia-Wolf** [comment]
I've been getting "404" errors on various sites lately whenever I try to use their PayPal button; Github is no exception. I hope this gets fixed soon!

**Comment by bluepnume** [comment]
@poops are you still seeing this issue? I'm unable to reproduce.

@Zirconia-Wolf -- which specific urls are you getting 404s for?

**Comment by poops** [comment]
@bluepnume no, it seems to be fixed now. thanks!
