### ISSUE TITLE
Error: Window closed

### ISSUE THREAD

**Issue by LarozeMultiservices** [paypal/paypal-checkout-components#1274]
I'm clicking the paypal button, but closing the window before it loads. This is the same issue as the following:
https://github.com/paypal/paypal-checkout-components/issues/132#issuecomment-265964573

The window closed error in console is consistent across the following browsers we use in our company. Is there anyway to stop this error?

### Affected browsers
- [ ] Chrome --- error thrown: err: "Error: Window closed"
- [ ] Firefox --- error thrown: err: "Error: Window closed"
- [ ] Edge --- error thrown: SCRIPT5022: Window closed

**Comment by Misiu** [comment]
More details and guide how to recreate the error here: https://github.com/paypal/paypal-checkout-components/issues/1107#issuecomment-561649364

**Comment by bluepnume** [comment]
We can track this over here: https://github.com/paypal/paypal-checkout-components/issues/1290
