### ISSUE TITLE
404 File not Found: https://www.paypalobjects.com/api/checkout.4.0.310.js

### ISSUE THREAD

**Issue by kevinantonacci** [paypal/paypal-checkout-components#1276]
Receiving a 404 error to the following URL: https://www.paypalobjects.com/api/checkout.4.0.310.js. 

This causes a broken promise resulting in the Paypal button not working when using the paypal-checkout npm package (https://www.npmjs.com/package/paypal-checkout)

This issue also occurred with the 4.0.308 release (closed issue #1273). It seems as though the NPM package is updated and released before the dependency is available on the server.

Rolling back to the 4.0.309 version of the package solves the issue.

Thank you!

**Comment by bluepnume** [comment]
Looks like there was an issue rolling out this file. Should be resolved now. Please let me know if you still see the issue.
