### ISSUE TITLE
Invalid Merchant/ClientID

### ISSUE THREAD

**Issue by Madlani** [paypal/paypal-checkout-components#1277]
### Description

Please provide a short description of the issue here, along with:
I'm trying to test out the paypal implementation for my ionic app, but get the error 

`PayPal SDK: Request has failed with error: invalid_client - System error (invalid_client). Please try again later. (401) | PayPal Debug-ID: 75ee3a922b144 [mock, PayPal iOS SDK 2.17.0] | Details: (
        {
        "error_description" = "Client Authentication failed";
    }`

I'm passing in the live production client ID & also my sandbox client id into 

this.payPal.init({
      PayPalEnvironmentProduction: 'AT5MGV0....',
      PayPalEnvironmentSandbox: 'Ab0A.......'
    }...
 but not sure why I'm still getting this error!

**Comment by bluepnume** [comment]
Hi, sorry this repo is only for the web js sdk.
