### ISSUE TITLE
Feature: I am not able to disable address fields on credit and debit card pay. 

### ISSUE THREAD

**Issue by shikha9031** [paypal/paypal-checkout-components#1280]
### Description

Please provide a short description of the issue here, along with:

- Screenshots or videos that show the issue
- Your code
- The `paypal.version` from your browser console
- The exact browser version
- A link to your page with the issue, if possible
- All console logs during the time of the issue, especially error messages
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
- Does the issue occur consistently, or intermittently?

### Steps to reproduce

Please provide each individual step required to reproduce the issue

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by shikha9031** [comment]
Hi All, 
I am not able to remove this billing address. Actually in my website I don't need  address fields. So, can anyone tell me how to remove this address

![image](https://user-images.githubusercontent.com/45247254/74608906-1c545380-510b-11ea-9bf6-fda1b2df6c46.png)

Thanks & Regards
Shikha

**Comment by bluepnume** [comment]
Hi, please pass NO_SHIPPING. https://developer.paypal.com/docs/api/orders/v2/#definition-order_application_context

Thanks.
