### ISSUE TITLE
Can smart buttons create a subscription and the server activate it?

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [paypal/paypal-checkout-components#1282]
I am using smart buttons for subscriptions on the client. I send the subscription id from the onApprove block to the server and the server calls the paypal api to check if the subscription is active and update the db.

The issue is that once the user approves the subscription on the client, the payment has already been captured before I get the subscription id to send to the backend.

I was wondering if there is a way to use smart button on the client but capture the subscription on the server?

Thank you

**Comment by ahmadabdolsaheb** [comment]
@blakejoy, you seem to be a domain expert. I was wondering if you know a solution to this query? thank you

**Comment by blakejoy** [comment]
Well you can look into webhooks or IPN to capture the specific event needed to get the data you need

**Comment by ahmadabdolsaheb** [comment]
Thanks for the quick reply, @bluelnkd.  
Correct, I can get notifications after creation and capture of a subscription, but I would like to add a logic ( lets say check my db) and capture subscriptions selectively after the user's approval. 
do you think that is possible using smart buttons?

**Comment by ravishekhar** [comment]
@ahmadabdolsaheb You can use below code snippet to avoid inline activate.
Docs https://developer.paypal.com/docs/api/subscriptions/v1/#definition-application_context 

```javascript
paypal.Buttons({
   
    createSubscription: function (data, actions) {
        return actions.subscription.create({
            'plan_id': 'P-XXXXXXXXXXXXXXXXXX',
            'application_context': {
                'user_action': 'CONTINUE' // By default its SUBSCRIBE_NOW
            }
        });
    },

    onApprove: function (data, actions) {
        alert('Approved By Buyer')
        // use below code to activate/make first payments (if any)
        // or call your server using fetch / axios / XHR etc. 
        // Must return a promise. 
        return actions.subscription.activate().then(res => alert('Activated by Merchant'))
    }
}).render('#paypal-buttons');
```

**Comment by ahmadabdolsaheb** [comment]
@ravishekhar oh this is beautiful. Thank you :)

**Comment by ahmadabdolsaheb** [comment]
I should post to
`https://api.sandbox.paypal.com/v1/billing/subscriptions/sub-id/activate \`
from the server to it active, correct?

**Comment by ravishekhar** [comment]
Yes you can use the activate api, details here https://developer.paypal.com/docs/api/subscriptions/v1/#subscriptions_activate 

On the same note, can you please help us understand the use case why you do not want to activate the subscription while buyer is still on paypal.com

**Comment by ahmadabdolsaheb** [comment]
I just needed to make sure the user has not donated and is signed in.

**Comment by lmatab** [comment]
This is the best thread I have found on the internet about how to make smart buttons work with subscription.

**Comment by lawlmart** [comment]
@ravishekhar 

Here's why: unless I'm missing something, if PayPal activates a subscription on Paypal.com, but the users connection goes out before the onApprove callback makes a request to our server to connect the subscription ID with our user ID, you have an orphaned subscription.

**Comment by armaserg** [comment]
It looks like it doesn't work now. At least for sandbox.
Even when I set 
```
'application_context': {
     'user_action': 'CONTINUE'
}
```
it still shows "Subscribe now" button and the subscription is automatically captured.

But what should I do with situations when the user loses connection or closes the window right after completing steps on Paypal but before saving subscription id in my DB?

**Comment by sebRomeo** [comment]
@blakejoy I think it would be interesting to answer the above question. I think a lot of us are trying to implement a robust application.

**Comment by blakejoy** [comment]
> @blakejoy I think it would be interesting to answer the above question. I think a lot of us are trying to implement a robust application.

I haven’t worked with the api for quite some time but I am definitely interested in the discussion

**Comment by sebRomeo** [comment]
@blakejoy maybe you could point out some staff that could answer ?
Here is a stackoverflow question about this case, if anyone is interrested in answering :)

https://stackoverflow.com/questions/67270378/how-to-confirm-billing-of-a-monthly-subscription-in-paypal-api-via-webhook

**Comment by blakejoy** [comment]
Let me take a look. I don’t know any staff. I was working with this as a side project before lol @sebRomeo
