### ISSUE TITLE
Paypal buttons were not visible once clicked "Debit or Credit Card"

### ISSUE THREAD

**Issue by JeromeDeLeon** [paypal/paypal-checkout-components#1283]
Similar issue with [react-paypal-button-v2#44](https://github.com/Luehang/react-paypal-button-v2/issues/44)

**Comment by khanghoang** [comment]
@JeromeDeLeon just want to let you know this is on my list and we'll have it soon.

**Comment by bluepnume** [comment]
FYI @khanghoang -- I think in the short term, the best solution here is just to render a 'cancel' link in the card field iframe below the submit button, that closes and returns to the buttons.

**Comment by gregjopa** [comment]
A close button was added to the Debit/Credit Card experience to get back to the rest of the buttons. Closing this.
