### ISSUE TITLE
Can a unique identifier be fed to the smart button and received with web-tokens

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [paypal/paypal-checkout-components#1284]
I am trying to handle all of our record updates using web hooks to keep the subscription integration simple and maintainable.

Other than the subscriber email there is no identifier in the webhook that we could query against our db and find the right records to update; 

That being said, I was wondering if a user id could be passed to the smart button during subscription creation or activation that we could receive back from the webhook?

**Comment by ahmadabdolsaheb** [comment]
@ravishekhar, thank you for helping out on a related issue. I was wondering if I could get your valuable opinion on this if possible.

**Comment by ravishekhar** [comment]
At present there is no support for passing a custom field in subscriptions use case. The support might come in sometime near future. I do not have exact dates though.
