### ISSUE TITLE
Tab close issue on IE and Edge

### ISSUE THREAD

**Issue by XEngine** [paypal/paypal-checkout-components#1288]
Last 3-4 days maybe more I don't know in IE 11 and Edge giving us strange error only in the pages that has paypal.js initialized. If you land a page that has the paypal express in it, doing nothing and try to leave that page with anything (click back or visit a link in that page), an alert window pops up. This is the exact error you get when you run `window.close()` on IE or Edge. 

"do you want to close the tab - Yes | No" 

I am currently on Mac so I cannot reproduce this issue with Chrome thus I can't provide screenshots.

This is how I initialize PayPal in our product pages.
```javascript
paypal.Buttons({
            style: {
                size: 'responsive',
                color: 'white',
                shape: 'rect',
                label :'buynow',
                layout: 'horizontal'
            },
            createOrder: this.payment,
            onApprove: this.authorize,
            onInit: this.validate,
            onShippingChange: this.shippingChange,
            //onError: this.error,
            onCancel: this.error,
            onClick: () => {this.modalClose.trigger('click')}
        }).render('#paypal-action');
```

### Steps to reproduce

It's simple just go to a page that has the paypal scripts in it. Do nothing and click your browser's back button.

### Affected browsers

- [x] Edge
- [x] IE

**Comment by arthurk777** [comment]
We can repro on this page:
https://developer.paypal.com/docs/checkout/

Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363

**Comment by nick-andersen** [comment]
Also experiencing the same issue

![image](https://user-images.githubusercontent.com/30809707/76653521-0d07d080-6526-11ea-8617-c1549e902176.png)

**Comment by nick-andersen** [comment]
@XEngine - This issue seems to be fixed for us, has it resolved for you?

**Comment by XEngine** [comment]
Yes, it seems fixed now closing this issue :) thanks for reminding!
