### ISSUE TITLE
Credit Card payment not possible after failed validation

### ISSUE THREAD

**Issue by tobiasdierich** [paypal/paypal-checkout-components#1291]
### Description

If you use the `actions.reject()` inside the `onClick` for validation hook, payment with credit card is no longer possible if validation fails once, even if you fix the validation errors. There are no console logs at all. All other payment methods work again once the user has fixed the validation issues. 

I remember there was a similar issue some time ago with the "PayPal" payment button, however, I can no longer find it.

### Steps to reproduce

Can be reproduced on: https://developer.paypal.com/demo/checkout/#/pattern/client

PayPal Version: 5.0.117

Code:

```js
<!DOCTYPE html>

<head>
    <!-- Add meta tags for mobile and IE -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>

<body>
    <!-- Set up a container element for the button -->
    <div id="paypal-button-container"></div>

    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD"></script>

    <script>
        let valid = false;
        
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({
            onClick: function(data, actions) {
              if (valid) {
                  console.log('valid');
                  return actions.resolve();
              }
              
              console.log('not valid');
              valid = true;
              
              return actions.reject();
            },

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '0.01'
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                });
            }


        }).render('#paypal-button-container');
    </script>
</body>
```

**What I expect:** The first click on the "Credit Card" button should fail since we call `actions.reject()`. The second click should, however, open the credit card payment form.

**What happens:** Even the second click on the "Credit Card" button does not open the credit card payment form, even though `actions.resolve()` is called.

### Affected browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [ ] Edge
- [ ] IE
- [x] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by fabiosussetto** [comment]
just got into the same bug. This basically makes the whole validation idea pretty useless, as it's impossible to restart a payment after validation fails...

**Comment by bluepnume** [comment]
Hi, this should now be resolved. Can you please let me know if you still see the issue. Thanks!
