### ISSUE TITLE
Cannot use v5/Smart Payment Buttons with popup bridge

### ISSUE THREAD

**Issue by manuhornung** [paypal/paypal-checkout-components#1294]
### Description

We're trying to setup the smart payment buttons together with the braintree PopupBridge and we're getting an empty `returnUrl` back instead of the native `redirectUri` from `reconstructReturnUrl` (`redirects.js`). This is because `if(!url)` below is true (`url is ''`).

![image](https://user-images.githubusercontent.com/4516798/79794923-677d2380-8353-11ea-9b35-2f9a2da23669.png)

This causes our popup bridge to never be called with a deep link but instead the page will just reload itself inside the "popup" (safari window).

Isn't the usage of the smart payment buttons together with the popup bridge supported?

(Braintree checkout is not an option since we don't control the back end, and checkout.js v4 doesn't seem to work for us either since the callback from the popup bridge doesn't provide the order ID back. We need it though for the authorization.)

### Steps to reproduce

1. Setup the popup-bridge-ios and load the smart payment buttons in the corresponding webview
2. Run the application and click the PayPal button
3. Enter credentials and checkout
4. Observe how the page reloads the last checkout step instead of returning to the popup bridge

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [X] Safari Mobile/Tablet
- [X] Web View / Safari ViewController
- [X] Other (PopupBridge)

**Comment by bluepnume** [comment]
Hi, thanks for the report. Just to confirm -- are you saying the user is never redirected back from the browser window after hitting continue/pay now?

**Comment by manuhornung** [comment]
Thanks for the quick response!

Yes, that's exactly what I'm trying to say. In the given scenario in the screenshot, url is explicitly set to null in the call and returnUrl is also undefined because the bank ends didn't return a returnUrl.href. That's why an empty string is returned and the user sees a reload instead of a redirect bank to the popup bridge.

We also tried setting a return url during order creation but the bank end doesn't seem to accept custom schemas, which is why we think the redirect_uri parameter would be the way to go. Unfortunately, we don't get to the part of code in reconstructReturnUrl where redirect_uri is used.

**Comment by bluepnume** [comment]
Great, thanks for the info. I think I might have an idea what's going wrong here.

Can you share an example of the full url you're loading into the new browser window after the popup bridge is invoked? Thanks!

**Comment by IbrahimalKhayat** [comment]
@bluepnume here is the requested sample

https://www.sandbox.paypal.com/checkoutnow?fundingSource=paypal&token=3FB15519E82243041&useraction=commit&redirect_uri=com.js.popupbridge://popupbridgev1/

**Comment by bluepnume** [comment]
OK, just as suspected. I have a fix I can try out tomorrow. Will let you know. Thanks!

**Comment by bluepnume** [comment]
Hi, we've pushed out the hopeful fix. Can you let me know if it works for you? Thanks!

**Comment by bluepnume** [comment]
Closing this as the fix appeared to work for https://github.com/paypal/paypal-checkout-components/issues/1293 -- please let me know if you see any issues. Thanks again.
