### ISSUE TITLE
Smart button - Credit

### ISSUE THREAD

**Issue by carltondickson** [paypal/paypal-checkout-components#1295]
### Description

I can't see the PayPal credit button when displaying my smart buttons using the JavaScript SDK, is this intended behaviour?

### Steps to reproduce

When using the SDK library...

1. https://developer.paypal.com/demo/checkout/#/pattern/client
2. No **PayPal Credit** button visible

This works...

1. Access https://developer.paypal.com/demo/checkout-v4/#/pattern/vertical
2. I can see the **PayPal Credit** button as a payment method

### Affected browsers

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Which country are you browsing from?

**Comment by carltondickson** [comment]
@bluepnume United Kingdom (England)

**Comment by bluepnume** [comment]
@vishakha94 can you take a look? Thanks

**Comment by vishakha94** [comment]
@carltondickson 
could you pls post the `Paypal-Debug-Id` under response headers of the `smart/buttons` call from your network tab?
Also pls specify the env.
Thanks!

**Comment by carltondickson** [comment]
@vishakha94 thanks for the response...
debugId: a276aeef4924a
env: sandbox

**Comment by vishakha94** [comment]
@carltondickson I see that the credit button is not allowed due to MERCHANT_NOT_ALLOWED for client id = `AVnZ9VGXvqdiE_qh2d5U9N9s4HnhDGFxD_mFuRLQssc9ys1WQJqUjBu7DMK47JHhb-JUenmDBIP4odYc`.

**Comment by carltondickson** [comment]
@vishakha94 ok thanks.
Is there documentation on credit about where this setting can be enabled?

**Comment by carltondickson** [comment]
Also on this [https://developer.paypal.com/demo/checkout/#/pattern/client] and pretty much all of the documentation I've seen I can't find a working example that displays the PayPal credit button.

I've only seen this working on the checkout.js implementation
https://developer.paypal.com/demo/checkout-v4/#/pattern/vertical

**Comment by tkeeber** [comment]
Hi, any update on this? Can we get @carltondickson questions answered please.
