### ISSUE TITLE
Client ID validation

### ISSUE THREAD

**Issue by VintorezVS** [paypal/paypal-checkout-components#1300]
### Description

I have a question. I'm developing a widget that accepts the user's PayPal Client ID. I need to validate that ID. Is there any ability to validate that ID is real?

**Comment by bluepnume** [comment]
You can call this api:

https://developer.paypal.com/docs/api/get-an-access-token-curl/

You can skip passing a secret and just pass `"<client_id>:"` (client id followed by a `:`). If you get a 2xx status code, it's a valid client id.

**Comment by VintorezVS** [comment]
Thank you. It works.
