### ISSUE TITLE
Paypal button goes missing for checkout.js integration

### ISSUE THREAD

**Issue by akshay93** [paypal/paypal-checkout-components#1305]
**Short description of the issue**
A merchant is using checkout.js button integration. They have given website URL https://gteceducation.com.sg/payment/index.
The issue is that the Paypal button goes missing. They have sent 3 screenshots wherein the button is not visible. The merchant has also sent the View Page Source.
I tried on multiple browsers and multiple devices but unable to reproduce this issue.

- **Screenshots or videos that show the issue**
Attached:
<---------------------->
![1](https://user-images.githubusercontent.com/5312995/81641747-5b125500-943f-11ea-89b1-d5afad2a2fd8.jpg)
<---------------------->
![2](https://user-images.githubusercontent.com/5312995/81641752-5e0d4580-943f-11ea-9862-16de3c24a1cc.jpeg)
<---------------------->
![3](https://user-images.githubusercontent.com/5312995/81641755-5fd70900-943f-11ea-8bd4-2a908f00ef71.jpeg)
<---------------------->

- **Your code**
[servlet.txt](https://github.com/paypal/paypal-checkout-components/files/4613561/servlet.txt)
- **The `paypal.version` from your browser console**
NA
- **The exact browser version**
NA
- **A link to your page with the issue, if possible**
Merchant's website: https://gteceducation.com.sg/payment/index
- All console logs during the time of the issue, especially error messages
NA
- **Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?**
No
- **Does the issue occur consistently, or intermittently?**
intermittent issue. Merchant loaded the button containing page on 4th May 6-7 times in one browser (Windows/Chrome) and got the issue 2 times.
The issue reported was from Buraimi, Oman, But today, one of their members in Kerala, India also got this issue in their mobile & laptop

### **Steps to reproduce**
As shown in screenshots

**Please provide each individual step required to reproduce the issue**
Populate, dummy values and submit the form, Paypal button not appearing as shown in screenshots

### **Affected browsers**
All of the below:
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Hi, we've been unable to reproduce this issue. Please let us know if you can repro, and let us know the steps.
