### ISSUE TITLE
Ability to change shipping options after getting shipping address

### ISSUE THREAD

**Issue by Littlelies** [paypal/paypal-checkout-components#1308]
In https://github.com/paypal/paypal-checkout-components/blob/master/docs/implement-checkout.md one can read:
This callback provides the merchant with a window to patch the cart with new amount or shipping option values through the Payments API

I managed to patch the order to update amount, but I haven't found anywhere how we can patch the cart with new shipping options?
Patching the order on item_list is not allowed for example.

Thank you

**Comment by bluepnume** [comment]
@amaclean2 can you help with this one? Thanks!

**Comment by amaclean2** [comment]
Yeah, the call to patch the shippingOptions is
```js
    return actions.order.patch([
        {
            op:    "replace",
            path:  "/purchase_units/@reference_id=='default'/shipping/options",
            value: <yourNewShippingOptions>
        }
    ]);
```

**Comment by paymentplugins** [comment]
Hi @amaclean2,

Using that patch path does update the order, however it doesn't seem to trigger an update in the PayPal popup window every-time. In my testing, it was every other call to patch the order that resulted in the shipping options being updated.

In addition, when `onShippingChange` is called for the first time when the buyer logs in, the Popup does not display the results of the initial shipping options patch.

Kind Regards,

**Comment by amaclean2** [comment]
Try again. There was a release today/yesterday that fixed some of that behavior.

**Comment by paymentplugins** [comment]
@amaclean2,

The shipping options now correctly refresh each time the patch path is called with a `replace` operation, once the Pop-up is open.

However, the `add` operation does not work when the initial `onShippingChange` is called when the buyer is logging in. 

PayPal sends the buyer's default address in the `onShippingChange` event, when the buyer is first being logged in to PayPal. Using the buyer's default address, it is expected that a list of shipping options can be provided for the default address. If the buyer then decides to change their address in the PayPal pop-up, the `replace` operation works as expected.

Kind Regards,

**Comment by Littlelies** [comment]
Thank you @amaclean2 this now works fine, however it looks like we have to change shipping option at least once, otherwise clicks  on 'Pay' button are not taken into account. I am afraid we loose some orders because of this.

**Comment by stanimal** [comment]
> Thank you @amaclean2 this now works fine, however it looks like we have to change shipping option at least once, otherwise clicks on 'Pay' button are not taken into account. I am afraid we loose some orders because of this.

We're noticing this too.  Default shipping option appears selected to the user, but clicking Pay Now does nothing.  User is forced to explicitly select a shipping method first, before they can Pay, but there is no warning/error message indicating that they must do so.

**Comment by 719media** [comment]
Can someone paste a link of where the patch to shipping options is in the paypal API documentation?
I can only see patch to order

**Comment by amaclean2** [comment]
Braintree does only support orders v1, I think. I have to get back to you on that.

**Comment by 719media** [comment]
Cool, thanks. Regardless, I'd love to see where the reference to `/shipping/options` is in the paypal documentation, I can't find it anywhere.

**Comment by amaclean2** [comment]
There's more shippingOptions/callback documentation coming out soon. It's in revision

**Comment by 719media** [comment]
Is there any documentation for this yet?

**Comment by 719media** [comment]
@amaclean2

**Comment by 719media** [comment]
@amaclean2 Is there any documentation for this yet?

**Comment by gazeattaus** [comment]
Patch for `/shipping/options` returns a `400` error. I'm not able to change the shipping options based on `onShippingChange` event. Any idea why?

**Comment by malewis5** [comment]
> Braintree does only support orders v1, I think. I have to get back to you on that.

Is there any update on this? Is Braintree still using v1?

**Comment by leffot** [comment]
> Patch for /shipping/options returns a 400 error. I'm not able to change the shipping options based on onShippingChange event. Any idea why?

I'm having this same issue. Can't patch an order at `/shipping/options`. Is there any update to this?

**Comment by tilman** [comment]
> There's more shippingOptions/callback documentation coming out soon. It's in revision

Any updates on the docs? Can't find anything about the shipping options patch in the docs.

**Comment by Bouhnosaure** [comment]
Hi, i'm also having issues with updating shipping options and i'm getting 400 errors. 

Can you update the documentation either REST, on the SDK or both because, it's blocking.
