### ISSUE TITLE
PayPal Commerce Platform Error "Request is not well-formed..."

### ISSUE THREAD

**Issue by DeYaqoob** [paypal/paypal-checkout-components#1312]
Hi,

When i click "Debit or Credit Card" This error show up 
How can i fix this 

![Annotation 2020-05-19 213641](https://user-images.githubusercontent.com/65621950/82365087-da43f200-9a18-11ea-9d3c-c6e389ad3758.png)

- Extension :  PayPal Commerce Platform
- Script : Open Cart v3.0.3.3
- browser : Chrome
- link : https://lomeyfarm.com/index.php?route=checkout/checkout
- Error Mesaage :  Request is not well-formed, syntactically incorrect, or violates schema.

**Comment by bluepnume** [comment]
This looks like an error on opencart side, not on paypal. Please reach out to that team. Thanks!
