### ISSUE TITLE
How to handle two different plans in a subscription?

### ISSUE THREAD

**Issue by lmatab** [paypal/paypal-checkout-components#1314]
### Description

I have been testing how the smart buttons work and it is wonderful although it lacks documentation.

I have been able to test the basic subscription with the example provided in  https://developer.paypal.com/docs/subscriptions/integrate/#4-create-a-subscription

Although it is not clear how to handle a subscription that has two plans, for example : Basic and pro.

Should we create to different  buttons?, or how should it be managed?

Thanks

**Comment by bluepnume** [comment]
@ravishekhar can you help here?

**Comment by ravishekhar** [comment]
You can show either two buttons for two different plans or can use one button as well for two plans. In later case you can can pass planId conditionally.
e.g.

```html
<script src="https://www.paypal.com/sdk/js?client-id=ARqKO-Zl4_Hw4YtskemsSuHwSHhY1i0LWd8VxU6uRjZzuI_rwB530TCaYPVvKXzimfMQaSC9Mg8Og4P2&vault=true"></script>

<h1>
  Single button with multiple Plans
</h1>
<h3>
  <label for="selectPlan">Select Plan</label>
  <select id="selectPlan">
    <option value="planA">Plan A</option>
    <option value="planB">Plan B</option>
  </select>
</h3>
<div id="paypal-buttons"></div>

<hr>
<h1>
  Different buttons for different plans
</h1>

<h3>
  Plan A
</h3>
<div id="paypal-buttons-plan-a"></div>


<h3>
  Plan B
</h3>
<div id="paypal-buttons-plan-b"></div>
```

```javascript
const planA = 'P-59M1017976970682PLZYGALA';
const planB = 'P-1JN05705K53953236LZYGBYA';

paypal.Buttons({
  style: {
    color: 'gold',
    shape: 'pill',
    label: 'subscribe'
  },
  createSubscription: function(data, actions) {
    return actions.subscription.create({
      'plan_id': document.getElementById('selectPlan').value === 'planA' ? planA : planB,
      'application_context': {
        'shipping_preference': 'NO_SHIPPING'
      }
    });
  },
  onApprove: function(data, actions) {
    alert(data.subscriptionID);
  }
}).render('#paypal-buttons');


paypal.Buttons({
  style: {
    color: 'silver',
    shape: 'pill',
    label: 'subscribe'
  },
  createSubscription: function(data, actions) {
    return actions.subscription.create({
      'plan_id': planA,
      'application_context': {
        'shipping_preference': 'NO_SHIPPING'
      }
    });
  },
  onApprove: function(data, actions) {
    alert(data.subscriptionID);
  }
}).render('#paypal-buttons-plan-a');



paypal.Buttons({
  style: {
    color: 'blue',
    shape: 'pill',
    label: 'subscribe'
  },
  createSubscription: function(data, actions) {
    return actions.subscription.create({
      'plan_id': planB,
      'application_context': {
        'shipping_preference': 'NO_SHIPPING'
      }
    });
  },
  onApprove: function(data, actions) {
    alert(data.subscriptionID);
  }
}).render('#paypal-buttons-plan-b');

```

**Comment by lmatab** [comment]
Thanks @ravishekhar and @bluepnume .

I will test it in my code.

I got a couple of questions:

1- When the user is returned successfully and the alert inside onApprove is shown it means that the user is already subscribed and will be billed automatically or do I have to capture the amount some how?

2- If I offer my clients 7 days of free service without the need to subscribe how can I charge  upfront the month when the trial period is gone and they decide to subscribe?

Thanks a lot for the enlighten about these topics, the documentation is good but it still lacks of many details for use to understand, after I finish my implementation I will try to make a video to show how to use this.

**Comment by ravishekhar** [comment]
> 1- When the user is returned successfully and the alert inside onApprove is shown it means that the user is already subscribed and will be billed automatically or do I have to capture the amount some how?

When you initiate a create subscriptions call, by default it will activate the subscription. No separate activate is needed. 
Some info on similar ask here https://github.com/paypal/paypal-checkout-components/issues/1282

> 2- If I offer my clients 7 days of free service without the need to subscribe how can I charge upfront the month when the trial period is gone and they decide to subscribe?

I am not sure if I am getting your question correctly. However if there is any upfront cost for a subscription which you need to bill your users, you can add a setup fee to your plan.
https://developer.paypal.com/docs/api/subscriptions/v1/#definition-payment_preferences
You can also use the Subscriptions Dashboard for plan and subscription management
Login to PayPal.com -> Go to Tools -> All Tools -> Accept Payments -> Subscriptions
You use this link as well https://www.sandbox.paypal.com/billing


> 3- Is it supposed that I have inside my app a mechanism to track is a client has an active subscription ? or the api is structured so I can be making api calls every time I want to check if the client has currently an active subscription.

You can track using Subscription Management APIs 
https://developer.paypal.com/docs/api/subscriptions/v1/#subscriptions
or the Dashboard pointed above. 



> after I finish my implementation I will try to make a video to show how to use this.

Thanks 🙏 . Appreciate it 👍

**Comment by Ogarunite** [comment]
Is there a way to pass a custom parameter? Like so:
```
createSubscription: function(data, actions) {
  return actions.subscription.create({
          custom_id: '1337',
          'plan_id': 'P-966909095D281704TL3G4X4Q' //Self generated
        });
      },
```
the custom_id value 1337 is the value I would like to receive in the webhook. But it does not seem to work with subscription. It did work with a normal payment, createOrder lik this:
`createOrder: function(data, actions) {
      return actions.order.create({
        purchase_units: [{
          amount: {
            value: '1.00',
          },
          custom_id: '1337'
        }]
      });
    }`

**Comment by ravishekhar** [comment]
The custom id support is being worked upon at present. I will update this thread once its available.

**Comment by Ogarunite** [comment]
> The custom id support is being worked upon at present. I will update this thread once its available.

Thanks, good to hear. Do you know how it's done otherwise, or have a suggestion how to do it differently with PHP? I guess there's no way to really know based on the webhook which user/user ID the purchase belongs to, when I can't pass it as a parameter.

Also, do you know when abouts it will be available, or is it just up to the paypal development team?

**Comment by ravishekhar** [comment]
The custom_id support will be available by June 15.

**Comment by Ogarunite** [comment]
Thanks for the response!
Do you know just how to use it within the createSubscription function? Would it be like this?:
createSubscription: function(data, actions) {
  return actions.subscription.create({
          custom_id: 'username',
          'plan_id': 'P-966909095D2...' //Self generated
   });
},

**Comment by ravishekhar** [comment]
@Ogarunite Custom ID feature is now available for Subscriptions. Please let me know if you have any questions. 

```javascript
createSubscription: function(data, actions) {
  return actions.subscription.create({
          "custom_id": "LM10-USER-1234567890",
          "plan_id":"{{plan_id}}",
   });
},
```

Create Subscription Webhook
```json
{
  "id": "WH-15P17806DJ092193M-71699717AW138843C",
  "event_version": "1.0",
  "create_time": "2020-06-04T09:36:56.084Z",
  "resource_type": "subscription",
  "resource_version": "2.0",
  "event_type": "BILLING.SUBSCRIPTION.CREATED",
  "summary": "Subscription created",
  "create_time": "2020-06-04T09:36:45Z",
  "custom_id": "LM10-USER-1234567890",
  //.... Other fields
```
Activate Subscription Webhook
```json
{
  "id": "WH-48M12015FU260600A-52R84971NE490952H",
  "event_version": "1.0",
  "create_time": "2020-06-04T09:37:48.890Z",
  "resource_type": "subscription",
  "resource_version": "2.0",
  "event_type": "BILLING.SUBSCRIPTION.ACTIVATED",
  "summary": "Subscription activated",
  "custom_id": "LM10-USER-1234567890",
  //...other fields
}
```

Payment.Sale.Completed Webhook
```json
{
  "id": "WH-01U43203R58534913-9KJ73811RC7239619",
  "event_version": "1.0",
  "create_time": "2020-05-05T14:04:35.863Z",
  "resource_type": "sale",
  "event_type": "PAYMENT.SALE.COMPLETED",
  "summary": "Payment completed for $ 2.05 USD",
  "custom_id": "LM10-USER-1234567890",
  //...other fields
}
```

**Comment by ivancukns** [comment]
Hello @ravishekhar 

The 'custom_id' field doesnt seem to work for subscriptions, in the IPN request I am not getting anything, for both custom and custom_id fields.

Also, in your example, there are responses for various webhooks, but does it for for the IPN calls?

**Comment by phuhl** [comment]
Any updates on this?

> The 'custom_id' field doesnt seem to work for subscriptions, in the IPN request I am not getting anything, for both custom and custom_id fields.

How are you supposed to link a subscription to a user? How are people doing it today?

**Comment by ivancukns** [comment]
@phuhl Hi, I've found a solution at the end, but it was really hard and I wasted many hours. There is no real documentation for this anywhere.

so, this is my paypal button on the frontend:

        createSubscription: function(data, actions) {
          return actions.subscription.create({
            'custom_id': name,
            'plan_id': 'XXXXXXXX'
          });
        },

And this is how I get it in the backend with the IPN request:

$username = $request['rp_invoice_id'];

I have no idea how this has any sense for PayPal, but its working like that, and isnt documented.

I hope I helped!

**Comment by phuhl** [comment]
@ivancukns Thank you for the quick response.

Is this `$username = $request['rp_invoice_id'];` a body field? My API-logs don't show that, neither as header field, body field or query parameter. 

My button code:
```js
              createSubscription: function (data, actions) {
                return actions.subscription.create({
                  custom_id: "CUSTOM_ID", // for finding it in the logs
                  plan_id: plan,
                });
              },
```
I can't spot a difference to what you are doing... I am really confused by now :/

**Comment by ivancukns** [comment]
@phuhl Oh yes, sendbox doesnt work properly, I was testing with the real account the whole time. :( 

so, on the frontend it must be called 'custom_id', but in the backend in your IPN listener, the 'custom_id' is going to be passed as 'rp_invoice_id' POST field.

**Comment by phuhl** [comment]
Thanks ivancukns, for the really quick answers the other day. Sadly we didn't get it to work, no matter what we passed into the buttons, there was nothing related coming out of the IPN.

We went with fully integrating PayPal and went to Stripe for credit cards.

**Comment by ivancukns** [comment]
@phuhl hm, weird since it works like that on my side. I see some differences in your code when compared to mine, for example custom_id not quoted in your code snippet.... maybe its some kind of small thing like this thats preventing it to work.

**Comment by ivancukns** [comment]
@phuhl I just wanted to let you know that I had a new subscription today, and my solution does not work any more.
The previous one I had on the Sepmteber 14. it worked!! This is such a BS! :( :( 👎

**Comment by ivancukns** [comment]
This is how this ends:
PayPal tech support guy: 'I have confirmed with our product developers that this is no longer supported via IPN.'

**Comment by phuhl** [comment]
> @phuhl I just wanted to let you know that I had a new subscription today, and my solution does not work any more.
> The previous one I had on the Sepmteber 14. it worked!! This is such a BS! :( :( -1

Yeah, Paypal is not dev friendly. As they say... :/

**Comment by mlerley** [comment]
@ivancukns @phuhl FYI I just tried passing the custom_id this way doing this on a new project with a single plan and a simple implementation, but this did work for me:

    createSubscription: function(data, actions) {
        return actions.subscription.create({
            'plan_id': 'planid',
            'custom_id': 'customid'
        });
    },

The custom ID is indeed being shown in my subscription info where I would expect it to be.
Thanks for the guidance - I hope this keeps working!

**Comment by ivancukns** [comment]
@mlerley yeah, it gets saved with the corresponding subscription, but we are not getting that information with the IPN request anymore- thats the problem.

It now requires more work and custom code to check the subscription username in the IPN listener, which sucks, cuz it could have been just a field in the IPN request (like it used to be).

**Comment by newearthmartin** [comment]
> The custom_id support will be available by June 15.

Hi @ravishekhar more than a year has passed and still `custom_id` is not showing up on the IPN, at least on sandbox.

**Comment by newearthmartin** [comment]
Will this be implemented? 

I wonder who can find this useful without being able to set a custom id to subscriptions and get it on the IPN notification. 

This all used to work perfectly before the switch to the Javascript SDK. It's really a shame.

**Comment by newearthmartin** [comment]
Since the PayPal dev team are rendering themselves useless in this matter, how did you guys manage to solve this?

I see that when creating the subscription in the `onApprove` callback we get `data.subscriptionID`. We can then tie this to the `custom_id` we just created. It's risky though because it depends on the user's browser window remaining open.

What else is there? Is there a way to query the server to get the custom_id for a subscription id from my backend?

**Comment by phuhl** [comment]
We stopped using paypal buttons and went for a full integration with all payment providers we desire (a.k.a. the cheapest)

**Comment by souldia1** [comment]
@newearthmartin
