### ISSUE TITLE
How can I add merchant logo on checkout page ?

### ISSUE THREAD

**Issue by pakman198** [paypal/paypal-checkout-components#1318]
### Description
I've been trying to find how to add the merchant logo on the checkout page and I haven't found a solution yet.
The documentation is not too clear on how to insert the company logo.

I'm using this project since my app is in react: [https://www.npmjs.com/package/react-paypal-button-v2](https://www.npmjs.com/package/react-paypal-button-v2)

**Comment by bluepnume** [comment]
@rajarampadmanathan is there documentation for how to do this with v2/orders?

**Comment by pakman198** [comment]
I posted the question on twitter to the PayPal developer account and someone came to me saying that's not possible.
At the end I was able to do so, here is my response:

> So in the page "Mis botones guardados" is like my saved buttons, there on the right side is a sidebar that has 2 links. If you click on "Gestionar estilos de la página de pago" which would be something like customize the checkout page. 
You'll be taken to another page, by default you'll have a page called PayPal which is the default one and is not customizable, so I created another page and then I was able to add my company logo.

There's no documentation available and I noticed something else, with the smart payments buttons, the popup window has a default width and height making it display the "mobile" content, hiding the logo. If the popup was a bit wider then the logo would be shown and I guess that'll improve the user experience.

**Comment by rsdighe76** [comment]
we have gone away from showing the logo because the experience is in context - back in the old days it was a full page redirect there was a disconnect and the logo comforted folks that they are still checking out with the merchant but it's not needed any more and as such the api doesn't quite support this capability nor does it seem to help conversion.

**Comment by pakman198** [comment]
@rsdighe76 thanks for your response :)
