### ISSUE TITLE
Error message for card payments - Something went wrong. We'll take you back to the checkout so you can try again

### ISSUE THREAD

**Issue by ianpetzer** [paypal/paypal-checkout-components#1319]
### Description

Some of our customers are receiving an error message saying `Error message for card payments - Something went wrong. We'll take you back to the checkout so you can try again`

This happens when they try to pay using `Debit or Credit card` button. Please note that we have successfully processed other transactions through the Paypal checkout buttons and our customer has already contacted their bank to check that the transaction is not being blocked from their side.

- Screenshots or videos that show the issue

![Screen Shot 2020-05-23 at 3 57 24 PM copy](https://user-images.githubusercontent.com/1169799/82841931-07d8e180-9ed8-11ea-8891-0b6afa52140c.png)

- Your code

    ```paypal.Buttons({
        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{
              amount: {
                value: context.get('transactionAmount').toString(),
              }
            }],
            application_context: {
              shipping_preference: 'NO_SHIPPING'
            }
          });
        },
        onApprove: function(data, actions) {
          context.ui.set('showProcessingModal', true);
          run.later(() => {
            //Basically stop showing that modal after 5 seconds.. as there is a lot of auto magic with Paypal
            context.ui.set('showProcessingModal', false);
          }, 5000);
          return actions.order.capture().then(function(details) {
            context.handleSuccesfulPayment(details)
          });
        },
        onError: function (err) {
          context.handleFailedPayment(stripeResponse).then().finally(()=> {
            context.ui.set('showProcessingModal', false);
            context.ui.showGeneralMessage('Oops', 'We were unable to process your payment. Please get in touch.');
          });
        }
      }).render('#paypal-button-container-'+context.elementId);```

- The `paypal.version` from your browser console

5.0.126

- The exact browser version
- A link to your page with the issue, if possible

I've created a similar trip in our staging environment here: https://staging.timbuktutravel.com/trip/-ad3787f5-4a38-425c-bc09-a9fe35765f12/pay

you can log in with:
email: paypal@test.com
password: paypal123

- All console logs during the time of the issue, especially error messages
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
- Does the issue occur consistently, or intermittently?
Intermittently

### Steps to reproduce

Go to the pay page of one of the trips that we sell
Click the black "Debit or Credit card" button. 
Fill in the card details. 
See error message
Some customers are able to pay. 
Some customers are not able to pay. Seeing this error message. We have two different customers that are experiencing this with different cards


### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by ianpetzer** [comment]
I have contacted Paypal customer support and they do not have any record of any failed transactions on the dates that the customers attempted to pay. They have tried twice now on 21 May and 23 May

**Comment by ianpetzer** [comment]
The customers have tried again and I can confirm that there are three of them that have been unable to pay. They are all trying to use Visa cards. 

The first attempt with the inline payment form fails, then they try again with the popup version and that also fails. Please advise how we can debug?

**Comment by bluepnume** [comment]
@khanghoang can you help take a look? Thanks!

**Comment by ianpetzer** [comment]
@bluepnume @khanghoang That would be amazing. Thanks.

So more info:
I managed to replicate yesterday and got these ids:
paypal-debug-id: f05b23e161ee6
paypal-client-context: 1EJ653753B396294B

paypal-debug-id: 16f9105fba1b7

paypal-debug-id: c460574060909

paypal-debug-id: c460574060909

paypal-debug-id: 54466ab0fbc3

	• CORRELATION-ID: eeae4e6de8d3f
	• Date: Thu, 28 May 2020 15:19:17 GMT
	• Paypal-Debug-Id: eeae4e6de8d3f

Token: 1EJ653753B396294B


FYI... One of the customers who was failing to pay managed to add the same card to a Paypal account and then paid through their paypal account using the same card.

Yesterday with those error messages, after failing the inline form, and entering the card details it did say "card declined" in red text but the other customers said to them as well.

**Comment by noornashriq** [comment]
I'm experiencing the same issue too. We haven't gone to full production and only tested with our own cards. In our case, the issue seems to occur for debit cards.

Have tested with the same cards at https://developer.paypal.com/demo/checkout/#/pattern/client and returns the same error.

**Comment by AdamHashim** [comment]
Me too, experiencing the same issue with debit cards!

**Comment by abhishekkarna** [comment]
I just integrated paypal to my application and it is giving the same error while making the payment via cards .

**Comment by 333design** [comment]
I am having the exact same issue with Woocommerce. Some clients can check out and some cannot.

**Comment by Cyriuz** [comment]
Same issue here, getting a lot of support requests every day with people that can't pay but I have not been able to repro it...

**Comment by remdd** [comment]
Me too unfortunately - exactly as per the previous comment, I'm unable to reproduce but getting a steady stream of reports.

**Comment by praggygruntt** [comment]
Same issue here - I can't reproduce it though.

I am using the Ecwid Integration through SiteJet, so I haven't touched the code. Just hooked in PayPal through the Ecwid Dashboard.

**Comment by givicha** [comment]
Hi Alexander
Thanks for your attention

I do not have ad blocker


My problem is -

If I select PayPal for the payment, it opens the modal login window of
PayPal correctly and works fine. But if I click on a credit or debit card,
I make the payment, it processes for a sec and says: "Something went wrong.
We'll take you back to checkout so you can try again". then it cut the
money and return it (Payment is not made).

I have a WordPress site, I use a WooCommerce (plugin -  WooCommerce PayPal
Checkout Gateway)

https://bombber.com/

**Comment by davidboon78** [comment]
Experiencing the same problem as people above.  Not using any ad blocker, and tried with the default paypal on woocommerce as well as the woocommerce paypal gateway plugin.  Same error every time I try to use a credit card.

**Comment by jamesnash10** [comment]
Same issue as above in WooCommerce - any news on a fix?

**Comment by RadoslavLazarov** [comment]
Same issues here. I'm using  WooCommerce PayPal Checkout Gateway. I have two Visa cards. First card is accepted when I use billing address in my country. When I use different billing address is not accepted. The second card does not accept it at all.

**Comment by difayez** [comment]
Having the same issue, really wish it would work as it's preventing me from launching my online shop.

**Comment by krosoftware** [comment]
Any solution on this, please?

**Comment by RBSUS** [comment]
Having the same issue with cards. I believe this is to do with passing an application_context object. You are able to "avoid" the error by not doing so or passing both a return and cancel url. [See here](https://developer.paypal.com/docs/api/subscriptions/v1/#definition-application_context). However, passing custom URLs fails to close the paypal dialog and thus doesn't trigger the onApprove event etc. Not passing the application_context object altogether massively reduces the flexibility of the smart buttons and also breaks my checkout flow.

Quite dissapointed in paypal on this one! Both docs and support have been lacking. Think I'll be moving to Stripe

**Comment by unakriti** [comment]
Getting the same error! Does anyone have a solution or a workaround?

**Comment by oxcarga** [comment]
Same here. Noticed an error in console:
<img width="686" alt="imagen" src="https://user-images.githubusercontent.com/5163553/100923240-87a5c100-34a4-11eb-9329-03c19f5c1f63.png">

Any other have seen that error? Is it related?

**Comment by jonwade** [comment]
I'm having the same issue.  Getting the unhandled error "CANNOT_FIND_MERCHANT_COUNTRY" but can't see where to set this in the request.  This is using dummy card details in the Sanbox API.  It fails every time when selecting to pay by card.  It doesn't matter which card type or country I choose.

<img width="850" alt="Screenshot 2020-12-11 at 11 58 44" src="https://user-images.githubusercontent.com/1330932/101901442-f5d73b80-3ba8-11eb-8997-0edfb5455e3c.png">

**Comment by log-out** [comment]
The same issue, any solution, please?

**Comment by j-grim** [comment]
Also having the same issue.

**Comment by AbdeladimSadiki** [comment]
> I'm having the same issue. Getting the unhandled error "CANNOT_FIND_MERCHANT_COUNTRY" but can't see where to set this in the request. This is using dummy card details in the Sanbox API. It fails every time when selecting to pay by card. It doesn't matter which card type or country I choose.
> 
> <img alt="Screenshot 2020-12-11 at 11 58 44" width="850" src="https://user-images.githubusercontent.com/1330932/101901442-f5d73b80-3ba8-11eb-8997-0edfb5455e3c.png">

Try removing the payee field from the purchase_units array.

**Comment by Sledro** [comment]
Same issue

**Comment by richpatanalytics** [comment]
same issue

**Comment by syedmaazali333** [comment]
Same Issue

**Comment by Tommy-tm11** [comment]
I have the same issue too! Has anyone got this issue fixed?

**Comment by esreal12** [comment]
Same issue in 2022

**Comment by Trappist-1G** [comment]
bump

**Comment by Trappist-1G** [comment]
PayPal is not available in my country that may be the issue. But I am using a debit card not a Paypal account. I do not see why that would be an issue.

**Comment by nosibor** [comment]
Experiencing the same issue now, just discovered as of a few days ago.

**Comment by Ivajkin** [comment]
Experiencing this issue with my PayHip product pages.
