### ISSUE TITLE
After successfull payment, paypal throw error - No Response from window. cleaned up

### ISSUE THREAD

**Issue by DmitryNyshchyi** [paypal/paypal-checkout-components#1322]
I'm implementing the Paypal payment gateway with React. I'm following a tutorial from robinwieruch.de.
I'm able to complete the payment procedure, but after payment completed it throws `no response from window. cleaned up`.

Errors in console:

![изображение](https://user-images.githubusercontent.com/40161404/83482202-5ffb7f00-a4a8-11ea-9f1e-f7fed8d69f74.png)

Code:
![изображение](https://user-images.githubusercontent.com/40161404/83482442-f760d200-a4a8-11ea-8053-e71f96efcf77.png)
![изображение](https://user-images.githubusercontent.com/40161404/83482363-cc767e00-a4a8-11ea-974d-ccda45375009.png)
![изображение](https://user-images.githubusercontent.com/40161404/83482384-d7311300-a4a8-11ea-9f51-b1f6b5483d2e.png)
![изображение](https://user-images.githubusercontent.com/40161404/83482403-e2843e80-a4a8-11ea-8ea7-a963471ff4b6.png)

### Steps to reproduce
Complete payment procedure

### Affected browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by DmitryNyshchyi** [comment]
Hi!
Can I get help?
I don't get any answer for more than 1 month.

**Comment by JannikZed** [comment]
we receive the same error!
