### ISSUE TITLE
[Bug] RTL UI fields aren't clickable after displayed error icon in it

### ISSUE THREAD

**Issue by laukstein** [paypal/paypal-checkout-components#1329]
While testing latest PayPal button SDK on latest Chrome with `locale=he_IL` (https://www.paypal.com/sdk/js?...&locale=he_IL).

When focused mandatory field and when focused out, it adds red error button in right side of field - should be displayed in left side (is BUG).
After when tried to focus the field, it is almost impossible - field is focusable only when clicked fields bottom area few pixels from bottom or when using keyboard Tab that is impossible on mobile. This BUG is due to error icon hovering the must of field area. Please use CSS `pointer-events: none` for this icons.

![grabilla g10284](https://user-images.githubusercontent.com/183966/83953412-e3222980-a848-11ea-9521-8fd41f74b950.png)

**Comment by mstuart** [comment]
@khanghoang, can you take a look?

**Comment by mnicpt** [comment]
@laukstein A fix has been released for this issue.  Thank you for being patient while we provided the fix.  Feel free to reopen this Issue if you find there is still a problem.  Thank you.

**Comment by laukstein** [comment]
@mnicpt, still the Hebrew RTL (right-to-left) UI is broken, see:
![grabilla Hp3192](https://user-images.githubusercontent.com/183966/94730215-8e606c80-036b-11eb-959a-cb9c3cb78ee5.png)

I think this task should be solved by someone having understanding of RTL UI, bidi-directional UI.

**Comment by mnicpt** [comment]
@laukstein So sorry this hasn't been fixed for you.  I will reach out to the team.

**Comment by mstuart** [comment]
Hi @laukstein, it's fixed! Let us know if that's okay. I don't have an issue clicking into the fields for RTL and it seems like the error icons, error tooltips are okay. Sorry about the trouble. Let us know if you have any other issues with these fields.

**Comment by laukstein** [comment]
It looks now fine.
