### ISSUE TITLE
[Bug] Credits Cards on Production declined silently with a strange graphql response

### ISSUE THREAD

**Issue by grmmph** [paypal/paypal-checkout-components#1333]
On sandbox everything works weel, however when trying (multiple) credit cards. The buttons are failing silently (no error hanlding) and looking at the network response shows this:
![Screen Shot 2020-06-10 at 19 45 26](https://user-images.githubusercontent.com/5146230/84321099-4a0e4e00-ab7b-11ea-8590-530e135372bc.jpg)

Also it shows on field `fundingOptions`: 
```declineReason: "unsupportedGeneric"```

**Comment by bluepnume** [comment]
@khanghoang can you help triage this one? Thanks!

**Comment by khanghoang** [comment]
Hi @grmmph, sorry to hear that. Could you please follow this link to capture either the EC token or debug id so that I can help you to triage the issue? https://gist.github.com/khanghoang/4c85b758ad9ba057191303579aba7c7e

**Comment by mstuart** [comment]
Hi @grmmph, closing this issue for now. If you're still facing this issue, can you reply w/ an EC token or paypal-debug-id response header to help debug further?

**Comment by nolegendhere** [comment]
Hi. I'm having the same exact problem

My paypal debug id is d6d91565d3dea

Credit cards are being declined with the same exact message

**Comment by nolegendhere** [comment]
If I try it from a incognito tab in chrome, I get this 
https://www.paypal.com/smart/api/order/4EX62828GK9968341
paypal-debug-id 887e9179b5afe
response: {"ack":"permission_denied","message":"Insufficient privileges"}
