### ISSUE TITLE
[Feature] Vue.js examples

### ISSUE THREAD

**Issue by realtebo** [paypal/paypal-checkout-components#1338]
### 🚀 Feature Proposal

vuejs integration

### Motivation

I see angular and react in examples but not vuejs and we're broadly using vuejs on our company projects

**Comment by mstuart** [comment]
Hi @realtebo, which Angular and React examples are you referring to? Can you drop a link here?

We're working on some clearer React, Angular and Vue docs right now and publishing them soon. We'd love your feedback on them!

/cc @mnicpt

**Comment by realtebo** [comment]
Here: https://github.com/paypal/paypal-checkout-components/tree/master/demo

**Comment by mnicpt** [comment]
@realtebo Thank you for reaching out!  As Mark mentioned, we have been working on providing some clearer docs around Single Page Application integration examples.  I will add this request to provide a driver and a working example for Vue.js as well.  In the meantime, I can help you with something in the short term if you would like to help you integrate with Vue.js.

**Comment by mnicpt** [comment]
@realtebo Wanted to reach back out to you as what I've posted above doesn't until `Vue`is initialized.  The updated docs will ensure this is the case.

**Comment by realtebo** [comment]
@mnicpt I forwarded the linkt to this thread to my coworker who inherited the task about paypal and vue. Personally, I'm sorry, I've not tried yet, but I'am of course interested and so I'm here to confirm that I appreciate your help

**Comment by mnicpt** [comment]
The update would be this: `const PayPalButton = paypal.Buttons.driver('vue', window.Vue);`

**Comment by mnicpt** [comment]
@realtebo Here is the full example with some other changes as well: ```
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>

  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.38/browser.js"></script>
  <script src="https://www.paypal.com/sdk/js?client-id=sb"></script>
</head>
<body>

  <div id="container">
    <app></app>
  </div>
  <script type="text/babel">
  
    const PayPalButton = paypal.Buttons.driver("vue", window.Vue);
  
    Vue.component("app", {
      template: `
        <paypal-buttons [props]="{
            createOrder: createOrder,
            onApprove: onApprove
        }"></paypal-buttons>
      `,
      components: {
        "paypal-buttons": PayPalButton,
      },
  
      computed: {
        createOrder: function (data, actions) {
          return actions.order.create({
            purchase_units: [
              {
                amount: {
                  value: "0.01",
                },
              },
            ],
          });
        },
        onAuthorize: function (data, actions) {
          return actions.order.capture();
        },
      },
    });
  
    var vm = new Vue({
      el: "#container",
    });
  
  </script>
</body>```

**Comment by z1haze** [comment]
paypal.Buttons is undefined..

**Comment by mnicpt** [comment]
@z1haze Have you loaded the JS SDK prior to executing the code above?

**Comment by Theorian** [comment]
Cannot change the amount it keeps defaulting 0.01
it's as if createOrder is not even getting called

`import Vue from "vue";

// import { PayPalButton } from "boot/paypal";
 const PayPalButton = paypal.Buttons.driver("vue", Vue);


export default {
  name: "Clubs",
  components: {

    "paypal-buttons": PayPalButton
  },

  computed: {

    createOrder(data, actions) {
      console.log(data);
      console.log(`-----------------------------------`);
      console.log(actions);
      return actions.order.create({
        purchase_units: [
          {
            amount: {
              value: "20.00"
            }
          }
        ]
      });
    },
    onAuthorize(data, actions) {
      console.log(data);
      console.log(`-----------------------------------`);
      console.log(actions);
      return actions.order.capture();
    }
  }
};
</script>
`

**Comment by souldia18** [comment]
Bomp

**Comment by z1haze** [comment]
> @z1haze Have you loaded the JS SDK prior to executing the code above?

Yes, i figured out my issue. For whatever reason you guys decided to change from `paypal.Button` to paypal.Buttons` when going from the checkout.js to the sdk. was confusing.

**Comment by z1haze** [comment]
@Theorian I wrote my own component that extends their vue driver. It actually worked pretty well. you just have to make sure you are loading the correct sdk (i had an issue there). I am happy to share it with you.

`<paypal-buttons env="sandbox" />`

```html
<template>
    <!-- eslint-disable-next-line vue/attribute-hyphenation  -->
    <paypal-buttons env="sandbox" :onApprove="paypalOnApprove" :createOrder="paypalCreateOrder" />
</template>

<script>
import Vue from 'vue';
import {mapState} from 'vuex';

export default {
    components: {
        'paypal-buttons': window.paypal.Buttons.driver('vue', Vue)
    },

    data () {
        return {
            paypalRequestId: ''
        };
    },

    computed: {
        ...mapState([
            'urls'
        ])
    },

    methods: {
        paypalCreateOrder () {

            return this.$store.dispatch('paypalCreate')
                .then(({data}) => {
                    this.paypalRequestId = data.requestID;

                    return data.token;
                });
        },

        paypalOnApprove (data) {
            const formData = {
                requestId           : this.paypalRequestId,
                billingAgreementFlag: false,
                paymentID           : data.paymentID,
                payerID             : data.payerID,
                isPayPalCredit      : false
            };

            return this.$store.dispatch('paypalSubmit', formData)
                .then(() => {
                    // do something
                });
        }
    }
};
</script>
```

this reminds me -- someone at paypal please update your lib so that we can pass the props down to the component the recommended way `prop-name` instead of `propName` is what is recommended -- so :create-order and :on-approve would be correct here

**Comment by Theorian** [comment]
I'm pretty sure I'm including the correct STK at the top of the file as
outlined in their documentation. I wish this actually helped me it seems
like because you're using VUEX and you didn't include everything. I'm not
even able to see where the data variable is coming from.

I really wish established companies would provide better documentation.

**Comment by z1haze** [comment]
@Theorian, sorry I didnt realize the a working example was something of demand, so I just threw this together. You are correct, as we are using vuex to handle the request to generate the token, but my backend implementation will likely vary that most/if not all other users implementations. We are making our requests _through_ cybersource to paypal.

But, as far as what happens in `this.$store.dispatch('paypalCreate')`, I am making a simple xhr request to my server, which makes some service calls to (cybersource in my case), who then on my behalf makes requests to paypal to setup a checkout session. The response returns a token, we parse the token from the response, and the token is what should be returned from the `paypalCreateOrder` callback method. The paypal SDK will use the return of this function to pass it into the popup url.

Hope this helps.

**Comment by cavid90** [comment]
How we can do so that checkout popup shows up after we get orderId from server ? Because at the moment it shows also if we get error from the server

**Comment by cavid90** [comment]
> @Theorian I wrote my own component that extends their vue driver. It actually worked pretty well. you just have to make sure you are loading the correct sdk (i had an issue there). I am happy to share it with you.
> 
> `<paypal-buttons env="sandbox" />`
> 
> ```
> <template>
>     
>     <paypal-buttons env="sandbox" :onApprove="paypalOnApprove" :createOrder="paypalCreateOrder" />
> </template>
> 
> <script>
> import Vue from 'vue';
> 
> export default {
>     components: {
>         'paypal-buttons': window.paypal.Buttons.driver('vue', Vue)
>     },
> 
>     data () {
>         return {
>             paypalRequestId: ''
>         };
>     },
> 
>     methods: {
>         paypalCreateOrder () {
>             return this.$store.dispatch('paypalCreate')
>                 .then(({data}) => {
>                     this.paypalRequestId = data.requestID;
> 
>                     return data.token;
>                 });
>         },
> 
>         paypalOnApprove (data) {
>             const formData = {
>                 requestId           : this.paypalRequestId,
>                 billingAgreementFlag: false,
>                 paymentID           : data.paymentID,
>                 payerID             : data.payerID,
>                 isPayPalCredit      : false
>             };
> 
>             return this.$store.dispatch('paypalSubmit', formData)
>                 .then(() => {
>                     // do something
>                 });
>         }
>     }
> };
> </script>
> ```
> 
> this reminds me -- someone at paypal please update your lib so that we can pass the props down to the component the recommended way `prop-name` instead of `propName` is what is recommended -- so :create-order and :on-approve would be correct here

How we can do so that checkout popup shows up after we get orderId from server ? Because at the moment it shows also if we get error from the server

**Comment by Artem-Schander** [comment]
For anyone looking for a dynamic solution without the need to always add the script tag to `head`.  
Put the following into the `beforeMount` lifecycle method in a parent component of which you want to use the `PaypalButtons` component.

```javascript
// ...
beforeMount() {
  const clientID = process.env.VUE_APP_PAYPAL_CLIENT_ID;
  const src = `https://www.paypal.com/sdk/js?client-id=${clientID}&currency=${this.currency}`;
  if (document.querySelectorAll(`head script[src="${src}"]`).length <= 0) {
    const script = document.createElement('script');
    script.setAttribute('src', src);
    script.onload = () => {
      const PaypalButtons = window.paypal.Buttons.driver('vue', Vue);
      Vue.component('PaypalButtons', PaypalButtons);

      this.$nextTick(() => {
        this.loading = false
        this.error = false
      })
    }
    script.onerror = () => {
      this.loading = false
      this.error = true
    }
    document.head.appendChild(script);
  } else {
    this.loading = false
    const PaypalButtons = window.paypal.Buttons.driver('vue', Vue);
    Vue.component('PaypalButtons', PaypalButtons);
  }
}
```
