### ISSUE TITLE
onShippingChange Data Property

### ISSUE THREAD

**Issue by paymentplugins** [paypal/paypal-checkout-components#1340]
### 📙 Describe the Issue
Doc Section: Shipping Changes
The docs incorrectly state that the data object provided in the `onShippingChange` callback contains the following property: `selected_shipping_method`.

The actual name of the property is `selected_shipping_option`.

https://developer.paypal.com/docs/checkout/integration-features/shipping-callback/

### 🔬 Minimal Reproduction
https://developer.paypal.com/docs/checkout/integration-features/shipping-callback/

### 😕 Actual Behavior
The actual property name is `selected_shipping_option` not `selected_shipping_method` as stated in the documentation.

**Comment by mstuart** [comment]
@amaclean2 can you take a look at ^^?

**Comment by oracle3987** [comment]
Fix to receivable to the merged master if any one rerouted any than to the master will loss accsess to the source also my loss badges and or be subjected to litigation please fix this is moniter your work . i do like your work and would want to keep your admission to contributions . please fix all issues to master lead then please email me for your inquiries to growing route for us to benift all that will fix for audits

**Comment by amaclean2** [comment]
Fix is submitted for review

**Comment by mstuart** [comment]
Looks like it was fixed! Awesome!! Ty @amaclean2 :D 

https://developer.paypal.com/docs/checkout/integration-features/shipping-callback/
