### ISSUE TITLE
[Bug] PP4MP sandbox: Payee(s) does not match expected merchant id 

### ISSUE THREAD

**Issue by jaynetics** [paypal/paypal-checkout-components#1354]
### 🐞 Describe the Bug

This is a follow up to https://github.com/paypal/paypal-checkout-components/issues/1178#issuecomment-645473538

We can no longer use paypal checkout in our staging pp4mp integration without passing ids explicitly.

It does work if we pass the IDs as suggested [here](https://github.com/paypal/paypal-checkout-components/issues/1178#issuecomment-636393552), but only for the first id combination encountered in an SPA.

The same integration also works fine in production without passing IDs (@ https://www.betterplace.me )

### 🔬 Minimal Reproduction

~~Click the paypal button here: https://www.bp42.me/ruhiger-abschied-fuer-waldemar/donate~~ (fixed by workaround now, let us know if you need a reproduction again)

### 😕 Actual Behavior

Uncaught Error: Payee(s) passed in transaction does not match expected merchant id. Please ensure you are passing merchant-id=* to the sdk url and data-merchant-id="SAMQKKKST7Z9S,NRXPPQMEFHRSE" in the sdk script tag. https://developer.paypal.com/docs/checkout/reference/customize-sdk/
    at buttons?commit=true&env=sandbox&....

### 🤔 Expected Behavior

No error.

### 🌍 Environment

- SDK version (`window.paypal.version`): "5.0.135"

**Comment by oracle3987** [comment]
I never gave my concent to do any of this none I never get a penny since day one . You are voilating me . I got recorded docs getting reveiwed I am going to get the ones that voilate the global government.

**Comment by jaynetics** [comment]
@bluepnume you've worked on a similar ticket in the past, can you provide any insights? is this a bug? or could this end up on production and make us unable to accept payments with our current integration?

**Comment by bluepnume** [comment]
@weihou can you please check into this? Do we have some public docs we can share with @jaynetics?

@jaynetics -- if you're passing multiple payees, you should also be passing those in `data-merchant-id`. That is required on both sandbox and production.

**Comment by jaynetics** [comment]
@bluepnume @weihou 

as stated above, *so far* it does work in production even without specifying the IDs as a data attribute.

the problem with specifying the IDs is that we are running a single page app. when the user browses between pages for different merchants, the ids of the first merchant will stick and the "does not match" error reoccurs. switching out the script tag does not fix this.

**Comment by bluepnume** [comment]
What is your client id, out of interest? Thanks.

**Comment by jaynetics** [comment]
stg `Ac7_XKXmbHm2zi5VXphrDkHzUQ-v8VOusvRuAAULtW-h72nmR2UjPh8eSQ-qHxpRZGN6-nHaXb95pzh9`
prd `AYiXLQVgLszolhHbiYAm2HZERgDF5BOPXG7i4m9BNsTTSdmWhVu2Np4_GqDJLrl5VA50VDAlMMpCMArb`

**Comment by iFlash** [comment]
I just made an integration for a marketplace where the cart of one specific user could hold items of various sellers. So loading the JS-SDK, how do I pass on all those merchant-id BY EMAIL (I do not have their merchant ids, only their emails).

**Comment by iFlash** [comment]
This is still buggy:

If I omit the merchant-id in the SDK-URL, Paypal will render five buttons (Paypal, Direct Debit, Credit Card, Giro Pay and Sofort). The payment works.

BUT: If I provide multiple merchant-ids like shown above, I will only see two buttons (Paypal and Credit Card) AND I will get an error after one the payment buttons is clicked:

_Error: Payee(s) passed in transaction does not match expected merchant id. Please ensure you are passing merchant-id=xyz or merchant-id=merchanta@mockup.de to the sdk url._

But the payee in transaction is one of the payees that I pass in the SDK-URL like this:

`<script src="https://www.paypal.com/sdk/js?client-id=AaVp6-tp-t44gKDHGMerqbVFU_F5KK6mb-IeGqPJR-pPin-2nbGUzKqUvqQ2YiN8xPOnjuBDheasflC7&amp;currency=EUR&amp;locale=de_DE&amp;merchant-id=*" data-merchant-id="merchanta@mockup.de,someothermerchant@emailofmerchant.de"></script>
`
