### ISSUE TITLE
[Bug] Pay Now button does nothing after patching ship method options with default address

### ISSUE THREAD

**Issue by stanimal** [paypal/paypal-checkout-components#1355]
### 🐞 Describe the Bug
When a user logs in, their default address is used to trigger the shipping change callback, where we can patch the resulting ship method options to the order.  Visually, the user sees the specified default ship method option in the dropdown.  If the user tries to click "Pay Now", the button does nothing.

If the user opens the dropdown and selects a different ship method option, they will then be able to click the Pay Now button to proceed. If the user desires the original default shipping method, they would have to select a different method, and once the form reloads, re-select the original method, before they can proceed.

The user, however, has no feedback on why clicking Pay Now does nothing, and we've seen many customers simply abandon their checkout.

### 🔬 Minimal Reproduction

1. Go to https://www.jewlr.com/products/JWL0018?sz=7.00&e1=foo&e2=bar and add the item to your cart
2. Click "Checkout"
3. Click "PayPal"
4. Select payment method, if prompted. When on the review screen, observe the shipping methods dropdown, and that a default is visually selected. (This assumes your default address is a US address.)
5. Click Pay Now.

### 😕 Actual Behavior

Clicking Pay Now does nothing. Only if you select another ship method option, will the user be able to proceed. There is no warning/messaging at all to the user on why the Pay Now button is not doing anything.

### 🤔 Expected Behavior

I would expect that clicking the Pay Now button would proceed in processing the checkout.

### 🌍 Environment

- Browser version: - Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS version: - Pop OS 20.04
- SDK version (`window.paypal.version`): - 5.0.135

### Affected browsers
What browser(s) are affected?

Testd only on Chrome

### ➕ Additional Context
Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.

**Comment by stanimal** [comment]
This issue seems to have arisen after this other issue was resolved/released: https://github.com/paypal/paypal-checkout-components/issues/1308

**Comment by gregjopa** [comment]
@stanimal thank you for reporting this issue. We are actively working on a fix.

**Comment by amaclean2** [comment]
I'm working on a fix for this. It'll be out soon

**Comment by amaclean2** [comment]
@stanimal can you check if you can still reproduce? I think this issue is fixed.
