### ISSUE TITLE
Click on Paypal smart button does not do anything on Mobile App (Webview)

### ISSUE THREAD

**Issue by bizready** [paypal/paypal-checkout-components#1356]
### 🐞 Describe the Bug
I have Quasar(VueJS) based app and the PayPal button works fine on the browser. Paypal button does NOT respond on the mobile app (Cordova version). No error message at all.
###

<img width="396" alt="Screen Shot 2020-07-02 at 10 41 35 PM" src="https://user-images.githubusercontent.com/63766875/86426286-49b62e00-bcb5-11ea-836c-b3cd83c4d25e.png">

```
<template>
  <q-page>
    <div class="q-pa-xl">
      <div
        class="col justify-center"
        v-if="!isPaymentComplete"
        id="paypal-button-container"
        ref="paypal"
      ></div>
    </div>
  </q-page>
</template>

<script>

export default {
  name: 'Payment',
  data () {
    return {
      isPaymentComplete: false,
      paymentAmount: 0,
      paymentFee: 0,
      serviceId: '',
      sessionIds: ''
    };
  },
  mounted () {
    console.log('mounted start');
    this.paymentAmount = this.$router.currentRoute.params.paymentAmount;
    this.paymentFee = this.$router.currentRoute.params.paymentFee;
    this.serviceId = this.$router.currentRoute.params.serviceId;
    this.sessionIds = this.$router.currentRoute.params.sessionIds;

    const script = document.createElement('script');
    script.src =
      'https://www.paypal.com/sdk/js?client-id=Ab7NisBf7fowrKaozO2lgGhI8f2-u8LIOEQh3sq-kVUfVdzYEYmxYhfWROBk2Xh9i51RGSWseF7ShX08';
    script.addEventListener('load', this.setLoaded);
    document.body.appendChild(script);
  methods: {
    setLoaded () {
      window.paypal
        .Buttons({
          style: {
            layout: 'vertical',
            color: 'white',
            shape: 'rect',
            label: 'paypal',
            size: 'responsive'
          },
          createOrder: (data, actions) => {
            // BELOW LOG IS NOT APPEARING in the console!!
            console.log('Payment:createOrder');
            return actions.order.create({
              // given_name, email_address
              purchase_units: [
                {
                  amount: {
                    value: this.paymentAmount + this.paymentFee
                  }
                }
              ]
            });
          },
          onApprove: async (data, actions) => {
            console.log('onApprove', JSON.stringify(actions));
            //call to server-side
          },
          onError: err => {
            console.log('error:', err);
          }
        })
        .render(this.$refs.paypal);
    },
  }
};
</script>
```

**Comment by bizready** [comment]
The above behavior is with Cordova based app. I wanted to see if issue exists in Capacitor based code. Quasar allows export to Cordova or Capacitor. I exported to Capacitor and the good news is that I see much better progress, but got stuck on 'Pay Now' button. No error when I click on the button

Sees screenshot below.
<img width="1068" alt="Screen Shot 2020-07-03 at 10 06 29 AM" src="https://user-images.githubusercontent.com/63766875/86476565-c88e8380-bd14-11ea-88a6-cc5270e4411c.png">

**Comment by bizready** [comment]
I do see the following message in the console after multiple clicks - 

[log] - Payment:createOrder
2020-07-03 10:30:35.834445-0400 App[9144:3681878] [Common] _BSMachError: port 14667; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2020-07-03 10:32:48.997833-0400 App[9144:3681878] [Common] _BSMachError: port 1350b; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"

**Comment by bluepnume** [comment]
Sorry, we don't currently support cordova apps with this integration.
