### ISSUE TITLE
No back button after choosing debit/credit-card

### ISSUE THREAD

**Issue by webdeb** [paypal/paypal-checkout-components#1358]
### 🐞 Describe the Bug
Paypal Smart Buttons, open the Debit-Credit Card dialog. It replaces all the buttons with the debit/credit dialog fields.
The problem is, the user cannot just cancel this dialog, and use something different.

### 🔬 Minimal Reproduction
https://developer.paypal.com/demo/checkout/#/pattern/client

### 😕 Actual Behavior
There is no way to close the debit/credit card dialog and use another payment method like paypal itself.

### 🤔 Expected Behavior
There is at least a Back-Button

**Comment by cezgit** [comment]
Having the same problem. One way to go around it is to have a custom select for Paypal or Credit card and show the correct Paypal button based on the user selection. But that's a workaround not a fix.

**Comment by canidas** [comment]
Having the same problem. This is not very user friendly and could lead to bounce rate.

**Comment by mnicpt** [comment]
Thank you for your feedback.  I will make sure this gets added to our backlog and will respond back here once it is in production.

**Comment by mstuart** [comment]
https://github.com/paypal/paypal-checkout-components/issues/1417 was filed recently. Closed that one in favor of this. Just wanted to reference it.

**Comment by Mansi1** [comment]
is it possible that it will open in a new window, than all checkouts will have the same flow ...

**Comment by mstuart** [comment]
This was released today! Woohoo 🎉
