### ISSUE TITLE
Create example using `create-react-app`

### ISSUE THREAD

**Issue by pedroapfilho** [paypal/paypal-checkout-components#1361]
### 🚀 Feature Proposal

The current example uses an implementation of `react` that is not very useful and doesn't work well with `create-react-app`. Could you create an example using it?

### Motivation

Very hard to implement Smart Buttons on a `react-app`

**Comment by mnicpt** [comment]
Thank you @pedroapfilho .  I have added this to our backlog and as an added note, there will be docs available soon regarding implementing the PayPal buttons using React, Angular and Vue.js.  I will be sure to post the link here when they become available.

**Comment by pedroapfilho** [comment]
Thanks!

**Comment by claeusdev** [comment]
hey @pedroapfilho @mstuart @mnicpt I'd like to work on this, could you please provide some extra details. A bit lost on the context of the issue. Thanks

**Comment by pedroapfilho** [comment]
@mstuart so, is this in progress, or the development didn't start yet?

**Comment by mnicpt** [comment]
@pedroapfilho This hasn't been started yet.  Here is the link to the docs I mentioned above though: https://developer.paypal.com/docs/business/checkout/configure-payments/single-page-app/#

**Comment by pedroapfilho** [comment]
I feel like the problems with the current implementation are:

1. We have to check if PayPal is available in the environment before we do anything with it, so using typescript is a nightmare.
2. We don't have examples on how it works with `styles`
3. We don't have implementations where the user can change its currency, so the script would change too

**Comment by mstuart** [comment]
Sorry @claeusdev, I mislabeled this w/ the hacktoberfest labels. I think we need to re-group and figure out what we want to do w/ this first. Let me know if that's okay.

**Comment by gregjopa** [comment]
Hi everyone, we just released the library react-paypal-js to make it easy to integrate PayPal with React: https://github.com/paypal/react-paypal-js. It should be pretty straight forward to integrate into a create-react-app application. Let me know if you have any questions about the new library.
