### ISSUE TITLE
Integrating React with paypal checkout (v2)

### ISSUE THREAD

**Issue by Richabhu** [paypal/paypal-checkout-components#1367]
I am integrating PayPal checkout with react using SDK. The seller currency is USD. I am testing it with an Indian sandbox account. The transaction is successful with all other accounts except for Indian Accounts. In all other cases, the sandbox does the currency conversion and pays the amount accordingly except in Indian currency which says the seller doesn't accept payment in your currency. What might be the possible issue? Any suggestions would be highly appreciated.

**Comment by mstuart** [comment]
Hi @Richabhu, thanks for filing this issue! Can you share a PayPal Checkout URL (w/ a `token` query string parameter) or any request with a `paypal-debug-id` response header? I wasn't able to reproduce the issue, but I might not have it set up correctly. Let me know, thanks!

**Comment by mstuart** [comment]
Hi @Richabhu, going to close this ticket for now. Feel free to re-open it once you have a token or paypal-debug-id response header, then we can take a look. Thanks!
