### ISSUE TITLE
[Feature] Attribute for extension detection of smart button

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout-components#1368]
### 🚀 Feature Proposal

Add an attribute to the SPB container

Would need to be done in both v4 and v5 buttons.

### Motivation

This would allow extensions (e.g. Honey) to begin detecting the SPB and acting accordingly. 

### Example

```html
data-paypal-smart-button-version="x.y.z"
```

**Comment by mstuart** [comment]
Tracking as DTCHKINT-113 internally

**Comment by mnicpt** [comment]
@bluepnume Was it confirmed why Shopify was putting the SPB inside another iframe?

**Comment by gregjopa** [comment]
This attribute has been successfully added to both v4 and v5. Closing.
