### ISSUE TITLE
[Bug] German Error Message Causes Scrolling

### ISSUE THREAD

**Issue by rajmondx** [paypal/paypal-checkout-components#1389]
### 🐞 Describe the Bug

The german text is too big for "paypals message box" which causes it to scroll

![120-paypal-scrolling](https://user-images.githubusercontent.com/56911973/88290782-8e9f1480-ccf7-11ea-9b26-d05d28f31ea0.gif)

It is caused by `height:160px` in "paypals message box":

![image](https://user-images.githubusercontent.com/56911973/88290829-a1194e00-ccf7-11ea-98d4-156c7086be4b.png)

### 🔬 Minimal Reproduction

1. Set Browser Language to German
2. Choose Credit Card (`fundingSource = 'card'`)
3. Write some non-sense (in order to fail the checkout at first try) 

### 😕 Actual Behavior

The german text is too big for "paypals message box" which causes it to scroll

### 🤔 Expected Behavior

No scrolling at all

### 🌍 Environment

SDK version (`window.paypal.version`): 5.0.138

### Affected browsers

Same on those browsers (didnt test more):

- Chrome
- Firefox
- Edge

### ➕ Additional Context

- Using [ngx-paypal](https://www.npmjs.com/package/ngx-paypal) but it doesnt matter because same would happen if I would load paypals buttons manually.

**Comment by mstuart** [comment]
Hi @rajmondx, thanks for letting us know about this issue!

**Comment by khanghoang** [comment]
Noted, I create a ticket for it.
