### ISSUE TITLE
[Bug] MSP with Hosted fields [error in xhr request to graphql endpoint] 

### ISSUE THREAD

**Issue by Arvind6353** [paypal/paypal-checkout-components#1394]
Hi Team ,
Am getting the below error in sandbox , when trying out MSP with Hosted fields (i.e pass multiple merchantIds in the script).
`Access` to XMLHttpRequest at 'https://www.sandbox.paypal.com/graphql' from origin 'http://localhost:3500' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested `resource`

![image](https://user-images.githubusercontent.com/23059431/88454261-e2426700-ce8b-11ea-96c6-1e16a9449b77.png)

Script - 
<script type="application/javascript" src="https://www.paypal.com/sdk/js?client-id=AVajOV0VnH8tD0mWYqeWH22uB-DOIWPO5yRzmrqTCOeWx0oopJfeZl6NiL1NAITC3mKiTY1XuAT_mXeh&amp;commit=true&amp;components=buttons,hosted-fields&amp;debug=false&amp;currency=USD&amp;intent=capture&amp;merchant-id=*&amp;locale=en_DE&amp;buyer-country=DE" id="ppscript" data-client-token="eyJicmFpbnRyZWUiOnsiYXV0aG9yaXphdGlvbkZpbmdlcnByaW50IjoiYTVmNmFmMjUwOTgwZWM2NDA2ZjMwNWY2YTM5YTc0ZjBiNDU0MGRmMWM1MTRlZTFkNmZmZWM1MzU3Zjc4ZDY5Y3xtZXJjaGFudF9pZD1yd3dua3FnMnhnNTZobTJuJnB1YmxpY19rZXk9NjNrdm4zN3Z0MjlxYjRkZiZjcmVhdGVkX2F0PTIwMjAtMDctMjVUMDk6NTY6NDMuNDU2WiIsInZlcnNpb24iOiIzLXBheXBhbCJ9LCJwYXlwYWwiOnsiYWNjZXNzVG9rZW4iOiJBMjFBQUYyLVcxc21nT2pmZ29yYXl2V3d4WGxSNVF5TEl0ZFpPOGlMdkxTZDV1WjlHS3RxYTd0cjNIWGMtU2E5SENSQnZuRlFZZFBpTDBrUkVhU0dUOHN0Wko0SklfWTVBIn19" data-merchant-id="Z8CBBYH86KX3C,3M5SFHD87UCNA"></script>

**Comment by mstuart** [comment]
Hi @Arvind6353, I tried this locally and removed the extra `merchant-id=*` parameter and it seems to work. I'm not sure why adding that extraneous parameter causes CORS to not work correctly. Can you try that?

**Comment by Arvind6353** [comment]
@mstuart , Yes I removed this parameter and it is working fine . And this is happening with hosted-fields alone. Am able to render Buttons with merchant-id=* for MSP.

**Comment by mstuart** [comment]
Awesome. What does `merchant-id=*` do?

**Comment by weihou** [comment]
try to host the page on `localhost.merchant.com` (with domain name).

**Comment by Arvind6353** [comment]
@weihou It would be good , if this can be updated on docs, as it's not mentioned anywhere else. Thanks.

**Comment by mstuart** [comment]
Any reason plain localhost couldn't work?

**Comment by Arvind6353** [comment]
@mstuart this was because there is a validator plug in that is being used to find if an origin is a valid Url or not. And this plug in is returning for localhost origin.

soln for localhost is to add to  require_tld: false   - Reference - https://github.com/validatorjs/validator.js/issues/754
 validator.isURL(clientOrigin, { allow_underscores: true , require_tld: false})

**Comment by mstuart** [comment]
Nice! Assuming that PR is merged and released, would this issue be resolved?

**Comment by Arvind6353** [comment]
Yes @mstuart  I think this would solve the issue.

**Comment by Arvind6353** [comment]
@weihou  I still see this issue
