### ISSUE TITLE
[Feature] Document and validate vault=true and vault=false

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout-components#1396]
### 🚀 Feature Proposal

Right now it's kind of a not-well documented requirement that:

- BA or BA+Purchase: you must pass `vault=true` to the SDK
- Purchase: you must pass `vault=false` to the SDK

https://developer.paypal.com/docs/checkout/reference/customize-sdk/#vault

We should:

- Do a better job documenting that.
- Add validation which fails in local, stage, and sandbox
- Add instrumentation which works in all envs, and goes to the integration issues dashboard.

Note: any new validation *can not error out in prod*, since I believe we have plenty of non-standard integrations which are not correctly passing `vault`.

### Motivation

Make integrations more consistent, and provide good validation errors and warnings when they can not be.

### Example

`https://www.paypal.com/sdk/js?client-id=sb&vault=true`
`https://www.paypal.com/sdk/js?client-id=sb&vault=false`

**Comment by bluepnume** [comment]
Only 0.92 confidence @issue-label-bot?

**Comment by mstuart** [comment]
It's AI. okay?
