### ISSUE TITLE
[Bug] SameSite Cookie blocked on Chrome: Payment not possible

### ISSUE THREAD

**Issue by MiladSadinam** [paypal/paypal-checkout-components#1406]
### 🐞 Describe the Bug
Our company offers a booking plugin which our customers can integrate on their website. Part of the booking process is the Paypal Plus Checkout Container (https://www.paypalobjects.com/webstatic/ppplus/ppplus.min.js). One of our customers integrated our plugin (with the Paypal Plus Checkout Container) using the Wix CMS (Wix.com). In Wix this can only be done using an iFrame which has internally another domain than the outer website. Because of this the Paypal plus Checkout Container cannot set the "paypalplus_session_v2" cookie. Thus, no payments are possible.

So, the Paypal Plus Container is opened in a iFrame with the domain https://www-alpenverein-hessen-de.filesusr.com. But the outer page has a different domain https://www.alpenverein-hessen.de/. Because of the Wix CMS no other solution is possible.

### 🔬 Minimal Reproduction
Visit https://www.alpenverein-hessen.de/dr-plano . Choose the first item in the list. Fill out the form (its German. Just choose any value in each input). Continue to next screen which will show the Paypal Plus Checkout Container. Choosing Paypal on that screen. Clicking on the Pay Button bellow will throw a javascript error. This is because the Paypal Plus Checkout Container could not set the "paypalplus_session_v2" cookie and thus does not work properly:
![image](https://user-images.githubusercontent.com/8689490/90005869-27da9e80-dc98-11ea-9e2b-1ae1cf9e853e.png)

### 🤔 Expected Behavior
I expect that the Paypal Plus Checkout Container does work included in an iFrame with another domain.

### 🌍 Environment

Tested on latest Chrome Version 84.0.4147.125

**Comment by Gvade** [comment]
Still can't use Payment Wall inside an iframe. The Chromium engine blocks setting the iframe's cookie `paypalplus_session_v2` values.

**Comment by Gvade** [comment]
Not a brilliant solution, but a temporary workaround:
```
const cookieDesc = Object.getOwnPropertyDescriptor(Document.prototype, 'cookie') ||
                Object.getOwnPropertyDescriptor(HTMLDocument.prototype, 'cookie');
            if (cookieDesc && cookieDesc.configurable) {
                Object.defineProperty(document, 'cookie', {
                    get: function () {
                        return cookieDesc.get.call(document);
                    },
                    set: function (val) {
                        const valueLower = val.toLowerCase();
                        if (!valueLower.endsWith(";")) {
                            val += ";";
                        }
                        if (!valueLower.includes("secure")) {
                            val += " secure;"
                        }
                        if (!valueLower.includes("samesite")) {
                            val += " samesite=None;"
                        }
                        cookieDesc.set.call(document, val);
                    }
                });
            }
        }
