### ISSUE TITLE
[Bug] JavaScript SDK throws error: PayPal Payments SDK script not present on page

### ISSUE THREAD

**Issue by komape** [paypal/paypal-checkout-components#1412]
I just tried to set up a page with Smart Payment Buttons to my side but I constantly get this error:

![image](https://user-images.githubusercontent.com/25869589/90650492-3e569c00-e23c-11ea-8232-60bbdc41efc9.png)

I just followed [this guide here](https://developer.paypal.com/docs/checkout/integrate/#2-add-the-paypal-javascript-sdk-to-your-web-page). And my page really just contains the following code (obviously the client id is just a placeholder here):

```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>

<body>
    <script
        src="https://paypal.com/sdk/js?debug=true&currency=EUR&client-id=<my_client_id>"></script>

    <div id="paypal-button-container"></div>

    <script>
        paypal.Buttons().render('#paypal-button-container');
    </script>
</body>

</html>
``` 

What am I doing wrong? Am I missing something?

**Comment by komape** [comment]
This error occurs both in Firefox and Chrome.

**Comment by komape** [comment]
Ok, I found out that I need to add `www` as described in [this issue](https://github.com/paypal/paypal-checkout-components/issues/1219). Please fix this! Or give a hint in your documentation.

By the way, [here](https://developer.paypal.com/docs/payflow/express-checkout/sale/#javascript) it's still documented without `www`.

**Comment by gregjopa** [comment]
@komape thanks for bringing this to our attention. The doc definitely needs the `www` added. We will get this fixed asap.

**Comment by elizabethmv** [comment]
Thanks again for raising this issue @komape, this has now been fixed and can be confirmed [here](https://developer.paypal.com/docs/payflow/express-checkout/sale/#javascript).
