### ISSUE TITLE
Uncaught Error: Order could not be captured

### ISSUE THREAD

**Issue by allanascano-otus** [paypal/paypal-checkout-components#1420]
I successfully implemented Smart Buttons on my website. I am now trying to integrate the same using webview on android.

I found a library that will support paypal on webviews - https://github.com/braintree/popup-bridge-android

Problem is, when submitting a payment, Im getting "**Uncaught Error: Order could not be captured", source: https://www.sandbox.paypal.com/smart/buttons?style.label=pay&style.layout=vertical&style.color=gold&style.shape=rect&style.tagline=false&style.height=55&components.0=buttons&locale.country=US&locale.lang=en&sdkMeta=eyJ1cmwiOiJodHRwczovL3d3dy5wYXlwYWwuY29tL3Nkay9qcz9jbGllbnQtaWQ9QVF5aVlCUk9La3Ffcm85X1hDeDRSWUtVQ2RvZ2Z0cnNpR1dXYnRhdFNMQ0lxTk1PTXl4akMwWHpja0ZtOUZWTEtLa2t3VTduR1JHUGg0aFgmY3VycmVuY3k9UEhQJm1lcmNoYW50LWlkPXNiLTd0Y2RjMTE4NjkxMEBidXNpbmVzcy5leGFtcGxlLmNvbSIsImF0dHJzIjp7fX0&clientID=AQyiYBROKkq_ro9_XCx4RYKUCdogftrsiGWWbtatSLCIqNMOMyxjC0XzckFm9FVLKKkkwU7nGRGPh4hX&sessionID=6a1a504dd5_mdy6ntg6mjk&buttonSessionID=44da5a8949_mdy6ntg6mjk&env=sandbox&fundingEligibility=eyJwYXlwYWwiOnsiZWxpZ2libGUiOnRydWUsInZhdWx0YWJsZSI6dHJ1ZX0sInBheWxhdGVyIjp7ImVsaWdpYmxlIjpmYWxzZSwicHJvZHVjdHMiOnsiZmxleCI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJwYXlJbjQiOnsiZWxpZ2libGUiOmZhbHNlfX19LCJjYXJkIjp7ImVsaWdpYmxlIjp0cnVlLCJicmFuZGVkIjp0cnVlLCJ2ZW5kb3JzIjp7InZpc2EiOnsiZWxpZ2libGUiOnRydWUsInZhdWx0YWJsZSI6dHJ1ZX0sIm1hc3RlcmNhcmQiOnsiZWxpZ2libGUiOnRydWUsInZhdWx0YWJsZSI6dHJ1ZX0sImFtZXgiOnsiZWxpZ2libGUiOnRydWUsInZhdWx0YWJsZSI6dHJ1ZX0sImRpc2NvdmVyIjp7ImVsaWdpYmxlIjpmYWxzZSwidmF1bHRhYmxlIjp0cnVlfSwiaGlwZXIiOnsiZWxpZ2libGUiOmZhbHNlLCJ2YXVsdGFibGUiOmZhbHNlfSwiZWxvIjp7ImVsaWdpYmxlIjpmYWxzZSwidmF1bHRhYmxlIjp0cnVlfSwiamNiIjp7ImVsaWdpYmxlIjpmYWxzZSwidmF1bHRhYmxlIjp0cnVlfX19LCJ2ZW5tbyI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJpdGF1Ijp7ImVsaWdpYmxlIjpmYWxzZX0sImNyZWRpdCI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJzZXBhIjp7ImVsaWdpYmxlIjpmYWxzZX0sImlkZWFsIjp7ImVsaWdpYmxlIjpmYWxzZX0sImJhbmNvbnRhY3QiOnsiZWxpZ2libGUiOmZhbHNlfSwiZ2lyb3BheSI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJlcHMiOnsiZWxpZ2libGUiOmZhbHNlfSwic29mb3J0Ijp7ImVsaWdpYmxlIjpmYWxzZX0sIm15YmFuayI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJwMjQiOnsiZWxpZ2libGUiOmZhbHNlfSwiemltcGxlciI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJ3ZWNoYXRwYXkiOnsiZWxpZ2libGUiOmZhbHNlfSwicGF5dSI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJibGlrIjp7ImVsaWdpYmxlIjpmYWxzZX0sInRydXN0bHkiOnsiZWxpZ2libGUiOmZhbHNlfSwib3h4byI6eyJlbGlnaWJsZSI6ZmFsc2V9LCJtYXhpbWEiOnsiZWxpZ2libGUiOmZhbHNlfSwiYm9sZXRvIjp7ImVsaWdpYmxlIjpmYWxzZX0sIm1lcmNhZG9wYWdvIjp7ImVsaWdpYmxlIjpmYWxzZX19&platform=mobile&experiment.oldWalletDesign=false&flow=purchase&currency=PHP&intent=capture&commit=true&merchantID.0=sb-7tcdc1186910@business.example.com** " 

When opening the same html content on a PC browser, the transaction was successful. Im only getting the error when its on an android webview. 

Im not sure if its a bug of braintree/popup-bridge-android (I already submitted an issue and still waiting for a response)

Im just getting desperate, any clues / leads on how to solve this will be a big help. Thanks.

**Comment by mnicpt** [comment]
@CodyEngel Can you take a look at this or assign to someone on the Android team?

**Comment by CodyEngel** [comment]
@allanascano-otus, it looks like you have opened an issue on the [Braintree library](https://github.com/braintree/popup-bridge-android/issues/29). I can follow-up with their team to find out more information, we'd likely want to close out this issue though.

**Comment by allanascano-otus** [comment]
thank you @CodyEngel . One last question, can I force the inline popup as seen here 
![success](https://user-images.githubusercontent.com/6380178/92835584-02af8c00-f40e-11ea-9302-bf8621ae4e17.png) instead of the new window popup when clicking the Pay with Paypal button?

**Comment by mostadev** [comment]
I've The same issue and tried different browsers to solve it and till now i can't find any helpful solution please take care of this asap

**Comment by CodyEngel** [comment]
@allanascano-otus I'm chatting with one of the engineers that works on `paypal-checkout-components`, can you update this issue to follow the [bug template](https://github.com/paypal/paypal-checkout-components/issues/new?assignees=&labels=bug&template=1-bug-report.md&title=%5BBug%5D+Bug+report)? Doing so will give us more details so we can determine the best resolution/next steps.

**Comment by dredd00** [comment]
I'm having exactly the same issue using paypal checkout button, popup bridge for android webview.

**Comment by allanascano-otus** [comment]
@dredd00 

I gave up on popup bridge webview. I used Chrome Custom Tab to make paypal work on mobile.

**Comment by mstuart** [comment]
We identified and fixed an issue w/ popup bridge integrations yesterday afternoon. If anyone's reading this, can you try again? If it's the same issue (assuming so w/ the information here), it shouldn't be an issue any longer. Thanks!

**Comment by Miguel-GS** [comment]
I still have the same problem in Chrome/Windows and Safari/Mac.
The problem only occurs when card fields open in a form under the payment buttons instead a popup.
I don´t  understand why browsers have different behaviors. Safari/Mac and Chrome/Windows doesn't open popup window and the capture fails. Chrome and Firefox on Mac open a popup window and the payment finishes successfuly.

**Comment by Spein** [comment]
Got the same issue on Chrome/Windows.. It appeared all of a sudden. I noticed that i've found the API calls in my dev dashboard, but the payment still not captured at the end of the process... Does anyone have any news about that?

**Comment by newearthmartin** [comment]
Hi I'm having the same error using the paypal js directly (not this library). The errors don't occur always, but sporadically. I can't reproduce it in my dev environment. There is something wrong with the core paypal js buttons. PLEASE look at this. **PayPal support is very slow to understand that there is something wrong with their button js library that is causing merchants to lose payments**.

**Comment by glucka** [comment]
@newearthmartin i have the same issue with smart buttons and crefit card payments. But not always! Terrible :(

**Comment by newearthmartin** [comment]
This issue is still very much active https://github.com/paypal/paypal-checkout-components/issues/1521#issuecomment-847685174
