### ISSUE TITLE
[Bug] Bug report - Type Error: Cannot read property 'paypal' of ...

### ISSUE THREAD

**Issue by domtripodi** [paypal/paypal-checkout-components#1425]
### 🐞 Describe the Bug
When clicking the first paypal smart button (not credit/debit button) - it randomly produces the error shown below:

![image](https://user-images.githubusercontent.com/24926301/92991489-3f20dc00-f523-11ea-8dcf-4c9d0d5e289f.png)

It does not produce this error every time - sometimes it does successfully go to the paypal gateway. The error is happening randomly more and more. 

### 🔬 Minimal Reproduction
There is no clear method to reproduce it - I just have the buttons set up as per the tutorial, rendered on a page with implemented callbacks. It happens at random and has never happened once up until today. I couldn't seem to reproduce it on another browser other than Chrome.

### 😕 Actual Behavior
Click the main paypal smart button and it errors out and dies silently. 

### 🤔 Expected Behavior
Click the main paypal smart button and it goes to the checkout gateway.

### 🌍 Environment

- Browser version: - Chrome 85.0.4183.102
- OS version: - MacOS Catalina 10.15.5

### Affected browsers
What browser(s) are affected?

- Chrome

**Comment by kklark** [comment]
Having exactly the same issue

**Comment by bluepnume** [comment]
This should now be resolved. Please let me know if you see this reoccurring. Thanks!
