### ISSUE TITLE
[Bug] Bug report

### ISSUE THREAD

**Issue by hicreate** [paypal/paypal-checkout-components#1433]
### 🐞 Describe the Bug

When using the Paypal Smart Buttons with Paypal JS in an inappbrowser window through Cordova, we get CORS errors preventing internal Paypal windows opening as part of the login/checkout process. These errors have started in the last fortnight (checked first week of September 2020 no issue, checked today and find the issue)

![SharedScreenshot](https://user-images.githubusercontent.com/55043779/93761446-b4686d00-fc05-11ea-8a2b-ca76803eb97f.jpg)

If we close that window there is actually a second window behind it that shows what is expected and the transaction can be completed.

### 🔬 Minimal Reproduction
Describe steps to reproduce. If possible, please, share a link with a minimal reproduction.

### 😕 Actual Behavior
A clear and concise description of what is happening. Please include console logs during the time of the issue, especially error messages.

On login to paypal in webView using the paypal JS sdk we get an error with a CORS console error stating "Refused to display 'https://www.paypal.com/signin/phone-confirmation?intent=xoToast&amp;flowId=85H61230ET769035T' in a frame because it set 'X-Frame-Options' to 'sameorigin'."

### 🤔 Expected Behavior

On login to paypal on webView the user is redirected to the payyment/order details screen

### 🌍 Environment

- Browser version: -
- OS version: - Android 10
- SDK version (`window.paypal.version`): - https://www.paypal.com/sdk/js

### Affected browsers
What browser(s) are affected?

### ➕ Additional Context
If I login successfully to paypal with my paypal email and password the error screen only shows on the first login. On subsequent logins/transactions, the error screen doesn't show at all and directs me straight into the order/payment screen as expected. It leads me to think it is how cookies are being handled/set as it it is on initial signin only?

**Comment by aminnoura** [comment]
This issue is still there :-(

**Comment by aminnoura** [comment]
still not solved
