### ISSUE TITLE
[Bug] Bug report

### ISSUE THREAD

**Issue by ToddHoff** [paypal/paypal-checkout-components#1445]
### 🐞 Describe the Bug

Uncaught Error: Window closed

js?client-id=XXXX&currency=USD:2 unhandled_error 
{err: "Error: Window closed↵    at https://www.paypal.com…XXX&currency=USD:2:10145", timestamp: "1601480886165", referer: "XXX", uid: "XXX", env: "production"}
env: "production"
err: "Error: Window closed↵    at https://www.paypal.com/sdk/js?client-

The code had been working fine, now it's failing for no apparent reason.

### 🔬 Minimal Reproduction
Describe steps to reproduce. If possible, please, share a link with a minimal reproduction.

Try to use the client SDK to create a payment.

### 😕 Actual Behavior
A clear and concise description of what is happening. Please include console logs during the time of the issue, especially error messages.

The payment buttons do not show. 
![Screen Shot 2020-09-30 at 8 50 50 AM](https://user-images.githubusercontent.com/1286318/94709838-fd51ad00-02fa-11eb-8d70-4fd920822632.png)

### 🤔 Expected Behavior

The payment buttons should display so the user can make a payment.

### 🌍 Environment

- Browser version: -
- OS version: -
- SDK version (`window.paypal.version`): -

### Affected browsers
What browser(s) are affected?

Just tested with Chrome.

### ➕ Additional Context
Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.

**Comment by misswayua** [comment]
I have the same problem but not in production but in sandbox.
