### ISSUE TITLE
[Documentation] Documentation issue report

### ISSUE THREAD

**Issue by jousi592** [paypal/paypal-checkout-components#1450]
### 📙 Describe the Issue
No description of all possible actions within lifecycles (onApprove, createOrder, ...).

### 🔬 Minimal Reproduction
https://github.com/paypal/paypal-checkout-components/tree/master/docs

### 😕 Actual Behavior
I cant find any information on what possible actions I can use within each of the lifecycles.

### 🤔 Expected Behavior
There should be a documentation of all possible actions within each lifecycle.

### ➕ Additional Context
I am unsuccessfully trying to find an action within the onApprove/onAuth lifecycles that would allow me to cancel the payment if I find out the user has chosen a different shipping address country from what they chose when selecting their shipping destination. I am using this information to calculate shipping costs so that I can add them to the basket total. If the user chooses a different country within the PayPal shipping address, I need to inform them that the price of shipping will change and that should re-view it again.

**Comment by gregjopa** [comment]
Hi @jousi592, we recently released this JS SDK reference doc that may help: https://developer.paypal.com/docs/business/javascript-sdk/javascript-sdk-reference/#buttons

There’s also an onShippingChange callback that seems like what you’re looking for: https://developer.paypal.com/docs/checkout/integration-features/shipping-callback/

**Comment by jousi592** [comment]
Hi there, indeed the shipping callback does seem like the correct solution, thank you for pointing me to it!

I do still think that there should be a more thorough explanation of all possible actions within each lifecycle. I had to dig into the src code and other materials to get some answers.

**Comment by nbierdeman** [comment]
@jousi592 Would you mind sharing what information you had to dig through the src code and other materials to find? I'm going to work on the documentation, and would really appreciate your input. Thanks!

**Comment by jousi592** [comment]
I will be glad to help.
What I had trouble finding, as my comment above says, were all possible actions I could take within each "lifecycle" (not sure what you call it), since I am usually not one to use pre-build solutions, I like to be able to customize my functionality. I think your your BE integration is thorough, but the SDK FE integration lacks a little more depth.
For example when looking at the most basic part of the integration: https://developer.paypal.com/docs/checkout/integrate/
When I scroll down to 4., I see that I should use `actions.order.create()` to create the order, but I dont see what else has the order object to offer. There is a link to the Order curl request, but that doesnt tell me much about the FE SDKs functionality. I like there to be a link to the breakdown of the order object and all its capabilities. Also, I know you can get to it through some clicks within the BE API docs, however it would be handy to have the purchase_units object description a little more easily accessible when going through the basic integration.

This is one example of the top of my head, but basically, I feel like the FE SDK is not covered in as much detail as the BE API, or at least it is not explained how the two are similar/same in naming and other aspects.

PS: Since I have the chance here to talk to you here, I am having trouble with the developer.paypal.com/developer application, I seem to be getting `TypeError: c.render is not a function` and `Deprecated, stop using this method` on almost every action I take. I dont have ADblock running on the page and I am using Chrome 86.0.4240.75. However when I try it on Firefox, I dont get these errors and the application runs smoothly.

**Comment by nbierdeman** [comment]
@jousi592 Thanks for the feedback! We appreciate it.

For the "scroll down to 4" bit, there's a link that goes to https://developer.paypal.com/docs/api/orders/v2/#orders_create for the options you can pass w/ `actions.order.create()`.

If you're still getting an error in Chrome, please head on over to https://developer.paypal.com/support/ for support.
