### ISSUE TITLE
NuxtJS - Error: zoid destroyed all components

### ISSUE THREAD

**Issue by ceronem** [paypal/paypal-checkout-components#1451]
Hi guys, I'm having a problem using this SDK with NuxtJs. The problem only occurs during client-side rendering. As a workaround I call the paypal.Buttons.render() function with a delay of 500 ms.
Loaded script inside nuxt.config.js
```
  head: {
    script: [
      {
        hid: 'paypal',
        src: 'https://www.paypal.com/sdk/js?currency=EUR&components=buttons&client-id=' + process.env.PAYPAL_CLIENT_ID,
        defer: true
      }
    ]
  },
```

```
<template>
    <div ref="paypalbutton"></div>
</template>
```
Doesn't work: 
```
mounted () {
    window.paypal.Buttons().render(this.$refs.paypalbutton)
},
```

It's works:
```
mounted () {
 setTimeout(() => { window.paypal.Buttons().render(this.$refs.paypalbutton) }, 500)
},
```

**Comment by gregjopa** [comment]
Hi @ceronem, it seems like you are running into trouble with using `defer` without having a reliable way to know when the script is done loading and is ready for use. To solve this problem, we recommend using the [paypal-js](https://github.com/paypal/paypal-js) library. This client-side loader library is for loading the script with a promise api so you know when it's finished. It loads the script on the client-side in a non-blocking way and will `resolve(null)` on the server-side so it doesn't break your build. Please give it a try and let us know your feedback.

**Comment by ceronem** [comment]
> Hi @ceronem, it seems like you are running into trouble with using `defer` without having a reliable way to know when the script is done loading and is ready for use. To solve this problem, we recommend using the [paypal-js](https://github.com/paypal/paypal-js) library. This client-side loader library is for loading the script with a promise api so you know when it's finished. It loads the script on the client-side in a non-blocking way and will `resolve(null)` on the server-side so it doesn't break your NuxtJS build. Please give it a try and let us know your feedback.

It works very well. Thanks a lot

**Comment by gregjopa** [comment]
@ceronem that's great to hear! 🚀 😄
