### ISSUE TITLE
[Bug] Paypal button - Problem with “Invalid sdk meta”

### ISSUE THREAD

**Issue by saltyfedor** [paypal/paypal-checkout-components#1453]
The script does load and I'm able to render the paypal button, however when clicked it opens an infinite checkout load. Upon loading the page sends a request to https://www.sandbox.paypal.com/smart/buttons?.....

and receives a response 400 bad request with body : 

Invalid sdk meta: eyJ1cmwiOiJodHRwczovL3BheXBhbC5jb20vc2RrL2pzP2NsaWVudC1pZD1BWHdITVB4cFFPNDdKeVFYcndDUXJKZzBlNlp0Q0dvRm9vYlpYTnpIa0lpR2FVQUp5bDlGRzlJYXYyRmQwZTE4aWdKVV95Wmk1LWJkdk1WSCZjdXJyZW5jeT1DWksiLCJhdHRycyI6eyJkYXRhLXVpZCI6IjBjNTYxNzQ0YjVfbXRrNm10bTZtdGsifX0

My code is:

Script import: 
<script src="https://paypal.com/sdk/js?client-id=AXwHMPxpQO47JyQXrwCQrJg0e6ZtCGoFoobZXNzHkIiGaUAJyl9FG9Iav2Fd0e18igJU_yZi5-bdvMVH
&currency=CZK"></script> (& currency is displayed incorrectly for some reason, this is not the issue)

The paypal button component:

const PayPal = ({ amount, onSuccess, currency } ) => { 
   

    return (        
        <div>
            
            <PayPalButton
              amount={amount}
              currency={currency}
              onSuccess={(details, data) => onSuccess(details, data)}
              options={{
                clientId: "AXwHMPxpQO47JyQXrwCQrJg0e6ZtCGoFoobZXNzHkIiGaUAJyl9FG9Iav2Fd0e18igJU_yZi5-bdvMVH"
              }}
          />
        </div>
    );
}
Parrent: 

const Payment = () => {
    
    const paymentHandler = (details, data) => {
        /** Here you can call your backend API
          endpoint and update the database */
        console.log(details, data);
      }

    return (
    <div className="center mt2">         
            <PayPal  amount = {200}
                    currency = {'CZK'}
                    onSuccess={paymentHandler} />      
    </div>         
    )

}

There are also SameSite cookie issues in the console. This is not a browser issue, I tried opera, firefox and chrome.

I'm using react-paypal-button-v2 however, I had the exact same issue without it.

It almost feels like my sandbox api credentials are incorrect but they are.

**Comment by kedzior-io** [comment]
@saltyfedor 

Had same issue today after applying html minification. 
Check your output html and make sure if you have any minification turned on that removes https protocol from attributes. 

In my case this was my output:
`<script src="//www.paypal.com/sdk/js?client-id={your-id}"></script>`

And it should be this:
`<script src="https://www.paypal.com/sdk/js?client-id={your-id}"></script>`

**Comment by padaliya-Kapil** [comment]
I'm also having the same issue  .
```

import {PayPalButton} from 'react-paypal-button-v2'

 const script = document.createElement('script')
      script.type = 'text/javascript'
      script.src = `https://paypal.com/sdk/js?client-id=${clientId}`
      console.log(script.src)
      script.async = true
      script.onload = ()=>{
        setSdkReady(true)
      }
      document.body.appendChild(script)

    }


                  <PayPalButton py={3}
                  amount = {order.totalPrice}
                  onSuccess = {successPaymentHandler}
                  >

                  </PayPalButton>

```
Please if anyone can help with the issue

**Comment by gregjopa** [comment]
It looks like you are missing “www” from the SDK url. It should be `https://www.paypal.com/sdk/js?client-id=${clientId}`

**Comment by padaliya-Kapil** [comment]
> It looks like you are missing “www” from the SDK url. It should be `https://www.paypal.com/sdk/js?client-id=${clientId}`
OMG :( , I feel so silly 
Thank you for your help .

**Comment by gregjopa** [comment]
@padaliya-Kapil no worries. I've made the same mistake myself with forgetting the "www" part in the url.

Also, I noticed you are using the `react-paypal-button-v2` library. We recently released an official react library for the JS SDK and recommend using that instead: https://github.com/paypal/react-paypal-js
