### ISSUE TITLE
[Bug] smartButtons onCancel() never called if PayPal popup window is immediately closed

### ISSUE THREAD

**Issue by fborm** [paypal/paypal-checkout-components#1468]
### 🐞 Describe the Bug
onCancel() is never called if PayPal popup window is immediately closed. As far is I can tell, this applies to the time period in which the order is being created on the backend (i.e. before the main browser window will be dimmed and the popup window starts to populate with content). This means that my checkout process will just keep on displaying "In Progress..." forever.

### 🔬 Minimal Reproduction / ### 😕 Actual Behaviour
Use SmartButtons checkout as described in Basic Checkout. In the createOrder() function, either delay the call to actions.order.create() by a busy loop or replace actions.order.create() call by a synchronous XMLHttpRequest() to do order creation on the server-side. Both of these steps are just there to give you enough time to close the popup. I've seen this happen even without any "artificial" delays in the Javascript code, simply by VPN'ing myself once to the other end of the world and back, introducing enough delay into the browser to PayPal API server communication. The delay in creating the order caused by that is enough to observe this issue even with actions.order.create() called immediately in createOrder().

### 🤔 Expected Behavior
onCancel() must always be called when the PayPal checkout popup window is closed without the user completing approval of the initiated ordering/payment process.

### 🌍 Environment

- Browser version: Firefox 82
- OS version: Windows 10
- SDK version (`window.paypal.version`): 5.0.184

### Affected browsers
What browser(s) are affected?
Tested only on Firefox. See above.

### ➕ Additional Context
The same thing works correctly when using the pre-February 2019 checkout.js integration. From the looks of it, the older SDK continues with the Payment Creation even if the popup is already closed. At least the main browser briefly dimms even after the popup window already closed, only to undim fairly quickly and then calling onCancel(). I am actually using the older SDK now due to this issue (well, and because, contrary to the SmartButtons checkout, it *DOES* allow you to select/change the transaction currency after the button is rendered, but that's a different issue...).

**Comment by mnicpt** [comment]
@fborm Can you reproduce here? https://developer.paypal.com/demo/checkout/#/pattern/client with the following code:
```
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '88.44'
                        }
                    }]
                });
            },
            
            onCancel: function() {
                console.log('cancelled');
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                });
            }


        }).render('#paypal-button-container');
```

**Comment by mnicpt** [comment]
Closing due to lack of response.  Please reopen if still not resolved.  I was unable to reproduce.
