### ISSUE TITLE
[Bug] Payee(s) passed in transaction does not match expected merchant id. 

### ISSUE THREAD

**Issue by giladv** [paypal/paypal-checkout-components#1470]
trying to create a payment to a third party merchant via payee merchant_Id e.g
```
payee: {
	merchant_id: 'XXX',
},
```
it worked perfectly until today when suddenly i'm getting a warning in the console

```
Payee(s) passed in transaction does not match expected merchant id. Please ensure you are passing merchant-id=XXXX or merchant-id=XXXX to the sdk url. https://developer.paypal.com/docs/checkout/reference/customize-sdk/
```
my use case is a marketplace were the money transfers directly to the merchants so i can't specify in the script tag a merchant id as it changes according to the product.

to reproduce:
- simple script tag with client-id and intent of "authorize"
- in the button creation we pass 
```
return actions.order.create({
purchase_units: [
	{
		amount: {
			value: 123,
		},
		payee: {
			merchant_id: 'XXX'
		},
	},
],
});
```

help.

**Comment by mnicpt** [comment]
@giladv Have you tried setting the query param, `merchant-id=*`, and then setting all of the merchant id's in the `data-merchant-id` attribute comma-separated on the script tag?  Something like this: 
```
<script
  src="https://www.paypal.com/sdk/js?client-id=xyz&merchant-id=*"
  data-merchant-id="abc,xyz,foo@bar.com">
</script>
```

**Comment by giladv** [comment]
@mnicpt this is not an option for my use case.. the merchants are dynamic (anyone can signup and start selling goods)
i cannot pass potentially thousands of merchants as argument

**Comment by mnicpt** [comment]
@giladv I understand.  I will got back to my team to discuss what we can do for marketplace integrations.  For now, I would look at this doc if you haven't yet: https://developer.paypal.com/docs/platforms/seller-onboarding/

**Comment by gregjopa** [comment]
Hi @giladv, to avoid this warning please pass the merchant id in the query param or as a list in the data attributes as @mnicpt mentioned.

> the merchants are dynamic (anyone can signup and start selling goods)
i cannot pass potentially thousands of merchants as argument

If the merchant ids are dynamic, you will need to re-load the script when the merchant ids change. I imagine your eCommerce flow has a user action like clicking a button to select a product and update your shopping cart. Try reloading the JS SDK script when this action happens with the latest merchant-ids. That way your JS SDK script is always in sync with the merchant ids in the payload to the create order api call. 

Also, I noticed you are using react-paypal-js. You can leverage the `resetOptions` action for reloading the JS SDK similar to this currency example: https://paypal.slack.com/archives/C012UT8NQJX/p1605039735157300

**Comment by gregjopa** [comment]
HI @giladv, I going to close this one out. Feel free to re-open if it's still an issue for you.
