### ISSUE TITLE
[Documentation] Is this possible to use directly these compoents instead of the paypal button?

### ISSUE THREAD

**Issue by tttp** [paypal/paypal-checkout-components#1472]
### 📙 Describe the Issue
Paypal button recommend loading the script directly from paypal and not use a local copy.
However, it seems mostly a thin wrapper around the checkout component.

For privacy reason, we do not want to load a script from paypal
https://us.cnn.com/2020/11/12/cnn-underscored/payment-app-privacy/index.html

Is this possible to simply have a copy of the button image and use our local copy of the paypal-checkout-component?

I didn't find an example of that in the documentation, is this missing, discouraged, forbidden?

**Comment by gregjopa** [comment]
> For privacy reason, we do not want to load a script from paypal
https://us.cnn.com/2020/11/12/cnn-underscored/payment-app-privacy/index.html

Hi @tttp, can you elaborate why you don't want to load the script from the PayPal CDN?

We encourage folks to load the PayPal SDKs from our CDN and not to use paypal-checkout-component directly.

**Comment by tttp** [comment]
`Can you elaborate why you don't want to load the script from the PayPal CDN?`

Sure: because the Paypal button isn't on a checkout page but it's for a "donate" type of button. On these pages with a lot of traffic will only have a tiny % of visitors donating. Using a CDN would give paypal information about every visitor, -not only about the donors- and used for nefarious/marketing purposes.

To be clear, I'm not saying that paypal does it, but the only way I can be sure it doesn't track our visitors is to not use your CDN and serve a local copy

Right now, the allowed alternatives are:
- not use paypal
- load from a cdn on mouseover the button (terrible user experience)
- keep a local version

I am aware that it will mean more dev work and maintenance, but that seems the only option.

Does it make sense?

Could you point me on how to start/a minimal test to hook the checkout component on a link/button?

**Comment by gregjopa** [comment]
@tttp thanks for explaining your use case. I would like to recommend another alternative. Lazy-load the JS SDK when the user is further down your funnel for possibly making a donation. For example, PayPal's default recommendation is to add the following script tag to your html:

```html
<script src="https://www.paypal.com/sdk/js?client-id=sb"></script>
```

As you mentioned, this leads to loading the JS SDK script for all users even though a small fraction of them will complete a transaction. Instead, dynamically load the JS SDK based on some condition that shows the user is closer to making the donation. The [paypal-js](https://github.com/paypal/paypal-js) library can be used to dynamically load the script.

The next step is figuring out how you can tweak your UX to load the SDK when the user is more likely to donate. If the PayPal Button is below the fold you could use [Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to conditionally load it based on scroll position. Having a separate Donate page that only renders the PayPal button is another option.

> Could you point me on how to start/a minimal test to hook the checkout component on a link/button?

It is not possible to host this paypal-checkout-components library yourself. The PayPal JS SDK includes several other features that are not part of this library.
