### ISSUE TITLE
generic-error

### ISSUE THREAD

**Issue by tigerosik** [paypal/paypal-checkout-components#1474]
Please help me, when paying via the Chrome browser, i get an error https://www.paypal.com/latinumcheckout/error/generic-error

When paying via the Microsoft edge browser, the payment is successful. Tell me how to fix this error in the Chrome browser

**Comment by gregjopa** [comment]
@tigerosik please use the issue template. We aren't able to help you when you don't provide a reproduction.

**Comment by manojbharti** [comment]
I'm also facing the same error please help.
