### ISSUE TITLE
disable "Confirm shipping details"

### ISSUE THREAD

**Issue by tigerosik** [paypal/paypal-checkout-components#1475]
Please help me how to disable "Confirm shipping details" so that you can pay immediately? I'll use this code I am using script on a button
Please edit my code

    <script>
        paypal.Buttons({
            createOrder: function (data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '<?php echo get_price($total_amount, 'decimal'); ?>',
                        }
                    }]
                });
            },
            onApprove: function (data, actions) {
                return actions.order.capture().then(function (details) {
                    $('.paypal-loader').show();
                    var data_array = {
                        'payment_id': data.orderID,
                        'currency': '<?php echo $currency; ?>',
                        'payment_amount': '<?php echo get_price($total_amount, 'decimal'); ?>',
                        'payment_status': details.status,
                        'mds_payment_type': '<?php echo $mds_payment_type; ?>',
                        'sys_lang_id': sys_lang_id
                    };
                    data_array[csfr_token_name] = $.cookie(csfr_cookie_name);
                    $.ajax({
                        type: "POST",
                        url: base_url + "paypal-payment-post",
                        data: data_array,
                        success: function (response) {
                            var obj = JSON.parse(response);
                            if (obj.result == 1) {
                                window.location.href = obj.redirect;
                            } else {
                                location.reload();
                            }
                        }
                    });

                });
            }
        }).render('#paypal-button-container');
    </script>

**Comment by elizabethmv** [comment]
Hi @tigerosik! You can disable shipping by adding  `shipping_preference: "NO_SHIPPING"` within `application_context`. Here are the docs for reference: https://developer.paypal.com/docs/api/orders/v2/#definition-order_application_context

You should be able to update your `createOrder` code with the following:
```
return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: '<?php echo get_price($total_amount, 'decimal'); ?>',
                    }
                }],
              application_context: {
                  shipping_preference: "NO_SHIPPING"
              },
            });
```

**Comment by tigerosik** [comment]
> Привет @tigerosik ! Вы можете отключить доставку, добавив `shipping_preference: "NO_SHIPPING"`внутри `application_context`. Вот документы для справки: https://developer.paypal.com/docs/api/orders/v2/#definition-order_application_context
> 
> Вы должны иметь возможность обновить свой `createOrder`код следующим образом:
> 
> ```
> return actions.order.create({
>                 purchase_units: [{
>                     amount: {
>                         value: '<?php echo get_price($total_amount, 'decimal'); ?>',
>                     }
>                 }],
>               application_context: {
>                   shipping_preference: "NO_SHIPPING"
>               },
>             });
> ```

Thank you, it works now, but unfortunately another problem comes out. When entering a phone number, the Google Chrome browser doesn't want to accept it. In Microsoft Edge and Internet Explorer, the phone number is verified successfully. Maybe you are familiar with this situation please tell me
Please see the screenshot: [https://www.prywat.com/1.jpg](url)
Help please

**Comment by elizabethmv** [comment]
Hi @tigerosik, we'd be happy to help. Would you mind opening up a new issue with more details so we can dig into this more?
