### ISSUE TITLE
Every payment results in a double payment

### ISSUE THREAD

**Issue by pistacchio** [paypal/paypal-checkout-components#1483]
### 🐞 Describe the Bug
I have installed the Paypal Smart Button on my page closely following  the official documentation:

```
        paypal.Buttons({
            createOrder: function (data, actions) {
                // This function sets up the details of the transaction, including the amount and line item details.
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '3.99'
                        }
                    }]
                });
            },
            onApprove: function (data, actions) {
                // This function captures the funds from the transaction.
                return actions.order.capture().then(function (details) {
                    axios.post('', {id: details.id}, {
                        headers: {
                            'X-CSRFToken': getCookie('csrftoken')
                        },
                        withCredentials: true
                    }).then(resp => {
                        if (resp.data.status === 'OK') {
                            alert('Transaction completed successfully! Check your email for the bundle!')
                        } else {
                            alert('Something went wrong, please contact us via email: xxx')
                        }
                    });
                });
            }
        }).render('#paypal-button');
```

In my paypal console I've noticed that every payment results in a double payment. Customers are sending emails complaining about it and requesting refunds.

**Comment by gregjopa** [comment]
Hi @pistacchio, sorry to hear you are experiencing this problem. Are you still getting complaints about double payments?

Based on your code snippet, my best guess is the custom api call in your onApprove callback (`axios.post('/your-custom-api', {id: details.id}`) can sometimes take a while to complete. The actual PayPal Loading Overlay disappears as soon as the payment is captured and does not wait for the onApprove callback to complete. We are working on a fix for this and are tracking it here: https://github.com/paypal/paypal-checkout-components/issues/1486. If this is the issue, you could apply a temporary work around by showing your own custom loading spinner or alert message to your user letting them know the payment is still processing and almost complete. Ex:

```js
return actions.order.capture().then(function (details) {
    // show your user your own custom loading spinner or message saying the payment is almost done.
    setPaymentLoadingMessage('almost Finished');
    
    axios.post('/your-custom-api', {id: details.id}, {
        headers: {
            'X-CSRFToken': getCookie('csrftoken')
        },
        withCredentials: true
    }).then(resp => {
        if (resp.data.status === 'OK') {
            setPaymentLoadingMessage('Success!');
        } else {
            setPaymentLoadingMessage('Failed, something went wrong');
        }
    });
});
```

**Comment by gregjopa** [comment]
Hi @pistacchio, I'm going to close this one out as a work around has been provided. Please reopen if you are still having this problem.
