### ISSUE TITLE
[Bug] The string did not match the expected pattern - Safari

### ISSUE THREAD

**Issue by nick4414** [paypal/paypal-checkout-components#1487]
### 🐞 Describe the Bug
When someone clicks on the payment buttons, I get this error 

> The string did not match the expected pattern.

### 🔬 Minimal Reproduction
Use Safari on Mac with the environment versions mentioned below and use the basic Smart-Payment-Integration on the paypal developer page. I am not 100% sure if that reproduces the error, because a buyer encountered the error. So I can just use my error log information.

### 😕 Actual Behavior
When the buyer tries to click on the payment buttons, he gets the error mentioned above. 
My code can't be the problem, because the payment has already worked 150-200 times with all other browsers.
It might be a browser compability issue.

> /sdk/js in error at line 2:60662

is shown in the log. I don't know if that helps.

### 🌍 Environment

- Browser version: Safari 11.1.2
- OS version: Mac OS X 10.11.6
- SDK version (`window.paypal.version`): 5.0.186

### Affected browsers
What browser(s) are affected?
- Safari

**Comment by gregjopa** [comment]
Hi @nick4414, thanks for opening up the issue. Can you share your implementation code? Or perhaps a url to try and reproduce the problem?

We tested in the Safari 11 and were not able to reproduce the problem:
<img width="1485" alt="Screen Shot 2020-12-08 at 10 04 58 AM" src="https://user-images.githubusercontent.com/534034/101508131-eb186e80-393c-11eb-98a6-5b5d6c9cb7d0.png">


> /sdk/js in error at line 2:60662

Unfortunately this line/column number is for our generic error handler in the JS SDK so it doesn't provide any additional info. Do you have a stacktrace you can share for the error that you can share?


Here are some resources we found around this "string did not match the expected pattern":
- https://developer.mozilla.org/en-US/docs/Web/API/DOMError
- https://www.reddit.com/r/firefox/comments/5nbmqi/on_handling_invalid_selector_strings/

**Comment by nick4414** [comment]
Hi,
Thanks for helping.
That is my stacktrace. I don't know if that helps.

> Error: The string did not match the expected pattern.
>   at error(/sdk/js:2:60662)
>   at parse([native code])
>   at ? (/sdk/js:2:73105)
>   at Er(/sdk/js:2:73240)
>   at ? (/sdk/js:2:79361)
>   at try(/sdk/js:2:14123)
>   at ? (/sdk/js:2:79156)
>   at ? (/sdk/js:2:79408)
>   at error(/sdk/js:2:60662)
>   at parse([native code])
>   at ? (/sdk/js:2:73105)
>   at Er(/sdk/js:2:73240)
>   at ? (/sdk/js:2:79361)
>   at try(/sdk/js:2:14123)
>   at ? (/sdk/js:2:79156)
>   at ? (/sdk/js:2:79408)

I tested my code on the Safari version 11.2 and the error showed up again.

That's my checkout-component code:
```
// payment paypal
paypal.Buttons({

    // order is created
    createOrder: function (data, actions) {

        return fetch('/xyz', {
            method: 'POST',
            headers: new Headers({
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
                'Content-Type': 'application/json'
            }),
            body: JSON.stringify({
                'xyz': xyz,
                'xyz': xyz != null ? xyz.value : "xyz",
                'xyz': xyz != null ? xyz : ''
            })
        }).then(function (res) {
            return res.json();
        }).then(function (data) {
            return data.id;
        });
    },

    // order has been approved by buyer
    onApprove: function (data, actions) {

      
        // display loading
        document.getElementsByTagName("xyz")[0].style.overflow = "hidden";
        document.getElementById('xyz').style.display = "block";
        document.getElementById('xyz').style.display = "block";

        return fetch('/xyz', {
            method: 'POST',
            headers: new Headers({
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
                'Content-Type': 'application/json'
            }),
            body: JSON.stringify({
                'xyz': xyz,
                'xyz': xyz != null ? xyz.value : "1",
                'xyz': xyz != null ? xyz : '',
                'xyz': data.orderID
            })
        }).then(function (res) {
            return res.json();
        }).then(function (data) {

            // update xyz
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            jQuery.ajax({
                type: 'PATCH',
                url: '/xyz',
                data: {
                    xyz: xyz,
                },
                success: function (data) {
                    // redirect to page
                    window.location = data.xyz;
                },
                error: function (error) {}
            });
        });
    },

    // an error occurred
    onError: function (error) {
        // Show an error page here, when an error occurs
        $('#xyz').modal('show')
    }

}).render('#paypal-button-container').then(function () {
    document.getElementById('xyz').style.display = "block";
    document.getElementById('xyz').style.display = "none";
});
```
