### ISSUE TITLE
onShippingChange is not called for guest (credit card) checkout

### ISSUE THREAD

**Issue by Shazwazza** [paypal/paypal-checkout-components#1508]
### 🐞 Describe the Bug

Trying to use the onShippingChange callback but this does not work when using a Credit Card to checkout. According to the docs here: https://developer.paypal.com/docs/checkout/integration-features/shipping-callback they state:

> PayPal calls your onShippingChange function when:
> * The buyer initially logs into their account (if the buyer already has a PayPal account).
> * The buyer submits their billing/payment information (if the buyer does not have a PayPal account).
> * The buyer makes a change to their shipping address on the review your payment page.

But the 2nd bullet point does not work. This does work when using the normal PayPal checkout once you log in with Paypal and change your address. 

### 🔬 Minimal Reproduction

Follow these instructions https://developer.paypal.com/docs/checkout/integration-features/shipping-callback/

But instead of Choosing PayPal, choose Debit or Credit Card

![image](https://user-images.githubusercontent.com/1742685/103386680-20873500-4b54-11eb-9d89-f55f0c576961.png)

I am using &currency=AUD as the query string param to load the SDK. 

Fill out your billing details but uncheck the box "Shipping same as billing address"

Change country and any other details for the shipping address and continue to make the purchase. The `onApprove` will be called but never the `onShippingChange`

### 😕 Actual Behavior

onShippingChange is not called is not called in this scenario

### 🤔 Expected Behavior

onShippingChange  should be called whenever the buyer is modifying their billing/shipping information.

### 🌍 Environment

- Browser version: - Microsoft Edge Version 87.0.664.57 (Official build) (64-bit)
- SDK version (`window.paypal.version`): - "5.0.187"

**Comment by Matt-TOTW** [comment]
I am also experiencing this. Did you get anywhere with it?

**Comment by Shazwazza** [comment]
I had to hack around this issue. In `onApprove` I get the order details with `actions.order.get().then...` and then I check if the shipping cost are what they are supposed to be and if they are not I issue a "patch" to update the order's shipping cost to what it is supposed to be with `actions.order.patch` (more or less like you would do in `onShippingChange`) but since it would be quite unfriendly to just proceed with the payment since the user would be unaware that the price has changed I have to show a custom summary screen with a confirmation button for the user to keep processing. This only occurs in this situation, else there's no custom summary screen shown/needed.

It's pretty annoying since it seems that onShippingChange should 'just work' even with a CC.

**Comment by Matt-TOTW** [comment]
Yeah it's really annoying, but I like your workaround, thanks for the reply. My implementation is actually simpler as I only need to reject or accept an address so I'll look more closely at what I can do in onApprove.

Nb tested in Safari and Chrome with the same results.

**Comment by gregjopa** [comment]
Hi @Shazwazza and @Matt-TOTW thanks for reporting the issue. The details in the PR description are well written and it really helps us understand the problem. 

The inline guest button does not support the `onShippingChange` callback yet. I'm checking with the teams internally to see when we plan to support this feature. We will update the thread when we learn more.

**Comment by albert-asin** [comment]
Hi, here I have the same problem. 
onShippingChange is not raised when the shipping address is changed for credit card (i'm not using the inline mode)
@Shazwazza thanks for your workaround

**Comment by stefanfisk** [comment]
I thought that my integration was almost done, and then I encountered this issue.

I've not decided yet, but seeing as there's not even an acknowledgement from PayPal that they've seen this issue, right now I'm leaning towards just not using PayPal.

**Comment by albert-asin** [comment]
bump

**Comment by Shazwazza** [comment]
Bump. Still an issue, nobody from PayPal has even acknowledged this.
