### ISSUE TITLE
[Bug] Capture after CCREJECT-REFUSED entered in address_line_1 field stopped working even after a correct address is entered

### ISSUE THREAD

**Issue by ivankokus** [paypal/paypal-checkout-components#1511]
### 🐞 Describe the Bug
When using CCREJECT-REFUSED in the address_line_1 field to invoke capture failure, once the window is opened again and correct information is entered, the capture still fails.  This used to work before.  After initial wrong info, if you enter correct information, capture used to succeed.

### 🔬 Minimal Reproduction
1.  Go to https://developer.paypal.com/demo/checkout/#/pattern/client
2. Press "Debit or Credit Card"

3. Enter address with CCREJECT-REFUSED in "Street address" field
![image](https://user-images.githubusercontent.com/40287813/103618910-1ca04c00-4f74-11eb-9bc3-f38b4d434c6a.png)

4. Press "Pay Now" button
5. Capture will fail, and the script will Open a popup to re-enter the billing information and show you the capture error.
![image](https://user-images.githubusercontent.com/40287813/103618952-2e81ef00-4f74-11eb-9810-2dbf88662dd8.png)

6. Reenter the personal info without CCREJECT-REFUSED by entering a normal address
![image](https://user-images.githubusercontent.com/40287813/103619041-5d986080-4f74-11eb-9c5e-9bc01ef3cf66.png)

7. Press "Pay Now" button

### 😕 Actual Behavior
Regardless of entering correct info the second time, capture returns an error
![image](https://user-images.githubusercontent.com/40287813/103619170-95070d00-4f74-11eb-8e17-1c20e6d610b3.png)

### 🤔 Expected Behavior
Payment should be successful

### 🌍 Environment

- Browser version: -Chrome latest
- OS version: - MacOS 10.14.6
- SDK version (`window.paypal.version`): -

### Affected browsers
What browser(s) are affected?
All

**Comment by gregjopa** [comment]
Hi @ivankokus, thanks for reporting the issue. Are you testing on mobile or desktop? I went through your steps in Chrome on Desktop and on step 6 I got a full page redirect instead of the popup.
