### ISSUE TITLE
mi cuenta pay pal

### ISSUE THREAD

**Issue by edith2727** [paypal/paypal-checkout-components#1514]
### 🔬 Minimal Reproduction
Describe steps to reproduce. If possible, please, share a link with a minimal reproduction.

### 😕 Actual Behavior
A clear and concise description of what is happening. Please include console logs during the time of the issue, especially error messages.

### 🌍 Environment

- Browser version: -
- OS version: -
- SDK version (`window.paypal.version`): -

### Affected browsers
What browser(s) are affected?

### ➕ Additional Context
Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.

**Comment by edith2727** [comment]
> ### 🐞 Describe the Bug
> A clear and concise description of what the bug is.
> 
> ### 🔬 Minimal Reproduction
> Describe steps to reproduce. If possible, please, share a link with a minimal reproduction.
> 
> ### 😕 Actual Behavior
> A clear and concise description of what is happening. Please include console logs during the time of the issue, especially error messages.
> 
> ### 🤔 Expected Behavior
> A clear and concise description of what you expected to happen.
> 
> ### 🌍 Environment
> 
> - Browser version: -
> - OS version: -
> - SDK version (`window.paypal.version`): -
> 
> ### Affected browsers
> What browser(s) are affected?
> 
> 
> 
> ### ➕ Additional Context
> Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.
>

**Comment by minkonaing13** [comment]
Hi
