### ISSUE TITLE
[Bug] Order could not be captured when paying with credit card

### ISSUE THREAD

**Issue by t7014210** [paypal/paypal-checkout-components#1521]
Hi,
I use the following code for our payment checkout:

```
paypal.Buttons({
            env: 'production',
            locale: 'de_DE',
            style: {
                layout:  'vertical',
                color:   'silver',
                shape:   'rect',
                label:   'paypal'
            },
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: value,
                            currency_code: 'EUR'
                        }
                    }],
                    application_context: {
                        shipping_preference: 'NO_SHIPPING'
                    }
                });
            },
            onApprove:  function (data, actions) {
                return actions.order.capture().then(function(details) {
                    ...
                });
            },
            onCancel: function (data) {
                ...
            }
        }).render('#paypal-button-container');
```
When paying with credit card this codes generates an error:
"Uncaught Error: Order could not be captured"

This code used to work and it works when paying with PayPal or Klarna. This error does not occur when using the sandbox environment.

Any ideas?

**Comment by Cyriuz** [comment]
I have the same issue. When looking what the response from the https://www.paypal.com/smart/api/order/capture call was it states:
`{"ack":"permission_denied","message":"Insufficient privileges"}` but I've tried adding all permissions to the client without any success.

**Comment by opanjki** [comment]
I have the same issue, en_US locale used with currency_code: 'EUR' and also shipping_preference: 'NO_SHIPPING'. Is it some configuration issue or bug in paypal? Sandbox with test card works fine.

**Comment by t7014210** [comment]
I switched to capture the order server side. Works perfectly, but client-side it comes to an error.

**Comment by gregjopa** [comment]
Hi @opanjki, @Cyriuz, @t7014210, thanks for reporting the issue. Can you please share an Order ID from your capture api call? We can use that to check our logs to further troubleshoot.

**Comment by Cyriuz** [comment]
Sure, here's a few:

2JS52152H19526231
36S48021JK784743B
8BM18879BK356315U

**Comment by jmanumurillo** [comment]
Hi, i have the same issue, es_ES locale or en_EN locale with currency_code: 'EUR'. I have written to paypal-support 10 days ago and I still have not had any response. 

It happens to me when payments are made that require authorization from the bank, for example with a code sent by SMS. When entering the code, it always returns the same, {"ack":"permission_denied","message":"Insufficient privileges"} and this error "Order could not be capture". However, with card payments that do not require authorization (less than 30 euros), it works correctly. ¿is paypal problem, businnes account problem or what? In sandbox there is no error.

**Comment by pokono** [comment]
News? Same issue in prod. Working locally and sandbox..

**Comment by giovannicechet** [comment]
Same issue in prod for me, seems related to payment verification offered from some payment provider (SMS o app notify confirmation), as already jmanumurillo reported.
Any news on this?

**Comment by hkalman** [comment]
I have the same issue. 

My Bank give back an error on the console:

```
https://acssv.otpbank.hu/acs/api/3ds2/challenge/oob
Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.
```

The transaction was authorized with my bank's app correctly, but the capture call response was:

```
https://www.paypal.com/smart/api/order/21C96522FP453814R/capture
{"ack":"permission_denied","message":"Insufficient privileges"}
```


I generated new, clean Paypal Buttons code, but I've got the same answer.
```

<div id="smart-button-container">
    <div style="text-align: center;">
        <div id="paypal-button-container"></div>
    </div>
</div>
<script src="https://www.paypal.com/sdk/js?client-id=APPID&currency=EUR" data-sdk-integration-source="button-factory"></script>
<script>
function initPayPalButton() {
    paypal.Buttons({
        style: {
            shape: 'rect',
            color: 'blue',
            layout: 'vertical',
            label: 'paypal',
        },  
        createOrder: function(data, actions) {
            return actions.order.create({
                purchase_units: [{"description":"25% Deposit","amount":{"currency_code":"EUR","value":1}}]
            });
        },
        onApprove: function(data, actions) {
            return actions.order.capture().then(function(details) {
                alert('Transaction completed by ' + details.payer.name.given_name + '!');
            });
        },
        onError: function(err) {
            console.log(err);
        }
    }).render('#paypal-button-container');
}
initPayPalButton();
</script>

```

**Comment by geraldpainsi** [comment]
I have the same issue and therefor can't provide standard credit card payment for my users (is it possible that it has something to do with the new 2 FA for EU credit cards payments made mandatory earlier this year?, https://euipo.europa.eu/ohimportal/en/news/-/action/view/8410243)

**Comment by MarMarIV** [comment]
I have same problem. Any solution now for card payment?

**Comment by oscarpignataro** [comment]
I have same problem. with card requiring other bank authorizations

**Comment by amcfarlane** [comment]
+1 for this issue. We have the same {"ack":"permission_denied","message":"Insufficient privileges"} error when trying to make payments from Turkish and Italian payment cards. Both payments are authorized correctly by the banks.

**Comment by calibr** [comment]
As a workaround we capture guest card orders on the server side when a webhook notification`CHECKOUT.ORDER.APPROVED` arrives. It seems to be working, but the strange thing is that `CHECKOUT.ORDER.APPROVED` arrives two times. When the first notification arrives the capture request fails with an error: `Payer has not yet approved the Order for payment`. On the second time the capturing succeeds.

Also, in order to not capture already captured orders you may check `order.purchase_units[0].payments[...].captures[...]` and if there are no `COMPLETED` captures it makes sense to capture on the server side.

**Comment by iopodx** [comment]
Facing the exact same issue. Paying with creditcard and Defaul Buttons integration as shown above failes with "Order could not be captured".

I also have language and currency set, in my case de_DE + EUR

**Comment by xLarry** [comment]
Same issue here.

@amcfarlane where do you get the `permission_denied` message from? I'm just getting an `Order could not be captured` error in the developer console without any further details.

I also posted the error to the PayPal Tech Support. Hope this will be looked at soon.

**Comment by oscarpignataro** [comment]
I think there is only one solution, open more and more help request on paypal

**Comment by amcfarlane** [comment]
@xLarry where/when you see the 'Order could not be captured' in the console. Switch to Network > XHR and you should see a failed API call to PayPal. This is slightly more specific.

I also opened a support request this morning. FYI, I'm trying to take payments in EUR from Italy, authorization using my banking app (not SMS).

**Comment by oscarpignataro** [comment]
banking app or SMS it s same, not accept all payments require other authorization

**Comment by amcfarlane** [comment]
Just posting here if it helps anyone. PayPal support is saying if you are trying to pay yourself with your own card then the checkout will automatically fail. This is the correct functionality as you cannot pay yourself. So if you're testing this with your own card that's probably the issue.

We aren't and have had two client payments fail also. Are you guys using your own cards for testing?

**Comment by MarMarIV** [comment]
> Just posting here if it helps anyone. PayPal support is saying if you are trying to pay yourself with your own card then the checkout will automatically fail. This is the correct functionality as you cannot pay yourself. So if you're testing this with your own card that's probably the issue.
> 
> We aren't and have had two client payments fail also. Are you guys using your own cards for testing?

I'm using second card for payments, still same problem

**Comment by xLarry** [comment]
@amcfarlane I captured some of these errors in Sentry while my customers tried to pay. They are most likely not using my card :) I can share a link to the Sentry details if it helps.

As @calibr and @t7014210 pointed out, the error doesn't occur when capturing on the server side. If the error had been caused by paying with your own card, the server side capture would have failed as well I guess.

**Comment by gtDataorg** [comment]
@MarMarIV I use my card but on shop of my customer, 2 completely separate accounts and 2 completely separate people ,2 company completely separate, paypal said this because not resolve the problem,

**Comment by gtDataorg** [comment]
Probably I found the problem is not a technical problem but related to regulations, and we would most likely have to switch and wait for a business account to be approved, after a long survey

**Comment by newearthmartin** [comment]
I have a business account, same problem. It feels that PayPal support will always try to find some fault in our website instead of taking this issue seriously.

**Comment by Cyriuz** [comment]
Same here, since I wrote my comment on 17 Jan PayPal support and tech support has shoved me around an insane amount with no real help whatsoever, including having to recreate my entire account because some business detail was wrong, and now that new account gets limited all the time because the "sudden" high amount of transactions. I have an outstanding tech support ticked since then and the only response I get when nagging is that the team is looking at the issue even though I have provided debug ids and logs at least 5 times.

I have given up on them and am switching to another payment provider.

**Comment by gtDataorg** [comment]
I tried to create a "paynow button" and work with all card Its very strange, I dont understand what happen

**Comment by gtDataorg** [comment]
If I use the credit card inside the button paypal "pay with a card" it asks 2 times the card but work

**Comment by lorenzosali** [comment]
Same issue here. No problem if paying with paypal, but "Order could not be captured" if using a credit card.

I added 

                    onShippingChange: function(data,actions){
                        return actions.resolve();
                    }

as a workaround. It's less smart, but it seems to work.

**Comment by gtDataorg** [comment]
@lorenzosali for me work !!

**Comment by MarMarIV** [comment]
> Same issue here. No problem if paying with paypal, but "Order could not be captured" if using a credit card.
> 
> I added
> 
> ```
>                 onShippingChange: function(data,actions){
>                     return actions.resolve();
>                 }
> ```
> 
> as a workaround. It's less smart, but it seems to work.

It works. Thanks!

**Comment by newearthmartin** [comment]
> I added 
> 
>                     onShippingChange: function(data,actions){
>                         return actions.resolve();
>                     }
> 
> as a workaround. It's less smart, but it seems to work.

Can you explain what this does and why it must be added?
Any reason why to add code to tell it how to handle situations? (apart from bad design from paypal)

**Comment by lorenzosali** [comment]
I don't understand completely how it works. The result is that the button opens a popup for the credit card payment and things go well :-D

You can find more information [here](https://developer.paypal.com/docs/checkout/integration-features/shipping-callback/).

Any advice to make the code better is welcome!

**Comment by giovannicechet** [comment]
The workaround seems works also for me, thank you very much @lorenzosali!

**Comment by FriesFlorian** [comment]
The workaround didn't solve the problem on my hand, still getting `{"ack":"permission_denied","message":"Insufficient privileges"}` after a successful 3DSecure valiation

**Comment by pedak** [comment]
Same here. +1
@lorenzosali the workaround works, however, it does remove other pay possibilities (like Klarna).
I hope PayPal will solve this issue!

**Comment by gtDataorg** [comment]
today, paypal inform me that the issue was resolved.

**Comment by Engin1980** [comment]
Right now, persists for me, the workaround with "onShippingChange" worked.

**Comment by gtDataorg** [comment]
paypal wrote this:
Our Engineers are reporting that this issue should be resolved.   I would recommend clearing your cache/cookies and try again at this time.

Please let me know if you are continuing to encounter issues.  I look forward to hearing from you.

Thank you,

Brian
Global Technical Support
PayPal, Inc.

**Comment by jfrubio** [comment]
@lorenzosali  Incredible!!! Works for me!
Thanks

**Comment by PC108** [comment]
Same problem with me. Suddenly credit card payment doesn't work anymore. Thanks @lorenzosali for the solution.

**Comment by Keirodev** [comment]
Same issue here. Workaround opening new window works for me. But initial issue stay, no useful response from paypal support currently.

**Comment by Tiefstapler** [comment]
same issue described here: [Paypal Smart Payment buttons cause error when selecting credit card #1224](https://github.com/paypal/paypal-checkout-components/issues/1224)

**Comment by marekfri** [comment]
Same for us, the issue is there when payment is recorded "in site". When the payment is recorded in the popup, all works well. This issue occurs only with Live accounts, not with Sandbox.

The workaround with "onShippingChange" method forces the functionality to open the popup, which eventually fixed the issue for us, as it is not there when recording payment via the popup.

**Comment by JoshHL** [comment]
Same problem here. The onShippingChange workaround didn't work for me unfortunately, still getting the same error.

**Comment by patrickbussmann** [comment]
Adding `onShippingChange` is working fine for me, too.
It opens the big window with much more data to collect.
Very interesting that this solves the issue.

Cant understand it but who cares - its working 🥳

**Comment by pedak** [comment]
Now, at my site, it works without the shipping workaround.
I hope it will stay like this.

**Comment by kevin-ryser** [comment]
Hi, I started to have the same problem on my site. Is there any more info about the problem, where to look at?
Thanks a lot!

**Comment by newearthmartin** [comment]
It would be nice if the PayPal team gave some kind of answer

**Comment by pasloc** [comment]
This bug is still there and massively annoying. How is it possible that paypal does not do anything about it?

**Comment by Kramerican** [comment]
This is still an issue and we see this on almost a daily basis. Incredibly annoying bug.

**Comment by LYBFORPHP** [comment]
Same issue ，any solution now for card payment?

**Comment by SamuPert** [comment]
We have a similar problem in production!

Api: /smart/api/order/XXXXXXXXXXXXX/capture returned ack: permission_denied (Corr ID: f335666b00bb1)

{"ack":"permission_denied","message":"Insufficient privileges"}



Are there any updates on this?

**Comment by webdock-io** [comment]
> We have a similar problem in production!
> 
> Api: /smart/api/order/XXXXXXXXXXXXX/capture returned ack: permission_denied (Corr ID: f335666b00bb1)
> 
> {"ack":"permission_denied","message":"Insufficient privileges"}
> 
> Are there any updates on this?

I suggest you create a new issue referencing this one as it's been permanently closed it seems. I can add that we see this on almost a weekly basis. To us this looks to be some issue with specific card issuers and 2 factor authentication, especially users from India in our case

**Comment by offaxis** [comment]
bump

**Comment by JeremyTellier** [comment]
Still happening.

**Comment by CynthiaBlue** [comment]
I am having this same error, but it happens when people try to use their PayPal account by logging in.  Credit Cards work fine.

"there was paypal error:  Error: Api: /smart/api/order/9J5915721D267592J/capture returned ack: permission_denied (Corr ID: f636697681fdc)

{"ack":"permission_denied","message":"Insufficient privileges"}"

I can use a different Live ID from a different PayPal developer account and that works fine.

**Comment by lukejames1111** [comment]
Is there any update to this? The fix above did not seem to do anything for me.
