### ISSUE TITLE
How do we get the Transaction ID using v2 of the API?

### ISSUE THREAD

**Issue by yabdab** [paypal/paypal-checkout-components#1524]
Previously we were returned the actual **Transaction Id** after capturing payment.

Now all that is returned in the orderId.

Paypal provides no obvious way to retrieve the transaction id using the orderId?

Anyone have a clue?

**Comment by mstuart** [comment]
Hi @yabdab, are you using the capture actions within the onApprove callback? We haven't returned a transactionId before. Do you know what it was previously called? Just wanted to make sure that transaction ID wasn't mistaken for something else. We always return a token (or Order ID) though.

**Comment by yabdab** [comment]
After executing payment server side I was able to gather the transaction id using the object path below (PHP)...

$rs->transactions[0]->related_resources[0]->sale->id;

I have yet to see a result payload using v2 that give the transaction id.

Not very good.
