### ISSUE TITLE
[Bug] Sometimes get 'script-src-elem' was not explicitly set error on windows

### ISSUE THREAD

**Issue by RahavLussato** [paypal/paypal-checkout-components#1531]
### 🐞 Describe the Bug

Sometimes on our sandbox env when we try click on the Paypal button to open the modal, its get stuck in infinite loading spinner and we see this error in the console
```
Refused to load the script 'http://bpp.eset.com/en-US/Redirect-Switch?token=XXX' because it violates the following Content Security Policy directive: "script-src 'self' https://.paypal.com: https://*.paypalobjects.com 'unsafe-inline' 'unsafe-eval' https://apis.google.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```
i reported that on https://github.com/paypal/react-paypal-js/issues/72 and they suggested I'll open it here.

### 🔬 Minimal Reproduction

Hard to reproduce as it sometimes happens and after some refreshes, it suddenly works.

### 😕 Actual Behavior

PayPal SDK not loaded because of the above error.

### 🤔 Expected Behavior

PayPal SDK should load and the Paypal modal should show the regular state.

### 🌍 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  | 2.0.0 |
| Browser          | Chrome |
| Operating System | Windows 10 |

**Comment by mstuart** [comment]
Hi @RahavLussato, we don't load anything from eset.com.

Can you retry again w/ Incognito mode? Just to rule out the possibility that a browser extension isn't loading it. Also, in your browser's dev tools, can you see what's loading it? Usually there will be a stack trace associated w/ it or something in the Network tab that points back to JavaScript that's loading it.

Hopefully that helps!
