### ISSUE TITLE
How to check paypal button component is already closed?

### ISSUE THREAD

**Issue by supercharge-team** [paypal/paypal-checkout-components#1534]
![image](https://user-images.githubusercontent.com/58783082/106353875-a1d71080-6328-11eb-8cdb-bd5dbf74a55e.png)

i got this error when trying to close the component by paypalButton.close()

**Comment by gnoyixiang** [comment]
Hi, I am experiencing the same error after calling paypalButton.close() when unmounting the parent component. How was this issue resolved?
![image](https://user-images.githubusercontent.com/30717323/110197910-8f04ae00-7e89-11eb-9388-0c0d4dccb9e8.png)
