### ISSUE TITLE
[Bug] Unable to open popup without explicit use of paypal button

### ISSUE THREAD

**Issue by z1haze** [paypal/paypal-checkout-components#1539]
### 🐞 Describe the Bug
Our client has designed custom comps for which they want to use to process through paypal. However, the paypal 'smart' checkout process does not expose the functionality to pop the paypal window without explicitly using the paypal sdk.

### 🔬 Minimal Reproduction
Create a normal html <button> element and want to bind the paypal popup flow to this button

### 😕 Actual Behavior
Functionality does not exist

### 🤔 Expected Behavior
We have custom comps, and wish be able to pop the paypal window using any regular button with custom javascript, etc.. example here:
![image](https://user-images.githubusercontent.com/6024725/107285404-56a1b980-6a1c-11eb-9228-430aefd99d07.png)

Please explain how this is done

### 🌍 Environment

- Browser version: -
- OS version: - Any
- SDK version (`window.paypal.version`): - Any

### Affected browsers
What browser(s) are affected? - All

**Comment by samuelgiles** [comment]
I believe this is related to pop-up blocking since the PayPal SDK opens the modal in a new window.

A hacky work around that many sites use is to put PayPal's button inside their own button and then using `opacity: 0.00000001` and some `position: absolute` to stretch the PayPal button over the top of their custom checkout button, this way clicking your custom button ends up triggering the normal PayPal logic.

**Comment by z1haze** [comment]
@samuelgiles that is definitely an interesting workaround.. might have to try it.  Ended up on this project just using a paypal button

**Comment by lingtalfi** [comment]
Or, another idea for a workaround would be that if the user chooses paypal as the payment method, then click the "continue" button, then the gui opens a modal with just the paypal buttons in it, so that the user is forced to focus on the paypal buttons.

**Comment by bbblgmsp** [comment]
the expected behaviour described above is actually required by DSGVO (GDPR) law in Austria and I believe some other countries too. So PayPal would be a much better pal if they made this possible. Apparently all Austrian law-abiding sites need to use a hack or work-around to make this work.
