### ISSUE TITLE
[Bug] PayPal Checkout JS does not work in TikTok's browser on iOS

### ISSUE THREAD

**Issue by brettchalupa** [paypal/paypal-checkout-components#1541]
### 🐞 Describe the Bug

Tapping the PayPal button in the TikTok browser in iOS opens a blank white screen and the PayPal mini-browser/overlay never loads, preventing payment from being sent.

### 🔬 Minimal Reproduction

1. Install TikTok on an iOS device
2. Go to this profile: https://www.tiktok.com/@brettbc, username: brettbc
3. Tap the link in bio, it goes to the PayPal checkout demo, https://developer.paypal.com/demo/checkout/#/pattern/client
4. Tap the "PayPal" button

### 😕 Actual Behavior

A blank white screen is displayed in the browser and nothing loads for PayPal

### 🤔 Expected Behavior

PayPal's mini-browser opens to allow payment details to be entered and people can pay using PayPal

### 🌍 Environment

- Browser version: - TikTok v18.5.0
- OS version: - iOS 14.3
- SDK version (`window.paypal.version`): - unfortunately there's no way to open a console to check here or see if there are any issues

### Affected browsers
What browser(s) are affected?

- Web View / Safari ViewController

### ➕ Additional Context

Here's a video demo:

https://user-images.githubusercontent.com/928367/107650445-80412780-6c4c-11eb-9fc4-68a212479cf2.MP4

And a screenshot:

![IMG_19E42DA0F0DD-1](https://user-images.githubusercontent.com/928367/107651649-bcc15300-6c4d-11eb-9de4-4c3c154e81a1.jpeg)

It's kind of tough to debug because it's in TikTok's in-app browser web view. It's happening on Big Cartel for our sellers who link to their Big Cartel shop in their profile bio. People aren't able to checkout and pay with PayPal through TikTok on iOS, which is how we became aware of this issue.

PayPal JS SDK does work on TikTok on Android, as expected, where one can log in and pay.

Getting your account to support a link in the bio is a process I'm not 100% confident in doing again, but I did these steps:

1. enrolled in TikTok beta and installed that app on iOS via testflight
2. changed my account to a business account
3. then was able to add my website

Let me know if I can provide any other details. Thank you!

**Comment by tylerfowle** [comment]
@brettchalupa any update on this? I'm experiencing the same issue.

**Comment by brettchalupa** [comment]
@tylerfowle nope, no updates or new discoveries on my end. This is still happening.

**Comment by brettchalupa** [comment]
This appears to have been fixed based on my latest testing on TikTok v20.1.0 on iOS v14.6. I am going to close this.
