### ISSUE TITLE
Users don't have PayPal balance as a payment method for subscription checkout

### ISSUE THREAD

**Issue by malikwas** [paypal/paypal-checkout-components#1542]
Hey everyone,

We have customers on our site subscribing using PayPal. However, I don't think they're able to use their PayPal balance to complete the checkout and finalize their subscription. On our staging and production setups, we only get options to pay via bank account or credit card:

![Screen Shot 2021-02-10 at 11 10 30 PM](https://user-images.githubusercontent.com/6495327/107601872-ddf65500-6bf5-11eb-90db-4e74dd9f42d0.png)

However, I also want the option to pay using my balance. For example, when I click to complete an order in this [storybook example](https://paypal.github.io/react-paypal-js/?path=/story/example-subscriptions--orders-and-subscriptions), I'm able to get the balance to appear:

![Screen Shot 2021-02-10 at 11 11 59 PM](https://user-images.githubusercontent.com/6495327/107601952-21e95a00-6bf6-11eb-8e79-a1ff6fd16e98.png)

We're noticing in our logs that a lot of users keep opening and closing the checkout window that appears when clicking on the PayPal button, presumably because they want the option to pay with their balance. Is there something I can do to give users the option to pay for the subscription using their balance?

Thanks!

**Comment by ravishekhar** [comment]
PayPal Balance is supported while subscribing using PayPal.

<img width="467" alt="Screenshot 2021-05-13 at 11 15 43 AM" src="https://user-images.githubusercontent.com/5966302/118083609-dacd5980-b3dc-11eb-8a0d-936b57123319.png">
