### ISSUE TITLE
[Bug] Locale have different behavior

### ISSUE THREAD

**Issue by antoniopacheco** [paypal/paypal-checkout-components#1543]
### 🐞 Describe the Bug

The normal behavior for the smart buttons is :
none of them forces of the users to create an account
"Debit or Credit Card" button opens the form in the same page

however when you specify a locale outside of US for example es_MX
all of the buttons will open a modal and will force the user to create an account

🔬 Minimal Reproduction

go to:
https://developer.paypal.com/demo/checkout/#/pattern/server

test the behavior without changing anything.
notice that buttons won't force you to create an account and
"Debit or Credit Card" button opens the form in the same page

now change the script src to
<script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD&locale=es_MX"></script>

😕 Actual Behavior

all buttons force the user to create an account
"Debit or Credit Card" opens in a modal.

🤔 Expected Behavior

Using different locales shouldn't force the user to create a Paypal account (this is the most important one)
Debit or credit card button should open within the page (like when no locale is specified or a US locale)

### 🌍 Environment

- Browser version: -
- OS version: -
- SDK version (`window.paypal.version`): -

### Affected browsers
What browser(s) are affected?

### ➕ Additional Context
Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.

**Comment by i7eo** [comment]
Maybe you should add `enableStandardCardFields: false` to your spb config
[I found the answer in this issue.](https://github.com/paypal/paypal-checkout-components/issues/1467)
