### ISSUE TITLE
[Bug] OnApprove not called when using PayPal Guest Subscription

### ISSUE THREAD

**Issue by roryaherne** [paypal/paypal-checkout-components#1544]
### 🐞 Describe the Bug
OnApprove not called when using PayPal Guest Subscription

### 🔬 Minimal Reproduction
Go to CodePen on https://codepen.io/roryaherne/full/Vwmbrvo
Create a subscription as guest (using the Debit or Credit Card Button). Don't create a paypal account.

### 😕 Actual Behavior
Subscription is completed but the pop up window stays open and onApprove doesn't get fired

### 🤔 Expected Behavior
Popup window should close and onApprove should be fired

### 🌍 Environment

- Browser version: -
- OS version: - Windows 10
- SDK version: paypal-js

### ➕ Additional Context
When creating a subscription via a paypal account the window has this url:

https://www.sandbox.paypal.com/webapps/billing/subscriptions?ba_token=BA-02088077736589136&country.x=AT&locale.x=en_AT&mode=member&sdkMeta=eyJ1cmwiOiJodHRwczovL3d3dy5wYXlwYWwuY29tL3Nkay9qcz9jbGllbnQtaWQ9c2ImdmF1bHQ9dHJ1ZSZpbnRlbnQ9c3Vic2NyaXB0aW9uJmNvbXBvbmVudHM9YnV0dG9ucyIsImF0dHJzIjp7ImRhdGEtdWlkIjoiMzcwOWVjOWFkZF9tZGc2bnRhNm10cSJ9fQ&token=16975028US054300J

But when creating one as a guest it only looks like this:

https://www.sandbox.paypal.com/webapps/billing/subscriptions?country.x=AT&locale.x=en_AT&mode=guest&token=3TJ578590W7641801

![](https://i.imgur.com/ekO4gBR.jpg)

**Comment by gregjopa** [comment]
Thanks for reporting the issue @roryaherne. We are able to reproduce and learned this bug is only happening in the sandbox environment. We are working on getting this fixed asap.

**Comment by ravishekhar** [comment]
@roryaherne Thanks for reporting. This issue is fixed.
