### ISSUE TITLE
[Bug] onShippingChange callback does not reject countries with actions.reject();

### ISSUE THREAD

**Issue by johnpash** [paypal/paypal-checkout-components#1555]
### 🐞 Describe the Bug
Cannot reject countries in `onShippingChange` callback with `return actions.reject()`

### 🔬 Minimal Reproduction
I've created a single html file ([gist here](https://gist.github.com/johnpash/be083d55a4540474ee999d366eaf6d9b)) following the instructions here: https://developer.paypal.com/docs/checkout/integration-features/shipping-callback/#c2cb-target-1

### 😕 Actual Behavior
The "Pay now" button is still enabled, and no error message shows.

### 🤔 Expected Behavior
When the `onShippingChange(data, actions)` fires and a rejected promise is returned `return actions.reject();` the UI should show an error message such as "Sorry, we don't ship to that destination" and also disable the "Pay now" button.

### 🌍 Environment

- Browser version: - Chrome 88.0.4324.192, Safari 14.0.2, Firefox 86.0
- OS version: - MacOS 11.1 - Big Sur
- SDK version (`window.paypal.version`): - 5.0.204

### Affected browsers
See above

**Comment by mbackermann** [comment]
@johnpash I had the same issue.

**Comment by dragosiordachioaia** [comment]
I am getting a similar issue: other actions work as expected, but actions.reject seems to do nothing anymore. This worked until about a week ago.

**Comment by samuelgiles** [comment]
Yeah we're now seeing this, this is really bad, it's making it look like customers can order to countries we don't ship to.

**Comment by amilaev** [comment]
I have the same issue. It was work about week ago, but now when I return `actions.reject();` from `onShippingChange` nothing is happens.

Also you can still change summary price by calling `actions.order.patch()` and it will be updated on PayPal payment page, but seems like `actions.reject();` is broken now.

**Comment by samuelgiles** [comment]
It seems like `actions.order.patch` calls are buggy too? Before the PayPal modal would display a loading icon with a message saying "Contacting the merchant to update your shipping address.". Now we're not seeing that label, instead the address updates instantly and then a couple of seconds "Processing..." is shown after which the amount then updates.

**Comment by johnpash** [comment]
It looks like there was some silent progress made on this with version `5.0.206`. I guess we just have to keep checking until bugs are fixed? Does anyone at PP monitor these issues? Or do they just wait for the Github sweeper to close old issues?

Ranting aside... 

It's now correctly rejecting the country as it has always done before the bug was introduced. But more importantly, **the bug still remains** where the "Pay now" button is not disabled. This means customers are still able to pay for items destined to undeliverable countries if they choose to ignore the "We don't ship to your destination" message.

**Comment by mbackermann** [comment]
@johnpash I have just tested it and I get the same issue. It shows the message that doesn't ship to that location, but the customer is still able to complete the checkout. Looks like PayPal never watches the issues here.

**Comment by amaclean2** [comment]
When `actions.reject()` happens, we send a message to the buyer that the address is not supported, but currently we do not stop the checkout process from continuing. Right now there is a PR out to stop that process and the buyer cannot take further action until they resolve their address choice. This should be the last step in resolving this issue.
Thanks for your patience.

**Comment by johnpash** [comment]
@amaclean2 thanks for the update. It's a little bit concerning that the behaviour changed without notice. So it must have been a bug, and not a feature change? Either way, I await the fix. Thanks again.

**Comment by amaclean2** [comment]
The other thing was the parameters in `onShippingChange()` got out of sync for a few days, but they should be back to what they were before.

**Comment by christian-reichart** [comment]
@amaclean2 Do you have an update on that PR? I am currently still having the issue that the buyer is not blocked to continue until I resolve onShippingChange.

**Comment by amaclean2** [comment]
@christian-reichart , this issue was fixed. I forgot to close it since I'm not an owner of this repo, but what you're talking about sounds like a different issue. If you want to send me an email at `amaclean@paypal.com`, I can help work you through it.

**Comment by christian-reichart** [comment]
@amaclean2 Thanks for your reply. I've created a new issue since I realised that my problem differs from this bug.
Would be happy if you could have a look. :)
https://github.com/paypal/paypal-checkout-components/issues/1648
