### ISSUE TITLE
[Bug] No Breakdown Details

### ISSUE THREAD

**Issue by mbackermann** [paypal/paypal-checkout-components#1556]
### 🐞 Describe the Bug
When I submit an order patch inside `onShippingChange` with Tax and Shipping breakdowns, it doesn't show up when I click on the amount on the top right corner, although it does show the correct total amount. When I first create the order, it does show up. However, when I submit a patch to the order inside `onShippingChange`, it hides those lines.
![image](https://user-images.githubusercontent.com/5454847/109565665-cac9fd00-7ab0-11eb-9944-6df90e7e47be.png)

This is the object that I'm sending to `orders.patch`

```
{
  "op": "replace",
  "path": "/purchase_units/@reference_id=='default'/amount",
  "value": {
    "breakdown": {
      "item_total": {
        "currency_code": "USD",
        "value": 259
      },
      "shipping": {
        "currency_code": "USD",
        "value": 9
      },
      "tax_total": {
        "currency_code": "USD",
        "value": 23.96
      }
    },
    "currency_code": "USD",
    "value": 291.96
  }
}
```

### 🔬 Minimal Reproduction
Create an order. Then submit a patch request changing the tax and shipping amounts.

### 😕 Actual Behavior
No Tax and Shipping breakdown are shown

### 🤔 Expected Behavior
Tax and Shipping values should appear under the breakdown dropdown.

### 🌍 Environment

- Browser version: - Version 88.0.4324.150 (Official Build) (64-bit)
- OS version: - Pop!_OS 20.04 LTS
- SDK version (`window.paypal.version`): - 5.0.204

### Affected browsers
What browser(s) are affected?

All

**Comment by mrphuzz** [comment]
I am very interested in this thread.  I have observed the same problem, and made an SO post about it: https://stackoverflow.com/questions/66466915/paypal-onshippingchange-patch-not-working-as-expected... but there hasn't been a response there yet either.
