### ISSUE TITLE
[Bug] PaypalButton failing in IE11

### ISSUE THREAD

**Issue by aandy28** [paypal/paypal-checkout-components#1560]
### 🐞 Describe the Bug
We currently have a small percentage of users still using IE11 (unfortunately) and when loading the PaypalButton they are receiving the following error:

![image](https://user-images.githubusercontent.com/6472996/110089869-87141380-7d8e-11eb-8bf8-d2c4b75ebdcc.png)

The screenshot is from local development, however this is affecting our production environment as well.

### 🔬 Minimal Reproduction
Try to open and click the PaypalButton component in IE11

### 😕 Actual Behavior
Buttons.js
- Object doesn't support property or method 'find'
- click_initiate_payment_reject [object Object]
- unhandled_error [object Object]

### 🤔 Expected Behavior
button to load and work as expected.

### 🌍 Environment

- Browser version: - IE11
- SDK version (`window.paypal.version`): - 5.0.206

### Affected browsers
What browser(s) are affected?

**Comment by DavidsRaptor** [comment]
I got the same error. See https://github.com/braintree/braintree-web/issues/557

**Comment by shrutikapoor08** [comment]
Thanks for filing this issue. I will take a look.

**Comment by gregjopa** [comment]
This IE 11 bug has been fixed in production. Closing this one out.
