### ISSUE TITLE
[Feature] Ability to force debit/credit card guest checkout to be done on PayPal

### ISSUE THREAD

**Issue by aStonedPenguin** [paypal/paypal-checkout-components#1587]
### 🚀 Feature Proposal

Add the ability to force clicking the "Debit or Credit Card" button to open in a pop up on PayPal's website as it already seems to do in some instances.

### Motivation

While you have the opportunity to enter guest checkout after clicking the PayPal button this escapes many users and is presumably one of the reasons the "Debit or Credit Card" button was added in the first place. Despite the "Powered by PayPal" tagline entering debit/credit card info on the sellers websites directly contradicts PayPal's primary purpose of acting as a trusted intermediary.

### Example

This would allow smaller websites who rely on PayPal's role as a trusted intermediary to better take advantage of the higher conversion rates having the "Debit or Credit Card" button offers without with eroding trust.

**Comment by Jakob-em** [comment]
I still think this is a useful feature to keep the user experience for the credit card checkout consistent with the other checkout options. Additionally the expanding credit card layout can be difficult to account for when integrating the smart buttons.
