### ISSUE TITLE
[Bug] popover the Debit or Credit Card

### ISSUE THREAD

**Issue by i7eo** [paypal/paypal-checkout-components#1596]
Can you provide a parameter to control whether the form will be displayed on the current page or in the pop-up window after clicking `Debit or Credit Card` button ?
i try to add `enableStandardCardFields: false` in my spb config option, but it didn't  work.

**Comment by savtrip** [comment]
This is something that we are also wanting. We have found multiple customers complain about the debit/credit card buttons when it displays on the UI instead of a Popup window. Is there a parameter to force it to go to the popup window when you click the debit/credit card button? @gregjopa

**Comment by i7eo** [comment]
Oops...
Nobody seems to be paying any attention to us
