### ISSUE TITLE
@Subscription: Charge user pro rata amount and subscribe user at the same time or vise versa

### ISSUE THREAD

**Issue by LavoTP** [paypal/paypal-checkout-components#1614]
## Description  
I want users to be able to choose when they want their subscription start,  
of course i restrict date range from now to two weeks.  

e.g. a user buys or subscribes to my service and choose that hi/her subscription start next week   
so i will have to charge this user a pro rata amount like some amount this week because they will be using the service  until their subscription start.  

so i want to know if is it possible to make a once off payment and subscription at the same time?  

i saw this issues [https://github.com/paypal/paypal-checkout-components/issues/1282](url) and am very clear on how to intergrade subscription using the smart button.  the only thing now is how do i make a purchase and subscribe a user at the same time.

Please help  
Thanks in advance

**Comment by ravishekhar** [comment]
You can use the start_time attribute to define when a subscription should start.

```javascript
paypal.Buttons({
      style: {
          shape: 'rect',
          color: 'gold',
          layout: 'vertical',
          label: 'subscribe'
      },
      createSubscription: function(data, actions) {
        return actions.subscription.create({
          plan_id: 'P-XXXXXXXXXXXXX',
          start_time: '2021-05-30T06:02:03.518Z' 
        });
      },
      onApprove: function(data, actions) {
        alert(data.subscriptionID); // You can add optional success message for the subscriber here
      }
  }).render('#paypal-button-container-P-XXXXXXXXXXXXX');
```

<img width="455" alt="Screenshot 2021-05-13 at 11 33 04 AM" src="https://user-images.githubusercontent.com/5966302/118084948-2da81080-b3df-11eb-936b-32ea10e82c13.png">



Regarding
> so i want to know if is it possible to make a once off payment and subscription at the same time?

Subscriptions supports charging a setup fee, which can be set while creating a plan. This amount will be charged to the buyers while subscribing. 
Please let me know if it answers your question?

**Comment by LavoTP** [comment]
Thank you = yes this helped. i will use the setup fees
