### ISSUE TITLE
404 on https://www.paypalobjects.com/api/checkout.4.0.329.js

### ISSUE THREAD

**Issue by Pwntastic** [paypal/paypal-checkout-components#1617]
Requesting https://www.paypalobjects.com/api/checkout.4.0.329.js returns a 404, which is causing the Paypal checkout button to become nonfunctional

**Comment by mnicpt** [comment]
@Pwntastic Can you request `https://www.paypalobjects.com/api/checkout.js` instead?  Or are you tied to that version?

**Comment by Pwntastic** [comment]
we're not loading it directly, we're using paypal-checkout ^4.0.314 which decides to load it based on other scripts coming from paypal.

forgive me if this is the wrong repo for this; i had seen some older issues referencing similar things in the past

**Comment by mnicpt** [comment]
@Pwntastic This is the correct location.  I will take a look.  Sorry that you are experiencing this issue.

**Comment by mnicpt** [comment]
@Pwntastic Can you lock in at version 328 for now until we get this published to our CDN.  We are shooting for EOD tomorrow.

**Comment by Pwntastic** [comment]
@mnicpt i think we can do that, thanks

**Comment by gregjopa** [comment]
Hi @Pwntastic we were unable to deploy 4.0.329 to the cdn today so we deprecated it on npm and made 4.0.328 the latest. The recommendation is to stick with 4.0.328 until a new version gets released next week.
