### ISSUE TITLE
[Bug] Bug report - PayPal with credit card newer finishing

### ISSUE THREAD

**Issue by toloekka** [paypal/paypal-checkout-components#1624]
### 🐞 Describe the Bug
We have a website with this page https://nwotv.no/videos/leie-uman-jakt/film-kun-for-test with a payment solution with PayPal that does not work with paying by bank card by clicking directly on "Debit or Credit Card".
I fill in all the bank card information, click "Pay now", insert a code from the bank and then it stops. Gets only a dialog window that says "Processing" and is never finishing.
See attachments "this-creditcard-payment-wont-work.jpg" and "red-dots-handling.jpg".

If I click the PayPal button first and go on to «Pay by debit card», then it works. Then I get another dialog window for filling in card information.
See attachments «this-creditcard-payment-works.jpg».

The web developer (https://www.wpvideosubscriptions.com emailddress: support@wpvideosubscriptions.zendesk.com) who created the WordPress template / theme says he could pay by clicking directly on "Debit or Credit Card" without any problem. The web developer of the template / theme is from Canada and made the payment from there.

A test page with login (you must have an account to be able to pay / test) is as I can give you login to: https://nwotv.no/videos/leie-uman-jakt/film-kun-for-test/
Login info can be provided.

What can be done about this?

Payment with PayPal account (not with credit card option) works as it should.

### 🔬 Minimal Reproduction
**_See the description above._**

### 😕 Actual Behavior
**_See the description above._**
Console log and Network log. See pdf-files "Console.pdf" and "Network.pdf".

### 🤔 Expected Behavior
The payment go through like when clicking PayPal button first and then chose "Debit or Credit Card"".

### 🌍 Environment

- Browser version: - Versjon 90.0.4430.93 (Offisiell delversjon) (x86_64)
- OS version: - Mac OS 10.13.6 (But same problem on Windows 10)
- SDK version (`window.paypal.version`): -

### Affected browsers
What browser(s) are affected?
Chrome, Firefox and Safari on my Mac OS 10.13.6. Chrome on Windows 10).

### ➕ Additional Context
Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.
[Console.pdf](https://github.com/paypal/paypal-checkout-components/files/6409160/Console.pdf)
[Network.pdf](https://github.com/paypal/paypal-checkout-components/files/6409161/Network.pdf)
![this-creditcard-payment-wont-work](https://user-images.githubusercontent.com/83489576/116776597-74a21780-aa69-11eb-83b6-5812e6b04cc2.jpg)
![this-creditcard-payment-works](https://user-images.githubusercontent.com/83489576/116776603-78ce3500-aa69-11eb-88ca-2d85d224944f.jpg)
![red-dots-handling](https://user-images.githubusercontent.com/83489576/116776606-7ff54300-aa69-11eb-8c5f-e4dd772d2ac7.jpg)

**Comment by f2boot** [comment]
Same problem for me.
Buy now has no effect (no message in console either)
Sometime I get an overbox (like the one when opening paypal) opening, then closing, then I get redirected to the page configured for failed payment.

Can't disable these "Standard Cards Fields" either as a temporary solution.

**Comment by toloekka** [comment]
Bump
