### ISSUE TITLE
[Bug] Bug report - Standalone Buttons not working

### ISSUE THREAD

**Issue by Erseni** [paypal/paypal-checkout-components#1629]
### 🐞 Describe the Bug
The standalone button integration is broken
https://developer.paypal.com/docs/checkout/integration-features/standalone-buttons/

Rendering a single button is broken for all provider except paypal.

### 🔬 Minimal Reproduction
```
paypal.getFundingSources().forEach(function (fundingSource) {
      var button = paypal.Buttons({
          fundingSource: fundingSource,
      });
      if (button.isEligible()) {
          button.render('#payment-' + fundingSource);
      }
  });
```

### 😕 Actual Behavior
After click on the button nothing happens and this error shows up:
`integration_error {err: "hosted components not found", timestamp: "1620411168027", referer: "www.sandbox.paypal.com", sdkCorrelationID: "32f43adc04355", sessionID: "49d5a29d7e_mtc6ntm6mju", …}`
And a second error:
`click_initiate_payment_reject {err: "Error: Hosted components not found↵    at https://…mmit=true&debug=true&supportsPopups=true:7404:38)", timestamp: "1620411168029", referer: "www.sandbox.paypal.com", sdkCorrelationID: "32f43adc04355", sessionID: "49d5a29d7e_mtc6ntm6mju", …}`

### 🤔 Expected Behavior
PayPal popup should open.

### 🌍 Environment

- Browser version: Latest Chrome
- OS version: Windows 10
- SDK version (`window.paypal.version`): "5.0.224"

### Affected browsers
What browser(s) are affected?

- Chrome
- Safari
- Firefox
- Edge
- IE
- Chrome Mobile/Tablet
- Safari Mobile/Tablet
- Web View / Safari ViewController
- Other

**Comment by dx-bhesse** [comment]
The browser probably fired a POST-Request to https://www.sandbox.paypal.com/v2/checkout/orders that failed and the "hosted components not found" error is generated as a result of that.
Check the response the browser got for that POST-request - it might reveal the actual problem.
(The described behaviour for example may occur if the order total amount is zero)

**Comment by Erseni** [comment]
No there is just a POST to https://www.sandbox.paypal.com/xoplatform/logger/api/logger  and those two errors from above in the console.  
It was working in APRIL but one of the releases broke the standalone buttons.  
Here is a fiddle with the code from https://developer.paypal.com/docs/checkout/integration-features/standalone-buttons/
https://jsfiddle.net/gv2m7zae/

**Comment by Erseni** [comment]
Thanks it is fixed now.
