### ISSUE TITLE
[Documentation] Update VueJS sample on official page

### ISSUE THREAD

**Issue by ivcuello** [paypal/paypal-checkout-components#1630]
The current checkout sample posted on the [official documentation][1] in  doesn't works as expected. 

The errors and unexpected behavior are documented on the issue #1540 .

However there are  working samples on GitHub such as that produce the desired results as seen at the [last interactions][2] on the issue #1338 by @z1haze.

Please update the docs to include [this working sample][2].

[1]: https://developer.paypal.com/docs/business/checkout/configure-payments/single-page-app/#vue

[2]: https://github.com/paypal/paypal-checkout-components/issues/1338#issuecomment-777005173

**Comment by leogedler** [comment]
The documentation has been updated with a [new example](https://developer.paypal.com/docs/business/checkout/configure-payments/single-page-app/#vue).

**Comment by gregjopa** [comment]
Thanks for getting this updated @leogedler! closing this one out.
