### ISSUE TITLE
javascript error in API

### ISSUE THREAD

**Issue by Ed-SA** [paypal/paypal-checkout-components#1642]
Since this morning, the API is crashing with "Unable to get property 'paypal-debug-id' of undefined or null reference\n   at un (https://www.paypal.com/smart/buttons?".  Nothing has changed on our end, has there been something new deployed?

**Comment by bluepnume** [comment]
Thanks for the report @Ed-SA. @mnicpt is rolling out a fix, can you please update this ticket when the release is complete.

**Comment by Ed-SA** [comment]
Will do




Ed Sargent
Director of Software Development

[cid:SITS-Logo-20th-Anniversary-Final-lo_9a43e6cc-4beb-475b-a564-fdafdf836e9e.jpg]


2215 E. Waterloo Rd., Suite 111
Akron, 44312
330-785-9467 x202
***@***.***


<https://www.facebook.com/summititsolutions>

[cid:Facebook_3762a8ad-797d-4395-957e-06fc6a208734.png][cid:SocialLink_Twitter_32x32_14cc9cc0-01f4-4c65-b2f4-772865a3cae8.png]<https://twitter.com/SummitITAkron>[cid:LinkedIn_573bac43-b7eb-40ee-9bb8-b025f38210c5.png]<https://www.linkedin.com/company/summit-it-solutions-inc-/>[cid:Instagram_598f8c72-25cc-444b-b899-3e0ae5cc22bf.png]<https://www.instagram.com/summititsolutionsinc/>   [cid:MicrosoftTransparent_f6c2e0fb-0b24-4a80-a337-368832b07fea.png]

Stablize. Secure. Soar. We offer Managed IT Solutions to fit your company size, budget, and technology requirements. Click ***@***.***/bookings/> to book a One-on-One discussion to qualify for a free network assessment!

**Comment by Ed-SA** [comment]
This issue seems to have been resolved with one of the recent releases, we have not seen any further occurrences of this error or the seemingly related empty error since 6/4.
