### ISSUE TITLE
[Feature/Bug?] Subscriptions: Allow only one Trial per PayPal account

### ISSUE THREAD

**Issue by el1s7** [paypal/paypal-checkout-components#1709]
After doing some tests on PayPal Subscriptions I found that it is possible for someone to sign up multiple times in subscription and get multiple trials from the same PayPal account. 

The only way to prevent this currently is by storing the `payer_id` and disallowing new subscriptions, but this is not ideal and leads to other issues.

It would really be better if PayPal would skip the trial cycle and charge directly for accounts that have already used the trial before.

**Comment by dj110919871** [comment]
blue

**Comment by joaomoon** [comment]
same problem here
