### ISSUE TITLE
Magento 2 PayPal popup issue

### ISSUE THREAD

**Issue by jawadalishah6068** [paypal/paypal-checkout-components#1717]
### 🐞 Describe the Bug
Magento 2 PayPal popup issue: When I click “pay with PayPal” the window pops up for split second and then vanishes. Issue is only happen for first time after refreshing it will work fine.

### 🔬 Minimal Reproduction
Describe steps to reproduce. If possible, please, share a link with a minimal reproduction.

### 😕 Actual Behavior
Paypal popup not working

### 🤔 Expected Behavior
Paypal popup open then customer pay payment through paypal .

### 🌍 Environment

- Browser version: -
- OS version: -
- SDK version (`window.paypal.version`): -

### Affected browsers
What browser(s) are affected?

### ➕ Additional Context
Console error :
ppxo_unhandled_error 
Object { stack: "Expected reject to be called with Error, got [object Undefined]\ns</o.reject@https://www.paypalobjects.com/api/checkout.min.js:2:18759\ne@https://www.paypalobjects.com/api/checkout.min.js:2:18298\npayment@https://eadn-wc02-4601666.nxedge.io/cdn/static/version1628582722/frontend/americanfireglass/afg/en_US/Magento_Paypal/js/in-context/express-checkout-smart-buttons.min.js:2:621\n@https://www.paypalobjects.com/api/checkout.min.js:2:835612\ne@https://www.paypalobjects.com/api/checkout.min.js:2:18140\n@https://www.paypalobjects.com/api/checkout.min.js:2:835290\ns</e.try@https://www.paypalobjects.com/api/checkout.min.js:2:21987\ndecorate/<@https://www.paypalobjects.com/api/checkout.min.js:2:818839\nn@https://www.paypalobjects.com/api/checkout.min.js:2:383051\nb</</<@https://www.paypalobjects.com/api/checkout.min.js:2:127555\ns</e.try@https://www.paypalobjects.com/api/checkout.min.js:2:21987\nb</<@https://www.paypalobjects.com/api/checkout.min.js:2:127523\nw[l.b.POST_MESSAGE_TYPE.REQUEST]/<@https://www.paypalobjects.com/api/checkout.min.js:2:115516\ns</e.try@https://www.paypalobjects.com/api/checkout.min.js:2:21987\nw[l.b.POST_MESSAGE_TYPE.REQUEST]@https://www.paypalobjects.com/api/checkout.min.js:2:115218\nL@https://www.paypalobjects.com/api/checkout.min.js:2:117244\n_@https://www.paypalobjects.com/api/checkout.min.js:2:117488\n\nw[l.b.POST_MESSAGE_TYPE.RESPONSE]@https://www.paypalobjects.com/api/checkout.min.js:2:116347\nL@https://www.paypalobjects.com/api/checkout.min.js:2:117244\n_@https://www.paypalobjects.com/api/checkout.min.js:2:117488\n", errtype: "[object Error]", timestamp: 1628595129658, windowID: "e991eb0d05", pageID: "96c6685782", prev_corr_ids: "", referer: "https://c9df297ea0.nxcli.net", host: "www.sandbox.paypal.com", path: "/smart/button", env: "sandbox", … }
logger.js:63:34
![image](https://user-images.githubusercontent.com/74955878/128863672-f2ada418-3fd3-4a45-8641-4ffd87076416.png)

**Comment by dennsuwanda777** [comment]
***@***.***
