### ISSUE TITLE
[Bug] Smart Payment Button iframe Does NOT Mark All Necessary Fields for Debit/Credit Card

### ISSUE THREAD

**Issue by madprogramer** [paypal/paypal-checkout-components#1753]
### 🐞 Describe the Bug
When using the new [smart check-out buttons](https://developer.paypal.com/docs/checkout/) for Debit/Credit Card checkout, the debit/credit card option will not mark all necessary fields consistently. In particular, it might appear to "lock up" until a valid e-mail address and phone number are specified without ever generating an error message.

### 🔬 Minimal Reproduction
1. Download a smart button from the [smart button maker tool](https://www.paypal.com/buttons/smart).
2. Save as an HTML file and either open it up in a browser, or host it on a server if you have any proficiency with that.
3. Choose to make a payment under the Debit/Credit Card option..
4. Attempt to click on `Pay Now` without completing all fields. This is when you should expect _some_ necessary fields to give a warning. See `Additional Context` for a visualisation and `Actual Behaviour` below, for more details.
5. Fill in **all marked** necessary fields (with mock information, see [test transactions page](https://developer.paypal.com/docs/payflow/integration-guide/test-transactions/)) and attempt to `Pay Now` again. Chances are the `Mobile` or `Email` field will remain unmarked and the screen will refuse to advance (despite the two fields being seemingly mandatory)

### 😕 Actual Behavior
Prevents advancing with payments when not all fields are filled. Does not tell user what necessary fields are missing consistently, if at all, seemingly locking up. If `Mobile` and `Email` are intended to be optional fields, that's two glitched in one.

### 🤔 Expected Behavior
All "necessary" fields in the Debit/Credit Card payment option being marked correctly if not filled, instead of locking up.

### 🌍 Environment

- Browser version: Brave Version 1.29.81 Chromium: 93.0.4577.82; also on Firefox 92.0.1 and Safari 14.1.2) -
- OS version: macOS 11.6-
- SDK version (`window.paypal.version`): 5.0.259-

### Affected browsers
What browser(s) are affected?

- Chrome/Chromium
- Safari
- Firefox

### ➕ Additional Context

Below are two separate instances of different fields being shown as "necessary" when `Pay Now` is clicked, with `Mobile` and `Email` never being marked.
![image](https://user-images.githubusercontent.com/3719664/135348048-3f9fea03-e1b0-459f-a1da-e4c3a78705f0.png)
![image](https://user-images.githubusercontent.com/3719664/135357579-f041b093-c1b9-40d3-8040-76d17d5262db.png)

**Comment by manavmodi22** [comment]
Can replicate this behaviour as well. Basically if the fields are explicitly focused, by clicking on them only then the fields show the error behavior. Also initially, even the card fields if left empty and pay now button is pressed don't display any errors.
![image](https://user-images.githubusercontent.com/55242552/135704726-8cd55626-8c3f-434c-9530-f7c45bd47f23.png)

**Comment by Pretty-19** [comment]
Hi, @madprogramer Can you assign this issue to me?

**Comment by madprogramer** [comment]
Still unsolved/

**Comment by madprogramer** [comment]
bump

**Comment by madprogramer** [comment]
bump

**Comment by MahamatTech** [comment]
I checked and it's working 

![screenshot-127 0 0 1_5500-2022 10 03-00_43_17](https://user-images.githubusercontent.com/88563359/193503425-eba2ece6-62d0-4f2c-bd23-24d95a4b30c7.png)

**Comment by MahamatTech** [comment]
do you want me to fix for the appt number?

**Comment by madprogramer** [comment]
bump
