### ISSUE TITLE
[Bug] Smart Button embed not advancing if user has not typed in any input field

### ISSUE THREAD

**Issue by madprogramer** [paypal/paypal-checkout-components#1754]
### 🐞 Describe the Bug
When using the new [smart check-out buttons](https://developer.paypal.com/docs/checkout/) if the customer never "types" the values for the `Variable Price` template, it will refuse to advance to check out.

### 🔬 Minimal Reproduction
1. Download a smart button from the [smart button maker tool](https://www.paypal.com/buttons/smart), use the `Variable Price` template.
2. Save as an HTML file and either open it up in a browser, or host it on a server if you have any proficiency with that.
3. Edit the HTML file to assign a `value` for the `descriptionInput` element.
4. Load the page and **use only the counter** to increment the price. See Additional Context for a visualization.
5. Attempt to check out either through Pay Pal or Debit/Credit Card. The check-out should never load.

### 😕 Actual Behavior
After about 30-60 seconds a `Failed to load resource: net::ERR_CONNECTION_TIMED_OUT` is raised from `counter.cgi:1`. Check-out fails to load.

### 🤔 Expected Behavior
Payment should advance to check-out as expected, the `createOrder` callback should run without error. You may click on either field and type in anything to continue as normal.

### 🌍 Environment

- Browser version: Brave Version 1.29.81 Chromium: 93.0.4577.82; also on Firefox 92.0.1 and Safari 14.1.2) -
- OS version: macOS 11.6-
- SDK version (`window.paypal.version`): 5.0.259-

### Affected browsers
What browser(s) are affected?

- Chrome/Chromium
- Safari
- Firefox

### ➕ Additional Context

Make sure not to press anything on the keyboard when inside of a field, using only the counter on the right to inc/decrement the price. 

<img width="769" alt="temp" src="https://user-images.githubusercontent.com/3719664/135364090-561ebd77-0681-46b3-8c56-420fb0808de4.png">

**Comment by manavmodi22** [comment]
Can confirm this behavior.
![image](https://user-images.githubusercontent.com/55242552/135704471-fe3d269a-0953-482f-97e4-895ae3f1f146.png)
also the ideally the counter shouldn't take in negative values, but it does.

**Comment by madprogramer** [comment]
Hmm... on second thought maybe I should for this in, before closing the issue?

**Comment by madprogramer** [comment]
It seems that the [example code](https://github.com/paypal/paypal-checkout-components/issues/1754#issuecomment-948053537) for `https://www.paypal.com/buttons/smart` is **NOT** on this repo. Let's hope someone from PayPal eventually sees this issue and considers thinking.

**Comment by madprogramer** [comment]
bump

**Comment by RithMB** [comment]
bump

**Comment by rithnhel** [comment]
bump

**Comment by madprogramer** [comment]
:| PayPal, why?!
