### ISSUE TITLE
[Documentation] How to enable modal/iframe/lightbox PayPal flow

### ISSUE THREAD

**Issue by ctsimpouris** [paypal/paypal-checkout-components#1776]
### 📙 Describe the Issue
I can see a way PayPal loading as a modal/iframe/lightbox (really not sure what is the appropriate term, from now on I will just call it modal) however I am unable to identify the documentation to do so. Note: Popup new window is NOT what I am refering to. After a lot of research I am really unable to identify the solution, so I am posting for a) maybe solution is more simple or out of the box and I am missing it and b) maybe out there others too are looking for it. In theory we have the following ways:
1. Redirect
2. Modal window
3. Popup window

### 🔬 Minimal Reproduction
I will explain existing implementation as it is as close as possible to what I can provide

### 🤔 Expected Behavior
Given a simple execution, I would like to enforce modal window or be able to let PayPal use that option in a spesific context. In [ChargeBee](https://www.chargebee.com) we have already connected PayPal. When using the same app in Browser, everything works as expected with the classic approach of Popup window. However, our app also runs in Webview (Windows and MAC) which in this case popup window are not allowed. There, no redirection happens and PayPal appears as modal window.
![Charalampos-21-10-2021-16-36-43](https://user-images.githubusercontent.com/42470074/138289454-8ab67453-7357-4563-b340-f1bad8e88010.gif)
Trying to reverse engineer it, nothing special seems to happen around the button (I was trying to identify "hidden init params")
```javascript
....
               renderPaypal: function(t) {
                    var e = this
                      , i = this.sandbox_site ? "sandbox" : "production";
                    return paypal.Button.render({
                        env: i,
                        style: {
                            size: "medium",
                            color: "gold",
                            shape: "rect",
                            label: "checkout",
                            tagline: !1
                        },
                        payment: function() {
                            return e.step = "REQUESTED",
                            e.getPaymentPromise(t)
                        },
                        onAuthorize: function(i, n) {
                            return e.handler(t, i)
                        },
                        onCancel: function() {
                            e.step = "NOT_AUTHORIZED"
                        },
                        onError: function(t) {
                            e._display_common_error(),
                            logger.e(t)
                        }
                    }, "#paypal-button").then(function() {
                        e.step = "RENDERED"
                    })
                },
                handler: function(t, e) {
....
```

### 😕 Actual Behavior
In the process of dumping existing implementation and developing natively PayPal, flow with Express Checkout is implemented as expected and works nicely with the popup window. However, we are unable to enforce modal window and redirect happens when in webview. In the context that "this is doable somewhere else" and "implementation _seems_ basic", I tried to post an issue as _documentation issue_, as I am unable to identify where such documentation supports it.

### ➕ Additional Context
- I have seen various issues discussing that "lightbox" has been deprecated around 2017, but I am not entirely sure if it's related.
- I am afraid that this functionality (modal) is supported out of the box and `checkout.js` decides when to do so. Is this the case? And if yes, when this happens and how can I facilitate it?

### Search keywords
iFrame, modal window, lightbox, popup

Any help is really appreciated

**Comment by ctsimpouris** [comment]
bump

**Comment by ansient0** [comment]
[PayPal security guidelines](https://developer.paypal.com/api/rest/reference/info-security-guidelines/#link-donotuseawebviewtodisplaypaypalwebpageswithinyourapplication) say to not use webviews, but rather "the system browser or an approved browser-view mechanism such as Safari View Controller on iOS or Chrome Custom Tabs on Android."  What these all have in common is an address bar so that the user can confirm they are logging into the actual PayPal site, rather than some lightbox pretending to be PayPal.

**Comment by ctsimpouris** [comment]
@ansient0 it doesn't matter actually what it **says** but what it **does**. Checking out the gif it seems feature is already out there in production environment. My question was how to enable it explicitly.
