### ISSUE TITLE
[Bug] PayPal button gets a fat blue border on click and does not work

### ISSUE THREAD

**Issue by leolux** [paypal/paypal-checkout-components#1821]
### 🐞 Describe the Bug
When clicking the mounted PayPal button for the first time  (somtimes even 3 times in row) the PayPal dialog does not open and the user is forced to click a second, or third time. In this case the PayPal buttom shows a blue border directly after the click which stays there until the next click.

### 😕 Actual Behavior
There is NO callback action during this bug and the console does not log anything. When the button works on the second click you have to reload the webseite to reenable the bug behavior.

### 🤔 Expected Behavior
PayPal has to open the dialog, or show some user message or fire some callback instead of doing nothing but adding a fat blue border

### 🌍 Environment
Latest Chrome version (stable)
Vuejs and
Sandbox PayPal Version 5.0.271
Windows 10

### Affected browsers
Chrome and others have not been tested.

### ➕ Additional Context
![Blue-Border](https://user-images.githubusercontent.com/5385814/147249168-df8338d2-22e6-4493-883a-288c60ec7ed1.png)

**Comment by Jay8181** [comment]
Hey @leolux, I was trying to reproduce the error, but facing issues with setting it up on my local environment. Actually npm test command is throwing errors. Can you pls let me know the steps for setting up it in local machine, so that I can reproduce the bug and solve this issue...
