### ISSUE TITLE
[Bug]payment endpoint: http 200 {"ack":"permission_denied","message":"Insufficient privileges"}

### ISSUE THREAD

**Issue by sabrina-fsl** [paypal/paypal-checkout-components#1994]
paypal.version "4.0.336"
Using paypal button (https://www.paypalobjects.com/api/checkout.js) with successful transaction in sandbox but getting error in production.
The http status returns 200, the amount is debited from the credit card, but the response returns an error {"ack":"permission_denied","message":"Insufficient privileges"}.
I've tried to add  "upgradeLSAT: true" as suggested in other issue report, but it didn't work either.

![Screen Shot 2022-08-24 at 12 25 02](https://user-images.githubusercontent.com/89555549/186459769-38c86e00-7706-46f2-bf9b-63f34d80d76e.png)
<img width="1199" alt="Screen Shot 2022-08-24 at 12 22 17" src="https://user-images.githubusercontent.com/89555549/186459839-2b26ec54-0620-4451-a889-339efdb3b22d.png">
<img width="1068" alt="Screen Shot 2022-08-24 at 12 22 45" src="https://user-images.githubusercontent.com/89555549/186459899-b6609a52-52c6-4d10-a859-eeee1fbab206.png">

### 🤔 Expected Behavior
No error returned.

### 🌍 Environment

- Browser version: - Chrome Version 104.0.5112.101
- OS version: - Mac OS Monterey - v.12.5
- SDK version (`window.paypal.version`):  Version 104.0.5112.101

**Comment by sabrina-fsl** [comment]
bump

**Comment by lukejames1111** [comment]
bump

**Comment by sabrina-fsl** [comment]
Paypal button is working fine again. The bug was fixed without any new coding in the application.
