### ISSUE TITLE
[Bug] (Gemany) SEPA, SOFORT payments fail

### ISSUE THREAD

**Issue by nick4414** [paypal/paypal-checkout-components#2017]
### 🐞 Describe the Bug
A lot of payments with SEPA and SOFORT fail. The buyer pays for the product and the bank account is charged with the amount. Then the buyer gets an email a couple of days later, that the transaction has failed and the money will be transferred back to their account.
The booking wasn't successful, so OnCapture is never called and the booking doesn't go through on our website.

### 🔬 Minimal Reproduction
It's difficult to reproduce, but it seems to happen with different banks from Germany, Austria and Switzerland. I guess you are already aware of that problem.

### 😕 Actual Behavior
Either the problem has to be fixed, so that SEPA and SOFORT is working or the buyer has to be notified that the payment is not going to work **before** paying for the product. Otherwise the buyer has to wait for at least 5 days to get his money back and try the payment with a different payment option.

**5-10% of our buyers experience this problem and I also know other companys who have the same problem as well. So it's a major problem.**

Thanks for the help !

I know the screenshot is in German. But this is the email.
![WhatsApp Image 2022-09-21 at 10 00 48](https://user-images.githubusercontent.com/55059394/195319854-3223fbdb-3b41-4b74-b38c-21c499ec612b.jpeg)

**Comment by GRSM78** [comment]
This issue still persists and is super annoying
