### ISSUE TITLE
[Feature] The Marks component needs a style prop similar to the buttons component 

### ISSUE THREAD

**Issue by CBoensel** [paypal/paypal-checkout-components#2034]
### 🚀 Feature Proposal

Similar as for buttons in the JS SDK, we need styling options for the marks component 

### Motivation

Without this option, merchants are forced to overwrite our stylings if not fitting their requirements, which isn't super nice. See https://github.paypal.com/cboensel/get-eligible-funding-sources/blob/master/SPB_with_Standalone_DE004.html#L42 for an example. 

### Example

 ```js
style: {
    layout: 'vertical', // or 'horizontal'
    color:  'white', // or 'grey' ... background
    shape:  'rect', // ...
    label:  'show/verbose' // to show payment method name next to the mark (especially important to credit cards, since the mark isn't that intuitive to identify 
  }
```

**Comment by gregjopa** [comment]
Hi @CBoensel for the Marks component, the merchant should be able to use their own css to style them since they are not wrapped in an iframe.

**Comment by CBoensel** [comment]
@gregjopa Yes, true. That's what I did in the linked example https://github.paypal.com/cboensel/get-eligible-funding-sources/blob/master/SPB_with_Standalone_DE004.html#L42 after all. However, I feel that 
(1) we can make it merchants a little easier and provide stylings that we'd prefer and from a corporate identity perspective and
(2) we should try to be consistent with the feature offering the `buttons` components also provide. Do you disagree? Also see the `label` suggestion (most relevant for credit card).

**Comment by CBoensel** [comment]
The label feature would also be very suitable to localize the local pay later product names: 

`en-US` : PayPal, Pay Later
`en-UK` : PayPal, Pay in 3
`fr-FR` : PayPal, Paiement en 4X
`de-DE` : PayPal, Später Bezahlen
`it-IT` : PayPal, Paga in 3 rate
`es-ES` : PayPal, Paga en 3 plazos
`en-AU` : PayPal, Pay in 4
