### ISSUE TITLE
[Bug] Typo in German Pay Later Button: "Später bezahlen" instead of "Später Bezahlen"

### ISSUE THREAD

**Issue by CBoensel** [paypal/paypal-checkout-components#2040]
### 🐞 Describe the Bug
The wording on the German Pay Later button should say "Später **b**ezahlen" instead of "Später **B**ezahlen". 

- 1st major argument: In German language, there is no capitalization of words in headers / names / brands. Typically, just the first word is capitalized. 
- 2nd major argument:  Let's be consistent with the German wording "Jetzt **k**aufen" (en: Pay Now, see screenshot below). 

### 🔬 Minimal Reproduction
Render the pay later button with `enable-funding=paylater`, set buyer country to `de` in sandbox. See image: 

![pay-later-typo-de](https://user-images.githubusercontent.com/4338717/206157216-5f2485df-b4c2-42d6-928d-d8bd597640e2.png)

### 😕 Actual Behavior
"Später **B**ezahlen"

### 🤔 Expected Behavior
"Später **b**ezahlen"

### 🌍 Environment
All

### Affected browsers
All

### ➕ Additional Context

German marketing also just refers to "Später bezahlen" for the reasons mentioned in the description. See https://www.paypal.com/de/enterprise/pay-later (contact: Christina Klug). 

We discussed this with product managers, with marketing, also publicly in Slack, see https://paypal.slack.com/archives/C012UT8NQJX/p1625055743061300. It's common sense by now locally, but no-one took ownership so far to drive this. That's why I wanted to try filing here again.

**Comment by wsbrunson** [comment]
After further internal discussion, we are leaving this as is
