### ISSUE TITLE
[Feature] Dynamic / Custom payment for subscriptions

### ISSUE THREAD

**Issue by oberoi90** [paypal/paypal-checkout-components#2107]
### 🚀 Feature Proposal

We have a custom payment widget - where the customer can select the amount they would like to pay monthly. Using the old way of payment (submit form) we could just create a subscription without even a plan. But we are trying to move to the Express Checkout now and there is no way for us to create subscriptions with different amounts. 

We don't want to create 100s of different subscription plans when customer select a custom amount. 

Please suggest an easy way for this.

If we can pass the custom amount along with the plan_id would be best

### Motivation

We have a lot of payments coming through everyday. We were recently asked by Paypal to switch to this new way because the old form submit is no more supported.

### Example

A widget that allows customers to enter custom amount and they will be subscribed to that amount on monthly basis.

**Comment by oberoi90** [comment]
Actually I was able to achieve this by the following code:

`return actions.subscription.create({
                        /* Create the subscription */
                        plan_id: paypalPlanId,
                        custom_id: "",
                        "plan": {
                            "billing_cycles": [{
                                "sequence":1,
                                "pricing_scheme": {
                                    "fixed_price": {
                                        "value": donationAmount,
                                        "currency_code": "EUR"
                                    },
                                },
                            }],
                            "taxes": {
                                "percentage":"0"
                            }
                        }
                    });`

**Comment by devchristina** [comment]
Hi @Divinebosst -- at present the current subscription api does not support creating a subscription without a plan_id, e.g. a custom plan.

A merchants integration can pass an additional plan object along with a planId when creating a subscription which will create a overridden plan for that particular subscription only, you can find that documentation here:
https://developer.paypal.com/docs/api/subscriptions/v1/#subscriptions_create!path=plan&t=request

Your latest question appears that your confusion is being created from where the pricing of a subscription is shown in two places one when you click the planId and one right below the subscription. Is this a fair conclusion? ![Screenshot 2023-09-11 at 5 55 28 PM](https://github.com/paypal/paypal-checkout-components/assets/84518758/8c8e8cd6-765a-4b76-ad18-b9e2437424b5)

If yes, generally pricing data is shown in both places, i.e. if you click Plan Name or one below will be always same, unless the merchants integration passed a customized plan when creating a subscription or updated the amounts for a subscription later. In that case UI will show them a customized flag ![Screenshot 2023-09-11 at 5 54 14 PM](https://github.com/paypal/paypal-checkout-components/assets/84518758/cbf35ace-a1d0-4d3f-b3d7-7483e78c8da0)
