### ISSUE TITLE
GitHub 

### ISSUE THREAD

**Issue by onegirlanna87** [paypal/paypal-checkout-components#2148]
https://www.paypal.me/IV4IQ44M

**Comment by onegirlanna87** [comment]
> https://www.paypal.me/IV4IQ44M

**Comment by MrThingchaiWaon** [comment]
This code will let you log in to your Wise account, so don't share it with anyone, even a Wise employee. Your code is: 776999. EFTM0ipbQEk

**Comment by monti-star** [comment]
@onegirlanna87 Unsure of your intention with these posts, but they are being closed as not planned since they appear to have an intention of spam.
