### ISSUE TITLE
What does this graph-ql error mean 'OAS_GENERIC_ERROR'

### ISSUE THREAD

**Issue by huweihong** [paypal/paypal-checkout-components#2151]
I'm using test card to payment in the sandbox. The payment was ok before. But today I met the error 'OAS_GENERIC_ERROR'. What's the error mean? How to resolve it?

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/233818/233829485-d1b4acc6-fd7b-40db-beaf-a8bf8f0ab493.png">

**Comment by blackchineykh** [comment]
Im having this same error with sandbox. Tried with several cards and test accounts and it only happens for the payments with "Debit or Credit Card". Been going hours trying to figure this one out. Any help here would be appreciated!

**Comment by blackchineykh** [comment]
Any feedback on this?

**Comment by jshawl** [comment]
Hello @huweihong and @blackchineykh do you mind providing either a debug id (`paypal-debug-id` in the response headers) and/or steps to reproduce? I'd be happy to take a look, thank you!
