### ISSUE TITLE
[Bug] Paypal Iframe Overlay crashes when clicking into input fields

### ISSUE THREAD

**Issue by malua** [paypal/paypal-checkout-components#2214]
### 🐞 Describe the Bug

When clicking into any input field, the Paypal Popup closes, as can be seen in the video.

### 😕 Actual Behavior

There are no errors in the console nor in the Paypal Developer Dashboard. We have the same integration with other apps, where the error not occurs. Also the error only occurs in the Capacitor app, when I serve the app and open it in Chrome the opened browser tab does not crash and I can complete the payment.

### 🌍 Environment

- Browser version: latest Chrome
- OS version: Android & iOS
- SDK version (`window.paypal.version`): - '5.0.386'

### Affected browsers

What browser(s) are affected?
- Web View / Safari ViewController

### ➕ Additional Context

https://github.com/paypal/paypal-checkout-components/assets/7237428/02bcc656-8660-4354-9753-bd313b7df6da

Any hints would be greatly appreciated! Thanks!

**Comment by Bhouben** [comment]
Oa

**Comment by malua** [comment]
I found the culprit. The paypal button was conditionally rendered due to a new config flag.
I fixed it by just hiding the button instead of removing it from the DOM.
