### ISSUE TITLE
[Documentation]  How to bill user periodic, with a dynamic value?

### ISSUE THREAD

**Issue by softov** [paypal/paypal-checkout-components#2222]
### 📙 Describe the Issue

As a developer working for software designed to ISP company, I need to implement a recurring billing system based on internet usage for our users who want to pay with PayPal. The challenge is to bill users periodically with variable prices, reflecting their specific internet usage. Users should not have to go through the PayPal checkout process every time, and we want to enable them to save their payment method securely for future payments.

### 🔬 Minimal Reproduction

1. User signs up for our internet service and chooses PayPal as their payment method during the initial checkout.

2. We create a subscription for the user using PayPal's Subscription API, selecting the appropriate subscription plan based on their chosen internet usage tier.

3. Throughout the billing period, we track the user's internet usage and calculate the dynamic pricing based on their actual usage.

4. Before the billing cycle ends, we want to use PayPal's Subscription API to bill the user for the upcoming period's internet usage, without requiring them to go through the checkout process again.

### 😕 Actual Behavior

Currently, we are unsure how to integrate the PayPal Subscription API effectively to handle dynamic pricing based on users' internet usage and perform recurring billing without user intervention.

### 🤔 Expected Behavior

We expect to have a working recurring billing system that utilizes PayPal's Subscription API to handle variable pricing based on users' internet usage. Users should be billed automatically at the end of each billing cycle without having to perform a separate checkout.

### ➕ Additional Context

Our team has already set up the PayPal integration and can create subscriptions with fixed prices successfully. However, we need guidance on how to incorporate dynamic pricing based on usage and automate the billing process using the saved payment method.

Documentation referenced: 
- PayPal Billing Agreements: https://developer.paypal.com/docs/api/payments.billing-agreements/v1/
- PayPal Subscriptions API: https://developer.paypal.com/docs/api/subscriptions/v1/

In the reference POST (https://github.com/paypal/paypal-checkout-components/issues/1105), a developer proposed a solution to handle dynamic plans for recurring billing with PayPal Checkout Components. The developer mentioned creating "dynamic" plans on the fly whenever one is needed via an additional AJAX call to their server. They pass in the required information, create the plan, retrieve the plan ID, and then use that ID to create the subscription.

The key point to note is that the plan created for dynamic billing has "INFINITE" or 0 payment cycles. This means that the plan allows for indefinite billing cycles, enabling flexibility in billing based on the user's actual usage, without the constraint of fixed billing cycles.

While the proposed solution may have limitations and complexities, the use of plans with "INFINITE" payment cycles provides the ability to bill users based on actual usage, making it suitable for scenarios where the billing amount can vary over time.

How can I achieve something like that?

resume.
Client login, add a new payment method, logout.
+1 month - the system check and bill the Client $15.32.
+1 month - the system check and bill the Client $17.45.
+1 month - the system check and bill the Client $16.75.
etc..

**Comment by devchristina** [comment]
Hi @softov -- Apologies for such a long delay in our acknowledgement and response. Unfortunately, this use case is not currently supported in the subscriptions api. The billing agreements api does support this use case, but that is a limited release api and would be considered legacy. I've passed this use case onto the product team for future consideration.
