### ISSUE TITLE
[Bug] Bug report FB alternative payment

### ISSUE THREAD

**Issue by PanWcislo** [paypal/paypal-checkout-components#2223]
### 🐞 Describe the Bug

After choosing an alternative form of payment and being redirected to the bank's website (BLIK, P24), the transaction is impossible to complete.
The problem only appears on Facebook (possibly on other socialmedia as well) when the page opens in the mobile app.

### 🔬 Minimal Reproduction

1. I click the pay with BLIK/P25 button
2. open paypal window with button continue with blik/p24
3. attempting to open a page for payment using BLIK/P24

### 😕 Actual Behavior

After clicking the continue button, an empty white window opens or information about a failed transaction or the page could not be open (ERR_BLOCKED_BY_RESPONSE)

Screenshots:
https://drive.google.com/drive/folders/1N-iI6-G0d_tJlVdJV8EdCKdlTx4TFqg0

### 🤔 Expected Behavior

After clicking the continue button, the right page of the bank should open up

### 🌍 Environment

- Browser version: -
- OS version: -
- SDK version (`window.paypal.version`): -

### Affected browsers

What browser(s) are affected?

- Web View / Safari ViewController ??

### ➕ Additional Context

The smart button is added on the page according to the documentation function

**Comment by PanWcislo** [comment]
Is there anyone here who can answer me?

**Comment by devchristina** [comment]
Hi @PanWcislo -- Apologies in the delay of our acknowledgement and response. Since this issue was created months ago, can you tell me if you ever found an answer and/or if you're still facing this issue?

**Comment by PanWcislo** [comment]
Hi @devchristina, unfortunately but the problem is still unsolved

**Comment by devchristina** [comment]
@PanWcislo -- Can you provide any additional details? E.g. Website? Code you've created? At first glance, this doesn't appear to be a problem on the PayPal side, we'll need additional information in order to truly understand how you're getting to the problem.

**Comment by PanWcislo** [comment]
Sure. I create everything like is on this website: https://developer.paypal.com/docs/checkout/standard/integrate/

Website: themankaacademy.com
PayPal SDK code: https://github.com/PanWcislo/PayPal-smart-buttons/blob/main/PayPal.vue

**Comment by PanWcislo** [comment]
@devchristina -- any news?

**Comment by devchristina** [comment]
Do you happen to be using an iframe?

**Comment by PanWcislo** [comment]
I use Inertia.js in the project. Maybe that's the problem? There seems to be an iframe there.

How does the redirect to payment open, maybe there is a way to do it?

**Comment by hqualityz** [comment]
Hi @PanWcislo 

I think you are using the old version of the Alternative Payment Method.
There are 2 methods for the new APM integration:
- payment fields component where the PayPal JS SDK takes care of the rendering
- full API

you can have a look at my project : https://codepen.io/Hqualityz/pen/wvYJZNq
To confirm if you are on the right path

**Comment by PanWcislo** [comment]
What about this one: https://developer.paypal.com/demo/checkout/#/pattern/responsive Here it already automatically loads APMs that are supported and credit or debit card is added

**Comment by devchristina** [comment]
Closing this issue due to age. If you continue to have an issue or cannot find an alternative solution please create a new issue.
