### ISSUE TITLE
Internet Payment Gateway

### ISSUE THREAD

**Issue by SaneshNarayanan** [paypal/paypal-checkout-components#2234]
https://www.ipg-online.com/connect/payment/paymentSelection;jsessionid=E224361A6914AF661331.dc?t=blue&r=dc&k=MTcyLjI5LjkuMjAwOjkxNDM

**Comment by SaneshNarayanan** [comment]
Please check out the payment

**Comment by devchristina** [comment]
Hi @SaneshNarayanan, what exactly is the goal of this issue? do you need help? If no response is received, we'll close this ticket as spam.

**Comment by devchristina** [comment]
Closing this issue as spam, no response received.
