### ISSUE TITLE
[Bug] PayPal button render issue on modern websites

### ISSUE THREAD

**Issue by ffxsam** [paypal/paypal-checkout-components#2250]
### 🐞 Describe the Bug

On modern websites that use dark themes, they often employ the new CSS `color-scheme: dark`. All modern browsers will now detect this and force an iframe's background color to be white instead of transparent. For the PayPal button, this causes there to be a white background, which looks undesirable.

### 🔬 Minimal Reproduction

N/A

### 😕 Actual Behavior

![CleanShot 2023-09-19 at 14 30 53](https://github.com/paypal/paypal-checkout-components/assets/12532733/ffc16b24-bbfa-4797-b26c-cd67c3e7d7e5)

### 🤔 Expected Behavior

There should be no white background.

### 🌍 Environment

- Browser version: all recent versions
- OS version: N/A
- SDK version (`window.paypal.version`): - 5.0.397

### Affected browsers

What browser(s) are affected?

All modern browsers

### Solution

The solution, thankfully, is simple: add `<meta name="color-scheme" content="light dark">` into the iframe's `<head>`.

**Comment by devchristina** [comment]
Hi @ffxsam -- Thanks for submitting this issue. I've passed this issue/solution onto our engineering team. Will circle back when I know more details about a fix.

**Comment by ffxsam** [comment]
Hi @devchristina, just wanted to check in with regards to this bug. Do you know if there are any updates?

**Comment by devchristina** [comment]
Hi @ffxsam -- I've sent this to the product team to prioritize for an upcoming sprint. Once I have an acknowledgement of the request I'll let you know. 

Also, just curious. Was there a reason you submitted a bug vs. a PR, since you knew the solution?

**Comment by ffxsam** [comment]
Thank you! And I just didn't have time to jump into the codebase and figure out where to apply the fix. Or if the PayPal dev team had a specific way of addressing the issue.

**Comment by sebastianfdz** [comment]
Hello @ffxsam! Thanks for reaching out and letting us know about this. After further inspection of the issue we have determined that it is more complex than it seemed on the surface. An issue has been created for us to look at it in more depth. We currently have no ETA on when this might be fixed (PRs are welcome!).

**Comment by sebastianfdz** [comment]
ticket PPCPSDK-1374 for internal tracking

**Comment by ffxsam** [comment]
Hey @sebastianfdz! Surprised to hear that it's more complex than we thought. So my solution didn't work out?

**Comment by sebastianfdz** [comment]
Hey @ffxsam! Its not that the solution does not work, it has side effects that could potentially affect other merchants.
**I'll leave the TLDR here from the engineer that triaged this** 😀: This issue is not so simple to solve when thinking how this will affect all merchants. When setting the CSS property color-scheme on a parent web page with an iframe that has a transparent background, the transparent background will only be applied if there is a match in the color-scheme CSS property. If we add this meta tag to our iframe, all merchants who don't have this CSS property set on this site wont have a transparent background in our iframe.

**Comment by ffxsam** [comment]
@sebastianfdz Ahh, gotcha. Makes sense! And this is why I didn't bother with a PR. 😉 The solution seemed too simple, and there are always other things potentially affected by bugfixes.

**Comment by devchristina** [comment]
Closing this issue, being tracked internally.
