### ISSUE TITLE
[Bug] Bug report

### ISSUE THREAD

**Issue by AnshulInvia** [paypal/paypal-checkout-components#2256]
I am getting an error while creating a subscription. Unable to login
<img width="956" alt="subscriptionIssue" src="https://github.com/paypal/paypal-checkout-components/assets/109938994/947a5a1f-b1fd-43ce-9907-0267e4012d12">

**Comment by devchristina** [comment]
@AnshulInvia -- You'll need to submit a ticket with [Merchant Technical Support](https://www.paypal-support.com/s/?language=en_US) team in regards to this issue, this is not a coding problem. 

Closing this issue as not planned.
