### ISSUE TITLE
[Bug] Deprecation warning about DOMNodeInserted

### ISSUE THREAD

**Issue by raya** [paypal/paypal-checkout-components#2288]
### 🐞 Describe the Bug

Adding the PayPal checkout script causes Chrome to print a deprecation warning about the `DOMNodeInserted` event due to this function in the script:
```
document.addEventListener("DOMNodeInserted", (function(event) {
                render(event.target);
}));
```

### 🔬 Minimal Reproduction

Add the script `https://www.paypalobjects.com/api/checkout.js` to the page.

### 😕 Actual Behavior

The Chrome console displays:
```
[Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (<URL>) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.
```

### 🤔 Expected Behavior

No deprecation warning.

### 🌍 Environment

- Browser version: - Chrome 119.0.6045.199
- OS version: - MAC
- SDK version (`window.paypal.version`): - 4.0.338

### Affected browsers
Chrome

➕ Additional Context
[Mutation events deprecation](https://developer.chrome.com/blog/mutation-events-deprecation/)

**Comment by wsbrunson** [comment]
@raya the fix is live in production
