### ISSUE TITLE
Error out if button rendered into <button> element

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout-components#349]
This causes the click to not be registered in the iframe in firefox.

**Comment by trainerbill** [comment]
Would blacklisting or whitelisting container types be an acceptable solution?  If so I could probably handle this.

**Comment by bluepnume** [comment]
The way I was thinking about implementing this was to add a `validateContainer(element)` method to xcomponent, so the button can implement it and make sure the element is not a `<button>`. If you want to work on that, please feel free, sounds good!

**Comment by trainerbill** [comment]
Closing here and opening in xcomponent

**Comment by bluepnume** [comment]
I'm going to keep this open here too, as it'll require changes in both places

**Comment by bluepnume** [comment]
Fixed in new sdk.
