### ISSUE TITLE
ppxo_unhandled_error, Window closed for postrobot_method before ack

### ISSUE THREAD

**Issue by mahendra-virtueinfo** [paypal/paypal-checkout-components#404]
Hi,

As now i got this error after payment process done.

Everything works well, just this 2 error log is creating bad impression :)

Using Chrome Version 59.0.3071.115 (Official Build) (64-bit)  on ubuntu 14.04 

For reproduce no case every time i got this.

==========================================
checkout.js:304 

ppxo_unhandled_error Object {stack: "Error: Window closed for postrobot_method before a…eltha.mmk/scripts/directives/checkout.js:3062:24)", errtype: "[object Error]", timestamp: 1499955617415, windowID: "60020b376d", pageID: "13e214282e"…}

checkout.js:3201 Uncaught Error: Window closed for postrobot_method before ack
    at checkout.js:3201
    at runInterval (checkout.js:3062)

Hope this helps!
Let me know if you have any suggestion.

Thanks
//Mahendra

**Comment by bluepnume** [comment]
Hi Mahendra,

Did you see the checklist for submitting new issues?

----

### Description

Please provide a short description of the issue here, along with:

- [ ] Screenshots or videos that show the issue
- [ ] Your code
- [ ] The version of checkout.js you're using (or the paypalobjects url)
- [ ] A link to your page with the issue, if possible
- [ ] All console logs during the time of the issue, especially error messages
- [ ] Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?

**Comment by mahendra-virtueinfo** [comment]
Hello @bluepnume ,

Description

Please provide a short description of the issue here, along with:

 - [ YES ] Screenshots or videos that show the issue
 - [ NO ] Your code
 - [ ] The version of checkout.js you're using (or the paypalobjects url)
https://www.paypalobjects.com/api/checkout.js
 - [ ] A link to your page with the issue, if possible
 - [ ] All console logs during the time of the issue, especially error messages
![screenshot from 2017-07-13 21 33 51](https://user-images.githubusercontent.com/417138/28175836-01193416-6813-11e7-83b6-17fc71d92cbb.png)
 
- [ ] Does the issue also occur at developer.paypal.com/demo/checkout?
YEs
![screenshot from 2017-07-13 21 25 31](https://user-images.githubusercontent.com/417138/28175848-0b54b180-6813-11e7-99a7-f5687bd344ad.png)

**Comment by bluepnume** [comment]
Hi,

> Your code

This one is important -- I need to know what's happening in your code so I can try to reproduce the error. You can strip out any sensitive data if you need to.

**Comment by mahendra-virtueinfo** [comment]
https://gist.github.com/mahendra-virtueinfo/a119cf05001a91b780a5b2f34ce1c5f6

**Comment by mahendra-virtueinfo** [comment]
Hello @bluepnume,

I got case about re-produce:
Please think on below steps:
1) We are using Angularjs 1.5.9
2) We have steps for purchase product
3) We using steps with "ng-switch-when='3' ", "ng-switch-when='2' ", "ng-switch-when='1' " 
4) Now Angular not render element when we switch to another view
5) So, checkout.js has rendered button and we move forward or back after rendered checkout button, That time checkout.js not able to find button because angular switch has removed that.
6) After this case checkout.js fired those errors as un-handled, We must remove button before move to another tab then checkout.js does not fire errors,
7) Can we have specific method to destroy or something related this ?
8) Right now i have fixed this issue as removed button and each time rendering again when user select paypal.

Let me know if i wrong here! 

Regards,
Mahendra

**Comment by bluepnume** [comment]
> So, checkout.js has rendered button and we move forward or back after rendered checkout button, That time checkout.js not able to find button because angular switch has removed that.
> After this case checkout.js fired those errors as un-handled, We must remove button before move to another tab then checkout.js does not fire errors,

I think you're correct with this analysis. I'll look into the best fix.

**Comment by Vetalb8** [comment]
@bluepnume I have the same problem occurs when you redirect to another page.

**Comment by georgiosd** [comment]
Any workaround here? I'm now getting this problem also with .110

**Comment by ardaerzin** [comment]
like @Vetalb8, I'm redirecting users after a successful transaction, and having this error.

**Comment by ionSolutions** [comment]
like @Vetalb8  and @ardaerzin, i also have the same Issue when redirecting the user directly.

I did the workaround with removing the rendered button, when the payment process has finished by wrapping the paypal-button with an <div ng-if="ctrl.paypalButtonVisible">

tested with paypal-checkout v4.0.167 and angular 1.6.6

This does the trick for now :)

Code:
`...,
 onAuthorize: function (data) {  
                var EXECUTE_URL = '/api/executepayment';
                      var formData = {
                          paymentID: data.paymentID,
                          payerID: data.payerID
                     };
                return paypal.request.post(EXECUTE_URL, formData).then(function (response) {
                    vm.paypalButtonVisible = false;
                    $state.go('yourState');
                });
            }`

**Comment by jkomusin** [comment]
We're running into this problem as well but it doesn't seem to cause us any problems downstream, just an error logged to the console. The payment (authorization, in our case) completes successfully. (Using the CDN-hosted checkout.js)

As mentioned, destroying the button (in our case, telling React to no longer render it) before moving to a new location seems to avoid the error.

**Comment by ThatKawaiiGuy** [comment]
Experiencing this as well, `ppxo_unhandled_error: "Error: Window closed for postrobot_method`

**Comment by spencersmb** [comment]
So far anytime I destroy the paypal Button component directly after a payment is made, I get that error. 
`{emailProps.valid && <PaypalButton/>`

However, when I complete a payment, and close my cart which essentially has the PayPal button nesting inside a few other components and the cart animates out and then is removed using `{CSSTransition} from 'react-transition-group'`- I get no error. 

But when I try to wrap the <PaypalButton /> in a csstransition component itself - I still get the error.

weird

**Comment by bluepnume** [comment]
Tracking this issue here: https://github.com/paypal/paypal-checkout-components/issues/1029 -- this should be fixed in the new sdk after the next release. 👍

**Comment by GAYATHRI2787** [comment]
it has been working all the while, all of a sudden I see this error - 
![image](https://user-images.githubusercontent.com/63217297/78516696-2116b900-77d8-11ea-83e4-95513b4aad79.png)

**Comment by pragsjain** [comment]
I am facing same error.What's the fix @bluepnume ?

**Comment by OctaneInteractive** [comment]
Hi, I'm new to using PayPal, and I'm having similar problems.

I'm getting what appears to be a successful result:

```
{
  id: 'ID_REDACTED',
  status: 'CREATED',
  intent: 'SALE',
  gross_total_amount: { value: '9.37', currency: 'GBP' },
  application_context: { brand_name: 'BRAND_NAME', locale: 'en-GB' },
  purchase_units: [
    {
      reference_id: '123',
      amount: [Object],
      payee: [Object],
      items: [Array],
      shipping_address: [Object],
      status: 'NOT_PROCESSED'
    }
  ],
  redirect_urls: {
    return_url: 'http://localhost:8080',
    cancel_url: 'http://localhost:8080'
  },
  links: [LINKS_REDACTED],
  create_time: '2021-03-02T21:29:33Z',
  applicationContext: { brand_name: 'BRAND_NAME', locale: 'en-GB' }
}
```

... but then in Google Chrome I get a `ppxo_unhandled_error` error with "checkout.js" 4.0.325

![Screen Shot 2021-03-02 at 21 39 48](https://user-images.githubusercontent.com/419501/109718954-df38f300-7b9f-11eb-8ae5-2a560751c723.png)
