### ISSUE TITLE
PayPal Checkout does not support AMP

### ISSUE THREAD

**Issue by omtinez** [paypal/paypal-checkout-components#440]
### Description

AMP pages do not allow including script tags at the top-level page, which prevents usage of checkout.js. There are 2 ways to resolve this issue:

1. Create an AMP native component for checkout.js (preferred solution long-term)
2. Fix checkout.js so it works within iframes without needing to add the script to the top-level page

### Steps to reproduce

See https://github.com/omtinez/paypal-repro for a minimal example that showcases this issue.

### Affected browsers

This affects all browsers.

**Comment by bluepnume** [comment]
Thanks for the details and the minimum example! I'll try to get some time to look into this and evaluate the options.

**Comment by venkata82** [comment]
is there any update on this one, I see it is happening to me.

**Comment by ahmedkaludi** [comment]
Looking forward to this one

**Comment by cnabar** [comment]
Hi - any updates on this one - thanks!

**Comment by stephengardner** [comment]
Hi - I run an app to convert Shopify stores to AMP (https://shopsheriff.com/amp) and this feature would be huge.  We power over a million AMP pages for ecommerce.  Looking forward to an update.

**Comment by bluepnume** [comment]
Closing this for now. There's no clear way to support AMP given that it blocks all custom javascript; and without that there's no way to communicate the success back to the parent page.

**Comment by westonruter** [comment]
@bluepnume AMP now allows for custom JavaScript via [`amp-script`](https://amp.dev/documentation/components/amp-script/). This component runs the custom script off the main thread and synchronizes the sanitized DOM changes back to the main thread via [WorkerDOM](https://github.com/ampproject/worker-dom). 

Nevertheless, I can see that the SDK is apparently 271KB+, whereas `amp-script` limits custom scripts to 150KB. So that's a problem.

**Comment by stephengardner** [comment]
@westonruter to add some additional color here, a quick scan of the PayPal JS SDK (https://www.paypal.com/sdk/js?client-id=sb) shows an abundance of methods not supported by WorkerDOM and/or amp-script.  `document.createElement('script');`, `e.preventDefault()`, `window.location`, etc, etc, etc.  So I'm not sure this would even be a viable route had it been under the script limit.
