### ISSUE TITLE
Button disappears with when the pop-up is closed and token is bad

### ISSUE THREAD

**Issue by tfulton** [paypal/paypal-checkout-components#676]
### Description

Button is disappearing under the following conditions:
- payment() callback returns an invalid PayID, token or other bad value
- pop-up closes eventually (or user closes it manually)
- overlay is closed via continue text or X close image
- button disappears

This is reproducible in the Integration Patterns site.  Sample code to reproduce:

```
        paypal.Button.render({

            env: 'sandbox', // sandbox | production

            // PayPal Client IDs - replace with your own
            // Create a PayPal app: https://developer.paypal.com/developer/applications/create
            client: {
                sandbox:    'AZDxjDScFpQtjWTOUtWKbyN_bDt4OgqaF4eYXlewfBP4-8aqX3PiV8e1GWU6liB2CUXlkA59kJXE7M6R',
                production: '<insert production client id>'
            },

            // Show the buyer a 'Pay Now' button in the checkout flow
            commit: true,

            // payment() is called when the button is clicked
            payment: function(data, actions) {

                // Make a call to the REST api to create the payment
                return "bad seed";
            },

            // onAuthorize() is called when the buyer approves the payment
            onAuthorize: function(data, actions) {

                // Make a call to the REST api to execute the payment
                return actions.payment.execute().then(function() {
                    window.alert('Payment Complete!');
                });
            }

        }, '#paypal-button-container');
```

- Checkout.js Version:  4.0.197
- Browsers:  latest Safari 11.1, Chrome 66.033
- Sample page:  https://tofulton-callback.herokuapp.com/index02
- Console logs:  seem to change depending on what is clicked when, but the button disappearing is consistent.
- Screen shots attached.

### Steps to reproduce

- payment() callback returns an invalid PayID, token or other bad value
- pop-up closes eventually (or user closes it manually)
- overlay is closed via continue text or X close image
- button disappears

### Affected browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [?] Edge
- [?] IE
- [?] Chrome Mobile/Tablet
- [?] Safari Mobile/Tablet
- [?] Web View / Safari ViewController
- [?] Other

![screen shot 2018-04-30 at 12 51 24 pm](https://user-images.githubusercontent.com/4206270/39447098-86cbccb2-4c75-11e8-9f04-2c5e9a02e1fe.png)
![screen shot 2018-04-30 at 12 51 29 pm](https://user-images.githubusercontent.com/4206270/39447099-86e89cf2-4c75-11e8-899b-15b64cda26d4.png)
![screen shot 2018-04-30 at 12 51 35 pm](https://user-images.githubusercontent.com/4206270/39447100-8702a96c-4c75-11e8-9a79-f9430a707302.png)

**Comment by bluepnume** [comment]
Thanks for the report. Good catch. I'll take a look into this.

**Comment by martinmckenna** [comment]
I can confirm this is still an issue

**Comment by bluepnume** [comment]
Should be fixed in latest integration.
