### ISSUE TITLE
Auto-Generate Funding List on Build.

### ISSUE THREAD

**Issue by ppnsanders** [paypal/paypal-checkout-components#768]
### Description

When the build for checkout.js runs a JSON file should be generated and deployed to the paypalobjects.com CDN to provide Partners with a list of available funding options for merchants in their admin panel.  This will allow merchants to explicitly allow/disallow funding methods as part of their Smart Payment Buttons integration.   The funding options should only be added to the JSON when they are considered GA.

### Example JSON

```json
{
  "funding_options": [
    {
        "name": "paypal.FUNDING.CARD",
        "display_name": "Credit Card Icons"
    },
    {
        "name": "paypal.FUNDING.CREDIT",
        "display_name": "PayPal Credit"
    }
  ]
}
```

**Comment by pmward** [comment]
+1 to this!

most ecommerce platform and cart partners will have setting to allow merchant to enable or disable certain SPB setting, in particular the funding_options. The problem now is the Partner can only disallow/allow the funding_options they know about. We dont want ecommerce platform partners (which will onboard over half our SPB merchants in most countires) to have make integration updates every time new APM's come out, something like Nate describes i think would entirely future proof things.

**Comment by bluepnume** [comment]
Closing this -- the APM team is working on an api with this kind of functionality, to help build dashboards.
