### ISSUE TITLE
MS Edge version 38.14393.2068.0 is not supported - the Return URL is being called within the in-context popup

### ISSUE THREAD

**Issue by shekharparkhi** [paypal/paypal-checkout-components#824]
### Description

My merchant is having constant weird issue with the MS Edge browser and is refusing to launch without the flow working correctly there. Here is a screen cast of the Edge experience that I just took on their site. Any thoughts, please?

login here  https://www.greatcollections.com/login.php
username sukumar
password sukumar
goto this page https://www.greatcollections.com/buyer_invoice.php
select Payment by Credit Card (Visa, MasterCard, Discover American Express
click "Continue button", on the next page check the terms and condition box and you can proceed to express checkout

![image](https://user-images.githubusercontent.com/7925684/44612576-5a92e000-a7be-11e8-9218-85ab8ea7264b.png)

[Recording #4.zip](https://github.com/paypal/paypal-checkout/files/2320197/Recording.4.zip)

Please provide a short description of the issue here, along with:

- Screenshots or videos that show the issue
- Your code
- The `paypal.version` from your browser console
- The exact browser version
- A link to your page with the issue, if possible
- All console logs during the time of the issue, especially error messages
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
- Does the issue occur consistently, or intermittently?

### Steps to reproduce

Please provide each individual step required to reproduce the issue

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by sukumaranj** [comment]
Thanks for posting this shekhar
Every onCancel url or onError url when returned properly will have an ec-token like one below,
www.greatcollections.com/buyer_invoice.php?method=legacy&token=EC-6UJ17379E6914850U
we use a url logger in our site to check this 
but on Edge when the page is loaded with in the Pop-Up, the ec-token is missing in the URL.

**Comment by bluepnume** [comment]
@vishakha94 can you please take a look?

**Comment by vuvutestaccount** [comment]
Hello,

I have a merchant using Microsoft Edge version 41.16299.726.0 (Microsoft Edge HTML 16.16299)
 and has come across a similar issue. After signing into PayPal, the incontext window doesn't close and instead, redirects the customer back to the merchant's checkout page in the incontext window. This can be tested by adding the following item to the cart and signing into the website using the below credentials:

https://online3-qa.kitco.com/buy/3104INC/1-oz-Silver-Maple-Leaf-Incuse-Coin-9999-3104INC

Username: vupaypal@gmail.com
 Password: vu12345

The issue does not occur in Chrome, Firefox, nor Safari as I have tested this on my end. Furthermore, I was able to duplicate the problem using the same Edge version and have screenshots from my test that I can forward for reference.

Lastly, I know this isn't high on the priority list; however, the merchant plans to go live before Thanksgiving and is asking if we can expedite this.

**Comment by mcntsh** [comment]
@vuvutestaccount we are looking into this. Can you tell me if you are accessing the checkout through a corporate device?

**Comment by shekharparkhi** [comment]
++ Vu Tang

Regards,
Shekhar.
(PayPal Merchant Solutions Engineer)

On Nov 30, 2018, at 4:47 PM, Jon McIntosh <notifications@github.com<mailto:notifications@github.com>> wrote:


@vuvutestaccount<https://github.com/vuvutestaccount> we are looking into this. Can you tell me if you are accessing the checkout through a corporate device?

**Comment by vuvutestaccount** [comment]
Hello,

Yes I am. Although I'm using a corporate device to reproduce the problem, the merchant and their development team are experiencing the MS Edge issue on their side as well as they brought this to my attention to begin with. 

The PayPal Express Checkout integration has been disabled by the merchant for MS Edge so if this needs to be re-enabled for testing, please let me know.

**Comment by mcntsh** [comment]
Hey @shekharparkhi and @sukumaranj there are quite a few reports mentioning a similar bug. Could you please see [this comment on issue #959](https://github.com/paypal/paypal-checkout/issues/959#issuecomment-443851819) and let me know if this solves your problem?

This will help us keep track of which ticket is related to which bug, since the example.com redirect can happen for a few different reasons.

**Comment by bluepnume** [comment]
Any updates on this one? @shekharparkhi can you confirm if the merchant is hitting either intranet or trusted mode? And are you able to personally repro?
