### ISSUE TITLE
Black screen appears when you try to pay with PayPal in Ecwid store on Wix within Facebook Mobile app

### ISSUE THREAD

**Issue by peachyecwid** [paypal/paypal-checkout-components#965]
### Description

When you try to pay with PayPal in Ecwid store on Wix in the Facebook mobile app, the popup doesn't work correctly. The black screen appears which is very confusing for customers. The issue occurs consistently.

Here is a screencast: https://monosnap.com/file/7icCglFGiaLN1Q9IzrMEtn8AkCfgEh
Link to the store on FB: https://www.facebook.com/pg/premierperformancecz.uk/shop/

### Steps to reproduce

1. Open Facebook mobile app > Open the Premier Performance CZ page.
2. Open the Shop tab.
3. Add any product to the shopping cart.
4. Proceed to the checkout that opens in the browser inside Facebook.
5. Go to the payment page and click on the Pay with PayPal button.
6. Black screen appears.
7. Click on the button again and the see the warning 'Please switch tabs to reactivate the PayPal window'.

**How it should work:** The popup window should be opened correctly within the Facebook app, like on this screencast: https://monosnap.com/file/uf2n6fhSKzDZEi0qaoKqcZc9cTww47

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [x] Other — webview in the Facebook app

**Comment by bluepnume** [comment]
Can you confirm if you're still seeing this issue?

**Comment by peachyecwid** [comment]
@bluepnume 
> Can you confirm if you're still seeing this issue?

Hello! You can't reproduce the issue in the merchant's store because they switched the shopping cart platform.

Though the issue still appears in my store. You can check it out at https://www.facebook.com/pg/Peachy-Store-344394829697370/shop/
Here is a screencast of the issue: https://take.ms/q4aI0

Please, let me know if you need more details. Thanks!

**Comment by peachyecwid** [comment]
Hi @bluepnume 

Could you recreate the issue in my store: https://www.facebook.com/pg/Peachy-Store-344394829697370/shop/ ? Do you have any update on this issue?

Thanks!

**Comment by bluepnume** [comment]
Closing as a lot of time has passed and we've been unable to repro or get any other reports. Please reopen a new issue if you're still seeing this. Thanks!
