### ISSUE TITLE
How to turn off paypal debug print information

### ISSUE THREAD

**Issue by SUNAnne** [paypal/paypal-checkout-components#974]
Why hasn't the print message been turned off
<img width="964" alt="2018-12-26 5 34 11" src="https://user-images.githubusercontent.com/39116039/50441187-7953df80-0934-11e9-9db0-2452c9977ec3.png">

**Comment by mcntsh** [comment]
Hey @SUNAnne, that is the correct way to set the log level. The set-up script looks for one of these values: https://github.com/paypal/paypal-checkout/blob/master/src/constants/misc.js#L22

Can you please show the logs that are printing for you?
