### ISSUE TITLE
actions.disable not preventing inline guest from being clicked

### ISSUE THREAD

**Issue by trainerbill** [paypal/paypal-checkout-components#976]
### Description

Please provide a short description of the issue here, along with:

- Screenshots or videos that show the issue
- Your code
- The `paypal.version` from your browser console
- The exact browser version
- A link to your page with the issue, if possible
- All console logs during the time of the issue, especially error messages
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
- Does the issue occur consistently, or intermittently?

### Steps to reproduce
https://developer.paypal.com/demo/checkout/#/pattern/vertical

![image](https://user-images.githubusercontent.com/3578259/50458966-be741380-092c-11e9-838b-b96fa868e77c.png)

### Affected browsers

- [X ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by khanghoang** [comment]
This issue is addressed by https://github.com/paypal/paypal-checkout/pull/978 and another Hermes's PR
