### ISSUE TITLE
Frameborder param triggering validation errors - move to CSS

### ISSUE THREAD

**Issue by ajlangsdon** [paypal/paypal-checkout-components#987]
### Description

When the iframe for the PP checkout gets rendered, a **frameborder** parameter is added as inline HTML. For merchants using validation tools, this is triggering an error since it is inline HTML/CSS. Can this be moved to CSS?

<iframe class="zoid-component-frame zoid-visible" frameborder="0" allowtransparency="true"..... ></iframe>

* If the full iframe HTML is required, let me know and I can post that.

**Comment by mcntsh** [comment]
Good call. I made a PR to krakenjs/belter which addresses this: https://github.com/krakenjs/belter/pull/4

**Comment by bluepnume** [comment]
Change released with new sdk. See https://developer.paypal.com/docs/checkout/reference/upgrade-integration/

**Comment by tizend** [comment]
Hi @bluepnume, we still seeing the same error in our end. 
![paypal](https://user-images.githubusercontent.com/47815795/53086419-5e9d8180-3505-11e9-9502-93a5a0486368.JPG)

Do we need to change something on our code? We are using the checkout.js 

Thanks
