### ISSUE TITLE
wrapper div has no class or id

### ISSUE THREAD

**Issue by atlanteh** [paypal/paypal-checkout-components#988]
The generated paypal button has a wrapper class with no class or id, so if we want to target it for css or js, it's not easy at all. I think we should consider adding a class or even allowing custom class to be inserted. https://github.com/paypal/paypal-checkout/blob/25a114751185f806fb6d7f53246d9a8df1353723/src/button/component.jsx#L135

I think a "paypal-button-wrapper" is good enough. What do you think?

Here's a screenshot:
![image](https://user-images.githubusercontent.com/3952700/51287332-9e9db000-19ff-11e9-9ec9-8c8ca4f6b6b6.png)

**Comment by bluepnume** [comment]
None of the elements rendered by this sdk should ideally have custom css applied. Unless there's a convincing use-case, please apply css to any container elements that you create, but do not rely on the inner dom structure as it may change in future without warning.

**Comment by atlanteh** [comment]
Actually in my case I want the button to self center or to take 50% of container, or margin etc.. Having a class on the container is very common practice.

**Comment by bluepnume** [comment]
Can't you place the element in your own container which is an inline-block with 50% width? Does that cause any problems?

**Comment by atlanteh** [comment]
Well in my case, I have the following structure (classes converted to style):
```
<div style="display: flex; flex-direction: column; justify-content: center; align-items: center">
  <div>...</div>
  <div>...</div>
  <div style="align-self: stretch">*This is the paypal container*</div>
</div>
```

The above is not possible as we can't access the paypal container (unless you consider .my-box > div valid). What I had to do is add another wrapper on top of the paypal button and I don't like it.

I do have to add that I really don't see the problem of adding a class on the top container so you can easily set margins, width, position, float, etc. You can always wrap this with another container and do the work there, but if every library followed that rule, we'd have many many uneeded & untidy code.

**Comment by bluepnume** [comment]
> You can always wrap this with another container and do the work there, but if every library followed that rule, we'd have many many uneeded & untidy code.

I take your argument; but we're treating this an an encapsulation issue.

- We don't rely on any parent styles being set, or any specific classes being present in the parent
- You don't rely on any specific styles being set on the child, or any classes being present in the child

That way either layer can change without risk of breaking the other. That should outweigh the downside of having an extra wrapper div to do what you need it do.

I agree that extra `div` is annoying; it's an unfortunate side-effect of how we deal with supporting multiple framework drivers at once in a consistent way.

**Comment by atlanteh** [comment]
Well I disagree, as I think that you should give the developer the freedom of choice. especially in a valid case like this and especially when the underline divs do have classes (ie paypal-button, zoid-outlet etc.), so I think you should reconsider (maybe add a warning on the docs?) but I do respect your decision, whatever you choose :)
