### ISSUE TITLE
Pay by Debit or Credit Card - Create Account - inconsistent

### ISSUE THREAD

**Issue by springknees** [paypal/paypal-checkout-components#989]
Using Chrome (incognito to eliminate cookie issues) I test the PayPal Checkout Button on this page:-

https://developer.paypal.com/demo/checkout/#/pattern/checkout

On a desktop/laptop the PayPal "log in" dialog opens with the "Pay by Debit or Credit Card" option button shown. When I do exactly the same with a phone/tablet, the PayPal "log in" dialog opens showing a "Create Account" button in place of the "Pay by Debit or Credit Card" button.

Is this the expected behaviour? If so, I'm curious as to why non-desktop users are forced to open a PayPal Account?

Desktop/Laptop Win 10 + Chrome 71
Phone Android (Nougat) Chrome 71
Tablet Android (Lollipop) Chrome 71

Thanks - Springknees

**Comment by springknees** [comment]
I've had no luck here, I've also "googled" without success - I've been unable to discover whether the behaviour I described above is "to be expected"! This is frustrating, as I now have to give the users of my online shop instructions that are specific to the device being used to access the shop. That, in itself, presents no technical difficulty, but why does PayPal have a protocol for mobile devices that differs from the protocol for desktop/laptop devices. If anybody reading this has insight into this, perhaps they can share that insight with me!!

In case it's relevant, I'm in the UK.

Thanks - Springknees

**Comment by bluepnume** [comment]
The experience changes based on a lot of factors, including cookies. + @bluelnkd for more info. (since this is a common question maybe we should come up with some content for the dev docs?)

**Comment by springknees** [comment]
Thanks @bluepnume  - in my case "the experience changes" according to the alignment of the planets and the direction of the wind ;) There is no consistency - sometimes the guest checkout option is there **(Debit or Credit Card)** other times it isn't **(Create Account)**. Almost 100% of the time the only option available on mobile devices is **Create Account**. I've tested in Incognito mode and virgin installs of Chrome and Firefox - all with similar unpredictable results.

I see this issue was previously raised on Issue #500 & #510, where it was addressed by @bluelnkd without any satisfactory conclusion. If you do add to the dev docs, as you suggest, all you can really say is that sometimes a guest checkout is permitted, but then other times it isn't!! If we know what to expect, we can advise users accordingly.

**Comment by bluepnume** [comment]
For what it's worth -- if you use the vertical button layout, you should always see card buttons, and those buttons should always redirect to the guest experience. That's the recommended approach for allowing one-time card payments.
