### ISSUE TITLE
Paypal button gets cut off with tagline set as false

### ISSUE THREAD

**Issue by vishakha94** [paypal/paypal-checkout-components#991]
### Description

Please provide a short description of the issue here, along with:

- Screenshots or videos that show the issue
- Your code
- The `paypal.version` from your browser console
- The exact browser version
- A link to your page with the issue, if possible
- All console logs during the time of the issue, especially error messages
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
- Does the issue occur consistently, or intermittently? -- happening consistently on second render for all sizes and color for horizontal layout

### Steps to reproduce

Please provide each individual step required to reproduce the issue

### Affected browsers

- [ ] Chrome
- [x] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

<img width="296" alt="screen shot 2019-01-18 at 12 04 54 pm" src="https://user-images.githubusercontent.com/12112794/51410374-4f4ba280-1b19-11e9-9895-b34bd4677d46.png">
<img width="438" alt="screen shot 2019-01-18 at 12 05 35 pm" src="https://user-images.githubusercontent.com/12112794/51410402-668a9000-1b19-11e9-8759-82ae41815c0e.png">

**Comment by bluepnume** [comment]
Fixed.
