### ISSUE TITLE
paypal button leads to error after using jquery ajax in onCancel function

### ISSUE THREAD

**Issue by kkagill** [paypal/paypal-checkout-components#997]
### Description

When a user decided to cancel transaction by clicking x on the paypal modal, I am updating DB by using jquery ajax in onCancel function like below: 

` 
onCancel: function (data, actions) { 
  
             $.ajax({
                type: 'GET',
                url: '@Url.Action("OrderCancelled", "ShopUserManagerAPI")',
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                success: function (res) {    
                    alert("Payment is cancelled")         
                }
            });    
        }, 

`

After updating db, alert message is successfully shown. Problem is, when I click on the paypal button again I get this error:

https://ibb.co/JpdSSwC

Instead of redirecting them to a cancel page, I show them an alert message because the user should be able to click on the paypal button to try again on the same page.

What's wrong with this when I use jquery ajax to manually perform something?

### Affected browsers

- [v] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by mcntsh** [comment]
Hey @kkagill, would you mind showing us a bit more of what you're doing in the `payment` handler? The error you're getting tells me that you're not passing a token back. We expect `payment` to either return a promise that resolves a valid token, or a token string.

**Comment by kkagill** [comment]
Hi @mcntsh, here's what I got:

`    paypal.Button.render({     
        env: 'sandbox', // Or 'production'
        // Set up the payment:
        // 1. Add a payment callback
        payment: function (data, actions) {
            // 2. Make a request to server
            return actions.request.post('/api/User/create-payment/')
                .then(function (res) {               
                        return res.id;                    
                });
        },
        // Execute the payment:
        // 1. Add an onAuthorize callback
        onAuthorize: function (data, actions) {
            // 2. Make a request to server
            return actions.request.post('/api/User/execute-payment/', {
                paymentID: data.paymentID,
                payerID: data.payerID
            })
                .then(function (res) {      
                    if (res.status === "Success") {
                        window.location.href = '@Url.Action("OrderSuccess", "User")';
                    }              
                });
        },
        onCancel: function (data, actions) {  
             $.ajax({
                type: 'GET',
                url: '@Url.Action("OrderCancelled", "User")', // Call OrderCancelled() to update order has been cancelled
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                success: function (res) {     
                    alert("Payment is cancelled")                
                }
            });    
        },
        // If an error prevents buyer checkout, define an error page using the onError callback:
        onError: function (err) {
            // Show an error page here, when an error occurs
        }
    }, '#paypal-button');`

So when the user closed the paypal modal in the middle of the process, then it will trigger onCancel function which will call the server's OrderCancelled method via jquery ajax to update that this transaction has been cancelled. 

If it's updated, it will return 200 response and show an alert message. 

Now, since it's just returning 200 response and you mentioned I need a valid token, do I need to pass token string from onCancel()'s callback parameter `data` to my OrderCancelled method and return the token in 200 response?

**Comment by mcntsh** [comment]
Hey @kkagill, apologies for the late response!

This all looks good – the `onCancel` callback doesn't require any token response, just `payment`. I'm wondering if something in your `OrderCancelled` API is causing failure in `/api/User/create-payment`. Can you confirm that `res.id` is a valid token?

**Comment by kkagill** [comment]
@mcntsh no `OrderCancelled` is not returning any token because that ajax is not passing any data to `OrderCancelled` api. That's why I asked you if I need to pass `onCancel`'s callback `data` to `OrderCancelled` and return token again,

**Comment by kkagill** [comment]
It is returning a valid token when it is requesting to `/api/user/create-payment` **at the first try**. Then when a paypal popup asks me to login and I close it intentionally, it triggers `onCancel`, showing the alert message then what I do is send GET request to `OrderCancelled` to update DB which returns 200 response. 

Then on the same page, I close the alert message and I clicked on the paypal button again. As a result,  **it redirects me back to return_url** instead of showing a paypal popup. 

So if you are asking about the second attempt on the same page, yes it is not returning a valid token. 

If I removed the ajax part in `onCancel` and just show an alert message, then it works fine on my second attempt to login to PayPal via popup on the same page. 

Not sure why ajax part is triggering me to redirect back to return_url when it only returns 200 response.

**Comment by mcntsh** [comment]
> So if you are asking about the second attempt on the same page, yes it is not returning a valid token.

Therein lies the problem. I'd check your network logs for your second request to `/api/user/create-payment` and see what's going on there. I suspect its a server failure resulting from the `OrderCancelled` request you made before it.
