### ISSUE TITLE
Unexpected init message from domain

### ISSUE THREAD

**Issue by bormanEcwid** [paypal/paypal-checkout-components#998]
### Description

Our ecommerce platform use paypal button integration(https://developer.paypal.com/demo/checkout/#/pattern/server)

Sometimes customers get error "Unexpected init message from domain http://.... -- expected message from https://www.paypal.com" from paypal
For example:
```
Mon Jan 28 11:20:47 GMT+000 2019: Error occurred - Error: Unexpected init message from domain http://MERCHANT_SITE_URL -- expected message from https://www.paypal.com
https://www.paypalobjects.com/api/checkout.min.js:1:88562
try@https://www.paypalobjects.com/api/checkout.min.js:1:86016
https://www.paypalobjects.com/api/checkout.min.js:1:61826
L@https://www.paypalobjects.com/api/checkout.min.js:1:64221
O@https://www.paypalobjects.com/api/checkout.min.js:1:64508]
```

What means this error? How can we prevent this error?

### Steps to reproduce

n/a

### Affected browsers

n/a

**Comment by bluepnume** [comment]
Can you please re-open the issue and answer all of the questions to help us triage?
