### ISSUE TITLE
Paypal Checkout button not clickable (intermittent)

### ISSUE THREAD

**Issue by drumil243** [paypal/paypal-checkout-components#999]
### Description
Paypal checkout button for  Sandox not opening the dialog box after clicking in Chrome (V 71.0.3578.98 (64-bit)) (windows 10) - This issue is intermittent, but when it occurs, nothing happens on the click of the button, no log or error is displayed on the console, no loading, no change on the screen - as if the button is disabled.

### Affected browsers

- [x] Chrome (V 71.0.3578.98 (64-bit)) (windows 10)
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Should never be an issue with the new integration. Please see the upgrade guide at https://developer.paypal.com/docs/checkout/reference/upgrade-integration/
